DistributedProofreaders/dproofreaders

SETUP/configuration.sh

Today the LoC stopped accepting connections at the YAZ address we were using. According to http://www.loc.gov/z3950/lcserver.html we should be using a different address anyway which appears to work, so lets make that the default.

Point to update LOC YAZ server

---

.travis.yml
SETUP/tests/SettingsTest.php
SETUP/tests/UserTest.php
SETUP/tests/phpunit_bootstrap.php
SETUP/tests/travis-ci_configuration.sh

This enables testing of the dproofreaders codebase through Travis-CI. So far this is a very (very) low bar, but it does ensure that the following work:
* all files successfully lint
* database schema successfully imports
* our meager unit tests all pass
Hopefully this also sets us up with a base and we can continue adding tests.

Use Travis-CI for basic testing

---

SETUP/update_from_github

The pgdp.net production server had customized the `update_from_sf` script to do local filesystem changes (copy over files, apply patches). This abstracts that functionality such that customization is still possible without changing code in source control that we have to then manually patch.

Allow call-out to local customization script

---

pinc/DPage.inc
pinc/Project.inc
pinc/stages.inc
project.php
styles/layout.css
styles/layout.less
tools/project_manager/diff.php
tools/project_manager/page_compare.php
tools/project_manager/page_detail.php

new file unformat.inc with function to remove formatting
and either completely unwrap or keep line structure but
remove leading and trailing spaces
diff.php: add option to remove formatting (not unwrap)
before compare.
If at least one round is F then show link option to remove
formatting or not.
Default is remove for P to F, keep for F to F
new file page_compare.php to compare pages with format
removed and unwrapped between selected rounds for a
project, either all pages or for the users pages in either
the first or second round. Makes a list of page image names
which link to diff.php
project.php: link added to page_compare.php if project has
reached formatting stage

Option to remove formatting before diff

---

SETUP/installation.txt

After ea40ee5d merged we know the code works with PHP 7.0.
When we merged ba74ae04, we broke support for phpBB 3.0. This
is because accounts/login.php pulls in metarefresh.inc which
pulls in slim_header.inc. ba74ae04 changed slim_header.inc to
bring in theme.inc which eventually brings in user.inc which
breaks phpBB 3.0 because it also defines a User class. phpBB 3.0
is out of support and phpBB 3.1 was released in Oct 2014 so
rather than trying to hack a fix in, lets just say 3.1 is the
minimum supported version.

Update PHP and phpBB version support

---

SETUP/tests/SettingsTest.php
SETUP/tests/UserTest.php

Unit tests frameworks are only useful for highlighting errors when you don't do something stupid like `die()` in a setUp fixture.

Fix unit tests

---

tools/project_manager/editproject.php
tools/project_manager/external_catalog_search.php

During project creation, if no record is selected after the
external catalog search and 'Create Project' is selected, we throw
a very useless error to the user. Instead, lets provide information
they can actually use.

Improve project creation error messages

---

pinc/iso_639_list.inc
pinc/iso_lang_list.inc

Per Wictionary, Galican is the preferred term.

Change Gallegan to Galician

---

pinc/User.inc
tools/modify_access.php

In addition to grant/revoke, admins and evaluators have the ability to deny a request for access too. This fixes a regression from the merge of cleanup_users_table in commit a99d656f.

Allow denying user-requested access

---

tools/project_manager/edit_common.inc
tools/project_manager/editproject.php
tools/project_manager/external_catalog_search.php

The size of the db columns for nameofwork and author is 255. Prior versions of MySQL would silently truncate longer strings to the size of the column, but modern versions throw an error. Prevent users from inputting strings longer than 255 for these columns.
Without a doubt there are other instances where we should be doing this type of enforcement, but this addresses this instance.

Restrict nameofwork and author inputs to 255 chars

---

pinc/project_quick_check.inc

Rather than issuing a warning if one of the word lists is empty,
only alert if both of them are empty. This was both the original
ask and what was announced, but not what was coded.

Only alert if both word lists are empty

---

tools/proofers/review_work.php

Cells with highlighted background color were being overridden if
they were on even rows because of the table.striped row CSS.
Change that to a style attribute to correct this.
While we're here, fix the number cells to be right-aligned to match
with our style guide and output proper attribute names for the number
columns.

Fix background for highlighted cell

---

pinc/SettingsClass.inc

First check if setting exists. Otherwise an error can occur.
This can happen e.g. if removing a task notification and then
reloading the page. (It would be good to modify the page causing
the problem also so this does not happen).

Settings remove_value() function modified

---

list_etexts.php
tools/post_proofers/smooth_reading.php

Inspired by [this post](https://developer.mozilla.org/en-US/docs/Web/RSS/Getting_Started/Syndicating#Adding_the_.3Clink.3E), I have added the relevant `link` tags which allow RSS feed readers to determine which RSS feed is connected to that page. 
If you open `/c/list_etexts.php?x=g` the extension detects the RSS feed and allows you to add it easily, which looks like this.
If you open the same page, you are able to choose the option "Subscribe to This Page..." which allows you to create a Live Bookmark.
- URL: `/c/list_etexts.php?x=g`
- Title of RSS Feed: `Completed Gold E-Texts`
- RSS Feed: `/c/feeds/backend.php?content=posted&type=rss`
- URL: `/c/list_etexts.php?x=s`
- Title of RSS Feed: `In Progress Silver E-Texts`
- RSS Feed: `/c/feeds/backend.php?content=postprocessing&type=rss`
- …

Add link tags for automatic detection of RSS feeds

---

tasks.php

A few lines after this one, the `SearchParams_echo_controls()` function is called which already prints:
<input type='hidden' name='action' value='search'>
So the removed line is a duplicate. Since it is a POST form, the duplicated input is overwritten, but if we edit it to use GET, the duplication is plain to see.
https://www.pgdp.net/c/tasks.php?action=search&action=search...
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Remove duplicate hidden input tag for task search

---

pinc/PageUnformatter.inc

Treat this in same way as a number reference. Change only an upper case letter to *.

When adjusting footnotes allow a lower-case letter reference

---

tasks.php

This is done for two reasons:
1. We want to clear the POST data so that by refreshing the user does not get the awkward Confirm Form Resubmission prompt.
2. After the Me Too request is finished, the user should be redirected to `https://www.pgdp.net/c/tasks.php?action=show&task_id=TASK_ID` and not to `https://www.pgdp.net/c/tasks.php`.
Related task:
* https://www.pgdp.net/c/tasks.php?action=show&task_id=1715

Redirect Me Too request to the show task page

---

tasks.php

There are edge cases (mostly through URL manipulation) where search_text may not be set. This handles those cases more gracefully.
This was found from the daily php_errors report from pgdp.net.

Only use search_text if it has been passed

---

pinc/theme.inc

Proofreading and formatting summary PDFs exist for French as well
as English, so those documents need to be routed through the new
FAQ language redirection interface.

Redirect proofing/formatting summaries

---

SETUP/db_schema.sql
SETUP/upgrade/12/20180822_alter_user_project_info.php
pinc/user_project_info.inc
project.php
tools/upload_text.php

Based on this task: https://www.pgdp.net/c/tasks.php?action=show&task_id=1615
It adds a new event called `sr_posted` which is fired every time someone uploads a new smooth reading report. The event is subscribable and off by default. Only the post proofer of that specific project can subscribe to the event.

Add ability to subscribe to SR reports

---

tools/upload_text.php

Right now users can uploaded non-zip files by just renaming the file with a .zip extension. This validates that the files uploaded are valid zip files.

Validate uploaded zip files are actually zip files

---

tools/proofers/preview.js

Remove any tags in the string before testing for all upper case. An all-upper-case small-cap string should be shown as small caps, but if it contains any lower-case characters it will be shown Upper-case with the lower-case chars as small caps.

Improve identification of all upper-case small-cap string

---

SETUP/db_schema.sql
SETUP/dp.cron.template
SETUP/upgrade/12/20180908_alter_user_project_info.php
crontab/finish_smoothreading.php
pinc/user_project_info.inc

Based on this task: https://www.pgdp.net/c/tasks.php?action=show&task_id=1317
It adds a new subscribable event `sr_complete` which fires when the project finishes smooth reading. The event is triggered by the crontab script `finish_smoothreading.php` which queries projects whose `smoothread_deadline` is within this interval `[current time - 1 hour, current time + 1 hour]` and then checks if the smooth reading deadline coincides with the current time (same year, month, day and hour). If it does, the script logs an event specifying the smooth reading period has ended and fires the `sr_complete` event. 
The script runs **hourly** and has a precision of up to an hour, meaning that 7:00 == 7:59 so it could potentially send a premature email.
We could add an artificial delay, for example by …

Add ability to subscribe to SR end event

---

pinc/DifferenceEngineWrapper.inc
pinc/prefs_options.inc
tools/proofers/PPage.inc
tools/proofers/spellcheck_text.inc

Now that all (modern) web browsers can use DPCustomMono2 because it's a web font, it's being used in a few places that many users don't expect although they aren't new. This changes those places to use the user's preferred proofreading font instead, giving them control over what is used and making it consistent in several places.

Don't hard-code DPCustomMono2 anywhere

---

pinc/html_page_common.inc
pinc/js_newwin.inc
pinc/metarefresh.inc
pinc/slim_header.inc
pinc/theme.inc
quiz/generic/wizard/checks.php
quiz/small_theme.inc
tools/authors/add.php
tools/authors/manage.php
tools/project_manager/page_table.inc
tools/proofers/button_menu.inc
tools/proofers/hiero/table.php
tools/proofers/processtext.php
tools/proofers/srchrep.php

At pgdp.net we have a script that runs daily and reports on any errors in `php_errors.log`. For *months* we have been getting errors like the below which make no sense:
```
1   PHP Notice:  Undefined variable: completed_projects_forum_idx in /data/htdocs/c/pinc/project_states.inc on line <num>
1   PHP Notice:  Undefined variable: deleted_projects_forum_idx in /data/htdocs/c/pinc/project_states.inc on line <num>
1   PHP Notice:  Undefined variable: posted_projects_forum_idx in /data/htdocs/c/pinc/project_states.inc on line <num>
6   PHP Notice:  Undefined variable: pp_projects_forum_idx in /data/htdocs/c/pinc/project_states.inc on line <num>
1   PHP Notice:  Undefined variable: site_supports_corrections_after_posting in /data/htdocs/c/pinc/project_states.inc on line <num>
1   PHP Notice: …
```

Fix php errors caused by includes on login redirects

---

tools/project_manager/edit_common.inc

Image sources can be created with arbitrary alpha-numeric codes, including all-numeric codes like `0`. All-numeric codes mess up the image source selection drop-down due to how php associative arrays work. This fixes the drop-down problem. Ultimately we should fix the image sources design to hide the code from the user since it's an internal-only field.
This is Task 1657.

Allow selection of image sources with numeric codes

---

pinc/forum_interface.inc

phpBB3 supports various types of avatars:
* uploaded - the "normal" way of uploading an image
* gravatar - pointing to a gravatar avatar via email address
* remote - pointing to a remotely-hosted image
This enables support for the latter two inside the DP code if it has been enabled in phpBB.

Support remote and gravatar avatars for phpBB

---

tools/proofers/for_mentors.php

This enables mentors to identify different users, see task  #1729
This change is in accordance with the Privacy Statement

Names of anonymous users now visible on mentors page

---

pinc/ProjectSearchForm.inc
pinc/ProjectSearchResults.inc
pinc/ProjectSearchResultsConfig.inc
tools/project_manager/projectmgr.php
tools/search.php

Changed back to GET instead of POST for project search so that searches can be bookmarked.
Add an invert filter checkbox for the language selector so that it is possible to search for all languages except a few. Otherwise selecting most of the language options would make the url too long. The other multi-selects do not have this problem because there are fewer options. This also simplifies the code slightly.

Pm new get

---

SETUP/tests/UserTest.php
accounts/activate.php
pinc/User.inc
stats/includes/common.inc
stats/members/mdetail.php
tasks.php

To reduce the possibility of bugs, make User->load() private. This ensures that an object can only be loaded by the constructor (or the two new static functions), and prevent the case where a developer
has created a loaded object and then loaded different data into part, but not all, of it.
This mirrors what the new NonactivatedUser class does.

Make User->load() private

---

pinc/theme.inc

We should only birthdays for users who have their privacy preferences set to public.

Exclude birthdays for 'anonymous' users

---

pinc/User.inc

Include 'Family' in the 'Friends' referrer option.

Include family in friends referrer

---

pinc/user_project_info.inc

This missed break caused the notification message body for sr_reported events to include sr_complete text as well.

Fix missed break in switch syntax for sr_reported

---

tasks.php

* https://www.pgdp.net/c/tasks.php?search_text=abcdefg
* https://www.pgdp.org/~mlazaric/c/tasks.php?search_text=abcdefg
* https://www.pgdp.org/c/tasks.php
* https://www.pgdp.org/~mlazaric/c/tasks.php

Fix two small visual bugs on tasks page

---

tools/site_admin/copy_pages.php
tools/site_admin/delete_pages.php
tools/site_admin/index.php
tools/site_admin/rename_pages.php

This pulls `noncvs/delete_pages.php` into the code proper. While here I standardized the output & styles some across the copy/rename/delete tools so they look less odd. They still make liberal use of `<pre/>` tags, but such is the life of an admin.

Pull delete_pages tool from noncvs and standardize tool styles

---

pinc/base.inc
pinc/misc.inc
stats/members/mdetail.php

Validate tally_name at the top of the mdetail page instead of letting the error show up later in the page render.
This was in the php_error logs.

Enforce tally_name values for mdetail page

---

accounts/activate.php
accounts/addproofer.php
pinc/theme.inc
project.php
stats/includes/team.inc
stats/stats_central.php
tasks.php
tools/mentors/view_page_text_image.php
tools/post_proofers/ppv_report.php
tools/project_manager/project_quick_check.php
tools/project_manager/remote_file_manager.php
tools/proofers/mktable.php
tools/proofers/my_projects.php
tools/proofers/review_work.php
tools/site_admin/copy_pages.php
tools/site_admin/delete_pages.php
tools/site_admin/edit_mail_address_for_non_activated_user.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/rename_pages.php
userprefs.php

HTML5 supports the new 'required' attribute on HTML form elements that are required to submit the form. The browser won't allow the page to be submitted until the element is filled in. This doesn't negate the necessity for server-side validation, but it does provide a nicer user experience.

Add 'required' attribute to HTML form elements

---

SETUP/MediaWiki_extensions/hospitalExtensions.php

This updates the MediaWiki hospital extension such that it includes HTML tags in the hospital comments like `noncvs/project_hospital.php` does.

Allow HTML tags in project hospital

---

SETUP/dp.cron.template

SR completion notifications run once an hour and send notifications for any projects that finish SR within that hour, even if the projects won't finish SR until the end of the hour after the job runs. To minimize the chances that the notification will be sent out before the project actually leaves SR, do the notifications at the end, rather than the beginning, of the hour.
This moves the notifications to be sent out at 55 minutes after the hour rather than 3 minutes after the hour.

Do SR completion notifications at end of the hour

---

SETUP/CHANGELOG.md
SETUP/installation.txt

Documentation updates for the 201903 release. I've confirmed that the DB schema upgrades are correct, we just need to update the docs and cut the release.

Prepare to cut the 201903 release

---

pinc/ProjectSearchForm.inc
pinc/misc.inc
stats/members/mbr_list.php
stats/teams/tlist.php
tasks.php

Creates a new `search_safe` function that replaces each run of whitespace characters with a single space. It normalises tabs to a single space, multiple spaces to a single space etc.
Code is live here: https://www.pgdp.org/~mlazaric/c/
- Uses `search_safe` when exact search is not checked: 
https://www.pgdp.org/~mlazaric/c/stats/members/mbr_list.php?uname=+++++test+++&uexact=no
- Doesn't use `search_safe` when exact search is checked: 
https://www.pgdp.org/~mlazaric/c/stats/members/mbr_list.php?uname=+++++test+++&uexact=yes
- Always uses `search_safe`: 
https://www.pgdp.org/~mlazaric/c/stats/teams/tlist.php?tname=+++++test+++&texact=no
https://www.pgdp.org/~mlazaric/c/stats/teams/tlist.php?tname=+++++test+++&texact=yes
https://www.pgdp.org/~mlazaric/c/stats/teams/tlist.php?tname=+++++Aussi …

Normalise whitespace characters in searches

---

tasks.php

When a user comments on a task, subscribe them to it for future comments or changes.
Task 1743

Subscribe user to task after commenting

---

pinc/ProjectSearchResults.inc
pinc/filter_project_list.inc

Change to NATURAL JOIN in ProjectSearchResults.inc so genre is not ambiguous.
Move maybe_create_temporary_genre_translation_table() in filter_project_list.inc so it is called
in all necessary cases.

fix two bugs

---

pinc/ProjectSearchResults.inc

When selecting the primary sort on a column which was previously the
secondary sort column, set secondary to the previous primary.

Avoid secondary sort column being same as primary

---

.travis.yml
SETUP/tests/MARCRecordTest.php
SETUP/tests/NonactivatedUserTest.php
SETUP/tests/PageCompareTest.php
SETUP/tests/README.md
SETUP/tests/SettingsTest.php
SETUP/tests/UserTest.php
SETUP/tests/misc_ParamValidatorTest.php

Our phpunit tests were created against phpunit4. phpunit6 introduced an updated, and backwards-incompatiable, namespace which was backported to phpunit5.7 (the last phpunit release to support PHP 5.x). This commit updates our tests to work with phpunit 5.7, 6.x, and 7.x.
phpunit6 also started flagging tests that did not do useful asserts as "risky", which they are since tests should assert that something useful was validated.
As part of this, I've updated the version of phpunit on the TEST server in `/usr/bin/phpunit` to be phpunit6 (was phpunit4). phpunit6 is the last to support PHP 7.0 which is what the TEST server is running. And if you are getting a headache trying to keep all of this in your head, you're not alone.

Update tests to work with phpunit >=5.7 and <8

---

default.php
pinc/walkthrough.inc

Now that the walkthrough is available in French, lets do some smart language redirection and set up a consistent per-language structure for possible future expansion.

Add language redirect for walkthrough

---

SETUP/CHANGELOG.md
SETUP/installation.txt
pinc/base.inc

The new minimum PHP version going forward is 7.0. This obviates the need for `undo_all_magic_quotes()` since magic quotes do not function after PHP 5.3.
Tagging all active developers to make sure everyone is aware of this change.

Set minimum PHP version to 7.0

---

tasks.php

This pulls in a few CSS/layout and behind-the-scenes changes to the Task Center:
* Slight changes to the page layout for better consistency. This also greatly simplifies some of the code that generates the votes / me too data.
* Uses fewer tables within tables in the layout.
* Consistently use a single `mysqli_query()` wrapper function throughout the code.
* Updates the task notification messages to contain more relevant information.
Some before/after links to show various changes:
* Open task: [new](https://www.pgdp.org/~cpeel/c/tasks.php?action=show&task_id=2240) | [old](https://www.pgdp.org/c/tasks.php?action=show&task_id=2240)
* Open task with votes & me too data: [new](https://www.pgdp.org/~cpeel/c/tasks.php?action=show&task_id=12) | …

Various tweaks to the Task Center

---

tools/project_manager/remote_file_manager.php

When using Remote File Manager to do uploads, rather than aborting an upload due to an invalid filename let's create a valid one instead. This fixes task 1662.
This PR also changes to `zipinfo` to validate that the file uploaded was a valid zip file. We use this in other places in the codebase already and it is more robust than `file`.

Rename invalid filenames upon upload

---

pinc/DifferenceEngineWrapper.inc

The updated MediaWiki diff code in 1fe084781 uses the `wfDebug()`
function so we need to define it.

Define wfDebug() for MediaWiki diff code

---

pinc/wordcheck_engine.inc

This contains no functional changes. Instead, this is normalizes some of the code formatting, specifically:
* Ensure function comments are above the function, not in-between the definition and the open bracket.
* Start function brackets on a line by themselves
* Remove whitespace around parens and functions
* Add whitespace between parameter in a function decl or call

Normalize code style in WordCheck

---

project.php

If a project is in PP, use the project page load by the PPer to indicate
activity rather than waiting until _after_ 90 days have passed. This
will reset the counter for the 90-day notification to the PPer thus
deferring the notification.
[Task 1764](https://www.pgdp.net/c/tasks.php?action=show&task_id=1764)

Use project load to indicate PPer activity when in PP

---

SETUP/dp.cron.template
crontab/notify_old_pp.php
pinc/gettext_setup.inc
pinc/languages.inc
pinc/maybe_mail.inc
pinc/post_processing.inc

This refactors the cumbersome logic used to collate old projects for a PP and notify them into two parts:
* a function to fetch results from the database and collate them to a PP
* a function to notify the PPer of their old projects
This fixes a bug where the last PPer in the DB query was not notified (identified by @jmdyck in https://github.com/DistributedProofreaders/dproofreaders/pull/121).
Given the refactor, it might be easiest to review the full code rather than the diff.

Refactor and address bugs in PP notification

---

.travis.yml
SETUP/tests/phpunit_bootstrap.php
SETUP/tests/pinc_WordCheckEngineTest.php
pinc/RoundDescriptor.inc
pinc/wordcheck_engine.inc
tools/project_manager/show_current_flagged_words.php
tools/project_manager/show_project_stealth_scannos.php
tools/project_manager/show_project_wordcheck_stats.php
tools/proofers/spellcheck_text.inc

As part of updating WordCheck to support UTF-8 I realized that there are no unit tests for WordCheck. I stepped back to add some and realized that some of the WordCheck functions, notably `get_bad_words_for_text()` was not unit-testable.
This series of commits reorganizes some of the WordCheck functions such that they are testable and then ultimately actually tests them.

Add WordCheck unit tests

---

SETUP/db_schema.sql
SETUP/upgrade/13/20190813_alter_projects.php

postednum stores the eBook number from PG. unsigned smallint only stores 65535 and PG is up to eBook 60000 already. Bumping this up to an unsigned mediumint keeps us good until eBook 16777215.
I ran this on TEST and it worked as-expected.

Increase size of projects.postednum column

---

pinc/showavailablebooks.inc
pinc/theme.inc

Show PPers in the UI projects that haven't been visited since the threshold. This pairs with the changes to the monthly PP notify script.
I do have a slight concern that putting the number of past-threshold projects in the navbar will be a performance hit for PPers. I put that in as a separate commit in case it becomes a problem and we need to roll it back.

Visually notify PPers of projects needing attention

---

tools/project_manager/remote_file_manager.php
tools/upload_text.php

For zip file uploads, tell the browser that we accept .zip files
to prevent the user from selecting a file that isn't a .zip file
(assumimg the browser supports it).

Prompt the user to upload .zip files

---

crontab/import_pg_catalog.php

"preg_match() returns 1 if the pattern matches, 0 if it does not, or FALSE if an error occurred."
So by comparing the result to FALSE, we're only detecting when an error occurs (which is probably never), rather than detecting a simple failure of the pattern to match.
Instead, just check if the result is falsy (covering both 0 and FALSE).
[This tweak is already in place on pgdp.net.]

Tweak condition for skipping unrecognized filenames

---

tools/proofers/previewControl.js

Remove Object.values() which doesn't work in IE

---

tools/site_admin/copy_pages.php

Newer MySQL versions are more strict on data types, in particular
assigning integer columns to "", which use to change into 0s, now
raises an error. Update copy_pages to assign *_time columns a
value of 0 instead of "".

Correct values for integer columns in copy_pages

---

styles/layout.css
styles/layout.less
tools/proofers/character_selector.js

This fixes two issues found on old browsers:
In Firefox 52 on windows XP the characters are very wide making the picker block too wide.
Firefox < 45 does not support innerText, using textContent instead which makes no difference in this context.

Picker fix 1

---

SETUP/upgrade/13/20190929_update_user_project_info.php
pinc/DPage.inc
pinc/user_project_info.inc

Don't update user_project_info.t_latest_page_event upon page checkout
or return to round. This allows a user to "try out" a page in a project
and return it without it being added to their My Projects page.
[Task 1208](https://www.pgdp.net/c/tasks.php?action=show&task_id=1208)

Don't update user_project_info on checkout/return

---

pinc/PageUnformatter.inc

This fixes a problem where Illustration markup immediately followed by a newline as required for block quote markup is  not removed. See forum post [https://www.pgdp.net/phpBB3/viewtopic.php?p=1181037#p1181037]

spaces after illustration etc. removed

---

pinc/user_is.inc

Correctly indicate that a user has DU access if they have PPV access.

All PPV users have de facto DU access

---

SETUP/db_schema.sql
SETUP/upgrade/13/20191019_alter_project_state_stats.php
SETUP/upgrade/13/20191019_alter_site_tally_goals.php
crontab/log_project_states.php
stats/jpgraph_files/cumulative_month_proj.php
stats/jpgraph_files/curr_month_proj.php

project_state_stats already includes a date column so there's no need to store additional year/month/day columns with the same data. Instead just use the right SQL in the stats queries.
Most importantly, use a valid default value for the date field.
I found this while working on Unicode conversion. MySQL got unhappy when it tried to update the encoding on this table with an invalid date default.

Remove duplicate fields from project_state_stats

---

tools/proofers/dp_proof.js

This simplifies the javascript code for inserting and transforming text. It removes the complexity to handle very old browsers.
It fixes the issues in tasks 1747 and 1749 and should simplify things we may want to do in the future such as retaining the selection and character insertion in wordcheck.
It should not otherwise make any difference to anything.

New proof 1

---

tools/proofers/preview.inc
tools/proofers/preview.js
tools/proofers/previewControl.js

This adds a "text" mode where inline markup (i, b, f g,u)  is replaced by a single character to show how text will appear in the "plain text" version of the book to get correct alignment of tables etc. Small caps markup is not marked in this way. "Wrap" is now a checkbox so that the Text mode can be used with or without re-wrapping.

Text format

---

tools/proofers/dp_proof.js
tools/proofers/dp_scroll.js
tools/proofers/spellcheck_text.inc

This implements task 1295 to enable the character pickers to work in the editable wordcheck boxes.

Enable character pickers to work in wordcheck

---

tasks.php

Add Edge and Chrome/Chromium to the list of browsers in the task center (this is in response to [Task 1785](https://www.pgdp.net/c/tasks.php?action=show&task_id=1785)).
While we're here, add a category for Format Preview.

Add Edge/Chromium & Format Preview to task center

---

tools/proofers/codepoint_validator.inc
tools/proofers/codepoint_validator.js

Suppose the user insert a combining diacritical mark. The text will
be normalised. 3 cases:
1, a good character results -- ok
2, a bad character results and will be marked.
3,  no more normal form exists and the diacritical itsef is marked
This is invisible so the user may not know what the bad character is.
This feature allows him to proceed.
Interestingly in php regexes \X matches a composed glyph but this
is not available in JS regex.
It would be possible to do this functionally but seems a lot of
work for little return.

Add a button to remove bad characters.

---

faq/font_sample.php
pinc/prefs_options.inc
quiz/generic/proof.php
tools/mentors/view_page_text_image.php
tools/proofers/button_menu.inc
userprefs.php

This centralizes code that returns the current proofreading font
style and size. This is in preparation for providing sane proofreading
font fallbacks.

Centralize proofreading font logic

---

pinc/DifferenceEngineWrapper.inc
pinc/prefs_options.inc
quiz/generic/proof.php
tools/mentors/view_page_text_image.php
tools/proofers/PPage.inc
tools/proofers/button_menu.inc
tools/proofers/dp_proof.js
tools/proofers/spellcheck_text.inc

If the browser doesn't have the specified font, fall back to something sensible.
This is most important for Safari and Chrome on macOS which don't show textareas in monospace fonts.

Specify a font-family to fall back to

---

pinc/MARCRecord.inc
tools/project_manager/external_catalog_search.php

php_errors on PROD have shown some cases where yaz_record() isn't returning an array, making MARCRecord very sad. We should skip those errors at the source.
Also handle an edge case where $marc_title isn't set (which is really cropping up because of the above error, but it seems sensible to handle here too).

Fix case where yaz_record() doesn't return array

---

faq/proofreading_guidelines.php
pinc/templates/comment_files/eets.txt
quiz/generic/data/qd_p_mod1_5.inc
quiz/generic/data/qd_p_thorn.inc
quiz/generic/quiz_defaults.inc
quiz/tuts/tut_p_aeoe_1.php
quiz/tuts/tut_p_thorn.php

The new character picker has replaced the character drop-down menus, but
we neglected to update all of the documentation.

Update doc refs to old character drop-down menu

---

pinc/post_processing.inc

Add a function to return the count of outstanding PPV projects over
the threshold, much like we have for PP. This is currently only
used in a noncvs script.

Add query to count PPV projects over threshold

---

pinc/user_project_info.inc
project.php
tools/change_sr_commitment.php
tools/upload_text.php

Here are all of the user-facing instances of `smooth reading`, `smooth-reading`, and `smoothreading` (even `smooth read`) that I found in the code.
I do wonder if in some of these places we should use `smooth read(ing)` with lowercase as the verb and `Smooth Reading` as a stage/noun. The former seems to read better alongside `proofread`/`proofreading` on the main page, for instance.

Standardize on Smooth Reading

---

faq/prooffacehelp.php
pinc/CharacterSelector.inc

Remove outdated paragraph in the proofreading interface help that discusses the old character selection UI and try to clarify the new character picker interface.

Fix wording about character picker in help

---

locale/translators/index.php
tools/upload_text.php

MAX_FILE_SIZE is relatively useless, as it isn't enforced on the browser side.
Ultimately it just leads to confusing messages. See also https://stackoverflow.com/questions/1381364/max-file-size-in-php-whats-the-point/1381422

Remove use of MAX_FILE_SIZE in form uploads

---

pinc/misc.inc

Zip files with Mac resource forks (ie: __MACOSX directories) fail validation when ZipArchive::CHECKCONS is used. The files still extract correctly so let's err on the side of less rigid checks knowing we an accept these zips with are not infrequent.

Don't do strict checks on zips

---

SETUP/INSTALL.md
SETUP/configuration.sh
SETUP/wikihiero-0.2.13.patch
tools/proofers/hiero/index.php

Add a patch file to make WikiHiero work with PHP 7.0 and update
the INSTALL.md file accordingly. Also change configuration.sh so
that it defaults to WikiHiero not being installed since it is an
optional tool.

Fix WikiHiero to work with PHP 7.0

---

pinc/project_quick_check.inc
tools/project_manager/bad_bytes_explainer.php

For the bad-bytes check, point to the round where the page text was pulled from, rather than just the OCR.
I suspect this will become more important later when we're using Unicode.
Task 1790

Point to round where PQC pulled the text

---

SETUP/upgrade/13/20191228_alter_page_events.php

past_tallies and page_events are the two largest tables on pgdp.net because they are constantly written to. Both contain indexes that are no longer used but are taking up disk space. For instance, the page_events index size is 2x the size of the data itself.
Drop the indexes on these tables that aren't used in queries against them as confirmed by explain plans.
This is done with an eye to the InnoDB conversion and later the Unicode conversion (although page_events is already InnoDB on PROD).

Drop redundant indexes

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md
SETUP/db_schema.sql
SETUP/upgrade/13/20191230_convert_to_innodb.php
pinc/DPage.inc

Create all non-project tables using the MySQL default engine. In MySQL 5.5 and later that changed to InnoDB. This also provides a script to convert tables to InnoDB.

Use default engine when creating tables

---

tools/project_manager/clearance_check.php
tools/project_manager/projectmgr.inc
tools/site_admin/index.php

Pull in the 3 different clearance check scripts from noncvs (`questionable_clearances.php`, `clearance_check.php`, `clearance_check2.php`) into one. This is only linked from the SA page, but PMs can access it too.

Add clearance check to PM tools

---

accounts/login.php
accounts/login_failure.php
pinc/forum_interface.inc
pinc/project_edit.inc
tools/project_manager/projectmgr.inc

Pass back the underlying phpBB failure reason to the DP login page.
Route the user to the forums if their maximum number of login attempts
were exceeded so they can log in through the CAPTCHA.
This is available for testing in the [phpbb3-login-improvements](https://www.pgdp.org/~cpeel/c.branch/phpbb3-login-improvements/) sandbox.

Pass back phpBB login failure reason to DP login

---

SETUP/apache2.conf.example
pinc/ProjectTransition.inc
project.php

For better privacy, don't save proofer's names in the CTF by default.
PMs and PPs can still access a CTF with proofer's names manually.
This also changes the final CTF to not include the proofer's names.
[Task 1806](https://www.pgdp.net/c/tasks.php?action=show&task_id=1806)
In the [ctf-default-no-usernames](https://www.pgdp.org/~cpeel/c.branch/ctf-default-no-usernames/) sandbox.

Don't save proofer names in CTF by default

---

pinc/button_defs.inc
tools/proofers/codepoint_validator.js
tools/proofers/proof_frame_enh.inc
tools/proofers/text_frame_std.inc

This addresses task DPUT 2250 where next image and text loads into right pane. This was because the target-changing code is executed but then wordcheck is not actually run. This task only executes the code if the validator succeeds and we actually do
wordcheck. Also move the h-v switch confirm so we do the
validation first.

Move the target-changing code into codepont_validator.js

---

SETUP/upgrade/13/20200127_fix_forum_topic_encoding.php
pinc/Project.inc
pinc/phpbb3.inc

phpBB encodes forum subjects before saving them to the database. We haven't been doing this since we moved over to phpBB3. Browsers appear to be forgiving the sin of not encoding the double quotes, but they draw the line at `>`s which breaks the rendering of project names with those in them.

Encode forum subjects when creating topics

---

pinc/html_page_common.inc
tools/proofers/codepoint_validator.js

This correctly highlights invalid characters with diacritical marks in the
validation view and removes them completely if required.
It also has code to enable use of valid glyphs with combining marks.

Handle combining diacritical marks

---

pinc/image_check.inc
pinc/project_quick_check.inc
tools/project_manager/add_files.php

Example where I forced every warning for > 50 bytes (so every image). It shows off rows with multiple warnings as well.

Add warning for images larger than 100 kibibytes.

---

tools/proofers/dp_proof.js

select modified text to allow further operations without reselecting text.

#1430: Firefox - retaining focus for multiple selections

---

styles/global.css
styles/global.less

Chrome 80 removed the 'appearance' attribute for <span>s:
https://developers.google.com/web/updates/2019/12/chrome-80-deps-rems
making the buttons just regular text on a screen.
The resumable.js docs say that we should use spans, however:
https://github.com/23/resumable.js#how-can-i-use-it
so we make our own "button like" styling. This, sadly, won't match any button for anyone in pretty much any browser on any OS because they all render them slightly differently, but at least it looks like a button.
Example screenshot:

Fix resumable upload buttons for Chrome 80

---

pinc/misc.inc

This addresses most of task 2262 [https://www.pgdp.org/c.unicode/tasks.php?action=show&task_id=2262](url). It allows various unicode whitespace characters but not zero width space.

Allow various unicode whitespace charcters

---

styles/layout.css
styles/layout.less

Make the buttons in the proofreading toolbox at least 2ems wide. This most notably affects the italics button.
[Task 1840](https://www.pgdp.net/c/tasks.php?action=show&task_id=1840)

Make toolbox buttons at least 2ems wide

---

project.php
tools/project_manager/page_table.inc

Adds an indicator to `/c/tools/project_manager/page_detail.php` of the WC status of each page. Useful for checking whether you ran wordcheck on each of your proofread pages.
- Relevant task: https://www.pgdp.net/c/tasks.php?action=show&task_id=1174
- Deployed at: https://www.pgdp.org/~mlazaric/c/
Currently it just prints `0` if it has not been wordchecked and `1` if it has:
Alternatively we could add a &check; (`&check;`) or &times; (`&times;`):
We could bold the items which weren't wordchecked or the ones that were:
We could add a new column which contains the WC status:
**Note:** this would mean one additional WC column per round so it would bloat the table.
- Should we add the WC status to the recently proofed pages?
- Should we treat it as a binary value (has been wordchecked / hasn't …

Add wordcheck status to diff page

---

pinc/codepoint_validator.inc
scripts/text_validator.js

Since there are also other invisible characters such as zero-width space
there is little point in automatically removing just one category.
The 'Remove bad characters and quit' button will remove them.
Add 'if possible' so the user knows there could be invisible bad characters.

Add 'if possible' and do not automatically remove invisible combining marks

---

pinc/Activity.inc
pinc/gradual.inc
pinc/page_tally.inc
pinc/stages.inc
pinc/user_is.inc

This MR is broken out into 3 separate commits, depending on how much of the R* code we want to pull out.
* dde2ab9 does the minimum amount needed for [Task 1842: P2 and F1 requirements still have old R1 and R2 pages as objectives](https://www.pgdp.net/c/tasks.php?action=show&task_id=1842).
* 90de3dc goes one step further and removes the references from the R* rounds from the beginner project exclusion and the "how many pages have you done" exclusion. This one makes sense to pull in as well.
* aee25fc is the last and final step of removing all reference to the R* rounds from the code -- this pulls out all access to R* statistics. I'm dubious of how useful these stats are at this point, but I can see some arguments for keeping them in.

Remove R* references from the code

---

tools/project_manager/diff.php

Adds a checkbox which allows users to skip empty difference pages when going to the previous or the next difference page. 
- Relevant task: https://www.pgdp.net/c/tasks.php?action=show&task_id=1518
- Deployed here: https://www.pgdp.org/~mlazaric/c/
Currently it hides the empty differences from the dropdown as well, but we can change it to display them normally or display them as disabled options.
Page `079.png` is an empty difference and it is not shown.

Allow users to skip empty difference pages (task 1518)

---

pinc/CharSuites.inc
pinc/CharacterSelector.inc
pinc/Project.inc
pinc/Quiz.inc
pinc/codepoint_validator.inc
quiz/generic/main.php
quiz/generic/proof.php
tools/proofers/ctrl_frame.php

pickerset and valid_codepoint functions moved out of project.inc
so we can use them if there isn't a project.
New function to construct charsuites for quizes.

Enable diacritical markup conversion in quizes

---

crontab/notify_old_pp.php
pinc/access_change_emails.inc
pinc/gettext_setup.inc

Rather than making every instance determine the desired user's locale and then setting it, create a wrapper function that does it as well as handle the global variables.
This then makes email composition something like:
```
// switch to recipient's locale
configure_gettext_for_user($username);
// build the email
$body = _("Hello fellow human!");
maybe_email(... $body ...);
// restore current user's locale for any future messages
configure_gettext_for_user();
```

Simplify configuring gettext for user emails

---

quiz/generic/main.php
quiz/generic/quiz_page.inc

When the quizzes were refactored to use `slim_header_frameset()` we didn't account for it already prefixing `$site_abbreviation` and thus it is being prepended twice.

Don't duplicate site_abbreviation on quiz titles

---

pinc/MARCRecord.inc
tools/project_manager/external_catalog_search.php

Ensure that Z29.50 results are always returned in UTF-8. Servers seem to ignore our request, so convert the encodings when pulled from the MARCRecord.
This is available in my [fix-loc-utf8-lookups](https://www.pgdp.org/~cpeel/c.branch/fix-loc-utf8-lookups) sandbox.

Return UTF-8 strings for MARCRecords

---

SETUP/Makefile
SETUP/lint_charsuites.php
SETUP/tests/UnicodeTest.php
pinc/CharSuites.inc
pinc/unicode.inc

This validates that all codepoints in a character suite are normalized to prevent non-normalized characters from being inserted into proofreading texts and confusing the user when validation fails, among other things.

Validate codepoints in a charsuite are normalized

---

pinc/DPage.inc
pinc/bad_bytes.inc
pinc/project_quick_check.inc
tools/project_manager/bad_bytes_explainer.php

This is a re-make of a similar branch but using the new unicode functions.
It shows multiple codepoints as well as bytes in the Bad Bytes tables in PQC.
Bad sequences are handled separately from invalid codepoints; this simplifies distinguishing the nature of the badness.
For Add Page it shows complete combined characters if present and title names for the bad characters.
BOM handling is also improved.

Allow for combined characters in project_quick_check and Add files

---

pinc/Project.inc
project.php
tools/project_manager/add_files.php
tools/project_manager/handle_bad_page.php
tools/site_admin/convert_project_table_utf8.php
tools/site_admin/copy_pages.php
tools/site_admin/index.php

Prevent changes to project tables that have not yet been converted to
UTF-8. This is mostly for the rare circumstances where projects created
before the conversion are unarchived. For these tables, provide an admin
tool to convert the table.
You can see how this works with the [Aspazio project](https://www.pgdp.org/~cpeel/c.branch/project-table-encoding-checks/project.php?id=projectID4fd62bf9ac045&detail_level=3) in my [project-table-encoding-checks](https://www.pgdp.org/~cpeel/c.branch/project-table-encoding-checks) sandbox.

Add checks to ensure project tables are UTF-8

---

SETUP/configuration.sh
crontab/notify_old_pp.php
pinc/Project.inc
pinc/ProjectTransition.inc
pinc/access_change_emails.inc
pinc/maybe_mail.inc
pinc/site_vars.php.template
pinc/user_project_info.inc
tasks.php
tools/modify_access.php
tools/post_proofers/ppv_report.php
tools/project_manager/manage_image_sources.php

Standardize email footers, and statement about automated messages, across the codebase. For pgdp.net, the footer would look like:
```
--
Distributed Proofreaders
http://www.pgdp.net
This is an automated message.
```
This was in response to an SA conversion in Slack. You can test this out in the [tweak-mail-footer](https://www.pgdp.org/~cpeel/c.branch/tweak-mail-footer/) sandbox.

Standardize email footer

---

project.php
tools/project_manager/page_table.inc

Remove the WordCheck status from formatting rounds. Also make the X less bold.
[Task 1855](https://www.pgdp.net/c/tasks.php?action=show&task_id=1855)
Available in [no-wc-indicators-in-formatting](https://www.pgdp.org/~cpeel/c.branch/no-wc-indicators-in-formatting) sandbox.

Remove the WordCheck status from formatting rounds

---

SETUP/db_schema.sql
SETUP/upgrade/14/20200322_alter_rules.php
pinc/RandomRule.inc
pinc/RandomRule.md

Increase the size of the subject field for random rules and ensure that we don't try to add data into subject or anchor that are larger than the field.
Available in the [long-random-rule-subjects](https://www.pgdp.org/~cpeel/c.branch/long-random-rule-subjects) sandbox.

Increase size of 'subject' field for Random Rules

---

SETUP/UPGRADE.md
pinc/base.inc

When maintenance mode is enabled the upgrade scripts won't run because `base.inc` will bail out. Allow scripts to override the maintenance check to enable upgrades to run.
I stumbled into this during the InnoDB conversion earlier in the year. This ensures that I don't have to hack this into the code again for the Unicode update.

Allow bypassing maint mode for upgrade scripts

---

SETUP/configuration.sh
SETUP/tests/travis-ci_configuration.sh
pinc/site_vars.php.template
tools/project_manager/editproject.php

Instead of defaulting to basic-latin, allow sites to specify their own default character suites for new projects.
This seemed like a small but useful change for other sites. `SETUP/UNICODE.md` doesn't exist yet but will ... soon.

Allow sites to define default character suites

---

styles/layout.css
styles/layout.less
tools/proofers/proof.php

Wide characters are currently getting cut off in the character picker (particularly in Firefox and Safari). Changing this to DejaVu Sans Mono ensures that they will all fit into the box and makes the characters look more like what they will look like in the monospace proofreading box.
I also tweaked the frameset for the proofreading toolbox so the entire picker shows up. I tested this on Chrome, Safari, and Firefox. This is available in the [dvsm-picker](https://www.pgdp.org/~cpeel/c.branch/dvsm-picker) sandbox.

Use DejaVu Sans Mono for character picker font

---

SETUP/apache2.conf.example
project.php
sitemap.php

Add a sitemap we can submit to search engines so they can reasonably index our site. Note that most of our pages require a login, so mostly these are project pages.
On the project pages, include LD+JSON metadata so search engines can glean a bit more structured data about the page.

Add a sitemap; also add metadata to project pages

---

pinc/LPage.inc
pinc/RoundDescriptor.inc
pinc/TallyBoard.inc
pinc/daily_page_limit.inc
pinc/stages.inc
project.php
tools/proofers/PPage.inc
tools/proofers/processtext.php

Each round optionally gets a daily limit on the (net) number of pages saved-as-done in that round.
This is a simplified version of PR #204. There, each DPL defines the set of projects that it applies to, based on any project properties; here, the only option is for a DPL to apply to all the projects of a round. So the 'back-end' is simplified, but the 'front-end' is, in practice, pretty much identical.
The messages to the user could probably be made shorter. I'll leave it to the reviewers to suggest specific wording.

Daily Page Limit Per Round

---

SETUP/lint_charsuites.php
pinc/charsuite-extended-european-latin.inc

Tony Browne discovered that we had a deprecated character in the Extended Latin pickerset. Worst yet we didn't have it in the character suite! This removes it and adds validation to ensure pickersets only contain characters within the character suite.
I confirmed this correctly failed before I fixed the Extended Latin charsuite.

Validate pickersets

---

pinc/project_quick_check.inc
tools/changestate.php
tools/project_manager/project_quick_check.php

Prevent projects from transitioning from NEW to P1.unavailable if PQC finds any errors.
This therefore changes the Bad Bytes check to output 'Error' instead of 'Warning'. This does involve a fair amount of out and back again redirecting using encoded URLs within encoded URLs and there is a nominal maximum URL length of ~2k characters. I don't think we're getting close to this limit but it is something I worry about.
This is available in the [pqc-in-transition](https://www.pgdp.org/~cpeel/c.branch/pqc-in-transition/) sandbox.

Require transitions to P1.unavail to pass PQC

---

SETUP/tests/UnicodeTest.php
SETUP/tests/pinc_WordCheckEngineTest.php
pinc/DPage.inc
pinc/unicode.inc
pinc/wordcheck_engine.inc

This implements two updates to WordCheck:
* Correctly parse words that contain combining characters. (oops)
* Detect if words contain a mix of Unicode script characters and if so, flag them as bad words.
I _really_ expected aspell to detect that second one, but no, it ignores them as "invalid words". Thanks aspell.
While I was here I broke out the diacritical markup flagging into its own function.
This is available in the [wc-multi-script](https://www.pgdp.org/~cpeel/c.branch/wc-multi-script) sandbox.

Further WordCheck updates for Unicode

---

tools/proofers/for_mentors.php

By PF / Mentor request: It's useful for Mentors to see projects that aren't yet available in the mentoring round when evaluating which projects to work on next.
This is available in the [for-mentor-tweaks](https://www.pgdp.org/~cpeel/c.branch/for-mentor-tweaks) sandbox.

Add projects in waiting state for Mentors

---

scripts/character_test.js
scripts/text_validator.js
tools/proofers/process_diacritcal_markup.js

IE doesn't implement "u" flag in regular expressions. We don't need it for the validCharacterPattern if we're not using astral plane characters.
IE also doesn't do normalise. This means in IE the square bracket diacritical conversion won't work (but ligature conversion will). Also the character validation will not normalise, so if for example you put in an Angstrom symbol it would normally get normalized to A with ring above which could be a valid character but this will not happen.
This fix just avoids javascript errors.

improve performance internet explorer

---

pinc/base.inc

Present a better error message to users -- and internal logging -- if we have DB connection problem and the site isn't in maintenance mode. This edge case should never happen, but if it does logging it is very useful.
You can see this in the [log-db-connection-failures](https://www.pgdp.org/~cpeel/c.branch/log-db-connection-failures/) sandbox.

Provide better logging on DB connection failures

---

pinc/mentorbanner.inc

Update the mentors banner to point to the for_mentors.php page (as requested by the GM) as well as being less obnoxious. This also moves the banner to immediately under the news on the round pages to match the Activity Hub.
This can be seen in the [for-mentors-tweak](https://www.pgdp.org/~cpeel/c.branch/for-mentors-tweak) sandbox.

Update mentors banner to be less obnoxious

---

SETUP/CHANGELOG.md

This updates `CHANGELOG.md` with the changes in `master` since the R202002 release. As stated in the CHANGELOG header, this isn't intended to be *everything* that has changed, but notable things that an upgrading user might want to know about in roughly importance order.
I welcome feedback on if there are things on this list that shouldn't be here, things that should be that aren't, or wording changes to what is already here.

Update CHANGELOG from before UTF-8 merge

---

SETUP/ARCHIVING.md
SETUP/INSTALL.md
SETUP/README.md
SETUP/configuration.sh
SETUP/dp.cron.template
SETUP/upgrade/14/20200511_convert_archive_db_to_utf8mb4.php

After reviewing remaining UTF-8 bits, I realized I had overlooked converting the `page_events` and `wordcheck_events` tables in the archive database. Which then lead me to realize that we don't talk about creating those tables anywhere.
This MR includes:
* A commit to convert the non-project tables in the archive database to UTF-8, since we will be inserting new values in that from UTF-8 tables in the main database.
* A new `ARCHIVING.md` file describing how to set up project archiving.

Document project archiving

---

SETUP/upgrade/14/20190818_convert_db_to_utf8mb4.php
SETUP/upgrade/14/20190819_convert_project_tables_to_utf8mb4.php
SETUP/upgrade/14/20200511_convert_archive_db_to_utf8mb4.php
pinc/Project.inc

Unarchived posted projects are used by evaluators, so they also need to be converted to UTF-8. This makes archived projects the only ones that are not converted.
This also adds @jmdyck's request for a more explicit stopfile name in all conversion files where one is used.

Convert posted projects to UTF-8

---

SETUP/README.md
SETUP/apache2.conf.example
SETUP/configuration.sh
SETUP/tests/pinc_WordCheckEngineTest.php
SETUP/upgrade/14/20191211_convert_project_text_files.php
SETUP/upgrade/14/20191211_convert_word_lists.php
pinc/unicode.inc
pinc/wordcheck_engine.inc
tools/charsuites.php
tools/site_admin/index.php
tools/site_admin/manage_site_word_lists.php

These are a few things that we discovered in yesterday's Unicode deployment or shortly thereafter. The two most notable code changes:
* Detect if writing out a converted text file fails and correctly report that back. Also provide some guidance to the user on permission during the upgrade scripts.
* UTF-8 normalize word lists upon save -- includes unit tests.

Variety pack of minor Unicode-related fixes

---

default.php
pinc/showstartexts.inc
pinc/theme.inc
styles/layout.css
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less

This addresses two mobile-layout related bugs:
* [Task 1884](https://www.pgdp.net/c/tasks.php?action=show&task_id=1884) - footer wraps and non-ideal Current Progress layout on the main page on very narrow screens.
* [Task 1872](https://www.pgdp.net/c/tasks.php?action=show&task_id=1872) - Retaining the "# preserved for the world!" text in the header as much as possible on mobile layout.
These can be seen in the [mobile-layout-updates](https://www.pgdp.org/~cpeel/c.branch/mobile-layout-updates) sandbox.

Mobile layout updates

---

project.php

For task 1893. Input is too narrow for Firefox on Linux.
Not really our problem but doesn't hurt to widen it.

Make number input wider

---

SETUP/lint_charsuites.php
pinc/DPage.inc
pinc/charsuite-basic-greek.inc
pinc/charsuite-basic-latin.inc
pinc/charsuite-extended-european-latin.inc
pinc/charsuite-polytonic-greek.inc
pinc/unicode.inc

Add two new validation checks for character suites in the code:
1. The suites do not contain characters that we convert on page save.
2. The suites use lowercase hex values to match what portable-utf8 provides with `utf8_chr_to_hex()`.
This MR is all non-functional changes outside of the linting. I have also confirmed via case-insensitive diff that the character suites before and after are identical outside of case.
These two functions in `unicode.inc` will be used in the per-project custom suites as well.

Better charsuite validation

---

SETUP/UNICODE.md
pinc/CharSuites.inc
pinc/CharacterSelector.inc
tools/charsuites.php

It occurred to me that some sites may not want to restrict characters to character suites. This provides documentation and some very small code changes to allow defining **very** broad suites to the same effect.

Updates to allow bypassing character suites

---

tools/post_proofers/ppv_report.php

To ensure the right character set and locale are used for PPV report use `configure_gettext_for_user()` instead of `setlocale()`.

Correctly change locale in PPV report

---

pinc/maybe_mail.inc

When maybe_mail() is called we are not guaranteed to be using the
recipient's language in order to correctly translate the footer.
Rather than sending out an email with a footer in an unexpected
language, always send it out in English -- so at least we're
consistently wrong when we're wrong.
Task 1898

Don't translate email footer

---

accounts/activate.php
pinc/User.inc
pinc/UserProfile.inc
pinc/misc.inc
userprefs.php

Abstract interaction with the `user_profiles` table into a separate class. This is building up to the removal of the `$userP` global (which I have completed in a branch off of this code).
Note: This is _not_ meant for merging until after the Unicode deployment happens and we decide to open up `master` for merging again. But I wanted to get some eyes on it while we wait for that.

Introduce UserProfile class

---

styles/preview.css
tools/proofers/preview.inc
tools/proofers/previewControl.js
tools/proofers/proof_frame_enh.inc
tools/proofers/text_frame_std.inc

This should not make any visible difference. Previously the same
effect was achieved using javascript.
This is a simplification.
One user reported that the preview controls were not visible in the new Edge browser which prompted me to look at this but the problem subsequently went away spontaneously.

Change format preview to use flexbox

---

tools/project_manager/edit_common.inc
tools/project_manager/editproject.php

Make postednum a number field and correctly enforce its value during validation. Previously invalid values would raise a database error as MySQL can't fit a string into an integer field.
Available in the [enforce-postednum-type](https://www.pgdp.org/~cpeel/c.branch/enforce-postednum-type) sandbox.

Enforce postednum format

---

SETUP/lint_charsuites.php

Character suite codepoints can either be specified in ranges or
individually. Individual specs can also have combining characters
but ranges cannot. Enforce this in the linter.

Add linting for combining and range codepoint specs

---

pinc/Project.inc
project.php
tools/project_manager/displayimage.php
tools/proofers/images_index.php

`displayimage.php` and `images_index.php` return a database error if the project table for the requested project doesn't exist. This MR abstracts out querying for project pages into the Project class and raises appropriate exceptions if the project table or directory doesn't exist.
This is available in the [no-project-table](https://www.pgdp.org/~cpeel/c.branch/no-project-table) sandbox.

Handle missing project tables better

---

quiz/start.php

Allow PFs and SAs to easily see quiz results for another user. This is most useful for PFs who need to respond to volunteer requests.
This is available in the [quiz-results-for-user](https://www.pgdp.org/~cpeel/c.branch/quiz-results-for-user) sandbox.

Allow SA/PFs to see quiz results for other users

---

pinc/charsuite-basic-latin.inc
tools/charsuites.php

Added florin sign to the Basic Latin character suite.
Removed micro sign and capital and small letter S and Z with caron
from pickersets. Reorganized pickersets.
Added title text display to pickerset display on character suite
details pages.
The changes to the picker sets were organized by DP user 
bunny-crunch and reviewed by the DP community.

Reorganized Basic Latin pickersets

---

pinc/DPDatabase.inc
pinc/Quiz.inc

This improves escaping for the quiz queries. It does so by introducing two new static methods in `DPDatabase` that wrap some common functionality. I wanted to get a wider set of eyes on it to see if these look reasonable to build off of elsewhere in the code before pulling them in.
Notably we can now escape queries in SQL with:
```php
DPDatabase::escape($value)
```
instead of:
```php
mysqli_real_escape_string(DPDatabase::get_connection(), $value)
```
And the new `DPDatabase::query($sql)` method will automatically log query errors and optionally raise an exception if the query fails.
So we could use this:
```php
$result = DPDatabase::query($sql);
```
instead of:
```php
$result = mysqli_query(DPDatabase::get_connection(), $sql) or die(DPDatabase::log_error());
```

Improve quiz query escaping

---

pinc/charsuite-extended-european-latin.inc

Based on research done by DP user bunny-crunch, and with input from
the forums, trimmed several characters from the Extended European
Latin character suite, and reorganized the picker sets.
See [extended-european-latin](https://www.pgdp.org/~srjfoo/c/tools/charsuites.php?charsuite=extended-european-latin) in my sandbox.

Updated EEL character suite and picker sets

---

api/dp-openapi.yaml
api/index.php
api/v1.inc
api/v1_projects.inc
pinc/ProjectSearchForm.inc

Building on top of the first part, this MR implements the project search endpoint as well as metadata endpoints to see valid values for the languages, genre, state, and difficulty fields.
Sample search query for two languages:
```
curl -i -g -H "Accept: application/json" -H "X-API-KEY: review" \
"https://www.pgdp.org/~cpeel/c.branch/api-part-1/api/index.php?url=v1/projects&languages[]=Afar&languages[]=Scots"
```
Query sorting descending by `pages_total`:
```
curl -i -g -H "Accept: application/json" -H "X-API-KEY: review" \
"https://www.pgdp.org/~cpeel/c.branch/api-part-1/api/index.php?url=v1/projects&sort=-pages_total"
```
Search results return an `X-Results-Total` header with the total number of search results and pagination links just like [GitHub …

Implement API project search and project metadata endpoints

---

tools/charsuites.php

Wrap the characters that don't belong in a picker set. Rename some functions to better map the arguments we pass them.
Viewable in [wrap-nonpicker-characters](https://www.pgdp.org/~cpeel/c.branch/wrap-nonpicker-characters/).

Wrap characters not in a picker set

---

tools/project_manager/page_table.inc

After a page leaves the NEW phase, only allow PFs and SAs to delete pages.

Prevent PMs from deleting pages in the rounds

---

SETUP/upgrade/14/20200724_update_users_privacy.php
faq/pophelp/prefs/prefs_pophelp.inc
pinc/prefs_options.inc
pinc/privacy.inc
stats/includes/team.inc
stats/members/mbr_xml.php
stats/proof_stats.php
stats/teams/teams_xml.php
userprefs.php

Now that all statistics require a login to access, remove the public option and default everyone to private.
When new user records are created the `u_privacy` field defaults to `0`, which is why set `PRIVACY_PRIVATE` to have that value instead of leaving it at 2 and removing `PRIVACY_PUBLIC`.
Available in the [remove-public-stats](https://www.pgdp.org/~cpeel/c.branch/remove-public-stats) sandbox.

Remove public stats and make private the default

---

api/dp-openapi.yaml
api/v1.inc
api/v1_stats.inc

This builds on top of the other two MRs (again, into the `api` branch, not `master`). This adds very basic site and round statistics.
To get some basic statistics about the site:
```bash
curl -i -g -H "Accept: application/json" -H "X-API-KEY: review" \
"https://www.pgdp.org/~cpeel/c.branch/api-part-2/api/index.php?url=v1/stats/site"
```
To get round statistics:
```bash
curl -i -g -H "Accept: application/json" -H "X-API-KEY: review" \
"https://www.pgdp.org/~cpeel/c.branch/api-part-2/api/index.php?url=v1/stats/site/P1"
```
My primary question is: should the round statistics URL be `v1/stats/site/P1` or `v1/stats/site/round/P1`? Now that I'm looking at it afresh the second one seems better (although I have implemented the first one).

Implement API for site statistics

---

SETUP/tests/jsTests/srchrepTests.js
tools/proofers/srchrep.js

It is due to unicode changes. As part of unicode changes, we updated search replace to support unicode characters. We accomplish this search by using regular expressions (even for non regular expression searches). To prevent searches in non regular expression searches from accidentally stumbling into a valid or invalid regular expression, we used an encoding algorithm defined here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Escaping. You can see (not obviously) that it encodes '-' to '\\-'. This encoding is not necessary since we will never be in a character class restriction. Thus, it is called an identity escape. Here is where it gets fun. For unicode regular expressions, the javascript specification makes this escape an error (more strict). I …

Unicode strict identity escaping

---

accounts/addproofer.php
faq/privacy.php

Per GM, clarification updates for registration hints paragraph in
accounts/addproofer.php, and updates to faq/privacy.php.
Available for review at [https://www.pgdp.org/~srjfoo/c.branch/addproofer-privacy/accounts/addproofer.php](https://www.pgdp.org/~srjfoo/c.branch/addproofer-privacy/accounts/addproofer.php)

Updates for addproofer.php and privacy.php

---

pinc/charsuite-polytonic-greek.inc

Removed ASCII semicolon and mid-dot from character suite. Revised
picker sets: removed capital vowels with grave or acute accents
that don't have breathing marks; removed capital Alpha, Eta and Omega
with iota subscript/adscript alone or in combination with any other
marks. Changed picker labels for the pickers with diacriticals or other
marks to use the initial accented lower case picker letter. The characters
that were removed from the pickers remain in the full character suite,
just not available via a picker.
Can be viewed in the [polytonic-greek](https://www.pgdp.org/~srjfoo/c.branch/polytonic-greek/tools/charsuites.php?charsuite=polytonic-greek&font=DP+Sans+Mono) branch sandbox.

Revised charsuite-polytonic-greek.inc

---

pinc/privacy.inc
stats/members/mdetail.php

Allow Project Facilitators to see Anonymous user stats. Updated the message that is displayed to reflect the change.

Allow PFs to see Anonymous user stats

---

pinc/abort.inc
pinc/html_page_common.inc
tools/proofers/proof_frame.php

In the Enhanced proofreading interface, when proofreaders use the "Start Proofreading" link, then the "Save and Proofread Next" button, and then use the browser's back button they can be presented with an image that does not match the text. If they then save the page the incorrect project page will be updated.
To fix this, we use a redirect from within the proofreading frame to ensure that "Start Proofreading" or "Save & Proofread Next" lead to a URL that is unique to that page. If the user tries to navigate back using the browser, they will be presented with an error because the page state does not match the expected state.
[Task 1911](https://www.pgdp.net/c/tasks.php?action=show&task_id=1911)
This is available in the [next-page-url](https://www.pgdp.org/~cpeel/c.branch/next-page-url) …

Use unique URLs for "proofread next page"

---

pinc/CharSuites.inc
tools/charsuites.php

Add an optional description variable to character suites. If set, this
is shown on the `tools/charsuites.php` page. Also change the layout of said
page to better support showing the description.

Add optional charsuite descriptions

---

SETUP/UNICODE.md
pinc/charsuite-medievalist-supplement.inc

Created medievalist character suite with characters that are commonly used in Middle English, Old English, Old Norse and medieval Latin.
Character suite layout available [here](https://www.pgdp.org/~srjfoo/c.branch/charsuite-medievalist/tools/charsuites.php?charsuite=medievalist-supplement&font=DP+Sans+Mono) for review. See [this project](https://www.pgdp.org/~srjfoo/c.branch/charsuite-medievalist/project.php?id=projectID44dda6ce1d66d) to view how the character pickers look in a live project.

Created medievalist character suite.

---

tools/mentors/view_page_text_image.php

Change the parameter names back to their original values to ensure that older links continue to work. This page isn't linked from anywhere in the code(!) so no other place to update.
See https://www.pgdp.net/phpBB3/viewtopic.php?p=1215773#p1215773

Revert param names back to their original values

---

api/ApiRouter.inc
api/README.md
api/dp-openapi.yaml
api/index.php
api/v1.inc
api/v1_projects.inc
api/v1_stats.inc
api/v1_validators.inc
pinc/base.inc
pinc/bootstrap.inc
pinc/html_page_common.inc
scripts/api.js

This adds (very) basic project page access to the APIs and allows the APIs to be accessed via session making them useful to JS UIs. Specifically it exposes the APIs needed to allow @70ray's new view images code to populate the data via AJAX instead of page loads.
I've also included a new global JS function to assist with creating the `$.ajax()` calls.
API examples:
```
curl -i -g -H "Accept: application/json" -H "X-API-KEY: review" \
"https://www.pgdp.org/~cpeel/c.branch/api-project-pages/api/index.php?url=v1/projects/pagerounds"
```
Results:
```json
[
"OCR",
"P1",
"P2",
"P3",
"F1",
"F2"
]
```
```
curl -i -g -H "Accept: application/json" -H "X-API-KEY: reviw" \
"https://www.pgdp.org/~cpeel/c.branch/api-project-pages/api/index.php?url=v1/projects/projectID45c225f598e32/pages"
```
Results: …

Add project page access to APIs

---

SETUP/tests/jsTests/splitControlTests.js
SETUP/tests/manual_web/split_test/switchable_split.js
SETUP/tests/manual_web/split_test/vertical_horizontal_split.js
SETUP/tests/manual_web/split_test/vertical_split.js
scripts/page_browse.js
scripts/splitControl.js
tools/mentors/page_text_image.js

Remove the direction constants,
replace by vertical true or false.
This makes it possible to invoke the splitter with just one function call.
This will probably conflict with other active merge requests. I can redo it or the others as appropriate.

Simplify splitter invocation.

---

pinc/Pool.inc
pinc/RoundDescriptor.inc
pinc/Stage.inc
pinc/showavailablebooks.inc
pinc/stages.inc
styles/themes/classic_grey.css
styles/themes/classic_grey.less
styles/themes/project_gutenberg.css
styles/themes/project_gutenberg.less
styles/themes/royal_blues.css
styles/themes/royal_blues.less
styles/themes/theme.less

This moves the per-stage table colors from the code into `theme.less` which allows them to be (optionally) overridden by the theme. There are zero visual changes to the user in this MR, but this enables some work @srjfoo is doing.
[mini-rant]Why are these different? Why are P1, P2, and F1 the same but different than P3 and F2? Why are PP, PPV, and SR all different from everything else?[/mini-rant]
This is viewable in the [move-round-colors-to-styles](https://www.pgdp.org/~cpeel/c.branch/move-round-colors-to-styles) sandbox.

Move round colors to theme

---

SETUP/MediaWiki_extensions/dpExtensions.php
SETUP/MediaWiki_extensions/hospitalExtensions.php

We no longer need to convert from ISO-8859-1 to UTF-8 in the DP MediaWiki extensions as the data is already UTF-8 now.
Thanks to @srjfoo for finding these!
See the extension demos at https://www.pgdp.org/wiki/User:Cpeel/MediaWiki_Extensions

Remove charset conversion in MediaWiki extensions

---

SETUP/INSTALL.md
SETUP/configuration.sh

Update docs to include phpBB 3.3 support, tentative PHP 7.2 support, and more general jpgraph 4.3.x support.

Update middleware support in docs

---

pinc/Quiz.inc

Now that the comprehensive Extended European Latin character suite is
no longer available, update `Quiz.inc` to point to Extended European
Latin B.
Issue discovered when trying to test an unrelated update. Can be tested at [fix-quiz-charsuites](https://www.pgdp.org/~srjfoo/c.branch/fix-quiz-charsuites/quiz/start.php)

Fix quiz character suites

---

accounts/addproofer.php
accounts/login.php
accounts/login_failure.php
accounts/logout.php
pinc/base.inc
pinc/html_page_common.inc
pinc/misc.inc
pinc/theme.inc
userprefs.php

Address CSRF vulnerability in user login, account registration, and user preferences as these are the most critical forms that deal with user data. I do not intend on retrofitting CSRF on all the forms at this time.
This also adds headers to prevent site pages from being loaded inside frames/iframes on another site.
This is available in the [fix-csrf](https://www.pgdp.org/~cpeel/c.branch/fix-csrf/) sandbox.
Things to test:
* login
* account creation
* user profile editing

Fix CSRF in login, registration, and userprefs

---

pinc/base.inc
pinc/misc.inc

Small set of refinements for the CSRF token from @chrismiceli. Note that we can't set the samesite attribute on the cookie because that was only added to `setcookie()` in PHP 7.3.0.
Available in the [improve-csrf](https://www.pgdp.org/~cpeel/c.branch/improve-csrf) sandbox.

Refinements to the CSRF token

---

pinc/access_change_emails.inc

Per request from the GM, clarify the pages-per-day portion of the
email that is sent automatically to new F1 formatters. This is just a small wording change.
Per suggestion from @cpeel, updated to include code to automatically include the daily page limit, since that's now stored in the code.
Test in [update-f1-access-email](https://www.pgdp.org/~srjfoo/c.branch/update-f1-access-email/). To test, go to your stats page. If you already have F1 access, disable it, and re-enable it. If you don't, just enable it. You should be shown a copy of the email that would have been sent if email were enabled for the test site. The daily page limit has been set to 5 pages for the purposes of this test.

Update F1 access email

---

quiz/generic/quiz_defaults.inc

In other places in the quizzes, quiz-takers are advised to provide the url for the specific quiz they're taking, the text they think should pass the quiz, and the error message they're getting, but this default feedback message was missing that advice. Added more specific instructions and removed "The algorithm for finding errors in this quiz is a quite simple one." This is an admin/GM request.
Can be tested in [update-quiz-message](https://www.pgdp.org/~srjfoo/c.branch/update-quiz-message/quiz/start.php). To trigger the message, go to one of the quizzes, scroll down and click on the "Check" button below the text box. The message should appear at the bottom of the feedback section on the right-hand side of the page.

Updated quiz default_feedbacktext message

---

SETUP/db_schema.sql
SETUP/tests/UserTest.php
SETUP/upgrade/15/20200815_create_team_membership.php
crontab/del_teams.php
pinc/Team.inc
pinc/User.inc
pinc/page_tally.inc
pinc/theme.inc
stats/includes/member.inc
stats/includes/team.inc
stats/members/jointeam.php
stats/members/mbr_xml.php
stats/members/quitteam.php
stats/teams/new_team.php
stats/teams/teams_xml.php
stats/teams/tedit.php
stats/teams/tlist.php

Allow users to join more than 3 teams by providing a proper mapping table between user and team. The teams code is ... let's just call it "rough". I tried to focus my changes only on what is needed to enable joining more than 3 teams although I did futz with the team listing page.
The number of teams is entirely configurable right now and I set it somewhat arbitrarily to 6. I need to consult with the other admins to determine the desired number.
This is [Task 773](https://www.pgdp.net/c/tasks.php?action=show&task_id=773) with 18 votes.
You can play with this in the [dynamic-team-membership](https://www.pgdp.org/~cpeel/c.branch/dynamic-team-membership/) sandbox.

Allow a user to join more than 3 teams

---

pinc/DPDatabase.inc

MySQL 8.0 [changed the UTF8 table collation names](https://mysqlserverteam.com/new-collations-in-mysql-8-0-0/) which requires us being a little more flexible on how we determine if a table is UTF8. Now we just check if the collation starts with the string that mentions the encoding.

Fix UTF-8 table detection for MySQL 8.0

---

stats/members/mbr_list.php
stats/stats_central.php
stats/teams/tlist.php

This adds a search form the to Members and Team listings. In a separate commit I styled the search forms on the Stats Central page. I'm not enamored with that one so I'm happy if folks think we should just drop that commit. [Task 1926](https://www.pgdp.net/c/tasks.php?action=show&task_id=1926)
See the [member-team-search](https://www.pgdp.org/~cpeel/c.branch/member-team-search/) sandbox.

Add search forms to the Members and Team listings

---

tools/proofers/spellcheck_text.inc

This updates WordCheck so that the page text is shown in the user's proofreading font. [Task 1928](https://www.pgdp.net/c/tasks.php?action=show&task_id=1928)
While I was here I used CSS for the line spacing instead of a `<br>`. This makes the lines with an input box appear uniformly spaced apart like all the other lines. And yes, I made it a smidge closer than they were before.
Available in the [wordcheck-proofreading-font](https://www.pgdp.org/~cpeel/c.branch/wordcheck-proofreading-font/) sandbox.

Show WordCheck page in user's proofreading font

---

tools/project_manager/autorelease.inc

Queue selectors can contain '%'s which means we can't use sprintf() to build the full query. Instead, we build it piecemeal to ensure other arguments are correctly escaped.
This is a regression from 5a21c6a8a.
I found and confirmed this is fixed on TEST.

Handle queue selectors containing '%'s

---

tools/proofers/my_projects.php

Don't output pages available or percent done for merged projects. This fixes the sprintf() warning from trying to force '' into a number.
@srjfoo found this bug on TEST. We don't show warnings on PROD so this isn't visible there.
Testable in the [fix-php-warning](https://www.pgdp.org/~cpeel/c.branch/fix-php-warning/) sandbox.

Fix PHP warnings for merged projects

---

pinc/LPage.inc

PROD and TEST have `$preceding_proofer_restriction` set to `not_immediately_preceding`, which means that when a proofreader hits "Start Proofreading" or "Save and Done and Proofread Next" we will only give them pages they have not proofed in the prior round. The value can also be set to `not_previously_proofed` which will only give them pages they have never proofed before.
[Task 1137](https://www.pgdp.net/c/tasks.php?action=show&task_id=1137) requests that even if the site is set to `not_immediately_preceding`, we first try to see if we can satisfy `not_previously_proofed` and give them a page they have never seen before. If we can't we fall back to `not_immediately_preceding`. That seems very reasonable and this MR implements that logic.
This is testable in the …

Give user a page they've never seen if possible

---

SETUP/UNICODE.md
pinc/charsuite-semitic-and-indic.inc

Characters used in Romanized forms of languages such as Arabic,
Hebrew, and Sanskrit. Viewable here: [charsuite-semitic-indic](https://www.pgdp.org/~srjfoo/c.branch/charsuite-semitic-indic/tools/charsuites.php?charsuite=semitic-and-indic). Project with the character suite enabled [here](https://www.pgdp.org/~srjfoo/c.branch/charsuite-semitic-indic/project.php?id=projectID5e672cf6b96c9).

Semitic and Indic transcriptions -- new Character Suite

---

pinc/special_colors.inc

Currently, for *every row* in a project listing on the round pages, we do a query to the database, load up the *entire special days table*, and return just a single color which may or may not be from the database query. Why? I have no idea.
This change does one query and stores the special days table into a static array that is populated just once on a page load. It also abstracts out the "common" special days into a single location rather than being spread across two places. This is an all-backend change and there are no user-visible differences.
Available in the [special-colors-perf](https://www.pgdp.org/~cpeel/c.branch/special-colors-perf/) sandbox.

Improve special day color selection performance

---

scripts/page_browse.js
styles/layout.css
styles/layout.less
styles/preview.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less
tools/project_manager/display_image.js
tools/project_manager/displayimage.php
tools/proofers/button_menu.inc
tools/proofers/image_block_enh.inc
tools/proofers/preview.inc

Pull page interface styling out of `layout.less` and into `theme.less`. This now centralizes all of the color for the various interfaces that deal with pages (proofreading, WordCheck, image display, format preview) into a single location. This is to enable some theming work that @srjfoo is working on.
This standardizes some of the UI style which makes for some small changes compared to what was there before:
* Buttons in control panes / control panels now all look the same. They have a small drop-shadow to help convey that they are a button. This includes the buttons in WordCheck.
* The background color of the image pane in the standard interface has changed to match the image pane color in the enhanced interface.
* Slight color changes to the control panels of Format Preview.
To review …

Pull page interface styling out into theme.less

---

faq/doc-copy.php
styles/layout.css
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less
tools/authors/harvest.php
tools/post_proofers/smooth_reading.php
tools/site_admin/manage_special_days.php
tools/site_admin/sitenews.php

This moves almost everything that can take a color out of `layout.less` and into `theme.less`. This includes border*, color and background-color. After experimenting with just breaking out the border color, I came to the conclusion that it was better to move the whole border property instead of breaking it up.  There are still a few border: none; and background-color: transparent; declarations that should probably be moved. The purpose is to make it easier to build additional site themes.
Instead of moving the stragglers, we might want to consider merging `layout.less` into `theme.less`: the problem with the current setup is that many structures have declaration blocks in both files, which can be confusing.
None of the class/mixin names I've choses are set in stone -- more logical …

Move color CSS from layout.less to theme.less

---

SETUP/Makefile
SETUP/generate_css_from_less.sh
package-lock.json
package.json
styles/layout.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

9a43fc8 had a mismatch between the `.less` files and the `.css` that should have come from them. This is possibly the result of an incorrect rebase, but it could have easily been exacerbated by the Makefile not regenerating `.css` files if they had a newer timestamp than the `.less` files.
Makefiles don't mesh well with git because the timestamps from the generated files might be newer than the source files but still out of date. Change to a shell script which is less "magical" than a Makefile and always rebuild every CSS file.

Always rebuild CSS from .less files

---

pinc/site_news.inc
styles/layout.css
styles/layout.less

Condense the news header and remove the images for the news title.
See the [condense-news-header](https://www.pgdp.org/~cpeel/c.branch/condense-news-header/) sandbox.

Condense the news headers and remove the images

---

styles/layout.css
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less
tools/project_manager/clearance_check.php
tools/project_manager/projectmgr.inc
tools/proofers/my_projects.php

The "pm_links" box is used on more pages than just the PM page now so rename it as "linkbox" and pull the color definition into the CSS instead of in the 3 separate pages.
This also introduces a very small margin at the top to separate it out from the navbar.
Viewable in the [rename-pm-links](https://www.pgdp.org/~cpeel/c.branch/rename-pm-links) sanbox.

Rename structure used for links

---

project.php
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less

Re-use the page status styles from page details on the project page rather than hard-coding the colors.

Re-use page detail colors on project page

---

activity_hub.php
default.php
pinc/Stage.inc
pinc/theme.inc

Some history: before the site was translatable into something besides English, each round page had a graphic at the top for its header. The graphics (the same ones we have today) have English text in them that we can't easily translate. During the effort to provide a translatable site, the compromise was to pull the images out of the codebase but make them accessible via `code_images`. If these images-with-English are present we show them  if the user's locale was English and otherwise we output the translated round title.
The downside is that this presents two very different versions of the Activity Hub and round pages for English and non-English speakers. It also means that we have a weird thing where the Activity Hub header is in a font distinctly different from everything else and it …

Separate round images from their titles

---

SETUP/db_schema.sql
SETUP/upgrade/15/20200925_alter_news_items.php
pinc/site_news.inc
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
styles/themes/theme.less
tools/site_admin/sitenews.php

Currently news items are a single blob of text. Admins have gotten in the habit of adding formatted header-lines (larger and with color) over the years. This MR pulls the header out into a proper field and allows the news item to have a type that influences the styling. This enables the header to be styled with the theme rather than hard-coded.
The header is optional and if not present won't show up at all so this is backwards compatible with all existing news items.
The item types and colors are mostly adhoc and I'm looking to @lhamilton1, @wf49670, and @srjfoo for recommendations on what these should be.
This also converts the news admin code to use the new DPDatabase functions. It's in a separate commit though so if it is preferable for it to be in a separate MR I can easily do so. …

Allow news entries to have a header and a type

---

pinc/Quiz.inc
styles/global.less
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

We need to be able to theme the passed/not passed colors for the quizzes. This moves them out of `Quiz.inc` into `layout.less`. I also removed an unused class reference from `Quiz.inc` and added a mixin for `x-large` text to `global.less`.
Testable here: [quiz-color-to-layout](https://www.pgdp.org/~srjfoo/c.branch/quiz-color-to-layout/quiz/start.php).

Move quiz colors into layout.less

---

pinc/page_table.inc
project.php
tools/project_manager/edit_pages.php
tools/project_manager/handle_bad_page.php
tools/project_manager/page_detail.php

Separate pulling the pagedetail data from the database and how it is presented to the user. This is key to making this data available via the API which is the motivation for this change.
Move `page_table.inc` to `pinc/` as the functions in page_table are used by more than PM pages.
This is purely backend work and there should be no changes to upstream callers or the UI.
Testable in the [abstract_pagedetails](https://www.pgdp.org/~cpeel/c.branch/abstract_pagedetails/) sandbox.

Separate pagedetail data from presentation

---

SETUP/API.md
api/README.md
api/USERS_GUIDE.md

Add a basic user's guide for the API to help developers get started using it.
You can view this rendered at https://github.com/cpeel/dproofreaders/blob/api-users-guide/api/USERS_GUIDE.md

Add an user's guide for the API 

---

faq/faq_central.php
styles/global.less
styles/layout.less
styles/statsbar.css
styles/statsbar.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Use EB Garamond for page headers, providing a bit more visual pizzaz to them.
This is viewable in the [eb-garamond-headers](https://www.pgdp.org/~cpeel/c.branch/eb-garamond-headers/) sandbox.

Use EB Garamond for page headers

---

pinc/metarefresh.inc

Properly escape redirect URLs in `metarefresh()` that use the `<meta>` tag. Also ensure we disallow redirects off-site when using the `<meta>` tag unless explicitly allowed. This addresses a XSS vulnerability.
This can be played with using the https://www.pgdp.org/~cpeel/c.branch/escape-metarefresh-urls/pinc/test.php page and passing in a URL, eg:
https://www.pgdp.org/~cpeel/c.branch/escape-metarefresh-urls/pinc/test.php?url=../project.php?id=projectID45c225f598e32

Properly escape <meta>-refreshed URLs

---

api/dp-openapi.yaml
api/v1.inc
api/v1_projects.inc
pinc/Project.inc
pinc/page_table.inc

This updates the API with the following changes:
* corrects project fields so the OpenAPI docs match the fields returned for a project
* updates the `/pages` endpoint to include more information about the page instead of just a listing of names
* adds a `/pagedetails` endpoint that returns largely the same data as the UI page with the same name
Testable via:
```bash
curl -i -g -X GET "https://www.pgdp.org/~cpeel/c.branch/api-updates/api/index.php?url=v1/projects/projectID45c225f598e32" \
-H "accept: application/json" \
-H "X-API-KEY: review"
curl -i -g -X GET "https://www.pgdp.org/~cpeel/c.branch/api-updates/api/index.php?url=v1/projects/projectID45c225f598e32/pagedetails" \
-H "accept: application/json" \
-H "X-API-KEY: review"
curl -i -g -X GET …
```

API updates: correct project fields; page details; more info in pages index

---

project.php
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Pull the formatting for event subscriptions and project holds out of `project.php` and into classes so they can be styled. Very minimal visual changes, just prep work for what @srjfoo is working on.
Viewable in the [checkbox-selected](https://www.pgdp.org/~cpeel/c.branch/checkbox-selected/) sandbox.

Style subscriptions and hold checkboxes

---

activity_hub.php
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/pool.php

Remove the drop-shadow from the news items and use vertical and horizontal borders to separate them. This creates a cleaner interface (and also looks better in the upcoming charcoal theme).
I also removed some unnecessary `<hr>`s and a paragraph on the pool pages that doesn't need to be there (we don't put that on the round pages, why do we do it on the pool pages?).
Testable in the [tweak-news-layout](https://www.pgdp.org/~cpeel/c.branch/tweak-news-layout/) sandbox.

Tweak news layout

---

styles/page_interfaces.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/proofers/image_frame_std.php
tools/proofers/text_frame_std.inc

Rather than rely on the standard interface inheriting from the site style, explicitly set the colors. This is a stepping stone to before we have themes that apply just to the proofreading interface. This is in prep for theming work that @srjfoo is doing.
Note that one downside to this is that buttons in the standard proofreading interface are now styled rather than simply whatever the browser agent is using.
Testable in the [set-std-interface-colors](https://www.pgdp.org/~cpeel/c.branch/set-std-interface-colors/) sandbox.

Explicitly set the standard interface colors

---

pinc/ProjectTransition.inc
tools/upload_text.php

This allows a PPer to return a project to the original PPVer after further work.
See task 1917. [https://www.pgdp.net/c/tasks.php?action=show&task_id=1917](url).
An email is sent to the PPer when the PPver returns the project for further work.
An email is sent to the PPVer when the PPer uploads the project to him after further work.
There was some discussion of how the return to PPVer should work. This is one possible way: If the project had been returned to the PPer from a PPVer then the PPer only sees the "Return to PPverifier" button but a project facilitator can upload the project from PP to the PPV pool.
The PPV statistics will be unchanged because the statistics for PPVer does not use the ppverifier field.
The project search and myprojects will show PPVer when the project is in PP …

Add PPV project transitions

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Create a set of styles that will allow tables that are used in Random Rules to be themed properly.
Test by opening a round page in the [style-random-rules](https://www.pgdp.org/~srjfoo/c.branch/style-random-rules) sandbox, as well as one on the regular test site or even one on the production site. Scroll down to the Random Rule section and refresh the page until a rule with a table shows up. Also can be compared against the corresponding section of the Proofreading or Formatting guidelines.
If you compare against the corresponding tables in the wiki on PROD, you will notice a border line weight difference. The only other visible change should be that the Random Rule tables that had a `width: 100%` style on them no longer do.

Add styling for Random Rules to layout.less

---

project.php
styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Allows theming of blurb boxes on the project page (the borderless boxes above and below the project table that include the `Start Proofreading` link (the top blurb box includes that link only if a proofer has saved at least one page since the project comments were last saved).
Also adds color classes for comment row headers for PP/PPV, SR and Project Comments.
Available for testing: [style-blurb-box](https://www.pgdp.org/~srjfoo/c.branch/style-blurb-box/)

Allow theming for blurb boxes on Project Page

---

tasks.php

Redirect back to the task's page after acting on a task. This clears the POST data and allows the user to refresh the page without resubmitting the form. [Task 1839](https://www.pgdp.net/c/tasks.php?action=show&task_id=1839)
Testable in the [task-center-redirect](https://www.pgdp.org/~cpeel/c.branch/task-center-redirect/) sandbox.

Redirect to task after acting upon it

---

styles/page_interfaces.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

This does three minor things:
1. Add styling for disabled buttons in WordCheck
2. Rounds button corners -- this is global for all page interface buttons, including the toolbar. If we think this is too dramatic I can lower it to 2px which is very subtle but still better than none, to @70ray's point.
3. Sets a non-white background color for buttons in the standard interface to make them blend in less. I used the button color that Chrome on Mac uses.
Testable in the [button-disabled](https://www.pgdp.org/~cpeel/c.branch/button-disabled/) sandbox.

Improve button styling

---

api/dp-openapi.yaml
api/v1.inc
api/v1_stats.inc

Allow requesting all site statistics in one API call in addition to the per-round calls.
```bash
curl -i -g -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
'https://www.pgdp.org/~cpeel/c.branch/api-round-stats/api/index.php?url=v1/stats/site/rounds'
```
Returns:
```json
{
"P1": {
"today_goal": 50,
"today_actual": 0,
"yesterday_goal": 50,
"yesterday_actual": 1,
"month_goal": 1550,
"month_actual": -3
},
"P2": {
"today_goal": 50,
"today_actual": 0,
"yesterday_goal": 50,
"yesterday_actual": 0,
"month_goal": 1550,
"month_actual": 0
},
...
```

Allow retrieval of all round stats in one call

---

pinc/DifferenceEngineWrapper.inc

This addresses task 1936 https://www.pgdp.net/c/tasks.php?action=show&task_id=1936.
The problem occurs because the text with padding is greater than the line height.

padding for highlighted text removed

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Somewhere among the recent style reshuffle, the selected tabs got a bottom border when they don't need one.
Check it out in the [fix-tab-bottom-border](https://www.pgdp.org/~cpeel/c.branch/fix-tab-bottom-border/) sandbox.

Remove selected tab bottom border

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/project_manager/manage_image_sources.php

Manage Image Sources (either to propose a new image source or edit an existing one) was the only place that a dotted border was used, and it was used simply as a spacer (Permissions row). Removed bottom border and let the drop-down menus be located next to the labels.
Project Managers and Project Facilitators can use this for proposing new image sources. Only Image Sources Managers, and site admins can edit.
Testable: [remove-dotted-border](https://www.pgdp.org/~srjfoo/c.branch/remove-dotted-border/tools/project_manager/projectmgr.php)

remove-dotted-border: removed dotted bottom border

---

phpcs.xml

Works out-of-box with Visual Studio Code's phpcs extension, and quells
warnings most of the code misformatting issues we have.
We can incrementally fix these up and re-enable the warnings we decide
are useful.

Add a sample phpcs.xml configuration

---

tasks.php

This localizes all the UI strings in the Task Center *except* the values for the task fields.
This also doesn't localize any of the notification emails.
Testable in [localize-tasks](https://www.pgdp.org/~cpeel/c.branch/localize-tasks/) sandbox.

Localize Task Center

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/post_proofers/ppv_report.php

The initial focus of this branch was to pull inline styles for colors out of the form and set it up to use site-wide styling. I've tried to keep that part of it in the first commit. This involved changing some content, as well.
The second commit updates more content and adds/corrects links from the form to the appropriate sections in the guidelines, and adds dummy `id`s to the PP FAQ and PPV Guidelines documents in the code for use as redirects to the wiki.
To test, you'll need to grant yourself PPV access. Probably easiest if you just use [this link](https://www.pgdp.org/~srjfoo/c.branch/update-ppv-report/tools/post_proofers/ppv_report.php?project=projectID5771f9753c0c7) to go directly to a project.

Update ppv report

---

tools/proofers/previewControl.js

This fixes two bugs which appeared after the change to font selection in format preview:
The fonts in the selector were duplicated each time the configuration was changed - now the selector is only set up once at start.
The example text in the configuration now uses the selected font.
Some comments have been deleted which referred to the previous way of selecting preview fonts.

Preview font fix

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.inc
tools/proofers/preview.js
tools/proofers/previewControl.js

This enables preview of Latex math markup using MathJax. Much the same as math_preview_3 but reworked with commits indicating purpose of each change and incorporating improvements suggested by @chrismiceli.
(preview.js still has many stylistic shortcomings beyond the scope of this MR).

Math preview 4

---

styles/preview.css
tools/proofers/preview.js

This re-writes some code in preview.js to remove eslint exceptions.
Also adds some padding to the example texts in format preview configure.
Can be seen in https://www.pgdp.org/~rp31/c.branch/misc_preview Only the padding change should have any visible effect.

Misc preview

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201023_alter_tasks.php
tasks.php

Create a function for loading a task instead of sprinkling that logic around. This also adds a migration script to correctly treat task_id as a primary key. This is a stepping stone to updating tasks to use proper escaping and the new DPDatabase functions.
Note that due to the 2-level de-indenting in `TaskDetails()` there are a lot of changes to that function that are mostly just whitespace changes. Consider adjusting the view to hide whitespace changes when reviewing it.
Testable in the [consolidate-task-queries](https://www.pgdp.org/~cpeel/c.branch/consolidate-task-queries/tasks.php) sandbox.

Create and use a func for loading a task

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

This commit standardizes the common background color names, more or less (there are still some oddballs), and tries to use names that will give some indication of what they should be used for.
Also included, an adjustment to the defined general purpose tables: for the striped tables, odd and even stripe backgrounds were flipped so that the even stripe uses the page background and the odd uses the stripe color. All striped tables now have a header row background color. This should not affect the round
listings.
Test in [background-colors](https://www.pgdp.org/~srjfoo/c.branch/background-colors/) sandbox.

background-colors: standardize bg color names

---

pinc/forum_interface.inc

Again, a few prefixes to table names were escaped when they shouldn't be.
Tested on pgdp.org and sandbox available at https://www.pgdp.org/~bfoley/c.branch/cleanup13

forum_interface.inc: Use modern DPDatabase::query, escaping, sprintf

---

activity_hub.php
pinc/mentorbanner.inc
pinc/page_table.inc
pinc/theme.inc
pinc/user_is.inc
project.php
styles/layout.less
styles/style_demo.php
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/proofers/PPage.inc

In `layout.less`, name text and border colors. Changed a few more isolated instances of inline styles controlling color to use classes.
In a separate commit, fixed some improperly closed elements in `styles/style_demo.php`.
sandbox: [text-border-colors](https://www.pgdp.org/~srjfoo/c.branch/text-border-colors/)

Name text and border colors

---

list_etexts.php
pinc/DPage.inc
pinc/Project.inc
pinc/ProjectSearchResults.inc
pinc/maybe_mail.inc
pinc/page_table.inc
pinc/special_colors.inc
project.php
stats/includes/member.inc
stats/includes/team.inc
tools/site_admin/copy_pages.php

After swapping TEST to PHP 7.4 these few notices popped up. There are likely to be more but these were the low hanging fruit. I did a grep for all `join()` and `implode()` calls and believe I have all of the ones using the deprecated form.
Testable, if you want, in the [php-7.4-updates](https://www.pgdp.org/~cpeel/c.branch/php-7.4-updates) sandbox.

Minor updates for PHP 7.4

---

pinc/access_log.inc

Changes to log_access_change and get_first_granted_date are both exercised by looking at a member detail page and granting/revoking permissions for a round. 
Sandbox at https://www.pgdp.org/~bfoley/c.branch/cleanup16/stats/members/mdetail.php?id=151

access_log.inc: Use DPDatabase, and set_col helper functions

---

pinc/DPage.inc

I introduced a bug into _project_adjust_n_available_pages.
$expr is an expression string, not a number.

DPage.inc: Stop project automodify setting n_available_pages to 0

---

scripts/character_test.js

causes a problem in IE, probably unnecessary.
This undoes an earlier commit in July  to fix a problem with Astral plane characters which was probably mistaken. But need to do some more tests to make sure everything works correctly.

u flag removed from XRegExp functions

---

pinc/DPDatabase.inc
pinc/Project.inc

Rather than doing an SQL query we expect might fail (and place an error in the `php_errors` log) use the information.schema to determine if a table exists.
Testable in the [check-pages-table-sql](https://www.pgdp.org/~cpeel/c.branch/check-pages-table-sql/) sandbox.
I found this after doing a deploy to PROD today and seeing the numerous "'table' doesn't exist" errors in the `php_errors` log.

Use information_schema to determine table existence

---

.travis.yml
SETUP/INSTALL.md

GRANT ... ON ... TO ... IDENTIFIED BY ...; is deprecated in MySQL 5.7
(and errors in MySQL 8 on Ubuntu 20.10)

travis.yml: CREATE mysql user and GRANT privileges separately

---

api/v1_projects.inc
pinc/LPage.inc
pinc/Project.inc
pinc/iso_lang_list.inc
pinc/wordcheck_engine.inc
project.php
tools/project_manager/editproject.php
tools/site_admin/show_common_words_from_project_word_lists.php

We encode a project's languages into a single column with the names separated by `" with "`. Centralize that logic into a single place instead of having it smeared across the codebase. This makes it easier to remove the redundant `proj_lang_code()` function entirely.
Accessible in the [project-languages](https://www.pgdp.org/~cpeel/c.branch/project-languages/) sandbox.

Centralize project language encoding/decoding

---

pinc/iso_lang_list.inc
pinc/wordcheck_engine.inc

When presented with text containing two different scripts, aspell behaves differently based on the dictionary. Words containing non-Latin characters are ignored completely with the English dictionary, yet words containing Latin characters are flagged as spelling errors with the Ancient Greek dictionary.
To fix this, restrict misspelled words (as returned from aspell) to only words that contain the script of the language we're checking. This ensures that only words with Latin characters are returned when checking against the English or French dictionary, and only Greek words are returned when using the Ancient Greek dictionary.
This is testable in the [wordcheck-script-support](https://www.pgdp.org/~cpeel/c.branch/wordcheck-script-support/) sandbox.

Use language script as part of spellcheck

---

SETUP/tests/jsTests/characterValidation.js
SETUP/tests/jsTests/formatPreviewTests.js
scripts/text_validator.js
tools/proofers/preview.inc
tools/proofers/preview.js
tools/proofers/previewControl.js

This does the check for invalid characters before entering preview and removes the check for tab character in preview.
Also improves layout of the configuration panel so the color selection is less confusing (at least to me) and the other options have a more uniform style. The changes made the indenting of the html wrong so I re-indented it all. This makes it seem much more different than it really is. It perhaps would be better to remove all the html indenting.
Can be seen in sandbox https://www.pgdp.org/~rp31/c.branch/preview_adjust

Preview adjust

---

quiz/generic/quiz_defaults.inc
quiz/generic/wizard/default_messages.php
styles/global.less
styles/layout.less
styles/page_interfaces.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/project_manager/remote_file_manager.php

In doing a series of checks to see if we were ready to actually start wider viewing of a new theme, I found a few more styling problems that needed to be resolved. Hopefully this is the last of them (at least for now).
Test in [color-tweaks](https://www.pgdp.org/~srjfoo/c.branch/color-tweaks/)
The only significant visual difference should be in the list of quiz default messages. Compare: [default-quiz-messages-before](https://www.pgdp.org/c/quiz/generic/wizard/default_messages.php) with [default-quiz-messages-after](https://www.pgdp.org/~srjfoo/c.branch/color-tweaks/quiz/generic/wizard/default_messages.php)

More color tweaks

---

styles/layout.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tasks.php

For narrows screens, such a mobile devices, make the task details transition to rows instead of columns using a flex layout. Task 1960
Bonus: make sure that verylongstringswithoutspacesincomments break instead of forcing the window very (very) wide.
Testable in [task-center-flex-layout](https://www.pgdp.org/~cpeel/c.branch/task-center-flex-layout/) sandbox.

Make task details render better on narrow screens

---

pinc/unicode.inc

When building the regex used to enforce character suites, we need to correctly escape special regex characters. All of the special regex characters are in the Basic Latin set and that character suite is defined in a way where this will never happen for it. And it's very unlikely that new suites will have this either. However, PMs can include them in project custom characters and can cause the filtering to fail.
The regex from this function is used for both the PHP code and the JS code. PHP uses delimiters (in our case `/`) but JS does not, so we only include the delimiter escaping for the PHP code. By my reading PHP and JS use the same escaping for regex special characters however.
This was noticed first on PROD by the 3106851(!) instances of `Unknown modifier '-' in …

Properly escape special regex chars in filter

---

tools/project_manager/manage_image_sources.php

New image sources were not being correctly identified during save due to an unset (and unused) `$new` variable. This fixes that and does a better job of input validation as well.
Testable in [fix-manage-image-sources](https://www.pgdp.org/~cpeel/c.branch/fix-manage-image-sources/).

Fix manage image sources

---

pinc/DPage.inc
tools/project_manager/add_files.php

Periodically we see a slew of errors in `php_errors` like:
```
DPDatabase.inc - log_error from /data/htdocs/c/pinc/DPage.inc:149: Duplicate entry '323' for key 'fileid'
```
This is called upstream by `add_files.php` which is used to load pages into a project. The error is that there is already a row in the project table for that page, but `add_files.php` checks for that so how is this possible? I believe this happens when a user clicks on the "Proceed with load" link and then, when it doesn't look like anything is happening (because it takes a while), they click on it again causing two `add_files.php` processes to race.
To prevent this, make the "Proceed with load" a POST and disable the submit button when it has been clicked.
As part of figuring this out I styled some of the error …

Prevent racing add_files processes

---

SETUP/diff_rq

`diff_rq` is a small utility program we use as part of the deployment process on TEST and PROD. This updates it to work with python3. python2 went officially out of support in Jan 2020. Ubutnu 16.04 includes python3 and it's the default in Ubutnu 20.04.
This is a very straightforward update -- it isn't a very complicated script. It looks worse than it is mostly because the original was a mixed spaces/tabs which simply isn't valid in python3.

Update diff_rq to python3

---

styles/layout.less
styles/page_interfaces.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Changed the border around words identified by WC to a darker grey, as some proofreaders felt the need for a higher contrast border between the two background colors. Since that was the only place the .x-thin-border mixin was used, removed it.
Testable: [darken-wc-border/](https://www.pgdp.org/~srjfoo/c.branch/darken-wc-border/)

darken-wc-border

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201215_alter_users.php
pinc/User.inc

While email is not guaranteed to be unique, there are times being able to load a user by email is very useful for some admin scripts. This adds the necessary function and index. It also cleans up some indexes in the dbschema that were missed when the API landed earlier.

Load user by email

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201215_alter_non_activated_users.php
accounts/addproofer.php
pinc/NonactivatedUser.inc

Disallow new user registrations for the same email address. This only prevents users from having duplicate outstanding activation requests which we've seen from users who haven't given the email enough time to get to them.
Testing this on TEST requires some code hacking which I've done. This MR is to ensure that my DB schema updates are correct and to solicit input on the error message returned to the user in this scenario.

Make account email activations unique

---

accounts/activate.php
accounts/addproofer.php

The account activation experience is one of the first entrypoints for new users and yet has some of the poorest user experience because it gets so little visibility for current users / developers.
This MR seeks to improve that by:
* Fixing the post-activation login form. Adding the CSRF token in e0c3ecd4a back in late August broke this so every time a new user is asked to sign in with it they get an error message.
* Improving the layout of the post-activation login form so it's more than a single input and looks like a login form.
* Improving the text layout of the activation page, adding a heading and some paragraph tags.
* Adding a header to the post-addproofer form submission page.
The only user workflow change is always redirecting logged-in users to the Activity Hub when they access …

Better account activation experience

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201217_alter_user_profiles.php
accounts/login_failure.php
pinc/Quiz.inc
pinc/gradual.inc
project.php

This is a small set of changes to improve the new user experience:
* Change the proofreading interface default for new users to *not* open in a new window. This often interacts poorly with popup blockers and we should really phase this out altogether.
* Make the reset password link on the failed login page more prominent and remove the very outdated line about page caching.
* Copy some of the wording in the new user emails into the callouts for new users. This includes adding a new callout on the project page right at the very top for proofreaders with < 100 pages.
* Small update on the quiz pages to link to the rounds that the quizzes are pre-reqs for.
Testable in the [better-new-user-info](https://www.pgdp.org/~cpeel/c.branch/better-new-user-info) sandbox. To see the new user callouts, …

New user experience improvements

---

pinc/Quiz.inc
quiz/generic/quiz_page.inc
quiz/start.php
quiz/tuts/tut_p_aeoe_1.php
quiz/tuts/tut_p_aeoe_2.php
quiz/tuts/tut_p_basic_1.php
quiz/tuts/tut_p_basic_2.php
quiz/tuts/tut_p_basic_3.php
quiz/tuts/tut_p_basic_4.php
quiz/tuts/tut_p_basic_5.php
quiz/tuts/tut_p_fraktur.php
quiz/tuts/tut_p_greek_1.php
quiz/tuts/tut_p_greek_2.php
quiz/tuts/tut_p_greek_3.php
quiz/tuts/tut_p_greek_4.php
quiz/tuts/tut_p_greek_5.php
quiz/tuts/tut_p_mod1_1.php
quiz/tuts/tut_p_mod1_2.php
quiz/tuts/tut_p_mod1_3.php
quiz/tuts/tut_p_mod1_4.php
quiz/tuts/tut_p_mod1_5.php
quiz/tuts/tut_p_mod2_1.php
quiz/tuts/tut_p_mod2_2.php
quiz/tuts/tut_p_mod2_3.php
quiz/tuts/tut_p_mod2_4.php
quiz/tuts/tut_p_mod2_5.php
quiz/tuts/tut_p_old_1.php
quiz/tuts/tut_p_old_2.php
quiz/tuts/tut_p_old_3.php
quiz/tuts/tut_p_thorn.php

Be consistent about referring to parts of a quiz as "pages" instead of "steps". This also adds some return links on page check failure to the tutorial and quizzes home in case the user gets really stuck and wants to exit the quiz.
Many thanks to @windymilla for the suggestions on tactical ways of making this clearer for users.
Testable in the [standardize-quiz-naming](https://www.pgdp.org/~cpeel/c.branch/standardize-quiz-naming/) sandbox.

Standardize quiz nomenclature

---

pinc/Activity.inc
pinc/Quiz.inc
pinc/gradual.inc
pinc/new_user_mails.inc
pinc/theme.inc
project.php
quiz/generic/quiz_page.inc
tools/proofers/round.php

By GM request, this code update requires users to pass the basic proofreading quiz before working in P1. The change itself is a two-line change in `pinc/stages.inc` but ensuring that new users can figure out that they need to do this and how to do it is what everything else is for.
Broadly, this MR attempts to guide new users to the basic proofreading quiz using a new callout and then, once they successfully pass the quiz, a pointer to P1 from the quizzes. The code has been changed such that if we decide to remove the quiz requirement the site will go back to the way it is now with only removing the requirement from `pinc/stages.inc`.
Like many changes, this is a balancing act between making things work for pgdp.net without limiting how other sites use the code. It also needs to balance …

Require users to pass the basic proofreading quiz before working in P1

---

pinc/User.inc

Cookies can only be set before headers have been sent to the browser, otherwise PHP generates a warning. Check that headers haven't been sent before resetting invalid profile cookies. Failing to reset it is fine since only valid profile cookies are ever used.
Seen in the `php_errors` log on PROD.
While I don't know for certain why we're seeing this, it could happen by a user deleting a profile in one browser that a second web browser had been using.

Check headers before resetting profile cookie

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201224_add_charcoal_theme.php
styles/layout.less
styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/royal_blues.css
styles/themes/royal_blues.less

This just themes the basic site pages -- Front Page, Activity Hub, Round and Pool pages, Project Pages, and the like.
Items deferred:
1. Proofreading interface and related -- that's a separate process, and work has begun, but it's not ready for review.
1. Special Day colors. This MR shows the special day colors as they currently are on PROD. There are a couple of alternatives under discussion, but no clear decision on which to use.
1. Logo and graphs -- needs more investigation. After we drop support for IE-11, we should be able to use SVGs directly, but we'll still need to figure out how.
1. Where Project Managers force background colors in PCs without specifying text color, there may be some readability issues.
Some theming work was necessary in page_interfaces so that the colors for …

theme-charcoal

---

pinc/DifferenceEngineWrapper.inc
styles/layout.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/project_manager/diff.php

To allow theme files to override the MediaWiki CSS for diffs, we need to import the CSS into the theme files. Also update the diff CSS for Charcoal.
Check it out in [fix-charcoal-diffs](https://www.pgdp.org/~cpeel/c.branch/fix-charcoal-diffs/).

Import the MediaWiki CSS into theme files

---

tools/modify_access.php

This message is only seen by those who are granting or revoking accesses to rounds which are auto-granted. It emphasizes that the operation is a revoke, not a block, and that, for the stages the message applies to, if the user meets all prerequisites, access can be auto-granted again. For P1, P2 and F1, it happens automatically if the user meets the access requirements; for PP, it's auto-granted after the user clicks the link to request access.
Reviewable in the [update-revoke-message](https://www.pgdp.org/~srjfoo/c.branch/update-revoke-message) sandbox.

Update revoke message

---

SETUP/check_require_login.php
pinc/3rdparty/parsedown/ParsedownExtra.php
pinc/3rdparty/parsedown/README.md
pinc/authors.inc
pinc/comment_inclusions.inc
tasks.php

Frustratingly, Parsedown doesn't add id tags to headers like GitHub and others do. The ParsedownExtra extension does with a bit of extra markup, as well as a few other minor things. Parsedown 2.0 is [suppose to have this built-in](https://github.com/erusev/parsedown/pull/765), but that branch hasn't gotten traction in a while so I'm not holding out on it.
Testable in the [parsedown-extra](https://www.pgdp.org/~cpeel/c.branch/parsedown-extra/) sandbox.
The [cpeel hacky UTF-8 test project](https://www.pgdp.org/~cpeel/c.branch/parsedown-extra/project.php?id=projectID45c225f598e32) project uses some of the new ParsedownExtra formatting, in addition to pulling in bio 3 which also uses it. Feel free to play with it if you'd like.

Add ParsedownExtra extension

---

SETUP/db_schema.sql
SETUP/upgrade/15/20201231_alter_special_days.php
pinc/ProjectSearchResults.inc
pinc/showavailablebooks.inc
pinc/special_colors.inc
styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/project_manager/show_specials.php
tools/proofers/round.php
tools/site_admin/manage_special_days.php

Rather than coloring the whole table row for special days, just do a single column that contains a special day indicator. This improves accessibility and overall UX.
Show special day information in round tables and show the legend to all users.
This is testable in the [special-color-improvements](https://www.pgdp.org/~cpeel/c.branch/special-color-improvements/) sandbox. See also the [discussion in the forums](https://www.pgdp.net/phpBB3/viewtopic.php?f=4&t=72729).

Add a row cell for special days indicator

---

SETUP/upgrade/15/20210104_generate_archive_metadata.php
crontab/archive_projects.php
pinc/archiving.inc

Previously, OLS (aka [dpcatalog](https://github.com/DistributedProofreaders/dpcatalog)) required database access to look up project metadata for cataloging. It's far simpler and more secure to include the metadata in a structured format with projects when they are archived so everything needed to catalog the projects are stored on the filesystem.
Another option would be for OLS to use the new DP API to look up this information, but having everything on a filesystem is far easier.
I tested this by archiving a project on TEST through the crontab. Here's the resulting [metadata.json](https://www.pgdp.org/out/projectID44dcf826adaa1/metadata.json). I then ran the upgrade script against a project that was already in `/out` but did not have the metadata file and [one was …

Add project metadata to archive project directory

---

pinc/new_user_mails.inc

At the request of the GM: Add a paragraph that provides a pointer for new users to information on certification of volunteer work. A larger percentage than before of new volunteers seem to be students needing to do volunteer work.
If you need to, you can test it in the [update-welcome-email](https://www.pgdp.org/~srjfoo/c.branch/update-welcome-email) sandbox.

Add volunteer cert info to new user email

---

SETUP/tests/manual_web/split_test/index.html
scripts/splitControl.js

I was experimenting replacing some of the <frameset>s with splitControl, but noticed it used absolute positioning. I figured we could do this with flex.
I really want @70ray's input here and not trying to step on your toes. Just a minor tweak to your major contribution.
I deployed here and you can check it out here:
https://www.pgdp.org/~chrismiceli/c.branch/flexSplit/tools/page_browser.php?project=projectID5e23ae7ff0a81&mode=imageText&imagefile=016.png
or in the manual test pages:
https://www.pgdp.org/~chrismiceli/c.branch/flexSplit/SETUP/tests/manual_web/split_test/index.html
If we do accept this PR, we'll need to update the text here: https://github.com/DistributedProofreaders/dproofreaders/blob/master/SETUP/tests/manual_web/split_test/index.html#L19

Don't use absolute for split

---

styles/layout.less
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

After settling in a while, the standard orange used for the medium level news announcement was determined to be too light. Switched to darkorange for defaults, and added orange for charcoal theme, as the normal orange looks fine there.
Viewable in the [update-news-color](https://www.pgdp.org/~srjfoo/c.branch/update-news-color/tools/post_proofers/smooth_reading.php) sandbox. Compare with the [main test site](https://www.pgdp.org/c/tools/post_proofers/smooth_reading.php).

Darken announcement-medium on default themes

---

SETUP/UNICODE.md
pinc/charsuite-symbols-collection.inc

Character suite `symbols-collection`, contains astronomical, zodiac, apothecary and music symbols, grouped into two picker sets. The Zodiac symbols are combined with the VS15 variation selector to try
to force them to appear as normal type instead of as emoji, though this does not work in all cases.
Character suite can be viewed at [symbols-collection](https://www.pgdp.org/~srjfoo/c.branch/symbols-collection/tools/charsuites.php?charsuite=symbols-collection); used in a project at [Elegantní Tanecník - WordCheck Testing](https://www.pgdp.org/~srjfoo/c.branch/symbols-collection/project.php?id=projectID47127a26a1f9b&expected_state=P1.proj_avail).

New character suite: Symbols collection

---

pinc/phpbb3.inc

phpBB 3.3.x supports Astral characters (like emojis) in posts, but they need to be encoded correctly for topic subjects. This is most easily seen in the phpBB's [posting.php](https://github.com/phpbb/phpbb/blob/master/phpBB/posting.php#L762) file.
The `utf8_encode_ucr()` function doesn't exist in phpBB 3.2.x so this should be safe for those versions (which is also what is running on PROD right now).
Testable in the [astral-forum-subjects](https://www.pgdp.org/~cpeel/c.branch/astral-forum-subjects/) sandbox.
[Task 1886](https://www.pgdp.net/c/tasks.php?task_id=1886)

Encode Astral characters in phpBB 3.3.x subjects

---

.eslintignore
SETUP/check_require_login.php
SETUP/lint_json_files.sh
composer.json
composer.lock
pinc/authors.inc
pinc/comment_inclusions.inc
pinc/misc.inc

Sanitize HTML-formatted content from users with htmlpurifier before presenting it to the user.
This is the same HTML sanitizer already hacked into TEST and PROD, this just pulls it into the codebase officially via composer.
Testable in the [use-htmlpurifier](https://www.pgdp.org/~cpeel/c.branch/use-htmlpurifier) sandbox.
Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/563

Sanitize HTML with htmlpurifier

---

pinc/smoothread.inc

This fixes https://github.com/DistributedProofreaders/dproofreaders/issues/569 (in one commit) and updates the SQL in `pinc/smoothread.inc` to use the `DPDatabase` escaping and query functions (in the second commit).
Testable in the [smoothread-sql](https://www.pgdp.org/~cpeel/c.branch/smoothread-sql/) sandbox.

Fix smoothreading SQL error on dup commit

---

SETUP/CHANGELOG.md
SETUP/db_schema.sql
SETUP/upgrade/16/20210214_alter_project_holds
pinc/Project.inc
pinc/maybe_mail.inc
project.php
tools/project_manager/automodify.php

Per GM / Squirrel request: This adds a notification to the PM when automodify attempts to transition a project but is unable to do so because there is a hold on the project. This is for all project holds, not just holds in Available.
A PM will only get one email unless the hold is removed and re-added, or if a proofreader later proofreads a new page. The latter is to address the scenario where:
1. The project has a hold for Available
2. The project is prevented from transitioning and the PM is notified
3. The PM clears some pages but does not remove the hold
4. Proofreaders proofread more pages
5. The project is (again) prevented from transitioning.
This is testable in the [notify-held-projects](https://www.pgdp.org/~cpeel/c.branch/notify-held-projects/) sandbox. We might need to add some …

Notify PMs about holds preventing projects from transitioning

---

crontab/take_tally_snapshots.php
pinc/LPage.inc
pinc/Project.inc
pinc/job_log.inc
tools/project_manager/automodify.php

Move the bad project detection into the Project class so the definition is in one place and not two. Move `job_log` table inserts into a central function instead of doing it in multiple places. And finally some small automodify cleanup. (All in separate commits.)
This should have zero visible changes to the user, database, or log files.
Available in the [automodify-cleanup](https://www.pgdp.org/~cpeel/c.branch/automodify-cleanup/) sandbox.

Automodify cleanup

---

pinc/showavailablebooks.inc
pinc/upload_file.inc
tools/project_manager/automodify.php
tools/project_manager/remote_file_manager.php
tools/proofers/images_index.php
tools/proofers/spellcheck_text.inc

This addresses various small warnings and notices seen in `php_errors`. It also hides the Delete button for illustrations if the user does not have permissions to manage the project (this was reported in the forums).
Available in the [fix-errors](https://www.pgdp.org/~cpeel/c.branch/fix-errors/) sandbox (not a very creative branch title, I know).

Fix various small errors found in php_errors

---

accounts/activate.php
pinc/upload_file.inc
tools/project_manager/remote_file_manager.php
tools/upload_resumable_file.php

Preface all our `error_log()` calls with the name of the script to we know where it came from.
Remove the logging from `remote_file_manager.php` since it isn't an actual error.

Minor updates to error logging

---

SETUP/API.md
SETUP/configuration.sh
pinc/site_vars.php.template

Now that Page Browser requires the API, enable it by default and
provide additional documentation on why. Also provide more docs
around the use of PHP sessions to access the API.

Enable the API by default

---

.github/workflows/static-checks.yml
.travis.yml
SETUP/Makefile

This moves everything except npm unit tests to GitHub Actions (@chrismiceli is working on moving the unit tests). Until https://github.com/github/super-linter/issues/1288 is fixed we use our current linting method for PHP and JSON. When that is fixed we can move the `linting` job over to super-linter which will help us with more advanced linting in the future.
You can see an example of what this validation looks like at https://github.com/cpeel/dproofreaders/actions/runs/616025652

Move linting and other static checks to GitHub Actions

---

SETUP/upgrade/16/20210306_clean_usersettings.php

WordCheck tool layout is now saved in local browser web storage rather than in the database.

Remove unused WordCheck tool settings

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.js

This change downgrades the scNoCap error into a warning when the text within the tags begins with an asterisk. This allows for cases where a word typed in small caps is fragmented over multiple pages or footnotes. I stumbled across this while formatting the other day, and I figured it would be a relatively trivial fix.

Fix scNoCap error criterion in format preview

---

pinc/upload_file.inc

Fixed the regex used to determine whether a subdirectory in a PM's
uploads directory was given a valid filename. Thanks to @cpeel for the code to do the fix. I just tested it and pushed up the MR.
Testable: [fix-subdir-creation](https://www.pgdp.org/~srjfoo/c.branch/fix-subdir-creation/tools/project_manager/remote_file_manager.php)

Fix subdirectory creation for PM uploads

---

SETUP/lint_charsuites.php
pinc/unicode.inc
quiz/generic/proof.php
tools/project_manager/handle_bad_page.php
tools/proofers/proof_frame_enh.inc
tools/proofers/spellcheck.inc
tools/proofers/text_frame_std.inc

This addresses two different problems:
1. For some reason `grapheme_extract()` treats "\r\n" as a single grapheme but all of our code assumes they are two separate characters (which they are).
2. Work around the portable-utf8 bug which is not correctly converting some Unicode strings to characters by using escape values for regexs instead.
Testable in the [fix-grapheme-split](https://www.pgdp.org/~cpeel/c.branch/fix-grapheme-split/) sandbox.

Work around portable-utf8 bug by using escape sequences in regex

---

pinc/misc.inc
pinc/unicode.inc
quiz/generic/proof.php
tools/project_manager/handle_bad_page.php
tools/proofers/proof_frame_enh.inc
tools/proofers/spellcheck.inc
tools/proofers/text_frame_std.inc

This includes 3 separate commits:
* Correctly escape JS characters > `0xffff` in `javascript_safe()`.
* Encode combined characters in the regex as Unicode escape sequences.
* Don't escape the regex (since it can no longer contain special characters) to improve development & debugging and use `json_encode()` for simple JS strings.
Either 1 or 2 & 3 are required, but not sufficient, to correctly support Unicode codepoints above `0xffff`. Said another way: this is not all that is required to support some high Astral plane characters but it gets us closer.
Testable in [minor-unicode-updates](https://www.pgdp.org/~cpeel/c.branch/minor-unicode-updates/)

Minor unicode updates

---

SETUP/Makefile
accounts/addproofer.php
pinc/User.inc
pinc/bootstrap.inc
pinc/dpsession.inc
pinc/dpsession_via_cookies.inc
pinc/dpsession_via_php_sessions.inc
pinc/gettext_setup.inc
pinc/misc.inc
tools/setlangcookie.php

Set all cookies to SameSite=Lax which is the default on newer browsers when not specified to None anyways. Set CSRFtoken cookie to SameSite=Strict as it is only sent on form POST/PUT which cannot be done from 3rd party context, even top level navigation.
Testable in sandbox here:
https://www.pgdp.org/~chrismiceli/c.branch/samesite
Scenarios to verify:
1. Login
2. Logout
3. Saving user preferences
4. Navigate to page with ?lang=<lang> and verify language cookie is set and respected throughout application as usual
5. Registering a new proofer. Also verify that navigating to the activate link works from another domain, such as an email web page like gmail.
6. Forums and wiki still accessible
You can read more about samesite cookie properties here: …

set samesite cookies

---

pinc/filter_project_list.inc

Properly escape language regex filters. This not only filters the regex special characters but the values themselves. This was found in `php_errors` from the every-two-weeks Detectify run.
Testable in [escape-lang-regex](https://www.pgdp.org/~cpeel/c.branch/escape-lang-regex/) sandbox.

Properly escape language regex filters

---

tools/project_manager/downloadproofed.php

Check for the project table existing before doing the query to avoid throwing an error to the user and logging one to php_errors.
This is the page accessed by going to the "View Images, Pages Proofread and Differences" link on the project page and then clicking one of the page text links. The error happens when you access a URL for a project that has been deleted or archived.
There was some discussion about removing this script entirely and making those links going to the Page Browser in text-only mode. I think that's a good idea if anyone wants to either try and convince the community of it and/or fight them after.
Testable in the [fix-download-delete-project](https://www.pgdp.org/~cpeel/c.branch/fix-download-delete-project/) sandbox.

Check for project table before doing query

---

stats/includes/team.inc

If a team is edited without re-uploading an avatar or an image we attempt to access an index of null. This suppresses the error but doesn't fix it, because the teams code is a mess and it's not worth the effort.
I've filed https://github.com/DistributedProofreaders/dproofreaders/issues/606 in case someone wants to take on redesigning the morass that is the Teams and Members code.

Suppress errors on team edits

---

pinc/post_processing.inc

When we switched from using projects.modifieddate to using user_project_info.t_latest_home_visit to determine when a PPer was notified of projects needing to be renewed, we left out the case where a project was reserved in the rounds and checked out automatically -- t_latest_home_visit is not updated when a project moves into a post-processing stage. This changes the query to use the more recent date for determining when it's time to renew.
I've verified on the command line that the query works, but can't think of a good way to verify it otherwise, so I haven't set up a sandbox for it.

Fix the PP alert threshold

---

list_etexts.php

The primary goal of this MR was to update the descriptive text for the Bronze list so that it matches what's actually displayed. See [Task 1163](https://www.pgdp.net/c/tasks.php?action=show&task_id=1163). To more correctly describe each star metal, the common boilerplate paragraph was removed, and similar text was customized for each one.
The original task and comments suggested changing the text as a possible option. Possibly in the future, the other suggestion will be implemented, but meanwhile, the text will at least correctly describe what's displayed.
Also added a maximum number of items to display per page.
Testable: [~srjfoo/c.branch/update-bronze-blurb](https://www.pgdp.org/~srjfoo/c.branch/update-bronze-blurb/list_etexts.php?x=b&sort=5).

Update descriptive text for Bronze list

---

pinc/ProjectTransition.inc
tools/project_manager/generate_post_files.php
tools/project_manager/post_files.inc

This started out as addressing errors in `php_errors` from someone trying to download post files for a deleted project (the new error checking in `post_files.inc`) and like many things while fixing that I cleaned up some other UX for generating post files along the way.
Testable in the [generate-post-files-improvements](https://www.pgdp.org/~cpeel/c.branch/generate-post-files-improvements) sandbox.

Generate post files improvements

---

tools/project_manager/show_good_word_suggestions_detail.php
tools/project_manager/show_word_context.php

This reverts commit 0c1d3b32f1cfe0942915b9f26d1a8195b08013f7.
'#' allows 'open in new tab' which opens the same page instead of the intended page in the new tab.
With the javascript void version, the options for opening in a new tab or window are not shown.
Perhaps a better fix would be to use an actual button but style it to look like a link in order to avoid changing the user experience.
published to https://www.pgdp.org/~rp31/c.branch/new_tab_fix

Revert "change href to #"

---

tools/site_admin/show_access_log.php

Script available to site admins and access request reviewers. Current choices were limited to grant and revoke. Added block, unblock, request and deny-request-for.

Added action choices to show_access_log

---

.php_cs.dist
pinc/DifferenceEngineWrapper.inc
pinc/SortUtility.inc

I noticed it scanned and found 2 php files in node_modules. This is a waste of processing as we don't want to touch these files. The linter also made these other changes so I thought I'd include them here.

skip node_modules

---

tools/site_admin/edit_mail_address_for_non_activated_user.php

The inline tags in this file are confusing PHP-CS-Fixer.
Testable in the [fix-inline-php-formatting](https://www.pgdp.org/~cpeel/c.branch/fix-inline-php-formatting/) sandbox (requires SA privs).
Why wasn't this caught/fixed in the initial pass? Good question, I'm glad you asked. For performance purposes, PHP-CS-Fixer creates a `.php_cs.cache` cache file to allow it to skip files that haven't changed since the last time it ran and fixed things. So the first time this ran it fixed the file, but it wasn't idempotent and changed the file _again_ the second time. I've confirmed that the codebase is now format-stable by running this multiple times and removing the cache file after each run.

Remove inline <?php tags from edit_mail_address_for_non_activated_user.php

---

.github/workflows/static-checks.yml

Add PHP style enforcement to our CI pipeline. Note that the pipeline will (correctly) fail right now until https://github.com/DistributedProofreaders/dproofreaders/pull/621 merges in. I intentionally wanted to get this in prior so we can see what it looks like when it fails.
This fixes https://github.com/DistributedProofreaders/dproofreaders/issues/619

Add PHP-CS-Fixer to GitHub linting

---

tools/proofers/character_selector.js
tools/proofers/dp_scroll.js

Task https://www.pgdp.net/c/tasks.php?action=show&task_id=1985
According to https://caniuse.com/?search=focus%3ApreventScroll it won't work on Safari or some older browsers.

prevent scroll caret into view on selecting a picker

---

pinc/User.inc

I hit this while switching identities. It occured in commit f3748c2bcbbde7cb8f7bf17fbacc8764d8d5b4f1

fix typo header_sent

---

scripts/page_browse.js
scripts/splitControl.js

This is the version of image widget we want to present for evaluation.
The text both has a splitter and is editable only for a user with Mentor, PF or Squirrel access.
The drag bar markers are not implemented. 
Sandbox at https://www.pgdp.org/~rp31/c.branch/split_simplify

Split simplify

---

pinc/ProjectSearchForm.inc
tools/project_manager/edit_common.inc
tools/project_manager/show_specials.php

Until now once a special day was created and enabled so that Project Managers could assign the special day to a project, it was permanent.
This fixes it so that a special day can be disabled for assigning to projects, but can remain for projects that used it prior to it being disabled. It also allows disabled special days to be selected in the project search form, and adds an indicator to the `show_specials` list to indicate which special days have been disabled.
Sandbox here [add-disable-special-day](https://www.pgdp.org/~srjfoo/c.branch/add-disable-special-day/).

Add the ability to disable special days

---

tools/project_manager/editproject.php

If the user selects no character suites when editing a project we need to treat the POST as an empty array (which we handle as an error case later) rather than an unset variable.
This fixes an error found in `php_errors` on PROD.

Correctly handle empty charsuite

---

activity_hub.php
project.php
tools/project_manager/clearance_check.php

On the Activity Hub, if filters are enabled for the  Site Progress Snapshot table, the rows in the Post-Processing part of the table displays the rows with the filter links the full width of the Round section of the table. This removes the IE hack, and re-does the logic to match row display to the table section. Sandbox here: [cleanup-2021-06](https://www.pgdp.org/~srjfoo/c.branch/cleanup-2021-06/activity_hub.php).
The other commit contains a couple of tweaks to the `gettext()` code that are designed for translators, but that will be invisible to users.

Snapshot table display fix

---

pinc/ProjectSearchResults.inc
project.php
tools/project_manager/edit_project_word_lists.php

Word lists are stored in the project directory and thus if the directory has been deleted (because the project was archived or deleted) the project's word lists cannot be managed. Prevent the link from showing up on the project page and do a more robust job of checking for these edgecases in the edit word lists page and failing early. This fixes an error seen in `php_errors` from PROD.
This consolidates some of the validation logic in `edit_project_word_lists.php`. It's still a hot mess (which I can say with both authority and shame since I wrote it all 14 years ago).
Testable in the [fix-archived-wordlist-edits](https://www.pgdp.org/~cpeel/c.branch/fix-archived-wordlist-edits/) sandbox.
Please help validate that this behaves like we would expect during project create. It should but …

Prevent editing word lists for archived projects

---

tools/project_manager/projectmgr.inc

This implements task 1989.
Is this the best wording and position in the list?
Sandbox at: https://www.pgdp.org/~rp31/c.branch/link_char_suite
It is apparent that the file  tools/project_manager/projectmgr.inc contains some redundant logic and is itself redundant in that the functions it implements are now each used in only one (different) php file and could be moved there. This could be addressed in another branch.

Added PM link to character suites

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.js

This first checks that proofers' notes are properly closed then removes them before format checking. This allows multi-line notes as in task 1977 and avoids various complications which can arise such as tags inside proofers' notes and notes inside markup.
Modified to handle nested pairs of brackest inside proofers note so handles case https://www.pgdp.net/phpBB3/viewtopic.php?p=1250240#p1250240.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/rem_proof_note_nest

Remove proof notes

---

pinc/upload_file.inc

GM request: In order to keep MaxScanSize in clamd.conf at what we hope is a reasonable level to not overstress the server, while still doing an AV check on all uploaded files, reduce the max upload to 200MB. Sandbox at [reduce-max-upload](https://www.pgdp.org/~srjfoo/c.branch/reduce-max-upload/).
This is PGDP-specific and should go in as a site-specific hack.

Reduce maximum upload size to 200MB

---

tools/project_manager/editproject.php
tools/project_manager/manage_image_sources.php

GM request; PG has asked that URLs (including email addresses) not be included in uploads to PG. Investigation showed that some of the image sources' credit lines included links. This MR updates the edit form for PMs to edit the project pages, and the Image Sources management form and display page to explicitly emphasize that the Credits line should not include URLs. Sandbox: [image-credits-no-link](https://www.pgdp.org/~srjfoo/c.branch/image-credits-no-link/).

Don't include URLs in credits for PG uploads

---

pinc/quizzes.inc

The quiz page does not explicitly state that the special topic quizzes are not required for advancement, which confuses some users (for the three quizzes that are required, it does say so) -- especially beginners. Add a note to the "Specialized Proofreading Quizzes and Tutorials" section that explicitly states that they are not required. 
No separate sandbox for this, but it can be seen in [this sandbox](https://www.pgdp.org/~srjfoo/c.branch/revise-greek-quiz-p3/quiz/start.php?show_only=proof).

Special quizzes not required

---

SETUP/CHANGELOG.md
SETUP/upgrade/16/20210807_update_sf_genre.php
pinc/ProjectSearchResults.inc
pinc/genres.inc
pinc/project_quick_check.inc
pinc/showavailablebooks.inc
project.php
stats/to_be_released.php
tools/project_manager/edit_common.inc
tools/project_manager/show_image_sources.php

GM request: Rename the `Science Fiction` genre to `Science Fiction & Fantasy`. This acknowledges explicitly how the genre is actually used.
Branch sandbox at [rename-sf-genre](https://www.pgdp.org/~srjfoo/c.branch/rename-sf-genre/).

Rename SF genre to SF&F

---

package-lock.json
package.json

Based on recent dependabot I'm updating major versions to fix npm security issues that don't really impact us since we only use this for development.

update npm versions for security fixes

---

tools/proofers/image_block_enh.inc
tools/proofers/image_frame_std.php

This avoids the effect seen when the control bar is at the side and the image view is very short so the buttons will not fit in the available space.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/widget_adjust_1

Hide overflow from toolbar

---

scripts/control_bar.js
styles/global.less
styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/page_browser.php

This fixes the toolbar disappearing off the bottom of the screen and the iPad fit-height problem using plain images.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/height_fix

Height fix

---

scripts/control_bar.js
scripts/page_browse.js
styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/proofers/image_block_enh.inc
tools/proofers/image_frame_std.php

The vertical control bar now scrolls if its contents will not fit. The scroll bar covers the "%" sign. The bar can also be scrolled horizontally (by arrow keys) to reveal it but the bar is so narrow that the browser does not display the horizontal scroll bar.
The way this is implemented is that the bar overflow is now set to "auto". Unfortunately this prevents the menu from appearing. This is apparently because it is in a relatively positioned div. This div was removed and the menu position set by javascript functions instead. Thanks to "https://css-tricks.com/popping-hidden-overflow/" and other sites.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/bar_scroll

Bar scroll

---

scripts/control_bar.js
styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

the -webkit... option worked with iPad but made input too wide on Edge and Chrome. 1.9rem is better on all.
This prevents percent being > 999 which would not fit in the box.
There are some anomalies due due to rounding percent to a whole number. e.g. fit height and width sometimes show a small gap or a scrollbar.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/adjust_percent_input

Adjust percent input

---

api/v1_projects.inc
pinc/ProjectSearchResults.inc
pinc/list_projects.inc

The MySQLisms `SQL_CALC_FOUND_ROWS` & `FOUND_ROWS()` are deprecated and will be removed in future versions. This replaces them with `COUNT(*)` to get the same result. Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/679.
Testable in the [remove-mysql-found-rows](https://www.pgdp.org/~cpeel/c.branch/remove-mysql-found-rows/) sandbox. The pages impacted are:
* [list_etexts.php](https://www.pgdp.org/~cpeel/c.branch/remove-mysql-found-rows/list_etexts.php?x=b&sort=5)
* [search.php](https://www.pgdp.org/~cpeel/c.branch/remove-mysql-found-rows/tools/search.php)
And the project search API:
```bash
curl -i -g -X GET "https://www.pgdp.org/~cpeel/c.branch/remove-mysql-found-rows/api/index.php?url=v1/projects&genre=Other" \
-H "accept: application/json" \
-H "X-API-KEY: …
```

Remove use of `SQL_CALC_FOUND_ROWS` & `FOUND_ROWS()`

---

activity_hub.php
faq/site_progress_snapshot_legend.php

Both the tooltip for ⓘ on the Activity Hub and the description in site_progress_snapshot_legend.php say "are" eligible. This commit changes that to "may be" eligible (for example, most people are not eligible to work as PPVers, yet everyone sees that icon for the PPV activity. Add to the Activity description for SR an explanation that the SR count is included in the PP count (should this be with PP, instead, or in addition?).
[ah-cleanup](https://www.pgdp.org/~srjfoo/c.branch/ah-cleanup/activity_hub.php)

Update wording on AH and snapshot legend

---

faq/translate.php

The `faq/translate.php` document still assumed Latin-1. Update it for UTF-8.
[update-translate-doc/faq/translate.php](https://www.pgdp.org/~srjfoo/c.branch/update-translate-doc/faq/translate.php)

Update translate.php for UTF-8

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md
SETUP/UPGRADE.md
SETUP/check_db_schema.template

This is prep work for the upcoming R202109 release, slated for the end of the month. This won't get merged in until just before the release is cut.
I welcome input on if there are other things we should include in the `CHANGELOG.md` or suggestions on the ordering (we like to focus on the most possibly-disruptive changes at the top).

Prepare R202109 release

---

scripts/control_bar.js

After clicking on the image it can be moved with the arrow keys as well as moved by dragging.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/image_drag_focus

enable image move with arrow keys

---

SETUP/GRAPHS.md
pinc/graph_data.inc
scripts/svgGraphs.js
stats/pp_stage_goal.php
stats/round_backlog.php
stats/round_backlog_days.php
styles/layout.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

This I believe is the last MR before we can merge to master in my opinion for feedback from TEST. It fixes the faint bars in https://www.pgdp.org/~chrismiceli/c.branch/adjustments/stats/pages_proofed_graphs.php?tally_name=P1
as well as adding a 0 horizontal line for bar/line charts that include negative y values. For example
https://www.pgdp.org/~chrismiceli/c.branch/adjustments/stats/pages_proofed_graphs.php?tally_name=P1
and
https://www.pgdp.org/~chrismiceli/c.branch/adjustments/stats/members/mdetail.php?id=393&tally_name=P1&range=365
Sandbox
https://www.pgdp.org/~chrismiceli/c.branch/adjustments

min width for bars and 0 line for negative bars

---

pinc/stages.inc

At the request of the GM and the French language coordinator, French projects have been removed from the newcomer reserve.
Testable: [remove-french-reserve](https://www.pgdp.org/~srjfoo/c.branch/remove-french-reserve), compare against [test-vanilla](https://www.pgdp.org/~srjfoo/c.branch/test-vanilla) (which still has the newcomer reserve for French). The sandboxes have had the `page_tally_threshold` set to 5 pages so that the change can be verified without having to proof 500 pages.

Remove French projects from newcomer reserve

---

styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Rev the Google Font URLs. This resolves GitHub linting errors when validating the CSS matches the LESS files.
The reason this happens is because the `global.less` file points to a static URL that resolves to a versioned URL in the generated `.css` files. This isn't a problem until the version changes and the linter sees that the new version differs from the one checked into the `.css` files.
Testable in the [update-google-fonts](https://www.pgdp.org/~cpeel/c.branch/update-google-fonts/) sandbox.

Rev Google Font URLs

---

quiz/generic/data/qd_p_basicx_1.inc
quiz/generic/data/qd_p_basicx_2.inc
quiz/generic/data/qd_p_mod1_1.inc
quiz/generic/data/qd_p_mod1_2.inc
quiz/generic/data/qd_p_mod1_3.inc
quiz/generic/data/qd_p_mod1_4.inc
quiz/generic/data/qd_p_mod1_5.inc
quiz/generic/data/qd_p_mod2_1.inc
quiz/generic/data/qd_p_mod2_2.inc
quiz/generic/data/qd_p_mod2_3.inc
quiz/generic/data/qd_p_mod2_4.inc
quiz/generic/data/qd_p_mod2_5.inc
quiz/tuts/tut_p_mod1_1.php
quiz/tuts/tut_p_mod1_2.php
quiz/tuts/tut_p_mod1_3.php
quiz/tuts/tut_p_mod1_4.php
quiz/tuts/tut_p_mod1_5.php
quiz/tuts/tut_p_mod2_1.php
quiz/tuts/tut_p_mod2_2.php
quiz/tuts/tut_p_mod2_3.php
quiz/tuts/tut_p_mod2_4.php
quiz/tuts/tut_p_mod2_5.php

GM request: the quiz page numbering system for the actual quiz and tutorial pages for the moderate quiz and tutorial pages differs from that used on the quiz start page, and the file names. This has been known to cause confusion when one person uses one numbering system, and another uses the other. This updates the numbering used by those tutorial and quiz pages to match those on the quiz start page.
Sandbox available [here](https://www.pgdp.org/~srjfoo/c.branch/quiz-numbering-tweaks). Tutorials 1-5 and 2-1 have some wording/format changes.

Updated quiz numbering, moderate and basicx

---

pinc/ProjectSearchForm.inc
pinc/special_colors.inc
project.php
tools/project_manager/edit_common.inc
tools/project_manager/show_specials.php

Use the `load_special_days()` code when populating the page to view them and when loading them when editing projects. This also adds a helper function for sorting them by the most commonly used methods. The only user-visible change is that special days that happen on the same month/day pair are now sub-sorted alphabetically by the special day display name. This is probably only relevant on TEST I think.
I did not change the queries used in `tools/site_admin/manage_special_days.php` since that is doing updates as well as queries. I think that's the last remaining place that queries the `special_days` table directly though.
This is some infra prep work as I putz on [Task 2011](https://www.pgdp.net/c/tasks.php?action=show&task_id=2011).
Testable in …

Use load_special_days() in more places

---

pinc/Project.inc
tools/project_manager/edit_common.inc
tools/project_manager/show_image_sources.php

This centralizes the queries against the `image_sources` table, with the exception of those in `manage_image_sources.php`. The `Project.inc` file isn't the ideal place for this, but it is at least a reasonable one until we make an `ImageSource` abstraction.
This has only one functional change: image source visibility is now enforced when creating or editing a project. Prior, any image source -- even ones that shouldn't be visible to PMs -- were selectable on the Edit Project page. This work enables progress on Task 2011.
Testable in the [centralize-image-sources-query](https://www.pgdp.org/~cpeel/c.branch/centralize-image-sources-query/) sandbox.

Centralize queries against image_sources table

---

api/v1_projects.inc
pinc/Project.inc
pinc/ProjectSearchForm.inc
pinc/filter_project_list.inc
project.php
tools/project_manager/edit_common.inc

Define the project difficulty options once instead of *four* times. This is in prep work for project validation as part of Task 2011.
Testable in the [centralize-difficulty-list](https://www.pgdp.org/~cpeel/c.branch/centralize-difficulty-list/) sandbox.

Centralize project difficulty definition

---

tools/project_manager/update_illos.php
tools/site_admin/delete_pages.php
tools/site_admin/index.php
tools/site_admin/project_jump.php

This brings the `noncvs/project_jump.php` script into the codebase. I modeled the code off of the other SA scripts -- and like those it isn't up to the same high standards as the rest of the codebase (translatable, etc). It is now generic and applies to whatever rounds are defined in the code. We'll need to augment this in `pgdp-production` to add the PP-specific stages we're interested in.
This script also now checks that the project's pages table exists before allowing the transition.
Testable in the [project-jump](https://www.pgdp.org/~cpeel/c.branch/project-jump/tools/site_admin/index.php) sandbox.

Bring project_jump.php from noncvs into the code

---

api/dp-openapi.yaml
api/v1.inc
api/v1_projects.inc

This PR extends the API to allow users to get a list of character suites, special days, and image sources. This will be necessary for users to create projects (eventually) as part of [Task 2011](https://www.pgdp.net/c/tasks.php?action=show&task_id=2011).
The API intentionally does not use the exact same field names as those stored in the database. Instead, we try to present a more unified view to the outside world. Like other parts of the API, these only return data that the user can already see in the UI. This is most relevant to image sources which have scoped visibility -- some can only be viewed by PMs, or Image Source Managers / SAs. The PR includes update to the Swagger schema as well.
This code is live in the sandbox at https://www.pgdp.org/~cpeel/c.branch/api-proj-gets/ but there …

Add API to get list of charsuites, special days, and image sources

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.js

This enables footnote markers to be italic or other tagged letters. Also improve some variable names and add tests.
Addresses https://www.pgdp.net/c/tasks.php?task_id=2013
Sandbox at: https://www.pgdp.org/~rp31/c.branch/italic_foot

Italic foot

---

tools/site_admin/project_jump.php

_This is going into the `pgdp-production` branch._
This updates the new `project_jump.php` script in the code to include PP-specific states that were not easily abstracted out into a generic form for released code. This should now match what is currently live in `noncvs`.
Testable in the [project-jump](https://www.pgdp.org/~cpeel/c.branch/project-jump/) sandbox.

Add PP states to project_jump.php

---

pinc/wordcheck_engine.inc

After some profiling using xdebug on "Manage proofreaders' Suggestions" in response to [Task 2010](https://www.pgdp.net/c/tasks.php?action=show&task_id=2010) I made some surgical fixes to two WordCheck functions that improved the processing time by 25% according to the profile. I don't know how much this will improve okrick's performance problems on PROD, as I think the overriding factors for him are the total number of projects (70!) & text therein.
Testing should focus on ensuring that the results shown on the "Manage proofreaders' Suggestions" in the sandbox match TEST for various users at the "1" cutoff. Other WordCheck PM tools use this underlying code as well, but that's probably the most robust method.
Testable in the [faster-wordcheck-funcs](https://www.pgdp.org/~cpeel/c.branch/fas …

Speed up select WordCheck functions

---

pinc/Quiz.inc
pinc/quizzes.inc
quiz/generic/quiz_defaults.inc
quiz/start.php

I found a few code improvements using the xdebug profiler, this is the first one and focuses on decreasing unnecessary overhead of every page load.
`pinc/Activity.inc` -- which virtually every page load uses -- includes `pinc/quizzes.inc` to determine the user's access privileges. `pinc/quizzes.inc` includes `quiz/generic/quiz_defaults.inc` which defines a very large global `$messages` array that is only used in the quizzes. This breaks apart that dependency which reduces the overhead for every page load.
This also improves the query and logic used to determine if a user has passed a quiz.
Testable in the [reduce-quiz-overhead](https://www.pgdp.org/~cpeel/c.branch/reduce-quiz-overhead/) sandbox. Primary thing to test is that the logic for determining if a user has passed a quiz (including …

Reduce quiz overhead for non-quiz pages

---

pinc/Activity.inc

Another optimization found via xdebug profiling.
Determining a user's access to a round is done by computing a score based on the activity's (stage, round, etc) criteria. Only determine the score based on the necessary activity's criteria, rather than doing it based on all criteria and only using the ones for the activity. This is oddly expensive because we need to know a user's access for every activity to create the navbar links and some, but not all, activities require quiz passes. Only do the work that is actually necessary to determine a user's access.
Testable in the [more-code-optimizations](https://www.pgdp.org/~cpeel/c.branch/more-code-optimizations/) sandbox. Easiest way to test this is to confirm that the activity links in the navbar are consistent with the user's access and …

More code optimizations for page loads

---

pinc/page_table.inc

The (final?) improvement I found while using the xdebug profiler.
Loops within loops within loops. Build and reuse a page state cache when filling out the page table. No need to calculate the same bad/available state again and again for every page for every round in a project.
Testable within the [page-table-optimizations](https://www.pgdp.org/~cpeel/c.branch/page-table-optimizations/) sandbox. Page tables for various projects should look identical to how they have before.

Build a reuse a page state cache for page table

---

pinc/ProjectTransition.inc
tools/proofers/my_projects.php

Last one, promise.
This has a minor improvement to the My Projects page to only update the user's My Project view settings in the DB if they've changed. This reduces some thrashing on the database in the most common case.
It has a major improvement to the PM and Search pages for users who are authorized to change page states. The aggregate time to determine what states the user can transition the projects to was almost the same as the SQL search for the list of projects. Caching viable transitions for a "from" state can help subsequent calls for later projects on the PM and Search pages.
Testable in the [myproject-search-optimizations](https://www.pgdp.org/~cpeel/c.branch/myproject-search-optimizations/) sandbox. The areas to watch out for are making sure the My Projects page correctly …

My Projects  & Search page optimizations

---

pinc/iso_lang_list.inc

Shockingly, half the time spent running WordCheck is building the list of available additional dictionaries for the drop-down. This is expensive because `langname_for_langcode3()` is called within several other language functions that get used as part of generating the list, resulting in 69k calls to `substr()`. We can reduce this by only checking the 23 possibly-valid dictionary files that have a 2- or 3-letter code rather than all 84 of them. Creating a reverse lookup cache would be even faster, but I'm not certain the memory overhead is worth the value.
Also correct the logic error where we use `substr()` to split apart combined language codes. Pulling out the first three letters isn't correct and will lead to `qaa` being a valid code when it is actually part of the `qaa-qtz` reserved …

Faster wordchecks

---

accounts/addproofer.php
pinc/email_address.inc

Increase the length of a valid TLD to 63 characters. While I was here I cleaned up a small localization error and removed an erroneous include.
Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/732.
This isn't easily testable on TEST because we skip email validation when `$testing = true`, but here's validation via script:
```php
<?php
$relPath = "./";
include_once($relPath."email_address.inc");
$addresses = [
"testing@valid.com",
"person@something.averylongtld",
"localhost",
"averyeryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryveryverylong@valid.com",
];
foreach ($addresses as $address) {
echo $address . "\n";
echo "    " . check_email_address($address) . "\n";
}
```
Output:
```
$ php test.php
testing@valid.com …
```

Accept longer TLDs in email addresses

---

pinc/CharSuites.inc

Very few pages actually care about character suites, so don't load them unless one or more of them is actually needed. This is a very small, but easy, micro-optimization that improves all pages. While here I updated the DB escape & query functions.
Testable in the [lazy-load-charsuites](https://www.pgdp.org/~cpeel/c.branch/lazy-load-charsuites/) sandbox.

Lazy load charsuites

---

pinc/ProjectSearchForm.inc
project.php
stats/PPV_avail.php
stats/checkedout.php
stats/release_queue.php
stats/to_be_released.php
tools/post_proofers/ppv_report.php
tools/project_manager/edit_project_word_lists.php
tools/project_manager/editproject.php

Standardize project field labels so they are consistent throughout various pages on the site (project page, project search, project edit, etc). These are message-string-only changes.
Previewable in [standardize-project-edit-labels](https://www.pgdp.org/~cpeel/c.branch/standardize-project-edit-labels/).

Standardize project field labels

---

pinc/misc.inc

`ValueError` is a very useful exception that was (finally!) included in PHP 8. Backport this so we can use it now. I am using this in the project validation work for Task 2011 but want to get it in now for some current PRs.

Backport ValueError from PHP 8

---

.gitignore
.php-cs-fixer.dist.php
SETUP/check_require_login.php
composer.lock

Update the PHP-CS-Fixer version to the latest 2.x and all of the dev package dependencies to their latest version (2 commits).
Note that PHP-CS-Fixer 2.x is EOLed. The 3.x version ends up with some additional, reasonable formatting changes that I don't want to inflict upon us quite yet given how much stuff is in-flight. We can worry about that later.
Nothing to test as these are all dev-only changes but validation that it doesn't change any of the formatting:
```
cpeel@ip-172-31-12-95:~/u-cpeel-dp (update-phpcsfixer)$ PHP_CS_FIXER_FUTURE_MODE=1 ./vendor/bin/php-cs-fixer fix
You are running PHP CS Fixer v2, which is not maintained anymore. Please update to v3.
You may find an UPGRADE guide at https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v3.3.0/UPGRADE-v3.md .
If you need help while …
```

Update PHP-CS-Fixer and dev dependencies

---

SETUP/tests/ProjectTest.php
SETUP/tests/UserTest.php
SETUP/tests/phpunit_bootstrap.php
SETUP/tests/phpunit_test_helpers.inc
pinc/Project.inc

This copies (but does not move) the project validation logic from `tools/project_manager/editproject.php` into the Project class. This will allow it to be used both for the UI and the API.
The validation logic in `editproject.php` is intertwined with the ProjectHoldInfo class in that file and I decided it was clearer if I did the move in two steps (this PR to create it, and a separate one to use it). I have a second branch prepared that uses this validation and is ready for review once this one goes in.
For validation I added several new unit tests. I also ran the validation code against all of the existing projects on TEST with this code:
```php
<?php
$relPath = "./";
include_once($relPath."base.inc");
include_once($relPath."Project.inc");
$sql = "
SELECT projectid
FROM projects
ORDER BY …
```

Add project validation logic to the Project class

---

pinc/Project.inc
project.php
tools/project_manager/editproject.php

Reduce duplicated mappings of project fields with their localized names. I introduced new ones with the new `validate()` function not realizing that we had some already mapped in `project.php` (with a helpful message that it probably belongs in `Project.inc`). In some future world we would re-use these elsewhere, but this is a starting point.
I discovered this because as part of `editproject.php` we store the names of changed fields in `project_events.details1`. But we store the names of the fields as they are in `ProjectInfoHold` -- not as they are in the `Project` object (which maps to the database). That's why we need some additional mappings.
Compare the Project History section of a project in the [main TEST sandbox](https://www.pgdp.org/c/project.php?id=projectID61e78b003e12d#holds) …

Move project field labels into Project table

---

pinc/ProjectTransition.inc

This is a small cleanup of `ProjectTransition.inc` for how we make DB calls. It also makes better use of the `$project` object in `project_pre_release_check()` to correctly detect projects without page tables. No functional changes.
Testable in the [update-proj-tran-queries](https://www.pgdp.org/~cpeel/c.branch/update-proj-tran-queries/) sandbox. I have confirmed:
* deleting a project deletes the project directory.
* valid projects correctly transition into P1 waiting and P1 available.
* invalid projects ([like this one](https://www.pgdp.org/~cpeel/c.branch/update-proj-tran-queries/project.php?id=projectID56f1e6bd90dcf&detail_level=3)) produce an error when being pushed into P1 waiting.
The changes to `project_pre_release_check()` might be better reviewed in the split (ie side-by-side) …

Clean up DB calls in ProjectTransition

---

SETUP/tests/ProjectTest.php
pinc/Project.inc
tools/project_manager/edit_common.inc
tools/project_manager/editproject.php

This adds unit tests (yay!) for the existing encode/decode language functions. It also removes one more place where we parsed the string and replaces that with the decode function.
This also introduces a new setter that allows us to set a project languages directly (via `$project->languages = [..]`). This will be used in the new project API.
The only place this PR impacts the current code is within the Edit Project page when changing a project's languages.
Available in the [language-handling](https://www.pgdp.org/~cpeel/c.branch/language-handling/) sandbox.

Improve language handling with encode/decode

---

pinc/ProjectSearchResults.inc
pinc/project_edit.inc
tools/pending_access_requests.php
tools/project_manager/edit_project_word_lists.php
tools/project_manager/editproject.php
tools/project_manager/handle_bad_page.php
tools/project_manager/move_projects.php
tools/project_manager/word_freq_table.inc
tools/site_admin/convert_project_table_utf8.php
tools/site_admin/copy_pages.php
tools/site_admin/delete_pages.php
tools/site_admin/edit_mail_address_for_non_activated_user.php
tools/site_admin/index.php
tools/site_admin/manage_random_rules.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/manage_site_charsuites.php
tools/site_admin/manage_site_word_lists.php
tools/site_admin/manage_special_days.php
tools/site_admin/proj_approvals.php
tools/site_admin/project_jump.php
tools/site_admin/rename_pages.php
tools/site_admin/show_access_log.php
tools/site_admin/show_common_words_from_project_word_lists.php
tools/site_admin/sitenews.php

We currently have two similar checks to determine if a user is able to manage a project. Centralize on the one within the Project class. This ensures that the API (which uses the Project-based method for checking wordlist management access) and the project edit UI (which uses the `project_edit.inc`-based way) use the same code.
Testable in the [single-manage-check](https://www.pgdp.org/~cpeel/c.branch/single-manage-check/) sandbox.

Centralize project manage check in Project class

---

SETUP/tests/misc_UtilsTest.php
pinc/misc.inc
tools/project_manager/editproject.php

In prep for a PR with some big changes to `editproject.php` to use the new `Project->validate()` function I wanted to get these two small commits in to make reviewing that one easier.
This:
* Removes the `get_default_character_suites()` function now that they are defined in `site_vars.php`
* Moves the generic `get_changed_fields_for_objects()` function into `misc.inc`.
Testing that recording of the fields changed for a project still works can be done in the [pre-project-save](https://www.pgdp.org/~cpeel/c.branch/pre-project-save/) sandbox.

Some small edit project clean-up

---

pinc/Project.inc
pinc/ProjectTransition.inc

In prep for some unit tests, move the logic of deleting a project to the Project class. No functional changes.

Move project deletion into Project class

---

pinc/Project.inc
tools/site_admin/index.php
tools/site_admin/projects_with_odd_values.php

Pull `noncvs/projects_with_odd_values.php` into the code so it can be maintained and make it work. This script has been broken since 2020-11-03 when langauges were pulled out of the global context into a function.
This also slightly changes the tool groupings on the Site Admin page.
Testable in the [data-check-tools](https://www.pgdp.org/~cpeel/c.branch/data-check-tools/) sandbox.

Pull projects_with_odd_values.php out of noncvs

---

tools/site_admin/shared_postednums.php

The script is somewhat resource intensive, and only site admins are able to deal with any new issues as they occur (and probably should have been restricted to SAs all along).
Testable: [restrict-dup-posteds](https://www.pgdp.org/~srjfoo/c.branch/restrict-dup-posteds).

Restrict access to the shared postednums script

---

SETUP/MediaWiki_extensions/dpExtensions.php
SETUP/MediaWiki_extensions/hospitalExtensions.php

Update the MediaWiki extensions to use DPDatabase functions. Update the projectinfo parser in dpExtensions file to work with MW 1.35.
You can view these on the [User:Cpeel/MediaWiki_Extensions](https://www.pgdp.org/wiki-test/User:Cpeel/MediaWiki_Extensions) page in the MediaWiki 1.35 testing wiki on TEST.

Updated MediaWiki extensions

---

crontab/onoff_special_event_queues.php
pinc/DPDatabase.inc
pinc/archiving.inc
tools/site_admin/copy_pages.php
tools/site_admin/rename_pages.php

Make DPDatabase::affected_rows() function and use it in existing code before new use.
The changed files have other database functions that could be updated. Should I do this in this branch to avoid them being in a partially updated state?
Sandbox at https://www.pgdp.org/~rp31/c.branch/affected_rows_function
I don't know why making less is needed to avoid erroring.

make DPDatabase::affected_rows() function

---

SETUP/tests/jsTests/characterValidation.js
quiz/generic/proof.php
scripts/character_test.js
scripts/text_validator.js
tools/proofers/process_diacritcal_markup.js

make validCharRegex when needed and use native javascript to make validCharRegex since unicode regex now in supported browsers. So don't need $(document).ready() in character_test.js which causes a problem in unit tests if another test uses promises.

Local regex

---

tools/project_manager/autorelease.inc

There was a bug in `attempt_to_release()` when called from `automodify.php` where it was passed a `$project` array but was expecting a `$project` *object*. This caused `project_pre_release_check()` to return an error (because it, too, was expecting an object). This resulted in every evaluated project being flagged as bad, and an email sent to the PM.
This creates the necessary project object for `project_pre_release_check()` and use in the error case for the emails as well.
This is the code code is hotfixed on PROD.

Fix autorelease logic

---

pinc/abort.inc

Properly sanitize output in `abort()`. This is not new, but we're using this at a higher level in the code now which makes it more visible. Detectify found this for us.
Compare:
* [TEST](https://www.pgdp.org/c/tools/proofers/text_frame_std.php?projectid=projectID453088b057325%27%22%3C/title%3E%3C/style%3E%3C/textarea%3E%3C/noscript%3E%3C/script%3E--%3E%3Cdtfy%3Ej5kFE1YD&proj_state=P1.proj_avail&reverting=0&imagefile=203.png&page_state=P1.page_out)
* [sanitize-abort sandbox](https://www.pgdp.org/~cpeel/c.branch/sanitize-abort/tools/proofers/text_frame_std.php?projectid=projectID453088b057325%27%22%3C/title%3E%3C/style%3E%3C/textarea%3E%3C/noscript%3E%3C/script%3E--%3E%3Cdtfy%3Ej5kFE1YD&proj_state=P1.proj_avail&reverting=0&imagefile=203.png&page_state=P1.page_out)
Also:
* …

Sanitize abort error messages

---

SETUP/CHANGELOG.md
SETUP/UPGRADE.md

This prepares for the upcoming R202202 release. I've updated the changelog with the notable changes I'm aware of after reviewing the git log since R202109. Devs, what have I missed?
Of note, this includes a message in the changelog about removing the code for the incomplete metadata and corrections features in the future.

Prepare for the R202202 release

---

SETUP/tests/jsTests/ajaxTests.js
SETUP/tests/qunit.html
scripts/api.js
scripts/page_browse.js

javascript native fetch uses the promise mechanism. This should make the code less incomprehensible than using two different methods for asynchronous operations.
There should not be any difference in function.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/api_fetch

change to using fetch for ajax instead of jquery function

---

SETUP/tests/ProjectTest.php
SETUP/tests/phpunit_test_helpers.inc
pinc/MARCRecord.inc
pinc/Project.inc
pinc/misc.inc
tools/project_manager/edit_common.inc
tools/project_manager/editproject.php

This is the big PR that all of the prior ones have been leading up to, and despite those smaller ones prior this is still a big one.
The overarching goal is to move the code that creates and updates project info from the `editproject.php` page to the `Project` class so it can be used both by the UI and the API. Indeed, I have a branch that builds on top of this one that adds project create and update code to the API.
I've added unit tests which cover basic project create, update, and delete functionality but the original Edit Project page is rife with interesting corner cases based on who is doing the editing (PM or SA) and testing this is going to be challenging. I've done a fair amount of testing already but I'd like a lot of eyes on this. If I've done my job right, this should behave …

Move project create and update logic to Project class

---

crontab/archive_projects.php
pinc/archiving.inc

When a project is archived, remove the `smooth/` directory. This directory contains redundant copies of existing files as a convenience to smooth readers and does not need to be retained. [Task 2017](https://www.pgdp.net/c/tasks.php?task_id=2017)
I also updated the archiving files to use the DPDatabase functions which is frankly the bulk of the PR.
I will provide testing instructions directly to @srjfoo.

Remove smooth dir on archive

---

api/USERS_GUIDE.md
api/dp-openapi.yaml
api/v1.inc
api/v1_projects.inc

Allow project holds to be managed through the API. This is part of [Task 2011](https://www.pgdp.net/c/tasks.php?action=show&task_id=2011).
I vacillated if the per-project endpoint should be `/holds` or `/holdstates` but `v1/projects/holds` didn't seem right and I went with `/holdstates` for both.
This is most readily testable via curl against the test sandbox:
```
export API_KEY=your_api_key
```
```bash
curl -i -X GET "https://www.pgdp.org/~cpeel/c.branch/api-project-holds/api/index.php?url=v1/projects/holdstates" \
-H "X-API-KEY: $API_KEY"
```
```bash
curl -i -X GET "https://www.pgdp.org/~cpeel/c.branch/api-project-holds/api/index.php?url=v1/projects/projectID44de3936807f1/holdstates" \
-H "X-API-KEY: $API_KEY"
```
```bash …
```

Manage project holds via API

---

pinc/DPDatabase.inc
pinc/Project.inc

If not specified, ALTER TABLE uses the *character set's* default collation during a character set conversion, not the *database's* default collation. Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/788
Testable in the [fix-utf8-table-convert](https://www.pgdp.org/~cpeel/c.branch/fix-utf8-table-convert/) sandbox.

Specify collation when converting charset

---

SETUP/tests/ProjectTest.php
pinc/Project.inc
pinc/misc.inc
tools/project_manager/edit_common.inc
tools/project_manager/editproject.php

Sharon's testing in #783 showed that we are missing some validation corner cases. I thought it would be best if I pulled those out to address separately.
Specifically this:
* Validates `comment_format` value (originally in 783 but is better here)
* Correctly validates `image_source` -- the prior code was simply wrong
* Validates Project field types during `validate()`. This is most notable through the API where we can assign an array to a string field which can confuse some other parts of the `validate()` checks and causes warnings as PHP casts the array into a string during `save()`.
* Updates the default value for `postednum` to be `null`. This matches what is actually in the database (NULL) but requires some massaging in the Edit Project page. This is, coincidentally, the only …

Better project validation

---

default.php

This para is being removed from `master` and will be expanded and added to `pgdp-production`. Compare [remove-verify-para](https://www.pgdp.org/~srjfoo/c.branch/remove-verify-para/) with [the main test server](https://www.pgdp.org/).

Remove para about verifying volunteering

---

default.php

The GM requested that the paragraph concerning volunteer service verification be expanded and updated. The original para has been removed from `master`. This PR adds the expanded para into the `pgdp-production` branch. See [updated-verify-para](https://www.pgdp.org/~srjfoo/c.branch/updated-verify-para/) for the updated text. I used `$wiki_url`, so that link will go to the nonexistent page in the TEST wiki; change `org` to `net` to see that the page for PROD does actually exist. This is a followup to PR #792.

Added updated verify para to pgdp-production

---

tools/project_manager/editproject.php

This fixes two bugs that have been found on the edit project page that came in with a71d4e30a:
* Correctly output a multi-level variable reference within a string. If we don't wrap it in `{}` only the part is used which is an object which raises an error and breaks the page.
* Remove PP-centric fields from cloned projects. These are being incorrectly cloned.
Testable in the [edit-project-updates](https://www.pgdp.org/~cpeel/c.branch/edit-project-updates/) sandbox.

Fix two project edit bugs

---

SETUP/tests/jsTests/formatPreviewTests.js
styles/preview.css
tools/proofers/preview.js
tools/proofers/previewControl.js

and mark as possible unrecognised tags, encode &, <, >  so output is valid html and browsers do not leave anything out.
This addresses the issue found in https://www.pgdp.net/phpBB3/viewtopic.php?f=34&t=61794&p=1273703#p1273703

detect all '<' characters

---

tools/post_proofers/ppv_report.php

GM request: Update PPV report card form and email body to link to/refer to PP FAQ for valid HTML versions. Also harmonized a couple of line items in the email body with their corresponding item in the form. Testable in the [revise-ppv-form](https://www.pgdp.org/~srjfoo/c.branch/revise-ppv-form/) sandbox.

Link PPV report to PP FAQ for valid HTML version

---

tools/upload_resumable_file.php

Don't log non-actionable client-induced upload errors. We continue to report them to the user (not that resumableJS will see them, but it's a good practice) but stop putting them in the `php_errors` log.
I feel confident we can review this by code inspection and that it doesn't need testing via sandbox.

Adjust resumable upload error logging

---

api/USERS_GUIDE.md
api/dp-openapi.yaml
api/index.php
api/v1.inc
api/v1_projects.inc

This enables creating and updating projects through the API. Virtually all of the heavy lifting was done in https://github.com/DistributedProofreaders/dproofreaders/pull/754, this just exposes it via the API.
The [api-update-project](https://www.pgdp.org/~cpeel/c.branch/api-update-project/) sandbox has the live code. This is testable via `curl` (as covered in the `USERS_GUIDE.md`) and also via the [Swagger Editor](https://editor.swagger.io/) (be sure to upload the new `dp-openapi.yml` file) via the `https://www.pgdp.org/api-dev/v1` development endpoint.

Enable project creation and update via the API

---

tools/project_manager/editproject.php

PFs are allowed to edit projects but not change the PM. This fixes a regression introduced in a71d4e30a.
Testable in [fix-project-edit-bug](https://www.pgdp.org/~cpeel/c.branch/fix-project-edit-bug/) sandbox.

Allow PFs to edit a project without changing the PM

---

api/exceptions.inc
api/v1_projects.inc

@srjfoo did some very thorough testing of the new project create/update API (thanks Sharon!) and found we were not doing the right permissions enforcement. This fixes those problems.
Testable in the [update-project-create-api-perms](https://www.pgdp.org/~cpeel/c.branch/update-project-create-api-perms/) sandbox.

Enforce correct project create/update perms in API

---

api/v1_projects.inc

The API was written for the "enabled" filter to be used as a boolean flag to either return all items or just enabled items. The Swagger UI expects it to accept both a "true" and "false" value as a boolean which is confusing for users who expect "false" to return all disabled items.
Update the 3 endpoints that accept an "enabled" flag to work both ways. This enables them to work with the Swagger UI as well as the original design.
Testable in the [fix-api-enable-disable](https://www.pgdp.org/~cpeel/c.branch/fix-api-enable-disable/) sandbox as well as the "Development" endpoint in the Swagger UI.

Allow selecting non-enabled data from endpoints

---

pinc/Quiz.inc

This centralizes the "did the user pass a quiz / quiz page" logic so we're not trying to figure out the same thing in 3 places. This was an initial investigation after @srjfoo found the unused `minimum_age` reference in `user_has_passed_quiz_page()` which is very likely a typo for `maximum_age` that has been there since its inception.
This should be functionally equivalent to what's on TEST.
Available in the [reduce-dup-quiz-page-pass-logic](https://www.pgdp.org/~cpeel/c.branch/reduce-dup-quiz-page-pass-logic/) sandbox.

Remove duplicate quiz page pass logic

---

api/v1_projects.inc

The clearance field is not available to all users -- restrict who has access to it in the API.
Testable with:
```bash
export API_KEY=review
curl -i -X GET "https://www.pgdp.org/~cpeel/c.branch/restrict-clearance-api-access/api/?url=v1/projects/projectID44de3936807f1" \
-H "X-API-KEY: $API_KEY"
```

Exclude clearance field for unauthorized users

---

quiz/generic/quiz_page.inc

When linking to a named guideline in the wiki, use the translated name if its available. We get the translated names via the RandomRule interface which parses the wiki pages to populate the Random Rule feature on the proofreading pages. Yes, this is all a very odd implementation.
Testable in the [link-to-translated-random-rule](https://www.pgdp.org/~cpeel/c.branch/link-to-translated-random-rule/) sandbox.

Link to a translated guideline entry

---

api/v1_projects.inc

The Author's DB column name was incorrect resulting in an inability to search by author in the `v1/projects` endpoint. Thanks to @70ray and @srjfoo (oops, Roger & Sharon rather) for finding this bug!
Testable at:
```bash
curl -i -X GET -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
"https://www.pgdp.org/~cpeel/c.branch/fix-api-author-search/api/?url=v1/projects&author=Long"
```

Correct Author's DB column name in v1/projects

---

api/v1_projects.inc

Allow SAs and PFs to search on clearance. We can't allow PMs to do so without opening up the ability for value-fishing as PMs can only see clearances for their own projects. This is also in prep for an expected PG use-case.
Testable with curl and an `API_KEY` for an SA/PF user:
```bash
curl -i -X GET -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
"https://www.pgdp.org/~cpeel/c.branch/api-project-search-clearance/api/?url=v1/projects&clearance=yes"
```
If the `API_KEY` does not belong to an SA/PF the parameter is ignored just as other unrecognized parameters are.

Allow SAs and PFs to search on clearance

---

api/USERS_GUIDE.md

The API supports combining project search params as ORs. This is only documented in the [Swagger docs](https://github.com/DistributedProofreaders/dproofreaders/blob/master/api/dp-openapi.yaml#L28) right now, but makes more sense in the User's Guide.

Updated API user's guide for ORed searches

---

api/v1_projects.inc
pinc/Project.inc

Allow Project Gutenberg's `pg-automation` account to view clearances. Note that this is going into the `pgdp-production` branch.
Testable with:
```bash
curl -i -X GET -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
"https://www.pgdp.org/~cpeel/c.branch/allow-pg-automation-clearance/api/?url=v1/projects&clearance=do-not-upload-to-PG"
```
If you use a regular user's `API_KEY` this will ignore the `clearance` field and not show the field in the output. If you use the `pg-automation` user's `API_KEY` this should return projects with the desired clearance *and* show them in the output.

Allow pg-automation user to view clearances

---

pinc/Quiz.inc

When evaluating if a user has passed a quiz, correctly reject quiz passes that are too old. This bug was introduced in 8cf7ce568. Big thanks to @srjfoo for tracking down the problem and providing a super-focused repro.
Testable in the [fix-quiz-pass-detection](https://www.pgdp.org/~cpeel/c.branch/fix-quiz-pass-detection/) sandbox.

Correctly detect expired quiz attempts

---

pinc/access_change_emails.inc
pinc/stages.inc

Requested by the GM and the P3 evaluators. This is site-specific (as are the other access-change emails) and going in the pgdp-production branch. Adds a new access-change email that will be sent to all new P2 proofreaders. Also some minor layout changes for the F1 access-change email.
Test in [add-p2-access-email](https://www.pgdp.org/~srjfoo/c.branch/add-p2-access-email); in your user stats page, revoke P2 (and F1, if you wish), and then grant them again. You should see the text of the emails displayed.

Add  an access-change email for new P2s

---

api/USERS_GUIDE.md
api/dp-openapi.yaml
api/v1_projects.inc

Allow an API client to limit which fields are returned for project searches using the `v1/projects` endpoint. This is in preparation to support a PG use-case.
Testable with curl:
```bash
curl -i -X GET -H "Accept: application/json" -H "X-API-KEY: $API_KEY" \
"https://www.pgdp.org/~cpeel/c.branch/limit-fields/api/?url=v1/projects&fields=projectid,title,author"
```

Allow client to specify fields for v1/projects results

---

pinc/Activity.inc
pinc/Quiz.inc
pinc/stages.inc

Those applying for P3 should re-take and pass any of the required proofreading quizzes that have expired per task 2028. At a later request, also added requirement for up-to-date Basic quiz pass for P2.
Because this is being merged into `master` and there are PROD hacks that are needed to do adequate testing, testing should be done in the [add-p3-prereq-hacked](https://www.pgdp.org/~srjfoo/c.branch/add-p3-prereq-hacked/) sandbox.
A large part if this is rewording the generic messages so that they at least mostly make sense for all users who will see them, since only the round information changes, and the rest of the message is not customizable per round.

Add quiz pass requirements for applying for P3

---

pinc/upload_file.inc

The most secure way to escape shell arguments is `escapeshellarg()`, not `escapeshellcmd()`.
Testable in [dont-use-escapeshellcmd](https://www.pgdp.org/~cpeel/c.branch/dont-use-escapeshellcmd/)

Use escapeshellarg() to escape arguments

---

crontab/clean_tmp.php
crontab/clean_uploads_trash.php
crontab/import_pg_catalog.php
locale/translators/index.php
pinc/POFile.inc
pinc/archiving.inc
pinc/wordcheck_engine.inc
tools/project_manager/show_project_stealth_scannos.php
tools/proofers/images_index.php

We already use `escapeshellarg()` in all places that accept user input. However, it is a best practice to always escape variables being injected into `exec()`, `shell_exec()`, and `system()` (also in backticks, but I confirmed we do not run commands via those in our code). This updates all instances of those to escape all non-literals.
Testable in the [better-exec-escaping](https://www.pgdp.org/~cpeel/c.branch/better-exec-escaping/) sandbox. I have tested the cronjobs, downloading images, running WordCheck, stealth scanno checks, and regenerating the xgettext sample.

Robustly escape all non-literals in shell commands

---

stats/release_queue.php

Encode page titles at the time we echo them, not before they are passed into other functions.
Testable in the [fix-release-queue-escaping](https://www.pgdp.org/~cpeel/c.branch/fix-release-queue-escaping/) sandbox.

Properly encode release queue page titles

---

activity_hub.php
crontab/extend_site_tally_goals.php
crontab/finish_smoothreading.php
crontab/notify_old_pp.php
faq/wordcheck-faq.php
locale/translators/index.php
pinc/Quiz.inc
pinc/archiving.inc
pinc/base.inc
pinc/dpsession_via_php_sessions.inc
pinc/graph_data.inc
pinc/html_page_common.inc
pinc/page_tally.inc
pinc/release_queue.inc
pinc/theme.inc
project.php
sitemap.php
stats/misc_stats1.php
tools/pending_access_requests.php
tools/proofers/for_mentors.php
tools/proofers/my_projects.php
tools/site_admin/edit_mail_address_for_non_activated_user.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/show_access_log.php

`strftime()` is deprecated in PHP 8.1. In many cases we don't need localization and can just use `date()` instead. This PR only takes care of the non-localized instances.
A few places were intentionally changed from what they were before:
* Seconds were removed from the timestamps on the My Projects page & WordCheck FAQ
* Quiz pages now show non-localized dates
* Some site admin pages now show non-localized dates
Testable in the [replace-nonlocalized-strftime](https://www.pgdp.org/~cpeel/c.branch/replace-nonlocalized-strftime/) sandbox.

Replace nonlocalized strftime()

---

crontab/notify_old_pp.php
faq/translate.php
pastnews.php
pinc/ProjectSearchResults.inc
pinc/gettext_setup.inc
pinc/graph_data.inc
pinc/list_projects.inc
pinc/page_table.inc
pinc/site_news.inc
pinc/stages.inc
pinc/theme.inc
project.php
tools/project_manager/editproject.php
tools/project_manager/show_all_good_word_suggestions.php
tools/project_manager/show_good_word_suggestions.php
tools/project_manager/show_good_word_suggestions_detail.php
tools/project_manager/show_specials.php
tools/site_admin/manage_special_days.php
tools/site_admin/sitenews.php

[More work to get us off `strftime()` in prep for its deprecation in PHP 8.1.]
Introduce an `icu_date()` function to localize date/time strings using `IntlDateFormatter`. This function can either take an ICU-formatted pattern, or use one of the presets. Using presets helps ensure consistent localized date formatting across the site.
One could argue that I've overloaded a single function where 2 would be better (one for ICU-formatted dates, one for templated dates). I welcome thoughts on that.
Testable in the [replace-localized-strftime](https://www.pgdp.org/~cpeel/c.branch/replace-localized-strftime/) sandbox.

Replace localized strftime() usage with icu_date()

---

crontab/onoff_special_event_queues.php
pinc/ProjectSearchForm.inc
pinc/ProjectSearchResults.inc
pinc/dpsession_via_php_sessions.inc
pinc/filter_project_list.inc

The monthly Detectify security run against TEST did not find any new security errors (🎉) but there were many warnings in the `php_errors` log for  things that we could have caught and handled slightly better. This PR pulls all of those in together. 
In short:
* For project searches, validate that none of the search terms are arrays. This is the "feature" of PHP where any URL params *and values* that end in `[]` are converted to an array in `$_GET`. So `?language[]=English[]` comes into PHP as `language = [English[]]` rather than `language=["English"]`.
* For project language searches (which use regex) use a better regex escaping function to catch all characters.
* Fully escape special day codes in the nightly queue cronjob.
* When inserting / updating values in the `sessions` table, do so …

Fix minor PHP messages from Detectify run

---

tools/charsuites.php
tools/site_admin/projects_with_odd_values.php

These two files need functions in `Project.inc`. They work on TEST and PROD because something in `pgdp-production` is including that somewhere in the chain. Both of these changes are in the PHP8 branch, but pulling them out into this PR to unblock some other dev work for @srjfoo.

Properly include Project.inc

---

composer.json
composer.lock
pinc/DPage.inc
pinc/unicode.inc
tools/proofers/spellcheck_text.inc

Upgrade portable-utf8 to 6.x to keep us up-to-date. The only major change with 6.0.0 is that it removed deprecated aliases for many functions. The only one we use is `split()` -> `str_split()`. See its full [changelog](https://github.com/voku/portable-utf8/blob/master/CHANGELOG.md) for details.
I put this up as a separate PR since it is a major component of our Unicode functionality and seemed to warrant the option of a more reasonable test pass.
Testable in the [upgrade-portable-utf8](https://www.pgdp.org/~cpeel/c.branch/upgrade-portable-utf8/) sandbox.
Note that the `charsuites.php` page throws an error for a missing include. This is currently a problem on `master` but not `pgdp-production` (and thus PROD and TEST) so the `project.inc` file is getting pulled in from somewhere else. This …

Upgrade portable-utf8 to 6.x

---

tools/project_manager/post_files.inc

While solving a bug in a `noncvs` script I found these small improvements to functions that generate post files.
* Move the `$pathbase` construction to after the validation checks. This ensures that if the directory doesn't exist we don't try to treat `null` as a string and generate a PHP warning in 8.x.
* Remove the directory check for `generate_interim_file()` as that function doesn't use or need the project directory -- probably a copy/paste error from the `generate_post_files()` function above it.
* Change the hard-coded `/tmp` directory name to the more flexible `sys_get_temp_dir()` function.
Testable in the [post-file-checks](https://www.pgdp.org/~cpeel/c.branch/post-file-checks/) sandbox.

Adjust checks in post-file generation functions

---

SETUP/UNICODE.md
pinc/charsuite-math-symbols.inc

Create new character suite containing commonly used mathematical symbols that are not in Basic Latin.
The Math symbols character suite can be viewed here: [math-symbols](https://www.pgdp.org/~srjfoo/c/tools/charsuites.php?charsuite=math-symbols) and tested in this project: [Foundations of & wireless](https://www.pgdp.org/~srjfoo/c/project.php?id=projectID5c13a64918b30)

Create new Math symbols character suite

---

SETUP/CHANGELOG.md
SETUP/UPGRADE.md

Prepare for our usual September release. This won't be merged until just before we're ready to cut the release.
The full list of commits can be seen with:
```bash
git log R202202..master
```

Prepare for the R202209 release

---

SETUP/INSTALL.md
feeds/backend.php
locale/translators/index.php
pinc/DPDatabase.inc
pinc/POFile.inc
pinc/ProjectSearchResults.inc
pinc/ThemedTable.inc
pinc/filter_project_list.inc
pinc/forum_interface.inc
pinc/gettext_setup.inc
pinc/misc.inc
pinc/theme.inc
stats/includes/member.inc
tools/project_manager/remote_file_manager.php
tools/project_manager/word_freq_table.inc
tools/proofers/my_projects.php
tools/proofers/review_work.php
tools/site_admin/copy_pages.php
tools/site_admin/manage_random_rules.php
tools/site_admin/manage_special_days.php
userprefs.php

These are some updates that, after limited testing, appear to make the code work cleanly with PHP 8.0 and 8.1. Thankfully our code is modern enough that we don't need any major changes.
This code should work on PHP 7.4, 8.0, and 8.1. Accordingly there are two sandboxes available:
* The [updates-for-php8](https://www.pgdp.org/~cpeel/c.branch/updates-for-php8/) on TEST which is running PHP 7.4
* ~The [updates-for-php8](https://100.22.14.219/~cpeel/c.branch/updates-for-php8/) on a separate EC2 instance running PHP 8.1 (the cert does not match so you will get an SSL error in your browser)~

Updates for PHP 8

---

pinc/filter_project_list.inc
scripts/filter_project.js
styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

While working on some unrelated potential updates to the round pages I saw a chance to improve the way we present project filter information. This update moves the current filter into the filter table along side the button to reset it. If there is no filter the filter isn't shown.
Compare:
* [original P1 page](https://www.pgdp.org/c/tools/proofers/round.php?round_id=P1#filter_form)
* [update P1 page](https://www.pgdp.org/~cpeel/c.branch/update-filter-box/tools/proofers/round.php?round_id=P1#filter_form)
Note that the filter form does not show up unless you've [proofread 20 pages](https://github.com/DistributedProofreaders/dproofreaders/blob/master/tools/proofers/round.php#L121), so if you don't see a filter selection box, go proofread 20 pages.

Streamline project listing filter interface

---

tools/site_admin/copy_pages.php

I've traced back a message in the daily `php_errors` report to the use of `copy_pages.php` on a project that did not have a pages table. This adds that check and slightly improves error reporting for the script.
Testable in the [improve-copy-pages-error-handling](https://www.pgdp.org/~cpeel/c.branch/improve-copy-pages-error-handling/) sandbox.

Add additional checks in copy_pages

---

pinc/DPDatabase.inc
pinc/forum_interface.inc

phpBB 3.x doesn't explicitly support PHP 8.1, nor do they set an explicit mysqli reporting value, so reset the value right before we do any inline calls to phpBB functions. This prevents the case where a DB call in phpBB code for login/logout errors and results in an uncaught DB error.
After phpBB supports PHP 8.1 we can either change MYSQLI_REPORT_OFF in `forum_interface.inc` to the value they use, or if they don't set a value, we can revert this commit entirely and use the PHP 8.1 defaults.
login and logout are the only place where we use inline phpBB code, so as long as login / logout both still work this commit is good to go after code inspection. Testable in the [play-nice-with-phpbb-db-errors](https://www.pgdp.org/~cpeel/c.branch/play-nice-with-phpbb-db-errors/) sandbox.

Reset mysqli error logging for phpBB calls

---

pinc/DPDatabase.inc
pinc/genres.inc

There are rare times when we know a query might fail and we don't want to log an error to the error log. Create a temporary table is one of them because we can't otherwise determine if the temporary table exists as it isn't populated in the schema and we don't want to give elevated privs to run sys.table_exists().
This is testable in the [fix-temp-table-logging-message](https://www.pgdp.org/~cpeel/c.branch/fix-temp-table-logging-message/) sandbox. Success is loading the round pages without generating errors in `php_errors`.

Enable bypassing error log on DB query failure

---

tools/authors/authors.inc
tools/authors/authorxml.php

If there is no author bio, there is no `$row["bio_id"];` to access and we get a warning of accessing an array offset on a null field, as seen in `php_errors` on PROD. Fix this by simplifying how we output bios on the author page. I did a bit more minor cleanup in `authors.inc` while I was here, none of it functional.
The other functional fix in this PR is making the `authorsxml.php` page render valid XML. Previously we were not closing the `<date>` tag making the document invalid.
Testable in the [fix-author-rendering](https://www.pgdp.org/~cpeel/c.branch/fix-author-rendering/) sandbox.

Fix Author page & XML rendering

---

pinc/project_quick_check.inc

Per request from @lhamilton1, adding a project quick check for page images being less than 1000px in any dimension.
Sandbox with small images: https://www.pgdp.org/~chrismiceli/c.branch/small-images/tools/project_manager/project_quick_check.php?projectid=projectID45ea6b97d9566#_test_project_for_small_images

Add project quick check for small page images

---

pinc/POFile.inc

"mixed" was introduced as a valid type in PHP 8.0 and is only a pseudo-type in 7.4. Fix the return type to work with 7.4.
This fixes an error in the translation center which we missed during the PHP 8.x updates.
Testable in the [fix-translation-center](https://www.pgdp.org/~cpeel/c.branch/fix-translation-center/) sandbox. Hotfixed on PROD8.

Return correct type for POFileIterator

---

default.php
pinc/theme.inc

Adds a link to the new DP presence on Mastodon. Also fixes a minor HTML validation issue in the donations blurb.
Testable in the [add-mastodon-social-media](https://www.pgdp.org/~cpeel/c.branch/add-mastodon-social-media/) sandbox.

Add Mastodon social media link

---

pinc/ProjectTransition.inc
pinc/project_edit.inc
project.php

The first commit removes the button that squirrels could use to move a project back into the previous round (the effect of which was to change the project state to unavailable for the previous round and the page states to the previous round's `page_avail` state. This was easy to confuse with doing a round repeat (which is done via separate script). The original reason for the button appears to have been to make it easier, after the move from 2 to 3 proofreading rounds, to shove a P3 project that had no P2 back into an empty P2 round.
The second commit removes the ability for disabled project managers to move a project out of the new project state. From the new project state, it is easier for them to fix problems with a project themselves instead of having to request a squirrel to do so. …

Change some project transitions

---

tools/proofers/srchrep.js

Make `^` and `$` match the first and last of each line within a page during search/replace, not just the first and last of the string. [Task 2044](https://www.pgdp.net/c/tasks.php?action=show&task_id=2044)
Testable in https://www.pgdp.org/~cpeel/c.branch/use-multiline-regex/

Make search/replaced Regex multiline

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.js

MathJax can compile inline math inside text inside display math but the format preview previously marked it as an error.
Also add a test for it not to cause an error.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/nest_inline

allow inline math inside display math

---

tools/proofers/processtext.php

Prevent XSS injection into "Save as Done" and "Return Page to Round" via the page state. We don't use the page state within the page, but we pass it into the return link.
Testable in [validate-proj-state](https://www.pgdp.org/~cpeel/c.branch/validate-proj-state/) sandbox.
This was found via the Detectify monthly run.

Validate page state on leaving proofreading UI

---

tools/proofers/srchrep.php

When the Search/Replace tool is popped in the proofing interface, ensure the keyboard focus is in its Search field. This enables the proofer to begin typing the Search term immediately without an additional click.

Set focus on proofing interface S/R Search field

---

SETUP/CHANGELOG.md
SETUP/UPGRADE.md

Update the changelog and upgrade docs for the upcoming R202303 release. This list tries to encapsulate the notable changes without getting into the weeds (that's what `git log` is for). I welcome thoughts if the wording should be updated or if there are additional things we want to include.
A reminder that you can see all of the commits since the last release with `git log R202209..upstream/master`

Prepare for the R202303 release

---

SETUP/tests/jsTests/dp_proofTests.js
pinc/button_defs.inc
tools/proofers/dp_proof.js
tools/proofers/proof_frame_enh.inc
tools/proofers/spellcheck.inc
tools/proofers/text_frame_std.inc

Buttons in the proofing interface that change the page's status can cause an error if double-clicked. Since first click changes the status, second click gives an error. Error only appears to occur on some systems.
Solution is to stop the second click from attempting to re-submit by returning false from onClick handler. On first click, set a user-defined data attribute to true, so second click knows it's the second click.
Affects WordCheck, Save as Done and Proofread Next Page (from proofing and WordCheck interfaces), Save as In Progress and Save as Done.
Testable at https://www.pgdp.org/~windymilla/c/

Avoid error if proofer dbl-clicks some buttons

---

tools/project_manager/diff.php

[Task 2048](https://www.pgdp.net/c/tasks.php?action=show&task_id=2048) requested quick links to access the full page text when viewing page diffs. This is a simple solution to point the user to the Image Viewer with the page text for the round.
Testable in the [add-text-links-to-diff](https://www.pgdp.org/~cpeel/c.branch/add-text-links-to-diff/) sandbox. For example [this diff page](https://www.pgdp.org/~cpeel/c.branch/add-text-links-to-diff/tools/project_manager/diff.php?project=projectID45c225f598e32&image=127.png&L_round_num=0&R_round_num=1).

Add page text links to diff columns

---

scripts/page_browse.js

and re-order 2 lines.
This fixes a bug with the horizontal split bar in the page browser. If you display image+text with a horizontal split and adjust the window width so that the split button just wraps into the next line thus: 
Then refresh the page and move the splitter bar. It would jump a small distance away from the mouse pointer.
This happened because the size of the viewing pane was measured before the image in the splitter button was loaded. This PR sets the size of the image so the layout is correct before the image is loaded.
Also the control buttons are now added before the splitter is set up.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/split_jump

Set a size for images in buttons

---

SETUP/tests/jsTests/formatPreviewTests.js
styles/preview.css
tools/proofers/preview.js

Both now allow multi-line headings and sub-headings (previously a multi-line all-bold heading was not marked as an error but the re-wrap still interpreted it as a heading.
This fixes task 2038 https://www.pgdp.net/c/tasks.php?action=show&task_id=2038
The test for an all-bold heading error revised to have a two-line heading.
unused styles removed.
Known bugs (mishandling <tb> in re-wrap) and dubious features (guessing what is a section heading) are still present.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/bold_heading1

Make check for all bold heading consistent with re-wrap

---

tools/proofers/proof_frame.php

Log whenever the debouncer triggers. There is suspicion that this is no longer needed and if we find that it is never triggered over a period of time we can remove it.
This is going into the `pgdp-production` branch since it is pgdp.net-specific.

Log debouncer uses

---

pinc/showavailablebooks.inc

Instead of allowing filter by PM of projects available for PPV, allow filter by PP instead
Available to test [here](https://www.pgdp.org/~windymilla/c.branch/ppv-filter/tools/pool.php?pool_id=PPV)

Filter by PPer not PM in PPV pool - Task #1572

---

pinc/user_project_info.inc
project.php
tools/set_project_event_subs.php
tools/site_admin/copy_pages.php

Put string generating code inside recipient loop.
Use function instead of global for event labels so they are translated at call time.
Fixes #582 
[Sandbox](https://www.pgdp.org/~windymilla/c.branch/event-lang)
Note that the popup of email contents on TEST is not seen for event notifications (possibly due to the delayed redirection) so the sandbox has a small additional hack to write the contents of the email to a file in /tmp. Name of file contains email address and timestamp to aid testing.

Send event notifications in receivers language

---

.github/workflows/static-checks.yml

Yesterday our static checks Github Action started failing when the aspell install started throwing odd package errors: https://github.com/DistributedProofreaders/dproofreaders/actions/runs/4554126764/jobs/8031574260?pr=875
This adds the suggested `apt` arg to fix it although I don't know why it started breaking. I'm also not 100% sure that this will fix it consistently because it doesn't seem to be failing consistently, but a run with this change did succeed.

Fix ImageMagick package conflicts

---

SETUP/CHANGELOG.md

Deprecate the sessions-via-cookies support in the code (`_USE_PHP_SESSIONS=FALSE`) in the change log. After the next release in ~6 months we can remove the code. Doing it this way gives other sites who might still be using this method notice before it happens.

Include deprecation notice for sessions-via-cookies

---

pinc/ProjectTransition.inc

Transitions that this commit affects are
PP Unavailable -> PP Available
PP Checked out -> PP Available
PPV Checked out -> PPV Available
Question: In an ideal world, the additional warning "This will clear the reserved PPer if there is one." would only be output if `checkedoutby` was not empty. I couldn't see how to check that at the point where the confirmation question is stored in the `ProjectTransition`. If there's not a simple way, it's not that important, since this transition is relatively rare, and only made by people who should know what's going on regarding any reserved PPer and the project being put into Available rather than Checked Out.
Addresses [Task 1881](https://www.pgdp.net/c/tasks.php?action=show&task_id=1881)

Notify event subscribers of PP/PPV transitions

---

scripts/control_bar.js

When using the page browser in image+text mode, if the image zoom is changed in one split mode, then change to other split mode the image itself remained at the same size. The number in the zoom control switched correctly but the image itself did not.
This fixes it so the image changes size correctly at once.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/image_switch

set image size when switching horizontal/vertical

---

stats/requested_books.php

Temporarily disable the `requested_books.php`. It creates a temporary table based on the `user_project_info` table, but due to the size of that table on PROD (3.7m rows) it takes 4 minutes to create. That table also drives the My Project table and is updated every time a user goes to a project page. Disabling it in `pgdp-production` branch until we get the table fixed.
Testable in the [disable-most-req-books](https://www.pgdp.org/~cpeel/c.branch/disable-most-req-books/stats/requested_books.php) sandbox.

Disable requested_books.php

---

scripts/page_browse.js
tools/project_manager/show_word_context.js

This simplifies pageBrowse by not getting project information in simple header mode since it is not needed. Also use a callback function to set the showImageFile function after it has been constructed. This simplifies its use in show_word_context().
Sandbox at: https://www.pgdp.org/~rp31/c.branch/rev_browse
Page browse and show word context should continue to work correctly.

Rev browse

---

pinc/ProjectTransition.inc

If PPV returns project to PP, who then uploads, the PPVer's stats differ from the "obvious" search. 
For example, it's the difference between
`select count(*) from projects where ppverifier = 'windymilla' and state like '%posted%' and postproofer <> 'windymilla' and checkedoutby <> '';`
and
`select count(*) from projects where ppverifier = 'windymilla' and state like '%posted%' and checkedoutby <> 'windymilla' and checkedoutby <> '';`
The latter is used by the PPV stats page and omits those projects that windymilla PPVed, but returned to the PPer for uploading.
This PR stops that happening to projects in future, i.e. if windymilla PPVed a project, but returned it to the PPer, who had it checkedout when it was marked as Posted, windymilla will be removed as PPVer. This seems correct, since …

Clear ppverifier field if they didn't upload to PG

---

tools/request_access.php

Minor changes to email requested by [Task #1529](https://www.pgdp.net/c/tasks.php?task_id=1529):
1. Username included in email header
2. Short version of round/stage name used
3. Removed word "stage"
4. Added link to Pending Access Requests page

Alter wording of access request notification email

---

pinc/BBDiffFormatter.inc
pinc/DifferenceEngineWrapper.inc
pinc/DifferenceEngineWrapperBB.inc
pinc/DifferenceEngineWrapperTable.inc
tools/project_manager/diff.php

In order to aid feedback to mentees and similar situations provide an option on the diffs page to view the diffs as BB-code formatted text instead of the usual table view
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/bbdiff
This addresses [Task #1875](https://www.pgdp.net/c/tasks.php?action=show&task_id=1875)

Allow mentors, etc to view diffs in BB format

---

credits.php

PHPMailer doesn't set a `homepage` in its composer metadata. Update the code to better handle this edgecase.
Testable in the [fix-missing-homepage-in-credits](https://www.pgdp.org/~cpeel/c.branch/fix-missing-homepage-in-credits/credits.php) sandbox.

Better handle missing homepage from composer deps

---

pinc/send_mail.inc

Previously, no final newline was included in the text emails. When HTML emails were added, no final `<br>` was added. This only appears to cause an issue where the email is send to a mailing list, e.g. PPV mailing list. It appears that a mailing list footer is appended, which probably includes a newline followed by a line of underscores then some info about the mailing list. This worked OK with text messages since the newline put the underscores onto the line below, but with the HTML version, a newline does nothing, and a `<br>` is needed.
In fact, it seems reasonable that all our emails, text and HTML, should have a terminating newline/`<br>`.

Append newline to email footers

---

pinc/user_is.inc

Obviously not something that's used often, or it would have been fixed long ago. `manage_site_access_privileges.php` and `user_is.inc` were not using the same setting name. Sandbox at [fix-pp-limit](https://www.pgdp.org/~srjfoo/c.branch/fix-pp-limit/).

Fix PP Limit

---

pinc/send_mail.inc

CharSet needs to be set to UTF-8 so that PHPMailer can encode the header lines correctly
As per [forum comments](https://www.pgdp.net/phpBB3/viewtopic.php?p=1310484#p1310484) and Slack discussion, email headers are not being encoded correctly. Most likely reason seems to be that PHPMailer uses `CharSet=ISO-8859-1` by default. Comment in [this PHPMailer issue](https://github.com/PHPMailer/PHPMailer/issues/133) implies that PHPMailer will encode the header correctly using B or Q encoding, but obviously it won't be able to do that if we are handing it UTF-8 header string but leaving it thinking the CharSet is ISO-8859-1
Testing: I don't know if the FakeEmail server would show the issue. If so, we can temporarily hack the code on TEST so it sends the email as well as displaying it on screen - …

Set UTF-8 CharSet for PHPMailer emails

---

SETUP/tests/manual_web/split_test/switchable_split.js
SETUP/tests/manual_web/split_test/vertical_horizontal_split.js
scripts/control_bar.js
scripts/filter_project.js
scripts/page_browse.js
scripts/splitControl.js
tools/project_manager/show_word_context.js
tools/proofers/previewControl.js

The main goal here is to remove jQuery for more usages that don't involve creating and modifying a bunch of DOM elements. This mostly consist of
1. Using normal event listeners
2. Removing $.Callbacks in favor of arrays of methods
3. Removing $.isPlainObject
I also took the opportunity to fix a deprecation warning on event.which.
Again, this is low priority with some risks, so no pressure to merge or review.
Branch for testing
https://www.pgdp.org/~chrismiceli/c.branch/jquery/

More basic usages

---

SETUP/upgrade/19/20230601_prune_user_project_info.php
crontab/notify_old_pp.php
pinc/post_processing.inc
pinc/showavailablebooks.inc
pinc/user_project_info.inc
project.php

The `user_project_info` tracks the last time a user visits a project page, proofs a project page, or subscribes to a project event. The table definition looks like:
```
+----------------------+--------------+------+-----+---------+-------+
| Field                | Type         | Null | Key | Default | Extra |
+----------------------+--------------+------+-----+---------+-------+
| username             | varchar(25)  | NO   | PRI | NULL    |       |
| projectid            | varchar(22)  | NO   | PRI | NULL    |       |
| t_latest_home_visit  | int unsigned | NO   |     | 0       |       |
| t_latest_page_event  | int unsigned | NO   |     | 0       |       |
| iste_round_available | tinyint(1)   | NO   |     | 0       |       |
| iste_round_complete  | tinyint(1)   | NO   |     | 0       | …
```

Only update user_project_info.t_latest_home_visit for PP/PPVers

---

pinc/send_mail.inc

Specifically, if a From address is given to override the default, don't specify the Reply-To address.
Previous HTML email work meant the Reply-To address got set to the default address, unless it was
explicitly set.

Restore previous Reply-To email behavior

---

tools/project_manager/show_all_good_word_suggestions.php
tools/project_manager/show_good_word_suggestions_detail.php
tools/project_manager/show_word_context.php

Use the full JS path so that the date modified arg is appended. This forces browsers to recognize when JS files have changed.
Testable in https://www.pgdp.org/~cpeel/c.branch/use-full-js-path/

Use the full JS path to get date modified arg

---

stats/teams/new_team.php

Team names and webpage were passed through `stripAllString` which is intended to convert bb markup in team info to HTML markup, e.g. for italic. This conversion is not needed for team name and webpage.
Since `stripAllString` calls `html_safe`, ampersands were getting encoded, then encoded again via `attr_safe` in `ShowEdit`.
Addresses task #2041
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/team-name

Permit ampersands in team names

---

stats/teams/team_topic.php

If someone manipulates the team discussion link on the Teams page to use a numeric, but invalid, team ID the script blindly plunges forward. Instead, if we can't find a team ID just error out. This page is only accessible from the teams page.
Available in https://www.pgdp.org/~cpeel/c.branch/better-checks-team-discussion/

Check if team_id exists before creating topic

---

tools/project_manager/editproject.php

Requested by task #836
If month/day is given on project edit page, but special code field is left empty, set special code to `Birthday` and output error message for user to check before saving.
Fix is not as slick as it might be, because month/date are not stored in the Project structure or database except when appended to Birthday/Otherday as a special code. This is trying to cope with the case when month/date are set, but special code was left blank. Previously, project would have been saved with no special day code at all, leaving it vulnerable to releasing before the PM realised the mistake.
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/special-date

Handle month/day given without Birthday/Otherday code

---

pinc/abort.inc
pinc/links.inc
pinc/project_quick_check.inc
tools/extend_sr.php
tools/post_proofers/ppv_report.php
tools/project_manager/add_files.php
tools/project_manager/diff.php
tools/project_manager/edit_pages.php
tools/project_manager/page_compare.php
tools/project_manager/page_detail.php
tools/proofers/PPage.inc
tools/proofers/images_index.php
tools/proofers/processtext.php
tools/proofers/proof_frame.php
tools/request_access.php
tools/set_project_event_subs.php
tools/set_project_holds.php
tools/site_admin/project_jump.php
tools/upload_text.php

As per task #1871, linked phrases such as
"Return to the project page" were inconsistently worded, puncutated and marked up for translation.
Standardize return to project, round and Activity Hub.
Note that further standardization of capitalization of "project page" could be done in future, where it does not appear just as a simple "Return to" link.
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/return-links

Standardize "Return to x" links

---

SETUP/db_schema.sql
SETUP/upgrade/19/20230627_alter_tasks.php
tasks.php

1. Remove references to version (meaning sister sites) from Task Center interface and create upgrade script to drop column from tasks table
2. Add sort indicator arrow to heading of the column currently used for sorting in the tasks list 
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/task-tasks

Small improvements to Task Center - task #1942

---

tools/project_manager/word_freq_table.inc

As requested in Task #1953, add links to project page and Edit project word lists page. Task requested links on Candidates for Good Words List from Proofreaders, but other similar pages also benefit from links, so added in common header.
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/good-bad-links
Testing notes: Affected pages should be
- Ad hoc word details
- Good word candidates from Word Check
- Good word candidates from proofers
- Bad word candidates from site list
- Bad word candidates from diffs

Add links from PM Word List pages

---

SETUP/tests/UserTest.php
accounts/addproofer.php
pinc/User.inc

By squirrel request: to further discourage people using emails for their usernames, disallow `@`s in new registrations.
Testable in https://www.pgdp.org/~cpeel/c.branch/disallow-ats-in-new-usernames/

Disallow @s in new usernames

---

SETUP/upgrade/19/20230703_clean_task_statuses.php
tasks.php

As per task #1828, tasks aren't closed properly
if their status is just set to Closed via the
Edit (or Create) Task form. It needs to be done
via the button on the main task page.
Therefore, omit Closed from the list of statuses on the Edit page.
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/close-tasks

Do not permit Edit Task to close a task

---

tasks.php

Move the global declarations to the top of the `handle_action_on_a_specified_task()` function. This addresses an undefined variable error seen in the php_errors file.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/fix-task-center-notices/

Pull in globals at top of function

---

SETUP/configuration.sh
SETUP/tests/ci_configuration.sh
pinc/forum_interface.inc
pinc/phpbb3.inc
pinc/site_vars.php.template

This is a stepping stone to supporting more forum types than just phpBB, specifically to have a "dev only" forum shim to allow local development without installing phpBB. A follow-up PR will rename `pinc/forum_interface.inc` and it is much easier to review the changes made to that file before doing so.
The PR should have no functional changes in it.
This is in https://www.pgdp.org/~cpeel/c.branch/forum-abstraction/

Rework forum code to be specific to phpBB3

---

project.php

Addresses Task #1353
If the "Start a Discussion" link on the project page is double-clicked, two project threads may be created.
Avoid this by replacing the link with plain text when it is clicked.
Sandbox:  https://www.pgdp.org/~windymilla/c.branch/double-forum

Avoid duplicate project thread creation

---

tools/project_manager/handle_bad_page.php

Validate that the requested page exists when handling a bad page. This can only happen with URL futzing so we don't have to be nice about it. This was found via `php_errors`.
Testable in https://www.pgdp.org/~cpeel/c.branch/validate-project-page-image/

Validate page exists when handling bad page

---

scripts/control_bar.js
scripts/page_browse.js

Use a more uniform pattern for callback functions. Following the model of `window.addEventListener("resize", function)`, let the function (call it A) which initiates the event return a `Set` of functions (possibly initially empty) and let it call each of them when the event occurs. The code which calls function A can add any functions to the set which it wishes to be called when the event occurs. The events are typically something which causes a window to change its size.
This should make it easier to add new cases where an action has to be taken when the event occurs.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/event_callback
This should not change any functionality. The changed code is used in the page browser and the image_widget in the proofreading interface.

Use different pattern for callback functions

---

pinc/bad_bytes.inc
pinc/project_trans.inc
project.php
tools/project_manager/autorelease.inc

In general, code should not override error reporting configuration set by the system because this could reveal information to users that they should not see.
TEST has very verbose error reporting (E_ALL) whereas PROD has a the recommended smaller set (E_ALL & ~E_DEPRECATED & ~E_STRICT)

Remove error_reporting() overrides

---

pinc/charsuite-basic-latin.inc

The first commit adds `Ẽ`, `ẽ`, `Ĩ`, `ĩ`, `Ũ`, and `ũ` to Basic Latin, and the appropriate picker set, completing the set of vowels with tilde above.
The second commit removes the superscript numbers, fractions, ordinals and standalone diacritical marks from the picker sets. This is a removal from the picker sets, only; the characters will still be valid for Basic Latin.
Compare [the new version in my sandbox](https://www.pgdp.org/~srjfoo/c.branch/basic-latin-mods/tools/charsuites.php?charsuite=basic-latin ) with [the currently deployed version](https://www.pgdp.net/c/tools/charsuites.php?charsuite=basic-latin).

Basic latin character suite modifications

---

SETUP/check_db_schema.template
SETUP/db_schema.sql
SETUP/dump_db_schema.template
SETUP/install_db.php

The `dump_db_schema` script is used in concert with `check_db_schema` during a code release to ensure that the prior release + new upgrade scripts = what's currently in the DB. The order mysqldump outputs tables is inconsistent and there's no guarantee that the tables will be output in an order that allows them to be created due to foreign key constraints.
@chrismiceli addressed this for the `users` table in a54b13b266317a477c0e15f78f4b590719811a30 for initial creation, but we still have that problem during the pre-release check. This PR rolls back Chris' commit and uses the `FOREIGN_KEY_CHECKS` variable to control how the checks are managed. This is another belt-and-suspenders approach where we make the changes in `db_schema.sql` (in case someone wants to just load it directly as it _is_ …

Update DB schema tooling

---

SETUP/MediaWiki_extensions/README.md
SETUP/MediaWiki_extensions/dpExtensions.php
SETUP/MediaWiki_extensions/hospitalExtensions.php

Update the DP MediaWiki extensions to support MediaWiki 1.32 and later, including 1.39 which is the latest LTS.
The `$wgParser` global is reportedly [just deprecated](https://www.mediawiki.org/wiki/Manual:$wgParser), but it actually refused to work after I upgraded MW to 1.39 on test, so move to the format that works with 1.32 and later.
Proof that they now work at https://www.pgdp.org/wiki/User:Cpeel/MediaWiki_Extensions

Update MediaWiki extensions to support MW 1.39

---

SETUP/CHANGELOG.md
SETUP/UPGRADE.md

Update the `CHANGELOG.md` file for the upcoming R202309 release happening next month. I'll hold off getting this in until just before the release but wanted to get the doc updates out for review.
A reminder that we only call out the "highlights" in the changelog and rely on the git history for the details. That said, I'm open to suggestions on if this hits the right balance or if things should be added or removed!

Update the CHANGELOG for the upcoming R202309 release

---

.github/workflows/static-checks.yml

Upgrade the versions of `actions/checkout` and `actions/setup-node`. This addresses a deprecation warning we're seeing in the CI output about node12 (which is used in the old actions) being deprecated. This is only a CI-related change and does not impact the DP code at all. If the tests pass, this should be good to go.

Upgrade Github action versions

---

SETUP/db_schema.sql
SETUP/tests/SettingsTest.php
SETUP/tests/phpunit_test_helpers.inc
SETUP/upgrade/20/20230920_update_user_table.php
accounts/activate.php
pinc/User.inc
pinc/new_user_mails.inc

The `id` column of the `users` table is horribly misnamed as it is only ever used as the account registration token and not an ID.
Like with many things, I encountered / stumbled over this while trying to do something else and decided I'd just take time to fix it for future-me and others. The DB changes have been already applied to TEST so account registration is testable in the following sandbox, but will fail on TEST outside of the sandbox.
https://www.pgdp.org/~cpeel/c.branch/rename-reg-token-column/

Rename user.id to user.reg_token

---

pinc/stages.inc

The daily page limit on PROD has already been hotfixed for P1 and P2 to be 60 pages per day. The purpose of this PR is to get the changes into the site-specific code. Sandbox [here](https://www.pgdp.org/~srjfoo/c.branch/update-dpl-to-60) if you really want to proof 60 pages per day to test it 😁 .
For reference, discussion topic [here](https://www.pgdp.net/phpBB3/viewtopic.php?f=1&t=80170).

Change daily page limit for P1 and P2 to 60

---

SETUP/db_schema.sql
SETUP/upgrade/20/20230920_drop_i_prefs_column.php
SETUP/upgrade/20/20230920_move_pmdefault_to_usersettings.php
tools/project_manager/projectmgr.php
userprefs.php

The `users.i_pmdefault` setting is only applicable to PMs so move the setting to the `user_settings` table rather than in the table for all users. This follows the pattern we user for other PM-specific settings and further simplifies the user table to be applicable to all users.
Also remove the unused and unreferenced `users.i_perfs` column. The only thing I think this is currently tracking is if the user has saved their preferences at any point and that doesn't seem useful.
Testable in the https://www.pgdp.org/~cpeel/c.branch/move-pm-pref-to-usersettings/ sandbox.
_Note that the new setting has been populated on the TEST system but the column has not yet been dropped from the `users` table. After this PR is approved I'll confirm than the update script works in-full rather than just the …

Move PM view preferences to user_settings table

---

pinc/abort.inc

If abort() is called from inside proof.php then the links are not shown but instead a message about a missing function `return_to_project_page_link` is shown.
The problems that cause this are `no expected state in url` or any of the issues that cause `can_be_proofed_by_current_user()` to fail.
It is probably not possible to see the problem this fixes without doing something naughty like changing your identity while proofreading a page or manipulating the url. For example start proofreading a page from a good project in round 1 on the test server and change the procectid in the url to that of the project that is not utf8 Nothing & co {not UTF-8} (projectID459698b8b63ac).
Sandbox at: https://www.pgdp.org/~rp31/c.branch/abort_link

add include links.inc to abort.inc file

---

list_etexts.php
pinc/list_projects.inc
pinc/showstartexts.inc
pinc/theme.inc

As reported in [Task 1883](https://www.pgdp.net/c/tasks.php?action=show&task_id=1883), the number of "titles preserved for the world" does not match the number of Gold texts.
Use a common function that only counts distinct PG ebook numbers for both cases, and use "group by" when listing the Gold texts on the `list_etexts` page.
Also, fix bug in number of pages used to display the Gold texts: if the number of texts per page was an exact divisor of the total number of texts, it miscalculated the number of pages needed by one, the last of which was blank. Testing note: on TEST, there are currently 15 projects, but if shown 5 per page, tries to use 4 pages. With these changes, there are only 14 projects, which can be shown 7 per page on 2 pages.
Questions:
1. Using "group by" means that it is …

Make main page completed numbers consistent

---

pinc/ProjectSearchResults.inc
pinc/theme.inc
tools/project_manager/clearance_check.php
tools/project_manager/projectmgr.php
tools/proofers/my_projects.php
userprefs.php

Some of our pages use "tabbed" views of data and we've copy/pasted that code so we have 4 copies of it. I want to use it in a new place and this centralizes it into one and re-uses it everywhere.
There should be no change in functionality on any of the pages.
Testable in the [centralize-tab-output](https://www.pgdp.org/~cpeel/c.branch/centralize-tab-output/) sandbox.

Centralize tab layout logic

---

stats/release_queue.php

This make several improvements to the release queue page after requests from srjfoo & puppernutter and from a few open tasks ([1125](https://www.pgdp.net/c/tasks.php?action=show&task_id=1125) and [1237](https://www.pgdp.net/c/tasks.php?action=show&task_id=1237)).
* Queue listing
* Refined the set of information available on this page
* Allow filtering by enabled/disabled
* Include the number of projects held
* Added current and next round statistics
* Queue detail page
* Added more information about each queue
* Added queue statistics
Some of the other queue stats requested in 1237 are just simply too confusing to convey in a useful manner and can easily be misinterpreted. I've opted for a set that seems(!?) straightforward.
Testable in the …

Release queue listing & detail updates

---

SETUP/tests/ProjectTest.php

[Note, this PR is against `pgdp-production` and not `master`.]
In `pgdp-production`, users must first pass a quiz and request access before they can proofreading in P1 making this test fail so skip it.
This was discussed in #pgdpdev and the PR passes if the test in the phpunit GHA all pass.

Skip ProjectTest::test_can_be_proofed_available

---

SETUP/tests/UnicodeTest.php
SETUP/tests/pinc_WordCheckEngineTest.php
pinc/unicode.inc
pinc/wordcheck_engine.inc
tools/proofers/spellcheck.inc
tools/proofers/spellcheck_text.inc

To improve proofreaders ability to differentiate look-alike characters, highlight non-Latin characters in WordCheck like we do for punctuation. This removes the current behavior where words containing multiple Unicode scripts are flagged as bad in lieu of highlighting the characters instead.
Testable in the [highlight-non-latin-scripts](https://www.pgdp.org/~cpeel/c.branch/highlight-non-latin-scripts/) sandbox -- in particular the [UTF-8 Practice: Dogs of all nations](https://www.pgdp.org/~cpeel/c.branch/highlight-non-latin-scripts/project.php?id=projectID5e20bc6bd5786&expected_state=P1.proj_avail) project which has some additional character suites and custom characters.

Highlight non-Latin unicode scripts in WC

---

SETUP/upgrade/20/20230920_move_pmdefault_to_usersettings.php

When running this upgrade script on PROD in today's deployment we ran into the case where a username was in the `user_settings` table but not in the `users` table. This shouldn't happen, but we don't have foreign keys in place to prevent it* and we shouldn't break the upgrade script if it happens.
\* MyISAM tables -- which we used originally -- didn't support foreign keys. InnoDB tables do and we should consider using them where we can although that's going to be a bit of a bear to implement since we need to handle cases like this in the process.

Handle edgecase in PM view upgrade script

---

pinc/stages.inc

At the GM's request, the newcomer reserve has been extended from 7 to 14 days for English projects.
Testable in [this project in the sandbox](https://www.pgdp.org/~srjfoo/c.branch/change-newcomer-reserve-english/project.php?id=projectID45b672b501229). The sandbox has been doctored so that you'll need to use an unprivileged account that has more than 2 days on site and more than 5 pages proofed to verify it (instead of the normal 21 days and 500 pages 😁).

Increase newcomer reserve for P1 to 14 days for English

---

.gitignore
README.md
SETUP/CODE_DOCS.md
SETUP/CODE_STYLE.md
SETUP/README.md
activity_hub.php

Introduce DocBlock as the preferred function code comment style. This PR includes an example of what this would look like in `activity_hub.php` and docs on how to generate the code-level docs using phpDocumentor. You can see an example of the rendered docs at https://www.pgdp.org/~cpeel/c/build/docs/files/activity-hub.html
As a bonus, many editors (VSCode, Sublime) can parse DocBlocks and provide both syntax color highlighting and function completion.
This is another case of [yak-shaving](https://en.wiktionary.org/wiki/yak_shaving#/media/File:Yak_shaving.jpg).
`php-cs-fixer` v3 has Strong Opinions on where function comments should be located in functions with multi-line parameters.
For instance, this:
```php
function example_with_multiline_params(
$param1,
$param2
)
// Function comment
{ …
```

Introduce code documentation standards and tooling

---

tools/proofers/images_index.php

When the `zip` command runs it outputs the list of files it's adding as it goes. When we use this in `images_index.php` to stream a zip file back to the user the output ends up in the Apache error logs. Prevent this with the `-q` argument.
I don't love the fact that we do a call-out like this, but I don't see a way to use the internal PHP zip tools to do this without creating the file, tossing it back to the user, and then deleting it -- and this appears to have worked since circa 2004.
Testable in the [quite-zip-creation](https://www.pgdp.org/~cpeel/c.branch/quite-zip-creation/) sandbox.

Quiet zip output when downloading project images

---

pinc/ProjectSearchResults.inc
pinc/RoundDescriptor.inc
pinc/abort.inc
pinc/faq.inc
pinc/graph_data.inc
project.php
quiz/generic/data/qd_formatting1.inc
quiz/generic/data/qd_formatting2.inc
quiz/generic/data/qd_formatting3.inc
quiz/generic/data/qd_formatting4.inc
quiz/generic/quiz_page.inc
tasks.php
tools/change_sr_commitment.php
tools/project_manager/manage_image_sources.php
tools/project_manager/remote_file_manager.php
tools/project_manager/show_image_sources.php
tools/site_admin/copy_pages.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/manage_special_days.php

This is another prep PR for the upcoming php-cs-fixer v3 update. The new version Has Opinions about switch statements and a few other things that I thought would be easier to handle in a separate PR.
This has 4 commits which touch different things:
* Standardizes switch statements across the codebase
* Remove errant `;`s
* Massage multiline `global` statements (v3 wants to format these oddly)
* Tweak comments (v3 wants to place these in interesting places)
The PR is best viewed with the "ignore whitespace" option.
I think a code review should be sufficient for this PR, but because it's easy to do, here's a sandbox: [update-odd-formatting](https://www.pgdp.org/~cpeel/c.branch/update-odd-formatting/)

Update odd formatting

---

tools/proofers/spellcheck.inc

`spellcheck.inc` is one of the few remaining oddities where we `include()` this file in the middle of another file (`processtext.php`) to inject its contents. It's also got an annoying mix of PHP and straight HTML. This is step 1 of 2 to addressing those issues by moving the contents into two pure PHP functions. I intend to lift all the functions in this file into `spellcheck_text.inc` and delete the `spellcheck.inc` entirely but it's going to be far easier to PR the changes if we do this first. The move will happen in a follow-up PR after this goes in.
The impetus for this is that php-cs-fixer wants to left-justify most of this file and I decided actually addressing the problem was a better approach.
Testable in [wordcheck-cleanup-1](https://www.pgdp.org/~cpeel/c.branch/wordcheck-cleanup- …

Move bulk of spellcheck.inc into a function

---

tasks.php

This enables ordinary users to create tasks.
Perhaps not an entirely satisfactory solution to the problem. Probably better to avoid redefining the task_status_array somehow, but seems to fix the problem for now.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/task_fix

redefine task_status_array after unsetting keys

---

pinc/Project.inc
tools/project_manager/update_illos.php
tools/proofers/images_index.php

This extends the ability to delete illustrations from the images index to all rounds/pools for squirrels. All others should still be limited to the new project state or P1 Waiting.
Testable in the [image-index-squirrel-delete-illos/](https://www.pgdp.org/~srjfoo/c.branch/image-index-squirrel-delete-illos/) sandbox.

Squirrels delete illos from images index

---

pinc/wordcheck_engine.inc
tools/proofers/processtext.php
tools/proofers/spellcheck_text.inc

Rather than restrict to only one additional aux language when calling WordCheck, allow multiple of them. This is the backend changes for [Task 2062](https://www.pgdp.net/c/tasks.php?action=show&task_id=2062) -- the UI bits need to still be implemented. There should be no user-visible changes with this change.
Unfortunately none of these high-level functions have unit tests because of the overhead of setting up a new Project with page text, etc. The lower-level calls are covered, but not the changed functions.
Testable in https://www.pgdp.org/~cpeel/c.branch/allow-multiple-dictionaries/

Allow multiple aux languages for a given WC call

---

pinc/phpbb3.inc

When a phpBB topic is created we need to populate `$forum_name` in the data object so it's included in any emails. This is probably only relevant if someone is watching for new topics in a forum. This has been broken since this code was updated in 2015 when we first supported phpBB 3.x 😳
It was tested on TEST as much as it could be without emails and validated as a hotfix on PROD.

Populate forum name on phpBB topic creation

---

styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/proofers/processtext.php
tools/proofers/spellcheck_text.inc

Allow users to de-select project dictionaries and add more than one non-project-defined dictionary. [Task 2062](https://www.pgdp.net/c/tasks.php?action=show&task_id=2062)
This is the feature that is out for discussion/review in the [Updates to how languages are selected (and de-selected) in WordCheck](https://www.pgdp.net/phpBB3/viewtopic.php?f=4&t=80775) topic.
Testable in https://www.pgdp.org/~cpeel/c.branch/multi-dict-ui/

Allow users more control over WC dictionaries

---

styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Fix setting the has-diff cell background color in Review Work for striped tables.
[Task 2067](https://www.pgdp.net/c/tasks.php?task_id=2067)
This is testable in: https://www.pgdp.org/~cpeel/c.branch/fix-review-work-style/
Specifically see srjfoo's diff [in the sandbox](https://www.pgdp.org/~cpeel/c.branch/fix-review-work-style/tools/proofers/review_work.php?username=srjfoo&use_eval_query=1&work_round_id=P1&review_round_id=P2&days=1200&sample_limit=0) vs the [main TEST code](https://www.pgdp.org/c/tools/proofers/review_work.php?username=srjfoo&use_eval_query=1&work_round_id=P1&review_round_id=P2&days=1200&sample_limit=0) -- you need to be a site admin or PF on TEST to see another user's diffs.

Correct cell bg color for striped rows

---

SETUP/tests/ProjectTest.php
pinc/LPage.inc
pinc/stages.inc
project.php

Factor out the logic used to determine if a user is able to work on a project that might be restricted to a round reserve. Require a User object to be passed in so we don't have to recreate it (with the DB hit) on every call -- which with the current interface is just once per page load, but won't be when I re-use this in the My Recommendations page. There is no functional change.
Testable in https://www.pgdp.org/~cpeel/c.branch/abstract-out-reserve-calculations/
Testing this is a bit hairy because you have to have a user with a certain time on site and a certain number of pages done in P1. I managed to do so on TEST but more importantly we have automated tests! Thanks to @70ray for the `validate_user_can_get_pages_in_project()` tests which caught a bug in my initial implementation!

Factor out user project reserve validation

---

tools/proofers/my_projects.php

These globals aren't used in the functions they are declared. Found these when working on the My Recommendations page.
Testable in https://www.pgdp.org/~cpeel/c.branch/remove-unused-globals/

Removed unused globals from My Projects

---

SETUP/tests/ProjectTest.php
pinc/stages.inc
pinc/user_is.inc

Fix functions that `validate_user_can_get_pages_in_project()` depend on to operate against the specified user and not assume `$pguser`. This makes the function more generally useful and more consistent.
Testable in https://www.pgdp.org/~cpeel/c.branch/dont-assume-pguser-in-checks/
The only place that the function is called right now is in `project.php` and `LPage.inc` during the proofreading process which all takes place only for the logged-in user so testing this just confirming its enforcing the reserve in the branch just like it does in `master`. The new recommendation page will optionally use this as another user.

Validate requested user's access to project, not pguser

---

pinc/smoothread.inc

if starting or extending smooth reading.
This is the first stage of a revised method of sending SR end notifications suggested by @cpeel . It is compatible with the old notification sender.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/sr_roundup

round up smooth read deadline to next hour

---

pinc/gradual.inc

For testing, as well as allowing PF/SAs to see what other users see on certain pages (My Projects, the upcoming My Recommendations), pass in the desired username and not assume `$pguser`. If the new optional argument isn't included, they call back to `$pguser` retaining all existing uses of these functions.
Testable in https://www.pgdp.org/~cpeel/c.branch/update-gradual/

Allow functions in gradual to accept a username

---

SETUP/API.md
SETUP/INSTALL.md
pinc/graph_data.inc
pinc/misc.inc
stats/round_backlog.php
stats/round_backlog_days.php

Introduce a generalized version of `query_graph_cache()` that can be used for any data-collecting function. As for the name, see the [Memoization](https://en.wikipedia.org/wiki/Memoization) wikipedia article if you're not familiar with it. The updated graph pages are best viewed ignoring whitespace as the code was just indented when added to a function.
Testable in https://www.pgdp.org/~cpeel/c.branch/memoize-function/
I've added a new `memcache-stats` feature to the Squirrel Workbench on TEST that shows the memcache statistics. This can be used to confirm the new code is hitting memcache to get the cached data.

Generalize function caching code

---

pinc/TallyBoard.inc
pinc/page_tally.inc

Currently on PROD, the round pages take ~2.5 seconds each to load. >2 seconds of this time is coming from the logic to calculate a user's neighbors for the stats bar.
Not all users proof in all rounds, so the size of the users table is always going to be bigger than the number of tallies in a round. So instead of generating tallies in a round for all users and trimming out those who aren't present, only get users with tallies and special-case when the current user isn't in the tally round. Performance is now based on how many users have proofread in a round rather than the number of entries in the user table.
I've simplified the function which makes it specific to this one use-case, but it's only used in one place so the extensibility isn't necessary.
Here are the timings of the SQL for …

Improve performance for neighbor stats

---

pinc/gradual.inc
tools/proofers/round.php

Add callouts to the round pages to encourage users to work in rounds with the largest backlog. This is a generalized, and improved, version of the 2b891bde0c009ba5642d2a1f1b4094e2da979287 commit in the `pgdp-production` branch which only applies to P1. This version will encourage users towards the round with the biggest backlog that they have access to or are eligible for except for quizzes.
We may want to consider updating the version of this that goes into `pgdp-production` to exclude the bits about applying for P3/F2 if they are otherwise eligible.
This is testable in https://www.pgdp.org/~cpeel/c.branch/encourage-higher-rounds/
The above sandbox has a hack applied to simulate the backlog order on PROD: P3, F2, F1, P1, P2 rather than what's on TEST which has the biggest backlog in P1: …

Add callouts on round pages to move up

---

accounts/activate.php
pinc/theme.inc
stats/includes/member.inc

If users don't want to see the neighborhood, don't incur the performance penalty of loading it. Also use u_neigh to show users a wider range on their personal stats page.
Testable in https://www.pgdp.org/~cpeel/c.branch/improve-stats-for-no-neighbors/
Should show identical stats to TEST with the exception of Rank which will now show actual rank on TEST and not "Valued Tester".
---
I also strongly considered setting the default value for new accounts so `u_neigh=0`. I still think that's a good idea but we can evaluate that separate from this optimization PR.

Don't incur neighborhood overhead if u_neigh=0

---

pinc/upload_file.inc
scripts/file_resume.js
tools/upload_resumable_file.php

This makes a checksum for the uploaded file, uploads it and checks it with the file received by the server.
The javascript function is based on the example in [this mozilla document](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API/Non-cryptographic_uses_of_subtle_crypto) reworked for the browsers we support which cannot use async, await, File.arrayBuffer() or String.padStart().
This checking should not really be necessary because lower levels of the internet protocol should already validate data but two users have encountered errors given by the zip validator so this is intended to discover if the problem is caused by data corruption or something else.
The change to upload_resumable_file.php is recommended in the resumable docs to avoid unnecessary error messages in the …

Upload check

---

SETUP/tests/jsTests/formatPreviewTests.js
styles/preview.css
tools/proofers/preview.js
tools/proofers/previewControl.js

This uses classes rather than styles to colour and style the format preview. This makes the tests less dependent on the details of the style.
Then colour no-wrap and block-quote blocks rather than just the tags. This addresses [task #2065](https://www.pgdp.net/c/tasks.php?action=show&task_id=2065)
Sandbox at: https://www.pgdp.org/~rp31/c.branch/format_preview_class

Format preview class

---

pinc/gradual.inc
pinc/theme.inc
tools/proofers/my_projects.php
tools/proofers/my_suggestions.php

A new page for users to find new projects to work on. Includes a very (very) rudimentary recommendation algorithm. The page was originally titled "My Recommendations" but "Suggestions" is both shorter and sounds a little less formal.
The algorithm -- and the bulk of the code -- is the same one currently in noncvs on PROD, however it is not the exact same as this one relies on a few recent PRs.
Code in the PR is testable in https://www.pgdp.org/~cpeel/c.branch/my-suggestions/

Add new My Suggestions page

---

stats/members/mdetail.php

Allow a generic URL for accessing a user's own details. This allows us to include it in forum posts and documentation. I want to include a link to a user's own P1 stats in a forum post and this allows that.
Diff best viewed ignoring whitespace.
Example in sandbox: https://www.pgdp.org/~cpeel/c.branch/allow-generic-mdetail-url/stats/members/mdetail.php?tally_name=P1

Allow generic URL for user's own details

---

pinc/Round.inc
pinc/page_table.inc
pinc/theme.inc
stats/release_queue.php
tools/project_manager/page_detail.php
tools/proofers/ctrl_frame.php
tools/proofers/for_mentors.php
tools/proofers/review_work.php
tools/proofers/round.php

Create and use a new function for validating a round ID and return the round object if found. This mirrors our other `get_[name]_param()` functions in `misc.inc`.
Testable in https://www.pgdp.org/~cpeel/c.branch/create-round-param-validator/
Specifically the following pages:
* [round page](https://www.pgdp.org/~cpeel/c.branch/create-round-param-validator/tools/proofers/round.php?round_id=P1)
* [Review Work](https://www.pgdp.org/~cpeel/c.branch/create-round-param-validator/tools/proofers/review_work.php)
* [release queues](https://www.pgdp.org/~cpeel/c.branch/create-round-param-validator/stats/release_queue.php?round_id=P1)
* [for mentors](https://www.pgdp.org/~cpeel/c.branch/create-round-param-validator/tools/proofers/for_mentors.php?round_id=P2)
* [page details without round …

Add round param validation

---

tools/proofers/spellcheck_text.inc

Escape warnings from WordCheck before outputting them to the user.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/escape-warnings/

Escape warnings from WordCheck

---

SETUP/MediaWiki_extensions/dpExtensions.php
SETUP/MediaWiki_extensions/hospitalExtensions.php

The 2 MediaWiki extensions are Special Snowflakes that do not pull in `base.inc`. They do, however, use `project_states.inc` which depends on the now-not-explicitly-included `misc.inc` (because it is included in `base.inc`) so we include it in the extensions instead.
This code was hotfixed on TEST and PROD.

Explicitly include misc.inc in MW extensions

---

activity_hub.php
pinc/gradual.inc
tools/proofers/round.php

This provides some minor standardization for our new proofreader cutoffs so we have fewer of them. This is a minor improvement for issue #995 but is not a fix.
Not putting up a sandbox as this is a pretty simple review via PR.

Standardize new proofreader page thresholds

---

styles/preview.css

consecutive no-wrap blocks would otherwise wrap onto the same line. This style was originally added to avoid an artifact where an uncoloured area would appear if long lines of no-wrap were scrolled into view but this is less serious.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/consec_nw

remove inline-block from no-wrap style

---

scripts/file_resume.js
tools/upload_resumable_file.php

This addresses two edgcases in an attempt to fix the upload problems we're seeing:
* Only ever return a single HTTP response code in GET requests
* Validate every chunk upload against its expected size.
To handle the edgecase where a file is fully uploaded but not reassembled, we attempt reassembly both on testChunks (GETs) as well as the uploads (POSTs). The original code responded with a 200 that the chunk exists but the reassembly could have failed and not reported a 5xx code. Now the code sets one and only one return code, or falls through to the script completion which is an implicit 200.
Also validate that every chunk is at least chunkSize to attempt and detect cases where the client didn't successfully uploading an entire chunk.
This PR is best reviewed ignoring whitespace as I …

Validate chunk size in resumable uploads

---

pinc/Round.inc
pinc/page_table.inc

Currently the value of `is_diff` returned from `fetch_page_table_data()` is opposite of what it says -- if the value is 1 there is no difference, if the value is 0 there is a difference.
The API directly reports the result of this function directly which means it's been wrong since the API was created. Update the code to use a collation-insensitive comparison operator (and stop using the deprecated BINARY operator) and ensure that `is_diff` is accurate. This removes the unused `textdiff_column_name` Round attribute -- this is the only place this is used in the codebase and noncvs.
Testable in https://www.pgdp.org/~cpeel/c.branch/fix-is_diff/ -- the page details page results should match TEST and the following `curl`:
```bash
API_KEY=xxx  # your key here
PROJECTID=projectID4c49f39aa829c …
```

Fix definition of is_diff

---

api/dp-openapi.yaml
api/v1_projects.inc
pinc/Activity.inc
pinc/page_table.inc

The [Gap Games](https://www.pgdp.net/wiki/Gap_Game) use the DP API to pull some information from the `v1/projects/:projectid/pagedetails` endpoint (which is the same underlying function that renders the Page Details table for a project). This returns data for every round which
1. is a lot of data if you only need one round of it
2. is a pretty expensive DB query for later-round projects with lots of pages
This PR allows the user to just request the round(s) they care about making the data smaller and the SQL simpler. By default the endpoint still returns all rounds. The new `pageroundid` query param works similarly to the [`field` query param for the `v1/projects` endpoint](https://github.com/DistributedProofreaders/dproofreaders/blob/master/api/dp-openapi.yaml#L79) by allowing multiple …

Enable filtering page details API by round

---

pinc/Quiz.inc
pinc/gradual.inc

This does 2 things:
* Update the new proofreader message (<100 pages proofread) that gets shown on the Search page to point them to the My Suggestions page.
* Update the post-quiz pass logic to automatically grant them access to the round if they are eligible for auto-grant -- this is what already happens if they pass the quiz and then go to the round page. Doing this here allows us to refer them to the My Suggestions page in addition to the round page and ensure they can work in both when they get there.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/finesse-new-proofreader-messages/
Note: The sandbox has the `pgdp-production` commit that requires passed quizzes to work in P1 so that this can be tested easily.

Refer new users to My Suggestions page

---

pinc/User.inc

Remove Twitter as a referrer source, as requested by @lhamilton1.

Remove Twitter as a referrer source

---

SETUP/configure

This helps catch configuration errors when installing PGDP.

SETUP/configure: Switch on bash errors for unset env vars etc

---

api/dp-openapi.yaml
api/v1_projects.inc

This requires a new boolean flag type which can be one of:
* absent (implicitly false)
* present but with no value, ie "&flag" (implicitly true)
* explicitly true or false, ie "&flag=false" "&flag=true"
Also, add smoothread_deadline as a valid datetime field in the response.
```bash
API_KEY=xxxx # update
API_ROOT=https://www.pgdp.org/api
FILTER="&in_smoothreading"
FIELDS="&field[]=title&field[]=smoothread_deadline"
curl -i -X GET "$API_ROOT/v1/projects?state=proj_post_first_checked_out${FILTER}${FIELDS}" \
-H "X-API-KEY: $API_KEY"
```

api/v1/projects: Add in_smoothreading flag to query

---

pinc/graph_data.inc
pinc/misc.inc
stats/pages_proofed_graphs.php

Generating the page stats is very resource intensive and can take a very long time. Cache the stats for as long as is reasonable which in some cases is up to a month. This mitigates https://github.com/DistributedProofreaders/dproofreaders/issues/1025
Clarify that memcached accepts both a timestamp *and* seconds from now: https://github.com/memcached/memcached/wiki/Programming#expiration
Testable in https://www.pgdp.org/~cpeel/c.branch/cache-graphs-longer/ -- note that the HTML for the page as a comment that shows exactly what the expiration times are evaluated to.

Cache page stats graphs as long as possible

---

api/USERS_GUIDE.md

Provide more details on how the API should be used, including the limitations of the Swagger Editor.
I've updated the examples such that all of the boilerplate is in the first line and all the useful stuff we want people to focus on is on the second line. This also makes it easier to repeat a command on the command line and make changes to it.
Viewing the [rendered markdown of this file](https://github.com/cpeel/dproofreaders/blob/update-api-docs/api/USERS_GUIDE.md) is likely to be useful when reviewing the updates.

Improve the API user's guide

---

SETUP/UNICODE.md
pinc/charsuite-basic-cyrillic.inc

The Basic Cyrillic character suite covers Russian. Discussion in the forums concluded with recommending that PMs who run projects for other Cyrillic-based languages add the few additional letters as project custom characters, and wait to see if a need develops later for another Cyrillic-based character suite.
[This project](https://www.pgdp.org/~srjfoo/c.branch/new-charsuite-cyrillic/project.php?id=projectID65ac79d59af7b) has been set up in the sandbox with pages that contain some Cyrillic upon which to practice (note that no Cyrillic-based dictionaries have yet been installed).

New charsuite cyrillic

---

api/v1_validators.inc
pinc/Project.inc
tools/proofers/my_projects.php

array_key_exists was introduced in PHP 4.0.7.
It's a little shorter to write and (after looking at the Zend source), it is more efficient because it tests directly against $a rather than allocating a temporary new list with the keys in it.

cleanup: use array_key_exists($k, $a) instead of in_array($k, array_keys($a))

---

faq/formatting_guidelines.php
faq/post_proof.php

Because this was in the place of the positional show_stats arg it caused the sidebar to appear.
This was missed in the refactor a2d59202ae483 (by me!)
It was never noticed because on PGDP these FAQs redirect to the wiki.

faq: Remove incorrect argument to output_header for builtin FAQs

---

tools/proofers/spellcheck_text.inc

No functional change, but it confused PHPStan

spellcheck_text.inc: Fix PHPDoc param types

---

quiz/generic/wizard/output_quiz.php

output_quiz.php: Fix (harmless) use of uninitialized variable

---

pinc/CharSuites.inc

TIL that PHP is unlike Python (in this way, as well as so many others :) ). Since 7.1 it has an explicit void return type, which differs from null.
You can either let a function implicitly return, or explicitly use `return;`
https://wiki.php.net/rfc/void_return_type

CharSuites.__set: Has a void return type so shouldn't return null

---

pinc/POFile.inc

It doesn't actually return anything (and the callers don't require it to)
Found by PHPStan

POFile: Update the PHPDoc for count_translated_strings

---

tools/proofers/my_suggestions.php

Even back in the dawn of time (ie 786723b9c96), it didn't.
Found by PHPStan

my_suggestions.php: get_desired_language() doesn't take an arg

---

pinc/DPDatabase.inc

PHP prints a warning if they're not.
This is a partial revert of 255f9c157.

DPDatabase.inc: (De)serialization methods must be public

---

tools/project_manager/editproject.php

`set_from_clone()` didn't accept a projectid, but we were passing it one in one place but not the other. When a project is cloned, the URL includes the projectid of the original project. But we _also_ include it in the POST as clone_projectid because we need it if they preview the new project info before they save it and upon save (because we clone more things than they can edit in this form). Everything worked but it did so in an unclear way.
Now use the clone_projectid value in the POST if we're getting data from the POST, and from the GET param if we're servicing a clone action.
This is an issue that @bpfoley found using PHPStan.
Sandbox to validate cloning still works as-desired at https://www.pgdp.org/~cpeel/c.branch/fix-clone-project-code/

Fix set_from_clone()'s argument

---

activity_hub.php
pinc/Project.inc
pinc/Quiz.inc
pinc/User.inc
pinc/gradual.inc
pinc/page_table.inc
pinc/page_tally.inc
pinc/release_queue.inc
pinc/site_news.inc
pinc/theme.inc
pinc/user_is.inc
project.php
tools/pool.php

This PR removes round globals in four broad areas:
* `project.php`
* `activity_hub.php`
* `pool.php`
* `pinc/*` files
Broadly speaking, validating the following should cover most of these changed files (but perhaps not all):
* Viewing the pool page
* Editing site news (and seeing all the activities up top)
* Viewing a project page
* Viewing a project's page table listing
* Changing a user's access to a round
* Viewing the release queue page
Sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-round-globals-project-pinc

Replace globals in project, AH, and Pool pages

---

.php-cs-fixer.dist.php
SETUP/import_old_configuration.php
api/v1_projects.inc
api/v1_queues.inc
api/v1_stats.inc
composer.lock
faq/prooffacehelp.php
pinc/misc.inc
pinc/upload_file.inc
pinc/wordcheck_engine.inc
stats/release_queue.php
tools/project_manager/external_catalog_search.php
tools/project_manager/manage_image_sources.php
tools/proofers/PPage.inc
tools/proofers/mktable.php
tools/proofers/my_suggestions.php
tools/proofers/review_work.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/manage_special_days.php

Also add and configure the [single_space_around_construct rule](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/language_construct/single_space_around_construct.rst) which enforces spacing after `if()`s and and other constructs. Spacing around these are part of the [PSR-2 spec](https://www.php-fig.org/psr/psr-2/#51-if-elseif-else) which we are using (via `@PSR12` ruleset) but isn't being enforced for some reason. This changed in php-cs-fixer 3.16.0 when this new rule was introduced somehow. Restoring this mirrors what we had in php-cs-fixer v2 which was used initially to format the codebase.
This is a code format only change so eval can be done just in PR without a sandbox.

Update php-cs-fixer version to latest

---

api/v1_projects.inc
api/v1_stats.inc
api/v1_validators.inc
stats/includes/member.inc
stats/pages_in_states.php
stats/pp_stage_goal.php
stats/release_queue.php
stats/round_backlog.php
stats/round_backlog_days.php

This PR removes the globals from the API and stats/* files.
Testable in https://www.pgdp.org/~cpeel/c.branch/remove-round-globals-api-stats/

Remove globals from api and stats files

---

pinc/ProjectTransition.inc

Whenever `ProjectTranstion.inc` was included it made all the project transition data whether it was needed or not. (`LPage` includes `ProjectTranstion.inc` because it is needed for `markAsBad()` and `v1.inc` includes `LPage.inc` indirectly.)
This removes the global `PROJECT_TRANSITIONS` and makes them once if they are needed.
Best viewed with hide whitespace.
The interleaved functions have been moved to the end.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/avoid_proj_trans

avoid creating project transitions unless needed

---

tools/project_manager/diff.php
tools/proofers/PPage.inc
tools/proofers/for_mentors.php
tools/proofers/my_projects.php
tools/proofers/my_suggestions.php
tools/proofers/review_work.php

Removes globals from My Projects, My Suggestions, "for mentors" page, the "diff" page for a project page text, and code used when getting a page for the proofreading interface, and finally review work.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/remove-round-globals-proofers/

Remove globals from proofer pages

---

pinc/page_tally.inc
stats/includes/member.inc
stats/proof_stats.php

These will be moved to `pgdp-production` branch immediately after this merges.
Direct link to stats page in test sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-r-rounds-from-master/stats/members/mdetail.php?id=1&tally_name=P1

Remove remaining(?) reference to R rounds in master

---

tools/modify_access.php
tools/pending_access_requests.php
tools/project_manager/automodify.php
tools/project_manager/generate_post_files.php
tools/project_manager/handle_bad_page.php
tools/project_manager/show_all_good_word_suggestions.php
tools/project_manager/show_project_wordcheck_usage.php
tools/set_project_holds.php
tools/site_admin/project_jump.php

Remove the last activity/stage/round/pool globals, these from the PM and SA pages.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/remove-round-globals-pm-and-sa/

Remove globals from PM and SA pages

---

SETUP/dp.cron.template
crontab/finish_smoothreading.php

This is the second stage of the revised method of sending SR end notifications. It should not be merged until at least 42 days after #987 or SR periods that have not been rounded up may fail to send notifications.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/improve_sr_notify

revise sending SR notifications assuming whole hour deadlines

---

.github/actions/setup-php/action.yml
.github/workflows/static-checks.yml

Make sure we don't accidentally introduce breakages on newer OSes.
NB the matrix definitions are duplicated across all the jobs for the moment. To avoid this sharing we need to build a job that emits JSON as a single line as a GITHUB_OUTPUT, and parse that using fromJSON in each job. I struggled to get this right, and gave up for now.

Run all tests on Ubuntu 20.04 and Ubuntu 22.04

---

.github/actions/setup-node/action.yml

This uses Node 20 internally in the action script itself, rather than the older Node 16 which is now deprecated on GitHub.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

.github: Update actions/setup-node tag to v4

---

SETUP/tests/RoundTest.php
SETUP/tests/misc_ParamValidatorTest.php
pinc/Round.inc
pinc/misc.inc

Improve the robustness of our `get_*_param()` function calls by adding type definitions rather than assert checking where we can. If the caller passes in the wrong type, PHP will raise an exception which most likely means a developer coded something wrong. Change all non-type validation asserts to raise exceptions. This introduces a slew of new unit tests as well as updating some exiting tests to check the exception message to make sure we're testing the right thing.
Because union types and the `mixed` type didn't enter PHP until 8.0 we are limited in a couple of cases and some comments have been added accordingly.
Code inspection and unit tests should be sufficient but for a sanity check, here's a sandbox: https://www.pgdp.org/~cpeel/c.branch/type-decls-in-get-params/

Add type declarations for get_*_param functions

---

api/dp-openapi.yaml
api/v1_queues.inc
pinc/release_queue.inc
stats/release_queue.php

This is already visible on stats/release_queue.php and in api/v1/projects/:pid, and it's useful (read: I have a use for :)), so make it visible in the queue projects API too.

api/v1/queues/:id/projects: Add project_manager field to output

---

.github/workflows/static-checks.yml
SETUP/phpstan_bootstrap.inc
pinc/bootstrap.inc

So we can run PHPStan without needing to set up mysql.

bootstrap.inc: Allow DPDatabase::connect to be skipped

---

phpstan.neon
tools/project_manager/external_catalog_search.php

It turns out the PHPStan error when analyzing this file was due to an old version of phpyaz on the dev machine. The issue appears to be incorrect metadata provided by phpyaz when using the extensions reflection API.
This was fixed in phpyaz 1.2.4.
See https://github.com/indexdata/phpyaz/pull/11#issuecomment-697478833

phpstan.neon: Remove exception

---

SETUP/tests/RoundTest.php
pinc/DPage.inc
pinc/ProjectTransition.inc
pinc/Round.inc
pinc/page_table.inc
pinc/stages.inc
stats/equilibria.php
stats/requested_books.php
tools/project_manager/automodify.php
tools/project_manager/autorelease.inc
tools/project_manager/diff.php
tools/project_manager/show_adhoc_word_details.php
tools/project_manager/show_all_good_word_suggestions.php
tools/project_manager/show_current_flagged_words.php
tools/project_manager/show_good_word_suggestions.php
tools/project_manager/show_project_possible_bad_words.php
tools/project_manager/show_project_stealth_scannos.php
tools/project_manager/show_project_wordcheck_stats.php
tools/project_manager/show_word_context.php
tools/proofers/review_work.php

Replace numeric iteration of the rounds by a more natural foreach over the objects. This ultimately removes `MAX_NUM_PAGE_EDITING_ROUNDS`.
Testable in https://www.pgdp.org/~cpeel/c.branch/remove-max-rounds-const/
Aside: This started as work on Task 2000 but it got into a bit of yak shaving.

Remove use of MAX_NUM_PAGE_EDITING_ROUNDS

---

scripts/page_browse.js
scripts/view_splitter.js

This is "Yak-shaving" getting ready to replace the horizontal/vertical splitter icon  with a font-awesome icon button so it will change size with the font size.
The 'control' class which the icon was given is only used to enable it to be selected and removed later in page_browse.js. This branch makes page_browse.js handle adding and removing controls entirely within itself.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/control_span

use a span to hold controls instead of giving them a class

---

api/dp-openapi.yaml
api/v1_projects.inc
pinc/page_table.inc

...using the same permissions checks that page_detail.php uses for each page, which is now factored out into a shared function.

api/v1/project/:id/pagedetails: Show username if permitted

---

pinc/page_table.inc

(This was what motivated me to add it in the first place.)
Sandbox at https://www.pgdp.org/~bfoley/c.branch/any-user

can_user_see_usernames_for_page: Use any() to de-boilerplate.

---

SETUP/tests/RoundTest.php
SETUP/tests/phpunit_bootstrap.php
pinc/Pool.inc
pinc/Round.inc
pinc/graph_data.inc
pinc/project_states.inc
pinc/stages.inc

This is the first part of the process, using a ProjectState object to hold the $medium_label, $long_label, $forum and $phase and a global $project_states array to associate the state names with the project states.
This has been remade with conficts resolved.
The next part will be to use a static class to remove globals.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/project_states_3

Remove duplicate definition of rounds in project_states.inc

---

styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tasks.php

The comment IDs and anchors already existed, we just needed to use them!
Example in sandbox at https://www.pgdp.org/~bfoley/c.branch/task-comment-permalink/tasks.php?action=show&task_id=2288

tasks.php: Add permalinks to each tasks comment

---

project.php

Add a link to the page browser on the project page. This is shown at level 3 and higher.
This also has two other small changes:
* move globals to top of function
* minor formatting of the Page Details cell contents
Testable in https://www.pgdp.org/~cpeel/c.branch/add-page-browser-link/ -- eg [this project's page](https://www.pgdp.org/~cpeel/c.branch/add-page-browser-link/project.php?id=projectID4c49f39aa829c)

Add page browser link

---

faq/pophelp/prefs/prefs_pophelp.inc
pinc/Project.inc
pinc/ProjectSearchResults.inc
project.php
tools/project_manager/add_files.php
tools/project_manager/edit_pages.php
tools/proofers/PPage.inc
tools/proofers/review_work.php
userprefs.php

Give project detail levels meaningful descriptors and allow users to select which one they want to see by default. This also removes all of the bits in the code that override the `detail_level` via URL.
Note that we change the default level back to 2 (it was changed from 2 to 3 in 2014). This present users with a smaller set of data to hopefully be less confusing. Subsequent PRs could further pair down the data shown at level 2 to improve the new user experience.
Testable in https://www.pgdp.org/~cpeel/c.branch/project-detail-level/
[Task 669](https://www.pgdp.net/c/tasks.php?task_id=669)

Allow users to select their preferred project detail level

---

sitemap.php
tools/project_manager/clearance_check.php

2b97d677d2 caused the initialization of PROJECT_STATES_IN_ORDER to move from project_states.inc to stages.inc (it's done by the call to declare_project_states in stages.inc)
sql_collater_for_project_state() (defined in project_states.inc) requires PROJECT_STATES_IN_ORDER to be defined.
(I'm not confident this is the correct fix, but I thought I'd put it up to advance the discussion)

sitemap.php: Fix error caused by PROJECT_STATES_IN_ORDER

---

SETUP/tests/RoundTest.php
pinc/graph_data.inc
pinc/project_states.inc
pinc/stages.inc

The global variables are $project_states which is only used in one place and has been removed.
$PROJECT_STATES_IN_ORDER is used in many places but only those in project_states.inc have been replaced so far (by ProjectStates::get_states();).
There are some functions which can also be replaced later.
Best viewed on here with whitespace hidden although it gets a bit mixed up even then.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/project_states_class

Use a ProjectStates class to avoid global variables. 

---

SETUP/check_db_schema.template
SETUP/db_schema.sql
SETUP/dump_db_schema.template
SETUP/install_db.php

This updates some of the pre-release tooling we use to confirm all database changes we made to the live DB on TEST are represented by the upgrade scripts. Every release I bang my head against subtle differences in the output due to collation (among others) and this time I decided to just fix it.
I've also updated the dump format so it is mostly just what `mysqldump` does rather than mirroring the phpMyAdmin dump format which we haven't used in well over a decade. There are no functional changes in `db_schema.sql`, just changes to comments (mostly format).

Update release tooling

---

tools/project_manager/page_compare.php

This removes the hard-coded round ids, addressing issue #1005 
The compare without formatting link on the project page should comtinue to work as before.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/no_hard_code_rounds

Generalise round options

---

tools/project_manager/page_detail.php

Example in sandbox: https://www.pgdp.org/~bfoley/c.branch/t2049-fix/tools/project_manager/page_detail.php?project=projectID5e26422ab19b5&show_image_size=0

page_detail.php: Don't stretch linkbox with long project titles

---

SETUP/tests/ProjectTest.php
api/v1_stats.inc
crontab/log_project_states.php
pinc/Project.inc
pinc/ProjectSearchForm.inc
pinc/ProjectTransition.inc
project.php
tools/changestate.php
tools/project_manager/projectmgr.php
tools/proofers/PPage.inc
tools/proofers/processtext.php
tools/proofers/proof.php

This + https://github.com/DistributedProofreaders/dproofreaders/pull/1124 will remove all instances of `$PROJECT_STATES_IN_ORDER`.
https://www.pgdp.org/~cpeel/c.branch/remove-page-states-global/

Remove last uses of $PROJECT_STATES_IN_ORDER global

---

credits.php
faq/pophelp/prefs/prefs_pophelp.inc
tools/project_manager/handle_bad_page.php
tools/project_manager/show_image_sources.php
tools/proofers/preview.inc
tools/proofers/spellcheck_text.inc

There should be no functional changes. Some of these are errors in the English strings that one of our translators found while updating translated strings, others are tweaking punctuation and spacing that I found while poking through the PO file to see if there were other things I could identify easily.
Sandbox at [https://www.pgdp.org/~srjfoo/c.branch/string-cleanup](https://www.pgdp.org/~srjfoo/c.branch/string-cleanup).

Fix translation-related typos in master

---

pinc/authors.inc
pinc/comment_inclusions.inc
pinc/misc.inc
pinc/send_mail.inc
tasks.php

These were visible in comments on the task center such as "&type c:\windows\win.ini&"
They rendered OK, but also emitted PHP Notice messages into the web page.
Example in sandbox at https://www.pgdp.org/~bfoley/c.branch/quell-parsedown-notices/tasks.php?action=show&task_id=2296

Centralize Parsedown code, and suppress Notices generated by the parser

---

userprefs.php

For the default form selection in preferences, correctly set the `project_detail` value to 2. It works as-is because 1 is not a valid option so the select shows the first option which is 2, but we should reflect what we actually want. Because of this the behavior of the sandbox won't look any different than what's on TEST, but here it is anyway: https://www.pgdp.org/~cpeel/c.branch/fix-project-detail-form-default/

Set initial project_detail selection to 2

---

project.php

We need to confirm the project table exists before fetching a list of pages.
Interesting edgecases are new projects with a page table but no pages and projects where the page table has been deleted (eg: deleted projects).
Sandbox: https://www.pgdp.org/~cpeel/c.branch/check-pagetable/

Check project table exists before fetching pages

---

SETUP/check_includes.php
api/index.php
pinc/base.inc
pinc/bootstrap.inc

When rounds/stages/etc are defined we use `_()` to translate strings. If we don't configure gettext first those strings will non-localized. Move site_structure.inc from bootstrap.inc to the two entrypoints: `base.inc` and `api/index.php`.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-site-structure-translation/

Configure gettext before creating site structure

---

SETUP/MediaWiki_extensions/dpExtensions.php
SETUP/MediaWiki_extensions/hospitalExtensions.php

Because of recent include restructuring we can't include more than site_vars.php and misc.inc without having conflicts with MW objects. The solution to this is going to be moving these to an API, but this unblocks the upcoming release until that is in place.
These are the changes that are currently running on PROD.

Fix MediaWiki extensions

---

.github/workflows/ci.yml
SETUP/smoketests/error.php
SETUP/smoketests/hello.php
SETUP/smoketests/notice.php
SETUP/smoketests/pageload_smoketest.py
SETUP/smoketests/posts.json
SETUP/smoketests/test_tables.sql
SETUP/smoketests/users.json
SETUP/smoketests/warning.php
SETUP/tests/ci_configuration.sh
api/index.php
stats/pages_in_states.php
stats/round_backlog.php
stats/round_backlog_days.php

A smoketest that sets up `site_vars.php` and a minimal set of database tables so that PGDP can be served from the `php -S` command line web server.
Then it loads many pages (soon to be every page) with representative parameters and checks if there are any PHP errors, warnings, or notices in the server logs.
Useful for, e.g., catching variables that happen not to be defined at runtime, and other issues that PHPStan and the PHP linter can't find.
This is deliberately not an exhaustive test of all possible inputs -- smoke tests are meant to be fast and to weed out obvious brokenness.  That said, we probably should check each of, e.g. `task.php`'s `action=` parameters so we get reasonable code coverage.
This is incomplete, but is good enough to be useful as is.
Next steps:
1. Add all the …

Pageload smoketest

---

SETUP/tests/jsTests/formatPreviewTests.js
tools/proofers/preview.js

This addresses [task 2077](https://www.pgdp.net/c/tasks.php?action=show&task_id=2077).
Sandbox at: https://www.pgdp.org/~rp31/c.branch/block_colour

Colour block quotes correctly when there is a nested block quote.

---

tools/project_manager/remote_file_manager.php

This makes it easier for site admins -- they don't have to remember if user dirs in ~uploads/Users are capitalized or not.

remote_file_manager.php: Case insensitive, natural sorting of dirs

---

stats/includes/member.inc

Because of how account creation is done, this isn't ordinarily possible in PROD, but occurs on TEST.
While here, allow any of the user's contact fields (apart from the username) to be undefined, not just a random subset of them.
Test sandbox at https://www.pgdp.org/~bfoley/c.branch/memberless/stats/members/mdetail.php?id=575

member.inc: Don't try to show forum info if the user doesn't have an account

---

accounts/activate.php
accounts/addproofer.php
pinc/theme.inc
quiz/start.php
tools/project_manager/clearance_check.php
tools/project_manager/page_detail.php
tools/proofers/my_projects.php
tools/proofers/my_suggestions.php
tools/proofers/review_work.php
tools/site_admin/edit_mail_address_for_non_activated_user.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/show_access_log.php

The autocapitalize attribute is standard HTML5, but the default behavior when it isn't explicitly set differs across browsers.
In particular we have some users using iPads, and in Safari, autocapitalize is on by default.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize#usage_notes
Support goes back to iOS Safari 5 (2012); Chrome 43 (2015); Opera 30 (2015); but not until Firefox 111 (2023). However the Firefox non-support is harmless as it defaults to autocapitalize off anyway.

Disable autocapitalization of username input fields

---

activity_hub.php
faq/prooffacehelp.php
pinc/quizzes.inc
pinc/stages.inc
quiz/generic/wizard/messages.php
quiz/tuts/tut_p_aeoe_1.php
quiz/tuts/tut_p_mod1_3.php
tools/project_manager/projectmgr.inc

Replace the hard-coded `faq/*` URLs with the ones that take the user directly to the wiki rather than relying on the redirects inside the `faq/*` pages to redirect them there. This is the first step in removing the the `faq/*` files that have been moved to the wiki.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/replace-hardcoded-faq-urls/

Replace hard-coded faq/*-referenced URLs

---

api/dp-openapi.yaml
api/v1_projects.inc

Clients can already access a subset of fields when listing projects with `api/v1/projects` so it makes sense to allow this for individual projects too. And in particular clients may want to avoid the `comments` field because it can be very large.

api/v1/projects/:id: Allow endpoint to return selected fields

---

pinc/LPage.inc
tools/proofers/proof_frame.php

rename function because the page has not necessarily been saved.
Use page_require instead of a database access.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/revise_resume

Revise page_resume function

---

api/v1_projects.inc

As suggested by srjfoo. I agree with her that it's better to fail loudly rather than silent ignore unrecognized fields. If nothing else, it helps when a dev makes typos in client code.
I needed to do some code reorg to avoid repeating a subset of SQL column names and API field names for a third time.
Sandbox at https://www.pgdp.org/~bfoley/c.branch/invalid-field but it doesn't touch any non-API code.
Example call:
```
curl -s -X GET "$ROOT/api/v1/projects&field[]=pages_total&field[]=no_such_field" \
-H "X-API-KEY: $INSERT_YOUR_API_KEY_KEY"
```

api/v1_projects.inc: Return an error if client requests invalid field

---

default.php

The [Certification of Volunteer](https://www.pgdp.net/wiki/DP_Official_Documentation:General/Certification_of_Volunteer_Work) Work disclaimer wording in the wiki has recently been updated. This PR realigns the wording on the home page with the updated disclaimer. GM request.

Update to volunteer certification disclaimer

---

SETUP/CHANGELOG.md
SETUP/db_schema.sql
SETUP/smoketests/test_tables.sql
SETUP/upgrade/21/20240403_update_user_table.php
faq/pophelp/prefs/prefs_pophelp.inc
pinc/gradual.inc
pinc/html_page_common.inc
pinc/theme.inc
scripts/navbar_menu.js
styles/global.less
styles/layout.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
userprefs.php

Introduce the idea of drop-down menu options to group like things together and make better use of the top header space. Much to my chagrin we use the new menu based on a user preference; if the preference is set to "auto" (the default) dynamically use the menu based on the width of the window.
This is available for testing in https://www.pgdp.org/~cpeel/c.branch/refine-navbar/
See also the discussion in the [Proposed changes to the navigation bar - 2024 edition](https://www.pgdp.net/phpBB3/viewtopic.php?f=4&t=81413) forum.
Testing notes: In addition to confirming this works in all our minimum browsers, we should make sure this looks good in all themes -- including having an unread message in the forums which will add an "unread messages" number to the new Inbox icon -- and on various …

Collapse Activities in navbar based on avail space (& preference)

---

stats/round_backlog.php
stats/round_backlog_days.php

61c6b1438 inadvertently used `min()` when we really want `max()`

Fix round backlog graphs

---

pinc/DPage.inc

While testing Ray's proofreading API PR I saw some weird string layouts in some of the exception messages, this fixes them. Interestingly because we output these in HTML it almost doesn't change the format from the web-perspective because all of the whitespace collapses together but it really improves them from the API perspective.
You can see one of them with: https://www.pgdp.org/~cpeel/c.branch/remove-error-formatting/tools/proofers/proof.php?projectid=projectID4c49f39aa829c&imagefile=190.png&proj_state=F1.proj_avail&page_state=F1.page_avail

Remove layout in page exception messages

---

pinc/theme.inc
styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Make the icon texts into links too. Right now they _look_ like they're links because we change the cursor to a pointer when you hover over them, but clicking them doesn't do anything. Make them actual links to increase their active area.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/wider-icon-links/

Make icon texts links too

---

api/v1_projects.inc

c9fc66620 introduced error reporting if the user requests to render a project field that doesn't exist, eg with `api/v1/projects?field[]=no_such_field`.
The refactoring to do this accidentally left the queryable attribute off the `state` field (and only that field!), and we had no error reporting to warn the user they were searching on unqueryable fields, so, eg, `api/v1/projects?state=P3.proj_avail` would silently ignore the `state` query term and would return all projects.
1. Make `state` work again. (Should there be a hat for this?)
2. Add error reporting on unrecognized query keys, eg `api/v1/projects?eligible_for_bulwer_lytton=yes`, which would have exposed this.

api/v1/projects: Fix project search bug, improve error reporting

---

SETUP/INSTALL.md
SETUP/configuration.sh
composer.json
composer.lock
locale/translators/index.php
pinc/POFile.inc
pinc/site_vars.php.template

xgettext has a nasty bug where it doesn't understand the PHP 7.3+ heredocs where the closing string is indented. This causes xgettext to skip the entire rest of the document. Replace it with xtext.
Because we use xtext in prod, not just during development, we need to require nikic/php-parser explicitly as a non-dev package.
We're able to use xtext like this because we pushed several feature enhancements up stream and the xtext developer has been superbly responsive to our requests!
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-xgettext/

Use xtext from vertilia/text to extract strings

---

pinc/site_news.inc

As requested by the GM (and frankly just makes sense).
Contrast the AH in the sandbox: https://www.pgdp.org/~cpeel/c.branch/global-news-first/activity_hub.php
With the main TEST code: https://www.pgdp.org/c/activity_hub.php

Sort GLOBAL news items first

---

stats/members/mbr_list.php
stats/stats_central.php

Also make the field name 'username' to match the rest of the site.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/no-autocap-user-stats/

Don't autocap usernames in stats searches

---

project.php

_Note: this is going into `pgdp-production`._
PP artifacts that were generated before the Unicode conversion still have their contents in Latin-1. There aren't many of these but we periodically stumble over some that are reclaimed.
Luckily, we just so happen to have have a project in TEST in this state: https://www.pgdp.org/~cpeel/c.branch/pgdp-warn-old-pp-artifacts/project.php?id=projectID44dda73a86096&expected_state=proj_post_first_available

Issue warning if the project CTF was generated pre-Unicode

---

pinc/forum_interface_json.inc
pinc/forum_interface_phpbb3.inc
pinc/theme.inc
scripts/navbar_menu.js
styles/global.less
styles/layout.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/site_search.php

This adds a new "site search" page. Users can either click on the search icon in the header or use the `/` hotkey in any non-input field on a site page. This has been available for public preview & discussion in the [New site search feature](https://www.pgdp.net/phpBB3/viewtopic.php?f=4&t=81458) forum.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/site-search/

Add new "site search" page

---

pinc/graph_data.inc
pinc/page_tally.inc
stats/misc_stats1.php

Part of solving https://github.com/DistributedProofreaders/dproofreaders/issues/1190 is going to be decreasing the number of instances where we directly query `past_tallies` where the caller assumes that it has entries for every single day. This PR removes one of the offenders used only in the statistics code. It pulls the DB-ness into a function. Right now that function just queries `past_tallies` directly, but in a future revision it will encode more logic to handle the transition to a sparse format.
This has two functional changes:
* `misc_stats1.php` (what a terrible name for a file, BTW) no longer outputs the top 10 proofreading days this year and it no longer outputs the days above certain thresholds. Supporting these two use-cases required more work for what I think is a pretty …

Remove select_from_site_past_tallies_and_goals()

---

pinc/html_page_common.inc
pinc/theme.inc
scripts/navbar_menu.js

Don't include the navbar JS when there is no navbar. In addition add some checks to see if the search menu exists before adding listeners for it. A slightly different approach than Ray's https://github.com/DistributedProofreaders/dproofreaders/pull/1193. Diff best viewed ignoring whitespace.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-navbar-js-error/
Testing notes: The new search menu should still function. On page without a header, like the Image Browser, there should be no error in the JS console.

Don't include navbar JS if there's no navbar

---

project.php

Users who are not logged in can't see project character suite details, so we shouldn't show them the rows for it. And they also don't need to know if the project isn't in UTF-8. Diff is best viewed ignoring whitespace.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/hide-charsuites-for-nonusers/
Logged out, compare
* [A project on TEST](https://www.pgdp.org/c/project.php?id=projectID4c49f39aa829c)
* [A project in the sandbox](https://www.pgdp.org/~cpeel/c.branch/hide-charsuites-for-nonusers/project.php?id=projectID4c49f39aa829c)

Hide errors and charsuites from non-users

---

pinc/TallyBoard.inc
pinc/graph_data.inc
pinc/page_tally.inc

This is, frankly, embarrassing.
The thing that takes _so long_ to generate the stats graphs is calculating the moving average due to some complex SQL that joins `past_tallies` against itself. If we calculate the SMA in the code it's more than 10x faster on TEST -- probably even faster on PROD. It also removes another direct use of `past_tallies` which is needed for moving to the future sparse format.
Note that the old code only generated integer-based averages (I don't know why) whereas the new one will generate floating point averages, so the graphs will look slightly different.
Compare:
* https://www.pgdp.org/c/stats/pages_proofed_graphs.php?tally_name=P1
* https://www.pgdp.org/~cpeel/c.branch/improve-sma/stats/pages_proofed_graphs.php?tally_name=P1
Both of the above have graph caching …

Improve performance of calculating moving average

---

pinc/theme.inc

The GM has requested that we put the total completed projects in the sidebar (since it is no longer in the header). This also reversed the months so the most recent one is up top.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/add-completed-number-to-sidebar/

Add the total completed to the sidebar

---

SETUP/tests/ProjectTest.php
phpstan.neon
pinc/Activity.inc
pinc/LPage.inc
pinc/Pool.inc
pinc/Project.inc
pinc/ProjectSearchForm.inc
pinc/ProjectSearchResults.inc
pinc/ProjectSearchResultsConfig.inc
pinc/ProjectTransition.inc
pinc/Round.inc
pinc/Stage.inc
pinc/TallyBoard.inc
pinc/filter_project_list.inc
pinc/page_tally.inc
tools/project_manager/add_files.php
tools/project_manager/edit_project_word_lists.php
tools/project_manager/editproject.php
tools/proofers/PPage.inc

Cherry picking the remainder of the class property declarations from #1112 so they can be submitted separately.
There were lots of merge conflicts doing this, so it turned out to be easier to cherry pick everything into a new PR. I'll close #1112.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/property-2/ (changed to cpeel's sandbox to pick up a small fix)

Add many property declarations to classes so PHPStan can type check, part 2

---

SETUP/tests/ApiTest.php
SETUP/tests/ProjectUtils.inc
api/dp-openapi.yaml
api/exceptions.inc
api/v1.inc
api/v1_projects.inc
api/v1_validators.inc
pinc/DPage.inc
pinc/Project.inc
pinc/ProofProject.inc
pinc/User.inc
project.php
tools/proofers/processtext.php

Sandbox at: https://www.pgdp.org/~rp31/c.branch/proof_api_10

Proofreading api with single page checkout

---

pinc/ProjectSearchResults.inc

All projects should have a valid genre. However, if for some reason they don't we still want them to show up in the project search.
On TEST, the following two projects do not have a genre and don't currently show up in a project search:
* projectID47ffb9bbb5139
* projectID61e639e687114
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-project-search-no-genre/

Return projects without genres in search

---

SETUP/db_schema.sql
SETUP/upgrade/21/20240101_drop_marc_records.php
pinc/Project.inc
pinc/archiving.inc
tools/project_manager/editproject.php

The reason why Dublin Core (`dc.xml`) files were originally created is unclear. Users (PMs, PPs, and squirrels) currently use them when managing project directory contents to make sure they are in the right place. Replace them with the `metadata.json` files we already generate during archiving.
This allows us to stop storing and managing MARC records in the database. We could have opted to just have the `dc.xml` file be updated from the project table rather than the MARC record (we only pull 2 fields from it), but we are already generating the `metadata.json` file during archiving and there doesn't seem to be a good reason to keep both.
This code does not proactively create `metadata.json` files for existing projects until they are edited (or archived), nor does it remove any existing …

Replace dc.xml with metadata.json and drop marc_records

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md

Bump the minimum version of MySQL we support to 8.0 (we let folks know about this upcoming change in the [last changelog](https://github.com/DistributedProofreaders/dproofreaders/blob/master/SETUP/CHANGELOG.md#notices--deprecations)).
And give a notice that the next release will be the last to run on PHP 7.4. When we upgrade TEST and PROD we'll be running 8.3 but I don't expect we'll be intentionally using anything that requires 8.3 while I know we'll be using things that require 8.0.

Update minimum MySQL version and future PHP version

---

.github/actions/setup-mysql-db/action.yml
SETUP/smoketests/test_tables.sql
SETUP/tests/ci_configuration.sh
SETUP/tests/phpunit_bootstrap.php
pinc/DPDatabase.inc

When running unit tests, run them against a test DB instead of the real DB. This doesn't impact the CI at all, but does help when running unit tests on the TEST server. While the tests try to clean up after themselves, it's impossible to do so cleanly, for instance the crazy high round page counts.
One downside to this approach on TEST is that its possible the databases will drift. It's easy enough to drop and recreate the database however if the unit tests fail because of said drift.

Ensure unittests are run against a test-only DB

---

phpstan.neon
pinc/ProjectSearchForm.inc
pinc/ProjectSearchResultsConfig.inc

To do this:
1. Make class Selector abstract as it already implicitly is and add the abstract method declaration it needs.
2. Fix OptionSelector::get_html_control() to return a string to make it consistent with the other get_html_control()s, The `echo`s in this method accidentally worked before now because of the use of `echo "foo", get_html_control(), "bar"` in Selector and PHP happening to evaluate the arguments to `echo` (and their side effects) in left-to-right order.
There's a sandbox to test this at https://www.pgdp.org/~bfoley/c.branch/invalid-fn/
The code in question affects all the widgets on the project search page, in particular the popup menus under 'Configure Result'; the checkboxes, and the lists such as Language, Special Day, State.

phpstan: Fix "Call to an undefined method" error (and re-enable)

---

SETUP/tests/ApiTest.php
SETUP/tests/ProjectUtils.inc
SETUP/tests/phpunit_test_helpers.inc

Explicitly give the test user access to P1. This resolves unit tests in the `pgdp-production` branch where P1 requires passing a quiz first. This also means we can remove the skip for `ProjectTest->test_can_be_proofed_available()` in that branch as it will now pass.

Explicitly give test user access to P1

---

pinc/Project.inc

Editing project information can happen even if the project directory doesn't exist (the project has been deleted or archived). In those cases, just don't generate the `metadata.json` file instead of failing.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-edit-deleted-project/

Don't die if metadata.json creation fails

---

api/USERS_GUIDE.md

Update the API User's Guide to include examples for the proofreading endpoints. These examples are from my comment on the PR https://github.com/DistributedProofreaders/dproofreaders/pull/975#pullrequestreview-2026258337

Add proofreading API examples to the user's guide

---

pinc/Activity.inc
pinc/DPDatabase.inc
pinc/gradual.inc

To investigate something else I added a DB tracing feature to optionally output SQL queries and their callers to a log file (commit 1). During that investigation I discovered that we're doing the same query against `quiz_passes` table and `current_tallies` multiple times in a page load. I traced that back to the `Activity->user_access()` call.
This PR removes a redundant call in `gradual.inc` (this is the second time we load that object in the function -- see line 335) and adds a small cache within `Activity->user_access()` for the user score. The cache removes 20 DB queries on each of the round pages and Activity Hub. The queries are fast but add unnecessary load to the DB for data we literally just asked for microseconds before.
Sandbox: …

Reduce the overhead of Activity->user_access() calls

---

SETUP/smoketests/pageload_smoketest.py
pinc/Activity.inc
pinc/Project.inc
pinc/ProjectState.inc
pinc/ProjectTransition.inc
pinc/ThemedTable.inc
pinc/archiving.inc
pinc/bad_bytes.inc
pinc/button_defs.inc
pinc/graph_data.inc
pinc/languages.inc
pinc/privacy.inc
pinc/upload_file.inc
pinc/user_project_info.inc
pinc/wordcheck_engine.inc
quiz/generic/quiz_page.inc
tools/project_manager/post_files.inc
tools/proofers/proof_frame.inc

`die()`s in functions are a Very Bad Idea because there's no way for callers to capture and do something about the error. They also can cause silent failures by exiting the page without anyone else knowing. This replaces `die()`s in our include files with exceptions. This does not replace `die()`s in non-include files. This shouldn't need a lot of (any?) testing as `die()`s are effectively the same as thrown exceptions from a "stop the world" perspective.
Also replace an `assert()` that should always be checked. Asserts are only for dev & test and in "production" mode the code within them is not generated or evaluated at all. See https://www.php.net/manual/en/function.assert.php
Sandbox: https://www.pgdp.org/~cpeel/c.branch/die-die-and-asserts/

Replace die()s with exceptions and fix an assert

---

.php-cs-fixer.dist.php
composer.json
composer.lock

After a looong review process and a couple of fast followup fixes, this introduces parallel linting.
On an M2 MacBook Pro (using 12 cores) lint times go from 16.5s to 2.1s.
On TEST (using 2 cores on a very underpowered AWS instance) lint times go from 16.8s to 15.6s.
This speeds up CI tests on GitHub somewhat (unscientifically a before and after CI run goes from ~85s to ~55s), and as long as it doesn't break anyone's development workflow, shouldn't need any additional testing.

Update php-cs-fixer to 3.57.1

---

pinc/theme.inc
styles/layout.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tasks.php
tools/site_search.php

Refine the new site search experience after input from users. In brief, this:
* Removes the "jump to username" feature if the string is a username, now this needs to be prefixed with `u:`.
* Adds an icon to the search menu to get to the site search help page
* If no prefix was used the search page now lists suggestions to help the user (thanks @windymilla for this suggestion)
* Enables searching for a task by summary in addition to string (thanks @srjfoo for the suggestion)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/refine-site-search/
Forum discussion: https://www.pgdp.net/phpBB3/viewtopic.php?t=81458

Refine site search based on user feedback

---

pinc/CharacterSelector.inc
styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css
tools/proofers/character_selector.js

This enables diacritical marks for polytonic greek to appear correctly in the character picker.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/picker_indent

change character picker text-align to right

---

pinc/archiving.inc

Reduce the post-archiving sleep to only 1x the time the archiving took instead of 6x. This should reduce the clock time of the nightly archive by 5x allowing us to free up the connection sooner and possibly reduce the Apache TimeOut down.

Reduce archiving delay to 1x

---

SETUP/check_db_schema.template
SETUP/db_schema.sql
SETUP/upgrade/21/20240414_update_current_tallies.php
SETUP/upgrade/21/20240420_sparsify_past_tallies.php
pinc/TallyBoard.inc
pinc/page_tally.inc

_Background pulled from #1190_
The `past_tallies` table stores historical round, user, and team statistics (`current_tallies` stores the current day's statistics) including the number of pages done that day (`tally_delta`). Once a day the site takes a snapshot of `current_tallies`, calculates the delta since the last snapshot, and adds a row in the `past_tallies` table for every `[tally_type, tally_name, holder_id]` tuple.
After a user has done a page in a round, they have an entry for that round in `current_tallies` and the site adds a new record in `past_tallies` for that user/round in every daily snapshot going forward. Said another way: we keep daily records of every user that has touched a round forever, even if they never proofread another page.
At pgdp.net, 24 years of this has …

Make past_tallies a sparse table

---

SETUP/db_schema.sql
SETUP/upgrade/21/20240611_update_job_logs.php
pinc/job_log.inc
tools/project_manager/automodify.php
tools/site_admin/index.php
tools/site_admin/show_job_log.php

Did you know we have a job log? Me neither! That's because we currently log to it in exactly two scripts and have zero way to view it. This gives SAs the ability to see the table and adds an index on the timestamp.
It removes a useless "MIDDLE" message from automodify.
https://www.pgdp.org/~cpeel/c.branch/job-log-visibilitiy/
This is related to https://github.com/DistributedProofreaders/dproofreaders/issues/1233

Add job log visibilitiy

---

tools/proofers/my_projects.php

If a user doesn't have access to proofread in any round, such as if they are a new user on PROD and have not passed the P1 quiz, we need to still construct a valid SQL.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/my-proj-avail-new-users/

Update SQL for Available tab for no-access users

---

SETUP/upgrade/21/20240420_sparsify_past_tallies.php

Turns out that if you don't reset the Stopwatch it keeps accumulating time making each subsequent sleep of the sparsify loop longer. This fixes that and also updates the status output to be more verbose. These are updates after adjusting the script running on PROD.

Fix stopwatch in upgrade script and adjust progress

---

tools/project_manager/autorelease.inc

During automodify we create a temporary table for each round, populate it, query against it joining on `projectid`, and then delete it. This creates the table with an index so the join doesn't have to do a table scan for every evaluation.
Can confirm this works by comparing the automodify log output in the sandbox to that on TEST as there should be no functional change.
* Sandbox: https://www.pgdp.org/~cpeel/c.branch/index-temp-table/tools/project_manager/automodify.php
* TEST: https://www.pgdp.org/c/tools/project_manager/automodify.php

Add primary key to temp table

---

default.php
pinc/list_projects.inc
pinc/showstartexts.inc

The home page gets queried a lot by crawlers and other non-users, cache star and user counts to decrease DB overhead for these non-critical "flavor" metrics.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/make-default-efficient/

Cache count contents for home page

---

list_etexts.php
pinc/list_projects.inc
pinc/theme.inc

`list_etexts.php` is one of the few public pages (does not require login to access) and its worth trying to decrease the system overhead for it. This PR does the following:
1. optimizes the SQL used to generate the page by:
* removing 1 of the 2 queries and using a 1-hour cached value for total number of projects per star metal
* simplifying the query for the silver and bronze stars
2. removing the sorting options on the page -- this reduces the links crawlers can hit that just generate more load and removes a feature that I don't think is really all that useful to humans.
While we're here increase the default page size to 50 from 20. This is likely more useful to users without changing the impact to the query.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/decrease-list_etexts-overhead/lis …

Decrease list_etexts.php overhead

---

pinc/User.inc
pinc/UserProfile.inc
tools/proofers/processtext.php
userprefs.php

In order to have proper PHPStan coverage, first
annotated the return value from User::load_current()
then added User type annotation to userprefs.php.
This uncovered 2 missing properties on Users (`profile`
and `navbar_activity_menu`) and some fields on `UserProfile`
that were typed as `bool` but should have been `int`.
Manually tested updating a user's prefs and changing
the layout during proofing.

Add User annotation for arguments in userprefs.php

---

SETUP/dp.cron.template
crontab/PruneJobLogs.inc
pinc/job_log.inc

The `job_logs` table stores when jobs run and is primarily `automodify.php` right now. It currently grows unbounded and we have 20 years of data. There's no real use in keeping it for that long though. At best being able to see how long something took to run a year ago seems generous. We could probably even get away with just a month of data.
This PR takes a generous view and just saves the past 13 months of data. 13 months is better than 20 years.
Aside: it was awesome how easy it was to create a new background job with the new class, so much boilerplate gone!

Prune job logs -- keep 13 months worth

---

crontab/ImportPGCatalog.inc

`noncvs/in_progress_check.php` uses a text-based catalog file. The script currently relies on the extracted RDF files that I removed in the new crontab file to create the file. Instead, create the file when we're parsing the catalog the first time. Because nothing in the main code uses this file, this commit is in `pgdp-production`.

Create a text PG catalog for noncvs/in_progress_check.php

---

pinc/page_tally.inc

For the user (and team) "lifetime" stats graphs, it's more useful to show them starting at the first non-zero entry -- that is the day with the first page -- rather than the beginning of when stats were collected. This is a regression from what they showed before the sparse `past_tallies`.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/start-user-stats-at-first-data/

Start user lifetime graphs at first non-zero value

---

scripts/control_bar.js
scripts/page_browse.js
scripts/view_splitter.js
tools/proofers/proof_image.js

This allows the image to scroll to halfway across the image to left and right and 80% of the way upwards.
These amounts could be changed and it could be made to work differently for vertical and horizontal layouts.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/image_overscroll

Allow image to scroll beyond edges

---

SETUP/db_schema.sql
SETUP/upgrade/21/20240620_update_wordcheck_events.php
pinc/wordcheck_engine.inc
tools/proofers/processtext.php

Every time someone submits a correction in WordCheck, in the record of the event itself we write the corrected text to the `corrections` column in the `wordcheck_events` table. They look like this:
```
[-Laman-] {+Lamán+}
[-Komarov-] {+Komaróv+}
[-pubHcist-] {+publicist+}
[-Vyazemsky-] {+Vyázemsky+}
```
But we never use it. Ever. Nor have we ever used it. At some point (circa 2007) we thought that data might come in handy for some analysis later but here we are ~17 years later and nada.
This PR:
1. stops collecting the data
2. includes an upgrade script to drop the column
Before we drop the column from PROD I intend to do write a dump of this SQL query to a file in some structured format:
```sql
select projectid, image, round_id, corrections from wordcheck_events where corrections <> ""; …
```

Stop logging WordCheck corrections

---

pinc/job_log.inc
pinc/theme.inc

Background job failures are pretty rare, but when they happen we want people to know about them. When background jobs fail, cron sends an email with the failure code. But we should also let SAs know in case the emails go awry. This adds a notice to the alert bar _only for SAs_ if there was a job failure in the last 24 hours. The query is fully covered by an index so it is both fast and efficient.
The downside is that there is no way to dismiss the bar, we just have to wait for it to age out.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/jobs-0-alert-sa-on-job-fail/
I've inserted a demo failed job so the alert will show for the next 24 hours.

Alert SAs on background job failures

---

pinc/showavailablebooks.inc

In rare cases if a user has passed 20 pages and set a filter, then returns pages to the round, they won't see the filter selection but their filters will be used which will lead to confusion. Only use a project filter if the user can see the filter and change it.
@srjfoo found this on TEST which is most likely bad data, but there's no reason not to fix it.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/filter-fixin/

Only use filters if we show the controls

---

pinc/Settings.inc
tools/site_admin/manage_site_access_privileges.php

The manipulated types were pretty clear
so this should be safe.
Manually tested the change by adding,
removing and loading some privileges.
_Update by cpeel_: Sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_type_site_admin_manage_privileges/

Type manage_site_access_privileges.php

---

crontab/CleanUploadsTrash.inc
crontab/run_background_job.php
pinc/BackgroundJob.inc
tools/site_admin/show_job_log.php

Last night's run of CleanUploadsTrash reported success in `job_logs` but the CLI (and cron) thought it failed. I don't know exactly why but in looking at it I've added some things to help us diagnose it in the future.
Until an HTTP stream returns some byte of data, the connection hasn't succeeded. And until the stream connects we can't get any useful metadata about it, such as if it timed out. This changes the web proxy code to flush out the HTTP headers as quickly as possible while the job runs, allowing us to better detect timeouts and handle other error conditions.
As part of this, adjust the clean up job to more gracefully handle the case where the TRASH folder doesn't exist, as the cleanup job will delete it if the folder has no contents (and Remote File Manager will create it again …

Adjust background job web proxy error detection

---

stats/misc_stats1.php

On the (horribly named) `misc_stats1.php` page, the adhoc graph at top was pulling up to and including the midnight of the next month which has non-zero goals but zero stats. The easy fix for this is to make the end date given by the user inclusive so we just get up to the last day of the given month. This doesn't prevent the graph from showing a zero value for future months, but it fixes the most common case.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-misc-stats-graph/stats/misc_stats1.php?tally_name=P1

Fix misc stats graph by making end date inclusive

---

pinc/User.inc
pinc/gradual.inc
tools/proofers/my_suggestions.php

I avoided a few types that I couldn't trace
back enough so would prefer to send them in
a separate PR.
Manually tested the activity hub &
my_suggestions to confirm that the new
user's banner is shown as expected.
_Updated by cpeel_: Sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_type_gradual_php/

Type pinc/gradual.inc

---

crontab/ImportPGCatalog.inc

This job hit a memory limit on PROD last night, so make it more memory efficient by just adding books as we process them instead of building an in-memory list and adding them all at the end.
```
$ php run_background_job.php ImportPGCatalog true
Background job: ImportPGCatalog
Succeeded: true
Message: Processed 73877 etexts
Output:
Downloading https://www.gutenberg.org/cache/epub/feeds/rdf-files.tar.bz2 to /tmp/pg-catalog-files/rdf-files.tar.bz2...
Extracting files from /tmp/pg-catalog-files/rdf-files.tar.bz2 to /tmp/pg-catalog-files...
Scanning files in /tmp/pg-catalog-files...
Finished processing 73877 RDF files.
Warning: The following MIME types do not have entries in $display_mapping:
11 application/x-musescore
```

Reduce memory usage of ImportPGCatalog job

---

README.md
SETUP/DEVELOPMENT.md
styles/README.md

It's a bit of a brain dump but here's my first pass at adding more useful development docs to the repo. A reminder that the markdown files can be viewed rendered in the [update-dev-docs branch directly](https://github.com/cpeel/dproofreaders/tree/update-dev-docs?tab=readme-ov-file).
To review this, my request is that you come at the updates with "fresh" eyes and think what other questions you might have as a new person interested in developing that this doesn't answer but should.

Beef up development documentation

---

phpstan.neon

This level gives us type coverage on arguments.
To ease the transition, the baseline that
corresponds to the current errors was added
to `phpstan.neon`. Due to our CI using PHP8.3
and prod/developers using PHP7.4, I have added
the baseline for both versions.
Some common, low-value exceptions were also
added to prevent having a large list of
individual errors.

Switch to PHPStan to level 5

---

.gitignore
SETUP/DEVELOPMENT.md
SETUP/ci/Makefile
SETUP/ci/check_includes.php
SETUP/ci/check_require_login.php
SETUP/ci/check_security.sh
SETUP/ci/lint_php_files.sh
phpstan.neon

Add phpstan to our ci Makefile and give instructions on how to run the static checks as part of our dev docs. I needed to update the phpstan temp directory such that it worked on TEST which is a shared dev environment.
FYI @mrducky4 & @jchaffraix

Include how to run static checks in dev docs

---

locale/debug_ui_language.php
locale/translators/index.php
pinc/base.inc
pinc/button_defs.inc
pinc/gettext_setup.inc
pinc/html_page_common.inc
pinc/languages.inc
pinc/misc.inc
pinc/phpbb3.inc
pinc/site_vars.php.template
pinc/wordcheck_engine.inc
project.php
stats/members/mbr_xml.php
stats/teams/teams_xml.php
tools/authors/authorxml.php
tools/authors/bioxml.php
tools/changestate.php
tools/proofers/spellcheck_text.inc
tools/site_admin/manage_site_word_lists.php

The site has been UTF-8-only since 2020, this just removes the `$charset` global variable. Should be zero functional change.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/prune-charset/

Remove $charset global

---

activity_hub.php
phpstan.neon
pinc/Activity.inc
pinc/Pool.inc
pinc/Project.inc
pinc/Stage.inc
pinc/stages.inc
pinc/theme.inc
sitemap.php
stats/includes/member.inc
stats/includes/team.inc
stats/members/mbr_list.php
stats/misc_stats1.php
stats/pp_stage_goal.php
stats/teams/teams_xml.php
tasks.php
tools/post_proofers/ppv_report.php
tools/site_admin/edit_mail_address_for_non_activated_user.php

There were 3 major errors:
- int fields from the DB that are returned as string by mysqli.
- date('s|d|y|U') that returns an int as a string.
- PHP float truncating functions that returns a float.
_Update by cpeel_: Sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_fix_int_to_str_conv/

Fix string|float-to-int convertion errors

---

faq/wordcheck_data.php
pinc/ProjectSearchForm.inc
pinc/filter_project_list.inc
pinc/iso_lang_list.inc
tools/project_manager/edit_common.inc

We give PMs a stupidly long list of languages when creating projects, but only a few of them have dictionaries installed for WordCheck. Give PMs information about which languages have dictionaries installed when creating and editing projects.
This also removes the duplicate entries in the `get_iso_language_list()` return and for the places where order matters (filters and project search form) we show the list of languages with dictionaries first then everything else. This means that English is no longer at the very top, but it's only a few down so that seems reasonable.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/warn-pms-about-wordcheck-dicts/

Give PMs info on languages without dictionaries

---

composer.json
composer.lock
crontab/ImportPGCatalog.inc
pinc/wordcheck_engine.inc

Symfony's Process class handles shell escaping and other niceties like stdin/stdout redirection. This instance fixes the issue where we can't tell if the aspell process completed successfully and didn't find anything misspelled or if it errored out.
This was identified in the newly spun up `clone.pgdp.net` instance because `shell_exec()` returned NULL and we passed that into `explode()` and that's now deprecated in PHP 8.1. Moving to `Process()` is an overall Good Thing and we should do it across the codebase. I'll create an issue.
I've done ImportPGCatalog as an example which doesn't use stdin.
Sandbox available at https://www.pgdp.org/~cpeel/c.branch/use-symfony-process/

Install and use Symfony Process for system calls

---

accounts/activate.php
tools/authors/manage.php
tools/project_manager/manage_image_sources.php

Those are covered by a general exception for int-to-string conversions in `phpstan.neon` so
were found by temporarily disabling it. That's also why there is no progression from PHPStan's perspective.

Remove unneeded calls to DPDatabase::escape()

---

SETUP/db_schema.sql
SETUP/upgrade/21/20240712_update_special_days.php
tools/site_admin/manage_special_days.php

Several fields are actually required and we should make them so on the input form. Also update the database schema to remove nulls and adjust the class to match -- it doesn't make any sense why the DB schema was like it was.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/wrangle-special-days/

Wrangle special_days management page

---

tools/proofers/processtext.php
tools/proofers/proof_frame.inc
tools/proofers/proof_frame_enh.inc
tools/proofers/spellcheck_text.inc
tools/proofers/text_frame_std.inc

Manually tested the different buttons in the proofer's interface. Also confirmed that we could add a word to the good/bad list.
_Update by cpeel_: sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_type_wordcheck/

Type tools/proofers/processtext.php and callees

---

SETUP/tests/unittests/ParamValidatorTest.php
pinc/misc.inc

Add a validation function to return a bool from various sensible "truthy" and "falsey" values. This isn't used anywhere but I think it will come in handy based on recent type declaration PRs. It even comes with unit tests!

Add get_bool_param() validation function

---

SETUP/ci/check_security.php
tools/proofers/spellcheck_text.inc
tools/site_admin/sitenews.php

I made some errors when adding comments for PHPStan.
The main one is that we must be using PHPDoc's format (/** @param type param_name */) or else those are
ignored by PHPStan.
This exposed a bad array syntax in
tools/proofers/spellcheck_text.inc that got fixed.

Fix comments for PHPStan

---

SETUP/tests/smoketests/pageload_smoketest.py
accounts/login.php
locale/translators/index.php
pinc/metarefresh.inc
stats/teams/new_team.php
stats/teams/tedit.php
tasks.php
tools/changestate.php
tools/project_manager/edit_project_word_lists.php
tools/project_manager/editproject.php
tools/project_manager/word_freq_table.inc
tools/proofers/processtext.php
tools/setlangcookie.php
userprefs.php

Last night's php_errors report showed some notices after someone was poking around in `tools/setlangcookie.php`. This addresses a few of them by tightening up param validation and enforcing param types in `metarefresh()`. I vetted the param types of every `metarefresh()` call in the code with this change and cleaned up a few optional parameters on some of the calls while I was there.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/better_param_vetting/

Better setlangcookie param validation

---

SETUP/configuration.sh
SETUP/tests/unittests/RoundTest.php
phpstan.neon
pinc/Project.inc
pinc/ProjectState.inc
pinc/ProjectTransition.inc
pinc/forum_interface_json.inc
pinc/forum_interface_phpbb3.inc
pinc/site_vars.php.template

The types are inferred from the usage.
This showed some inconsistencies in `get_forum`'s return that was noted but not fixed to prevent regressions.
Manually tested some transitions and creating a post associated with a new project in PHPBB.
_Update by cpeel:_ sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_type_ProjectState/

Type pinc/ProjectState.inc

---

userprefs.php

The untyped functions in userprefs.php
were related to displaying individual
preference to the user.
The PR worked around the current logic
that invokes a specific function based on
the type of the preference to show the user
(e.g. a font selection dropdown or a textfield).
This means that we added some wide type for
now and may revisit this in the future.
Tested the PR by displaying and changing
some user prefs.
_Update by cpeel_: sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_fulltype_userprefs/

Fully type userprefs.php

---

pinc/User.inc
pinc/UserProfile.inc

The types were inferred from usage.
Also added an explicit integer cast on the
`profile` cookie as the comment mentioned
it was an ID.
_Edit by srjfoo_: Sandbox at https://www.pgdp.org/~srjfoo/c.branch/julien_fully_type_UserProfile/

Fully type pinc/UserProfile.inc

---

pinc/base.inc
tools/authors/add.php
tools/authors/manage.php
tools/proofers/processtext.php
userprefs.php

This adds an explicit [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) beyond preventing other sites from embedding our code in frames/iframes. This isn't a very high bar since we still allow inline JS and CSS but it is a small step in the right direction since we now disallow unsafe-evals.
The new CSP should let everything else work, including:
* the use of MathJAX in Format Preview
* the use of JS to manipulate CSS (used in Format Preview)
* the use of images from anywhere in project comments
The following pages were updated to remove unsafe evals:
* https://www.pgdp.org/~cpeel/c.branch/explicit-csp/tools/authors/manage.php
* https://www.pgdp.org/~cpeel/c.branch/explicit-csp/userprefs.php
* Leaving the proofreading interface …

Add an explicit Content Security Policy (CSP)

---

userprefs.php

This fixes an edgecase where a user tries to select the current profile but since the field is disabled the submit results in an error. Fixes the error @srjfoo discovered testing https://github.com/DistributedProofreaders/dproofreaders/pull/1293
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-profile-switching-error/

Allow selecting existing profile

---

pinc/misc.inc
tools/project_manager/edit_common.inc
tools/project_manager/editproject.php

Sometimes we just want to do basic type validation and return a param of that type. We already accept null values for these, so make them optional. This implements what @jchaffraix suggested in https://github.com/DistributedProofreaders/dproofreaders/pull/1292 -- which is obvious in retrospect but it took me thinking about it post-merge to see it.
Note that this means that `get_{type}_param($array, $key)` must return a value of that type and not null since `$default=null` and `$allownull=false`. This makes sense to me.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/relax-type-getters/

Relax get_(integer|float|bool)_param() definitions

---

crontab/run_background_job.php
tools/project_manager/remote_file_manager.php
tools/upload_text.php

`apache_setenv()` is only available if we're running PHP under `mod_php`. It isn't available if we're using php-fpm. Simply test if the function exists before using it. While we're here, disable brotli compression too.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/conditionalize-apache_setenv/

Don't assume we're running under `mod_php`

---

SETUP/ci/check_security.php
crontab/CleanUploadsTrash.inc
locale/translators/index.php

I tested in the development VM.
I tested the translators change from the Translation Center page, as an admin, deleted the locale is_IS and verified the files and directories were actually deleted.
I tested the clean uploads trash job with `run_background_job.php CleanUploadsTrash` and verified it deletes TRASH/... files older than 30 days and deletes empty folders.
_Update by cpeel_: Sandbox avail at https://www.pgdp.org/~cpeel/c.branch/process_class/

Partial fix for issue #1274, converting exec() to Process()

---

pinc/page_table.inc
project.php
scripts/page_table.js
tools/project_manager/edit_pages.php
tools/project_manager/page_detail.php

contribution to issue #1298 
Sandbox at: https://www.pgdp.org/~rp31/c.branch/unscript_project

remove <script> from page_table.inc

---

pinc/ProjectSearchResults.inc
tools/project_manager/manage_image_sources.php
tools/site_admin/manage_special_days.php

We have 3 `make_link()` functions in the codebase, one each in:
* `ProjectSearchResults.inc`
* `manage_special_days.php`
* `manage_image_sources.php`
For the last two scripts, one of them was very likely created as a copy of the other in the distant past.
Recently type definitions were added for the one in `manage_special_days.php` and for some users phpstan is getting confused with having duplicate names that accept different types. Even though these functions are never defined concurrently in a single page scope, phpstan doesn't know this and having duplicate function names (without namespaces) is a bad practice anyway.
This:
1. removes the two functions in the `manage_*.php` functions as they really aren't needed.
2. renames some functions in `ProjectSearchResults.inc` to be less …

Resolve duplicate -- and different -- `make_link()` functions

---

pinc/theme.inc
scripts/navbar_menu.js

Sandbox at: https://www.pgdp.org/~rp31/c.branch/alt_theme_script
There are some considerations regarding the icon links: It was necessary to use the url "#" for the search to prevent the page from refreshing and immediately removing the search box. This apparently does not happen if "onclick" is present. This is mentioned in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#onclick_events. Using an anchor in this way it is possible to right-click and attempt to open the search in a new tab which does not work (same for present version).
As discussed on the mozilla page, ideally a button should be used for this purpose. I tried this earlier but it presents a different appearance which could probably be fixed by styling. I also tried (in the earlier PR) using a 'div'. This does …

remove scripts from theme.inc (simpified version)

---

SETUP/ci/Makefile
SETUP/ci/check_includes.php
SETUP/ci/check_require_login.php
SETUP/ci/check_security.php
SETUP/ci/lint_json_files.sh
SETUP/ci/lint_php_files.sh

This adds PHP and JS style checks and JS linting to the Makefile for devs to easily run them locally. I've updated the check scripts to be less verbose while still reporting progress as they go. The CI does not use the Makefile directly but it does use the `SETUP/ci/*` scripts.

Add style checks & JS linting to Makefile

---

pinc/base.inc

Exceptions are errors so format them with our standard error styling. Exceptions that are thrown before the stylesheets are included won't have this, but it won't hurt either.
When `$testing`, include the same output as PROD in addition to a formatted stacktrace.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/update-exception-handlers/

Better format HTML exception handlers

---

tools/site_admin/copy_pages.php
tools/site_admin/delete_pages.php
tools/site_admin/project_jump.php

This fixes 3 of the 5 scripts in `tools/site_admin/` that have duplicate function names (see https://github.com/DistributedProofreaders/dproofreaders/issues/1307). The functions now also have typing.
* `copy_pages.php`
* `delete_pages.php`
* `project_jump.php`
Sandbox: https://www.pgdp.org/~cpeel/c.branch/uniquify-site-admin-func-names/

Make site admin function names unique

---

tools/proofers/text_data_processor.js

Smart punctuation list in the characteMap should include horizontal ellipsis. First noticed in the quizzes, and not discovered before, because by the time new proofers using iPads got that far, they'd switched off smart punctuation, until recently.
If anyone can think of anything that might be considered part of that set of characters that Apple considers to be "Smart punctuation", I'm happy to add it, but the only one I could think of offhand that might affect us is the en-dash (slightly shorter than the em-dash, and commonly used for ranges in numbers and dates). I checked on my iPad, and fortunately that doesn't seem to be happening.
Sandbox available [https://www.pgdp.org/~srjfoo/c.branch/fix-ellipsis/](https://www.pgdp.org/~srjfoo/c.branch/fix-ellipsis/). Should work in both PIs and …

Add horiz ellipsis to smart punctuation list

---

tools/proofers/my_suggestions.php

Found another use of dynamic attributes that is deprecated in PHP 8.2.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-8.3-dep-warnings/

Use wrapper around project class for My Suggestions

---

SETUP/ci/check_security.php
pinc/archiving.inc

cleaning up file archiving.inc, use Process instead of exec. Add DocBlock function header comments.
Add type declarations for functions.
Remove unused functions.
I did not test this change in my developer VM. cpeel suggested testing it in a TEST sandbox.

Issue #1274 convert exec to Symfony Process

---

styles/page_interfaces.less
styles/themes/charcoal.css
styles/themes/charcoal.less
styles/themes/classic_grey.css
styles/themes/project_gutenberg.css
styles/themes/royal_blues.css

Found when investigating what it would take to do a dark themed version of the proofreading interfaces for the Charcoal theme:
* Update PM WC management colors for charcoal
* Make tdbottom background color same as tdtop for Enhanced interface.
Sandbox: [misc-style-fixes](https://www.pgdp.org/~srjfoo/c.branch/misc-style-fixes/)

Some style cleanups

---

tools/proofers/for_mentors.php

This allows mentors to checkout and return pages for a single proofreader in bulk. This implements the longstanding [Task 1221](https://www.pgdp.net/c/tasks.php?action=show&task_id=1221) and the UX was reviewed by two mentors (and perhaps others who did not return feedback).
This PR removes the requirement of the `LPage` caller to include the page's state and makes it optional instead. If a page state isn't passed in the constructor will look it up.
https://www.pgdp.org/~cpeel/c.branch/mentor-multi-checkout/

Allow mentors to checkout / return pages in bulk

---

accounts/addproofer.php

This adds typing to `addproofer.php`. I did this as part of resolving some PHP deprecation issues for PHP 8.3 in our `site_registration_protection.php` code which is not checked in anywhere (by design) because it includes out bot-rejection code.
https://www.pgdp.org/~cpeel/c.branch/type-add-proofer/

Add typing to addproofer

---

SETUP/configuration.sh

Fix spaces that php-cs-fixer complains about, when incorporated into site_vars.php.
The error appears if you use configuration.sh as the input to SETUP/configure,
which creates site_vars.php, and then you run `make -C SETUP/ci code_style`

Fix code_style error in configuration.sh which flows into site_vars.php

---

SETUP/ci/check_security.php
pinc/languages.inc

The list of system locales is only used in the translation center for managing translations. The list being returned from `get_installed_system_locales()` incorrectly included the `.utf8` extension. Sharon found this during the PHP 8.3 testing.
This fixes that bug and also changes the `exec()` to a `Process`. Because this bug prevents creating new translations I'd like to get this merged before the upcoming release -- even if we don't get it rolled out to PROD until next month.
https://www.pgdp.org/~cpeel/c.branch/fix-translation-center/

Correctly load UTF-8 system locales

---

SETUP/db_schema.sql
SETUP/upgrade/21/20240915_update_image_sources.php
tools/project_manager/manage_image_sources.php

86ab2156db set the types for the ImageSource class but some of the strings can be null in the DB. Reconcile the two. While we're here make the url and credit fields the max 255 varchar size (like the URLs are in other tables).
That commit was added right after the R202403 release so I'd like to get this one in before the upcoming one. Turns out there is a single row in PROD with a `null` value in it and it's a wonder we didn't catch this prior in the past 6 months.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-manage-image-sources-types/

Make ImageSource class & DB match

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md
SETUP/UPGRADE.md
SETUP/check_db_schema.template

This updates the usual doc suspects for our upcoming R202409 release. As a reminder we try to highlight things in the changelog that we think most site admins would be interested in`*` and tell them to look in the git history for the full details. The order is roughly what I think is the most important first which is very subjective.
Feedback on what was included, the order of the things listed, and any other thoughts are appreciated!
`*` I also ensure that every developer who contributed to the release has an item in the `CHANGELOG.md` file too.

Documentation updates for upcoming R202409 release

---

api/exceptions.inc
pinc/Project.inc
pinc/User.inc

The arguments from the derived classes are passed
to the base constructor and thus must match the
definition from PHP:
https://www.php.net/manual/en/exception.construct.php

Type most *Exception::_construct

---

pinc/CharSuites.inc

This exposed that CharSuite::description was not initialized in the constructor and was never set for several charsuite, Basic Cyrillic among them.
TESTS=Enabled/disabled a charsuite for the SA,
made sure all charsuites could be displayed in SA, added/removed a charsuite on a project.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_CharSuite/

Type pinc/CharSuites.inc

---

pinc/Settings.inc

The file has a lot of PHPStan type annotations that were left as is (ie still not enforced by the PHP runtime).
For the new types, I have made them enforced.
TEST=Manipulated the settings page for different profile.
_Update by cpeel_: Sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_add_missing_type_Settings/

Add missing types in Settings.inc

---

pinc/smoothread.inc

Because of Reasons, the SR coordinator doesn't want to round the SR deadline up and wants to retain the seconds (see [Task 2079](https://www.pgdp.net/c/tasks.php?action=show&task_id=2079). This should retain the original goal of keeping the deadline to right next to the hour for our alerting purposes.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/dont-round-up-sr-deadline/

Don't round SR deadlines up to the next hour

---

pinc/Stopwatch.inc
tools/upload_text.php

Somewhat shockingly, these are the only two outstanding issues that were found in the PHP 8.3 testing. These address two deprecation warnings.

Fix two PHP 8.3 deprecation warnings

---

pinc/DPage.inc
pinc/unicode.inc

The collection of functions are leaves so it
should help type its callers.
While touching it, changed the return type for
guess_string_encoding to ?string instead of using
the existing return (string|false).
TEST=PM: created project + upload, some P1 review, SA charsuite display.
_Update by cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_unicode/

Type pinc/unicode.pinc

---

SETUP/tests/unittests/DPDatabaseTest.php
SETUP/tests/unittests/phpunit_bootstrap.php
pinc/DPDatabase.inc

The function is core to all the code so this
PR adds some integration tests to make sure
that the basic operations still work.
The tests uncovered a few issues that were fixed,
like `close` wouldn't clear the connection or
`query` could return an unset variable.
The code in DPDatabase.pinc was switched to the
object-oriented API for easier typing but the
caller are mostly using the imperative API. The
mysqli documentation confirmed that this should
be fine, albeit ugly.

Type pinc/DPDatabase.inc

---

pinc/iso_lang_list.inc
pinc/wordcheck_engine.inc

There were some missing return types and params.
When possible, I have narrowed down the PHPStan
annotations so they are more useful (the runtime
behavior in this case is unchanged).
TEST=Tested adding/removing words to the site-wide and the project-wide lists.
_Update by cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_wordcheck_engine/

Type pinc/wordcheck_engine.pinc

---

pinc/wordcheck_engine.inc
tools/site_admin/manage_site_word_lists.php

Centralize where we define the location of the site's word list files and handle the case where the directory doesn't exist.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/simplify-site-word-list-management/

Create site word list dir if it doesn't exist

---

pinc/ProjectTransition.inc
pinc/project_trans.inc

The types are inferred from the
callers and the stored values.
Manually tested doing some transition,
either from a PM or a site-admin role.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_ProjectTransition/

Type ProjectTransition

---

pinc/Project.inc
pinc/ProofProject.inc

The validate_text() function does not belong in the ProofProjectPage class since it does not depend on the page.
(preparing for wordcheck api)

move validate_text into project

---

pinc/CharacterSelector.inc

This addresses issue #1334.
The problem was that an identifier is used to link the selector button with the appropriate picker set. This was based on the contents of the selector button which was the same for the two greek sets. Any unique identifier would serve. There are  some issues with uniquid() but it appears that it sleeps for a microsecond at each invocation so it works for our purpose. A serial number would also work.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/uniq_picker

use unique identifier for character pickers

---

SETUP/ci/check_security.php
pinc/ImageUtils.inc
pinc/project_quick_check.inc

Project Quick Check (PQC) already checked for corrupt page images (pngs) but not for corrupt illustrations (usually but not always jpegs). This adds illustration file checking by centralizing image checking functionality into a new `ImageUtils` class. This class can later be expanded to include using `pngcrush`/`optipng` on images on project load too, hence the more generic name for the class.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/add-jpegs-pqc/
Two projects with "problem" images on TEST:
* Bad JPG illus: `projectID5e6821d744beb`
* Bad page PNG: `projectID4c49f39aa829c`

Add checks for corrupt illustrations in PQC

---

SETUP/ci/check_security.php
tools/project_manager/add_files.php

I went to add the corrupt page & illustration checks to the project load and decided it would be best to start with removing the shell commands. More work towards #1274.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-shell-add-files/

Remove shell commands from add_files.php

---

pinc/ImageUtils.inc
pinc/project_quick_check.inc
tools/project_manager/add_files.php

Check for corrupt images at project load -- both page images and illustrations. We've found that there are some warnings reported by the image check tools that don't prevent the image from loading. We special-case these as warnings, not errors, in add projects.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/validate-images-add-files/

Check for corrupt images at project load

---

SETUP/ci/check_security.php
tools/proofers/images_index.php

Remove `passthru()` from `images_index.php`. And TIL how to use callbacks with the `Process->run()` function.
More iterative work on #1274.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/remove-zip-from-illus/

Remove passthru from images_index.php

---

project.php

The change uncovered some mistyped synthetic rows from the project events table in `fill_gaps_in_event`. Those were fixed to use the correct type. Also added a TODO as this underlines a missing class for the type.
TEST=Manipulated a project as PM (state change, add pages) and confirmed that it renders correctly.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_projectphp/

Type project.php

---

pinc/Activity.inc
pinc/Pool.inc
pinc/Round.inc
pinc/Stage.inc
tools/proofers/my_projects.php
tools/proofers/my_suggestions.php

Those 4 are closely coupled so it made
sense to handle them as a single PR.
Unfortunately due to the coupling, the return of
some key getters were not added, instead I added
a comment explaning the situation. Properly typing will likely require some refactoring to split up
the per-type lists, which is better done in a follow-up.
TEST=Checked a user's available rounds, updated a project's state to confirm that the rounds/pools were still listed.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_Activity/

Type Activity/Stage/Round/Pool

---

api/index.php
pinc/base.inc
pinc/bootstrap.inc

Our exception handlers use `html_safe()` so we need to include `misc.inc` before connecting to the database in case it raises an exception. Discovered this on the clone test system.

Move misc.inc include above exception handlers

---

pinc/project_quick_check.inc

For page images in PQC, link to the Image Browser and not the image. Note that illustrations still link to the image since they can't be browsed in PQC.
[Task 2092](https://www.pgdp.net/c/tasks.php?action=show&task_id=2092)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/pqc-to-image-browser/

Link page images to Image Browser in PQC

---

scripts/userprefs.js
userprefs.php

Sandbox at: https://www.pgdp.org/~rp31/c.branch/userpref_js

Move javascript for credit checkboxes to the js file

---

SETUP/tests/manual_web/page_compare/manual_page_compare_test.php
SETUP/tests/unittests/MiscUtilsTest.php
SETUP/upgrade/20/20240205_alter_queue_defns.php
api/index.php
api/v1_projects.inc
api/v1_queues.inc
pinc/misc.inc

This PR only covers SETUP/* and api/*.
It also deprecates array_get so users know that
they should migrate.
TESTS=None.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/julien_remove_array_get_1/

[1/n] Remove array_get

---

accounts/activate.php
accounts/addproofer.php
locale/debug_ui_language.php
project.php
tasks.php
userprefs.php

The change updates accounts/*, locale/*,
project.php, tasks.php and userprefs.php.
TESTS=Created a new account, created a new task,
updated user prefs, and updated a project.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/julien_remove_array_get_4/

[4/n] Remove array_get

---

tools/proofers/ctrl_frame.php
tools/proofers/mktable.php
tools/proofers/my_projects.php
tools/proofers/my_suggestions.php
tools/proofers/processtext.php
tools/proofers/review_work.php
tools/proofers/spellcheck_text.inc

The change updates tools/proofers/*.
TESTS=Did a few P1 checks, including WordCheck.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/julien_remove_array_get_5/

[5/n] Remove array_get

---

composer.json
composer.lock
phpstan.neon

PHPStan was upgraded to 2.0 in November, but we're not ready to upgrade as it detects a lot of new errors.
That said our first step is to upgrade to the latest 1.x.x release, per:
https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md
There is one upside to this upgrade, which is to be able to disable errors using their identifier (added in 1.11).
Also it seems like a low-value error was removed from L5, so removed it from our configuration file.

Upgrade PHPStan to 1.12.12

---

SETUP/tests/unittests/ApiTest.php
api/dp-openapi.yaml
api/v1.inc
api/v1_projects.inc
pinc/ProofProject.inc

Sandbox at: https://www.pgdp.org/~rp31/c.branch/api_wc3
There are two endpoints:
- PUT v1/projects/:projectid/wordcheck This does not require the user to own the page. Needs accepted words and languages. Returns an array of bad words with their levels. 
-  PUT v1/projects/:projectid/pages/:pagename/wordcheck. [edited] This requires the user to own the page and executes save_wordcheck_event(). The logic of when to call this is left to the client. It can be as follows: When the user does any kind of save, if he has previously entered wordcheck mode and a wordcheck report has not previously been submitted then submit a report before the save even if the user has not suggested any words to be accepted. On any subsequent saves submit a report only if the user has suggested some words since the …

Wordcheck API returning bad words with levels

---

SETUP/tests/unittests/ApiTest.php
api/dp-openapi.yaml
api/v1.inc
api/v1_projects.inc
pinc/CharSuites.inc

We could avoid the expand_pickersets() function by creating the pickersets with character names to start with but then we would have to change some other stuff to use the data in this form.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/api_pickers

Add an endpoint for get pickersets

---

api/USERS_GUIDE.md
api/v1.inc

This alpha-sorts the `v1/projects/:projectid/` API routes instead of them being in two separate blocks (how they got this way I don't know and didn't bother to look up). No functional change here.
Added a section to the API user's guide on the wordcheck endpoint too.

Alpha-sort `v1/projects/:projectid/` API route & add WordCheck API to docs

---

SETUP/tests/unittests/MiscUtilsTest.php
pinc/DPage.inc
pinc/LPage.inc
pinc/misc.inc
tools/proofers/PPage.inc

This exposed 2 issues:
1. In Page_MarkAsBad, `$reason` was typed as a string but it should have been an int. The function and its callers were updated so we have better typing moving forward.
2. `array_remove_invalid_keys` was not removing any keys if the list of valid keys was empty. Fixed this as this is a potential security issue (returning unexpected data in our API) and added a test for this case.
TESTS=Uploaded several files, marked a page as bad, proofread a page.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/julien_type_misc/

Type pinc/misc.inc

---

tasks.php

This uncovered a few float -> int conversions
that were fixed using get_integer_param, which
allowed some simplification in argument checks.
TESTS=Created a task and manipulated it:
add/remove related task/topic, close, add "me too"
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/julien_type_tasks/

Type tasks.php

---

pinc/Settings.inc
pinc/user_is.inc

Usernames may be null if the user is not
authenticated so we need to allow it.
TESTS=Tried a few pages with/without being auth'd.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_user_is/

Type pinc/user_is.inc

---

api/v1_queues.inc
api/v1_validators.inc
pinc/release_queue.inc
stats/release_queue.php

Enforced a few types in pinc/release_queue.inc
that were annotated as it seemed like a low
risk change and better for us.
TEST=Tried the queue API and the stats endpoint.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_release_queue/

Type release queues

---

SETUP/tests/jsTests/characterValidation.js
quiz/generic/proof.php
scripts/character_test.js
scripts/text_validator.js
tools/project_manager/handle_bad_page.php
tools/proofers/process_diacritcal_markup.js
tools/proofers/proof_frame_enh.inc
tools/proofers/spellcheck_text.inc
tools/proofers/text_frame_std.inc

so escaped characters don't get changed back to plain characters. This should fix the issue with the test project projectID462699ad8f1c6 which has custom characters which are regex special characters found by @srjfoo. 
Sandbox at: https://www.pgdp.org/~rp31/c.branch/regex_escape

Encode valid characters

---

pinc/ProjectSearchForm.inc
pinc/ProjectSearchResults.inc
pinc/ProjectSearchResultsConfig.inc

Typing all those files together made sense as
they are all helping the search feature.
TESTS=Run searches by different fields.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_projectsearch

Type pinc/ProjectSearch*

---

api/v1_projects.inc
pinc/LPage.inc
pinc/ProofProject.inc
tools/proofers/PPage.inc

This uncovered an inconstency in our API where we used the result of a void function. Explicitly added a `null` return to keep our current behavior.
TEST=Tested all the proofing buttons (save, mark as bad, ...).
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_LPage_all/

Type LPage and users

---

SETUP/tests/unittests/ApiTest.php
api/ApiRouter.inc

This PR reworks the ApiRouter to clearly state that it was using a trie and add an appropriate TrieNode. This helped clarify what the code does and clean up the types in the class.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_trie_in_apirouter/
TESTS=Tried calling some APIs after the change to confirm that the routing still works.

Type api/ApiRouter.inc

---

SETUP/tests/jsTests/ajaxTests.js
scripts/api.js
scripts/page_browse.js

Our current supported browsers can use async and await which need FF 52, Chrome 55, Safari 10.3.
This should make the code more comprehensible.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/async_await
It should only affect pages using the page browser.

Use async and await for ajax

---

pinc/LPage.inc

Turns out this is a 1-line change, so lets do it. [Task 1786](https://www.pgdp.net/c/tasks.php?task_id=1786)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/username-in-bad-page/

Include username in bad page notifications

---

SETUP/CHANGELOG.md

Partial changelog update after deciding the updated plans for PHP 7.4 deprecation and the removal of the authors code.

Correct PHP 7.4 support & authors deprecation

---

api/v1_projects.inc
api/v1_queues.inc
api/v1_validators.inc
pinc/Project.inc

The first step was to rework the ApiRouter to
clearly state that it was using a trie and add
an appropriate TrieNode. This helped clean up
the types a bit.
Typed the handlers/validators though their
return value is anything that `json_encode`
can consume (so anything effectively :-)).

Type api/*

---

tools/site_admin/rename_pages.php

When pages are renamed (renumbered) we need to update `wordcheck_events` and `page_events` to keep the implicit foreign keys the same. [Task 2080](https://www.pgdp.net/c/tasks.php?task_id=2080) 
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-wordcheck-events-on-rename/

Update wordcheck_event & page_events on page renames

---

pinc/wordcheck_engine.inc
tools/project_manager/show_all_good_word_suggestions.php

This attempts to speed up the "Manage proofreaders' Suggestions" page from [Task 2098](https://www.pgdp.net/c/tasks.php?action=show&task_id=2098) after some analysis in xdebug. Unfortunately there's not a lot we can do to make it faster because the bulk of the time is spent in getting all the distinct words from each project and ultimately that boils down to a `preg_match_all()`. I tried various iterations on ways to speed that part up but none of it panned out.
These changes are small code improvements that I tested and discovered which may help the page load faster on a loaded system but it's likely only to be a marginal improvement.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/faster-word-suggestions/

Try to speed up manage proofers suggestions

---

composer.json
composer.lock
pinc/misc.inc

This allows us to use many built-in PHP functions that are in versions 8.0 through 8.4 before we upgrade to that version. For the full list of functions see https://github.com/symfony/polyfill. Once we bump our minimum version to 8.2 we'll remove 8.0, 8.1, and 8.2 from this list.
Confirmation that they are installed in this branch can be seen from the credits page of the branch sandbox: https://www.pgdp.org/~cpeel/c.branch/symfony-84-polyfills/credits.php

Add symfony polyfills up to 8.4

---

pinc/Project.inc

If the MARC record has multiple languages, take the first two as the primary and secondary. [Task 2095](https://www.pgdp.net/c/tasks.php?task_id=2095)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/marc-records-two-languages/

Handle MARC records with multiple languages

---

accounts/login_failure.php
accounts/logout.php
pinc/User.inc
pinc/base.inc
pinc/dpsession.inc
pinc/theme.inc
project.php
quiz/generic/proof.php

Minor code cleanup to remove the global to determine if the user is logged in. Found this working though some session cleanup in prep for PHP 8.4 support.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-user-logged-in-global/

Replace $user_is_logged_in global with static User call

---

pinc/dpsession.inc

Using the individual callback form of `session_set_save_handler()` is deprecated in PHP 8.4. Use the SessionHandlerInterface form instead which works with PHP > 5.4.
Diff best viewed ignoring whitespace, probably. No functional changes -- users should still be able to log in / log out / stay logged in just as before.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/update-session-handler/

Use SessionHandlerInterface object for sessions

---

pinc/CharSuites.inc
pinc/misc.inc
pinc/showavailablebooks.inc
pinc/unicode.inc
tools/site_admin/copy_pages.php

/** @param $var type */ is not a valid PHPDoc
and thus is not recognized by PHPStan.
Fixing those uncovered some mistyped values in
CharSuites.inc. Kudos to Ray for finding those
in the first place on PR #1430!
There should be no prod impact as those are
just PHPStan annotations.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_fix_phpdoc_param_syntax_errors

Fix syntax errors in PHPDocs

---

pinc/theme.inc

If the user is logged in and on a profile that that isn't their own the Profile link in the header should still point to the user's profile. [Task 2099](https://www.pgdp.net/c/tasks.php?action=show&task_id=2099)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-profile-link/

Fix profile link in header

---

SETUP/tests/unittests/ApiTest.php
api/dp-openapi.yaml
api/v1.inc
api/v1_docs.inc

The code has been put in api_docs.inc. Perhaps we should give it a more generic name like api_site_data.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/api_dics

Add endpoint for languages with dictionaries

---

SETUP/ci/check_require_login.php
SETUP/dp.cron.template
crontab/AutoModify.inc
pinc/automodify.inc
pinc/autorelease.inc
tools/project_manager/automodify.php

This lifts automodify into a normal BackgroundJob. In doing so it moves logic that was in `automodify.php` into `pinc/automodify.inc` so it can be called from within the new BackgroundJob. Unlike the prior version, the new job will save the text output directly to a log file so we no longer need the redirect in the crontab.
The `automodify.php` file is still there and can still be run by PMs for a single project (needed for some project transitions) and by SAs.
The crontab on TEST has been updated to use the job in the sandbox below for testing.
https://www.pgdp.org/~cpeel/c.branch/automodify-as-background-job/

Lift automodify into a BackgroundJob

---

.github/workflows/ci.yml

GitHub is deprecating 20.04 at its EOL but is doing brownouts before we're fully cut over on TEST and PROD to Ubuntu 24.04. This is a stop-gap until then to continue coverage on PHP 7.4.
Recent email from GitHub:
> The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025. To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 20.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:
> * March 4 14:00 UTC – 22:00 UTC
> * March 11 13:00 UTC – 21:00 UTC
> * March 18 13:00 UTC – 21:00 UTC
> * March 25 13:00 UTC – 21:00 UTC

Remove Ubuntu 20.04 from CI

---

accounts/login.php
accounts/login_failure.php
pinc/forum_interface_phpbb3.inc

We use phpBB for authentication by calling its `$auth->login()` function. Except that if the account is banned in the forums, that function never returns because `trigger_error()` is called which kills the page. We can install our own error handler to catch that and throw an exception which we _can_ handle more gracefully.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/handle-banned-accounts/
Testing notes: User authentication should continue to work as-is, and users with banned accounts who try to log in will now get a more reasonable error messages instead of an styled phpBB error page.

Better handle banned account logins

---

pinc/wordcheck_engine.inc

Without the Common script, words with apostrophes are filtered out of aspell results in WordCheck. [Task 2100](https://www.pgdp.net/c/tasks.php?action=show&task_id=2100)
Beyond fixing the bug, we need to ensure that this doesn't break the use of the Ancient Greek dictionary, because that's the whole reason we added and use this function in the first place:
```
commit e1353291eacd255392534bd4101211ca0fa2cc2a
Author: Casey Peel <cpeel@users.noreply.github.com>
Date:   Tue Nov 3 15:29:06 2020 +0000
Use language script as part of spellcheck
When presented with text containing two different scripts, aspell
behaves differently based on the dictionary. Words containing non-Latin
characters are ignored completely with the English dictionary, yet
words containing Latin characters are flagged as …
```

Include the Common script for apostrophes

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md
SETUP/UPGRADE.md
SETUP/check_db_schema.template

We're coming up on another of our 2x/year DP code releases next month. This PR updates the changelog and upgrade document. A reminder that we try to only list "major" changes in the changelog in roughly the order that a site admin might want to know about them -- this is not intended to be a value judgement about the features themselves.
Please let me know if I missed something we should include or if we should adjust the order of the entries.
This PR won't be merged until I cut the release.

Prepare for upcoming R202503 release

---

pinc/upload_file.inc

Some AV scans take longer than the default 60 second Process timeout, expand this to 2 minutes. Also catch the timeout if it happens and report a more useful error (that doesn't leak the command that timed out).
Sandbox: https://www.pgdp.org/~cpeel/c.branch/longer-av-scan-timeouts/
This will not be merged until after the code freeze lifts.

Extend AV scan timeout and catch if we trigger it

---

crontab/ArchiveProjects.inc
pinc/BackgroundJob.inc

Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/1457 -- see the issue for the problem we're trying to solve here.
We will need to get this in ASAP to re-enable archiving after the OS upgrade such that they safely run within the updated TimeOut needed for server stability.

Set runtime target for web context BackgroundJobs

---

project.php

This resolves a TypeError when `$pguser` isn't set and we try to determine if they can work in a stage. But we shouldn't show unauthenticated users post comments anyway.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-type-error/

Don't show post-comments to unauth users

---

.github/workflows/ci.yml
SETUP/INSTALL.md
SETUP/tests/unittests/ParamValidatorTest.php
pinc/misc.inc

Per the 202409 changelog, the next release will not support PHP 7.4.
This PR removes any mention of PHP 7.4. Very importantly, it removes the PHP 7.4 CI so we can rely on the updated type system in PHP 8.1 (e.g. `mixed`). Right now, adding those types makes PHP 7.4 CI unhappy.

Remove mention of PHP 7.4

---

.github/workflows/ci.yml
SETUP/tests/unittests/WordCheckEngineTest.php

This adds regression testing for the bug found in [Task 2100](https://www.pgdp.net/c/tasks.php?task_id=2100) and closes #1444. We have pretty decent unit tests already, we just had a gap here.

Add more unit tests for WordCheck

---

SETUP/tests/unittests/ApiTest.php
SETUP/tests/unittests/ProjectTest.php
SETUP/tests/unittests/ProjectUtils.inc

This fixes some small issues in our unit tests in prep for phpunit 10 and for typing `Projects.inc`:
* Correctly handle `$pguser` when creating projects -- there needs to be a valid current user when creating projects to record that data to the event log.
* Don't bleed `$pguser` values from one test to the next. Stupid globals.
* Fix incorrect `posted_num` to `postednum`.
* Squash the "email" that is output on stdout when reporting a bad page when `$testing=1`.

Fix small issues in unit tests

---

pinc/DPage.inc
pinc/faq.inc
pinc/stages.inc
pinc/wordcheck_engine.inc

Don't assume because something is declared outside a function that it is a global. Be explicit about globals being global when we define them.
This is a forward-looking PR in preparation for upgrading to phpunit 10 and won't be merged until after the PROD upgrade and we lift the code freeze.

Be explicit about site globals

---

SETUP/configuration.sh
pinc/site_vars.php.template
project.php
tools/project_manager/remote_file_manager.php

pgdp.net hasn't allowed FTP file uploads for almost a decade and even sharing credentials for something like SCP is not a best practice, so remove it altogether.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-ftp-uploads/

Remove FTP-based file uploads support

---

SETUP/db_schema.sql
SETUP/upgrade/23/20250401_alter_sessions.php
pinc/dpsession.inc
tools/site_admin/edit_mail_address_for_non_activated_user.php
tools/site_admin/index.php
tools/site_admin/manage_site_access_privileges.php
tools/site_admin/manage_user_sessions.php
tools/site_admin/sa_common.inc

_Note: This will not be merged until after the code thaw in March._
In very rare cases admins may need to log a user out of the site. This makes that easier by including the username in the session table and a very simple UI for seeing the current sessions for a user and the option of logging them out.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/track-sessions-to-users/
Testing notes: when testing this, be sure to use the sandbox for the user you want to log out. Sessions created outside of this sandbox will not have the username associated with them and won't be logged out. When this code is deployed any site activity will add the username to the user's session thus solving the problem after deployment.

Map sessions to users and allow admins to manage them

---

tools/site_admin/project_jump.php

_Note: this PR is going into `pgdp-production`, not `master`._
Allow jumping projects to PPV per https://github.com/DistributedProofreaders/dproofreaders/issues/1451.
I only mostly know how these transitions should work and copied the PP restrictions we already had in the branch.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/project-jump-updates/

Add PPV states to project_jump.php

---

pinc/BackgroundJob.inc
pinc/site_vars.php.template
pinc/upload_file.inc

We have two places we're trying to constrain script run times, let's centralize that to a constant. This makes the code match what we're doing on PROD for ArchiveProjects BackgroundJob as well.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/max-code-runtime/

Centralized max script runtime target

---

scripts/control_bar.js

Reverts DistributedProofreaders/dproofreaders#1455
There are reports that this change causes problems for some Safari users.

Revert "Avoid initial image flash."

---

SETUP/import_old_configuration.php

import_old_configuration.php was incorrectly updating lines in the configuration file that shouldn't be updated. These lines were for the automatic path detection for _PHP_CLI_EXECUTABLE and _URL_DUMP_PROGRAM. The easy fix is to consider only variables that start at the beginning of a line, and not touch any indented variables such as these that have additional logic applied to them.
I tested this for two cases:
1. The "old_config_file" has a blank value for _PHP_CLI_EXECUTABLE. The new output file also had blank, as desired.
2. The "old_config_file" has a custom path value for _PHP_CLI_EXECUTABLE. The new output file has the custom path, as desired.
For both cases, the new output file still contains the same indented lines as the configuration.sh you are updating, as desired.
I verifed …

Enhance import_old_configuration.php so it handles the automatic path detection

---

scripts/control_bar.js

Is it still worthwhile to try to fix this image flash issue? I saw the discussion about this, so thought I might have an idea for another solution. I tested only with Chrome on Windows, I don't have a Mac or iPad.
The idea of this fix is to calculate the image styling immediately when adding the image source URL, so by the time the browser has a chance to render the image the styling is already calculated.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/no_image_flash/

Suppress the image flash when opening the page image viewer

---

project.php

Insertion order (event_id) is usually a good proxy for time-based ordering, but there are cases where we backdate the time for an event.

Order project history by timestamp

---

pinc/project_edit.inc
tools/project_manager/add_files.php

Allow SAs to change project page images (and illustrations) regardless of the state of the project. Prevent them from changing project page texts however. Fixes https://github.com/DistributedProofreaders/dproofreaders/issues/843
Sandbox: https://www.pgdp.org/~cpeel/c.branch/sa-manage-images/

Allow SAs to change project images in any state

---

stats/teams/teams_xml.php
tools/proofers/review_work.php
tools/site_admin/edit_mail_address_for_non_activated_user.php

Two corrections for English strings, and adding gettext() markup for another.
These are all tweaks that the translators notified me of. Specifically, I'm curious about the markup for the "Search" button in `review_work`. Does it need the `attr_safe`? I used the "Search" button from the project search form as a model.
Sandbox at [more-translation-strings/](https://www.pgdp.org/~srjfoo/c.branch/more-translation-strings/).

Localization tweaks

---

api/index.php

Relax the CORS policy to allow web browsers to access the API on the test server. This will allow a better devex for JS-based applications like the page browser and the upcoming proofreading interface.
All API callers still need an API key, that hasn't changed.

Relax CORS policy for API on testing servers

---

tools/proofers/text_frame_std.inc

Fix navigation bug when opening comments or image from the standard proofing interface
This fixes the bug described [here in the forum](https://www.pgdp.net/phpBB3/viewtopic.php?t=83760). The problem was caused by the proofing interface trying to re-use a browser tab every time the user clicked on the Image link, even if the user was using that tab for something else now. This fix will really open a new tab now, rather than try to steal back an existing tab. The text that pops up when you hover over the Image link has always said "View Image in New Window". This fix makes that a reality, it really opens in a new tab/window.
Sandbox available for testing: [https://www.pgdp.org/~mrducky/c.branch/image_navigation/](https://www.pgdp.org/~mrducky/c.branch/image_navigation/)

Fix navigation bug when opening image from the standard proofing interface

---

pinc/POFile.inc

`--add-comments` can be used as a boolean flag (included or not) or passed a string, the latter requires the `=`. This should fix the POT generation from JS.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-js-xgettext/

Correctly pass in the TRANSLATORS string

---

project.php

This addresses task 2109.
Also offer to download all formats only if there is more than one.

Enable explicit download of a pdf file for smooth reading.

---

SETUP/CHANGELOG.md
SETUP/INSTALL.md
SETUP/tests/jsTests/characterValidation.js
SETUP/tests/jsTests/qunit.html
eslint.config.js
package-lock.json
package.json
scripts/analyse_format.js
scripts/character_test.js
scripts/text_validator.js
tools/project_manager/handle_bad_page.js
tools/project_manager/handle_bad_page.php
tools/proofers/previewControl.js
tools/proofers/proof_frame_enh.inc
tools/proofers/proof_validate.js
tools/proofers/spellcheck_text.inc
tools/proofers/text_frame_std.inc
tools/proofers/wordcheck.js

This makes the text validation JS into a module. This also removes XRegExp and ups our minimum browser versions slightly.
This is the last modularization commit into `js-infra` and the next (and final!) PR is the one that adds JS packaging.
Testing suggestions:
* Confirm that the text validation code (that confirms if all the characters in a page text are in a project's character suites on page save) work in both the enhanced and standard interfaces.
* Confirm that the WordCheck JS (suggesting a word, etc) continue to work.
* We need to double-check that the text validation JS works with the new browser versions. I tested them all myself via BrowserStack but another pair (or two) of eyes on that would be appreciated.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/js-infra-03-xregexp-replace …

Make text validation JS into a module

---

pinc/unicode.inc

The correct Unicode value for the hair space is `U+200A` (see https://www.compart.com/en/unicode/U+200A) not `U+20A0` (see https://www.compart.com/en/unicode/U+20A0) which is the Euro-Currency sign ₠.
After this merges I'll update [this wiki page](https://www.pgdp.net/wiki/Site_conversion_to_Unicode#Unicode_to_ASCII_mapping).
Fixes #1503.
Thanks for finding this, @windymilla!

Correct hair space Unicode value

---

pinc/automodify.inc

Little of the DP code uses the `$GLOBALS` superglobal and I missed this use of `$testing` during the SiteConfig update.
Found via `php_errors` and hotfixed on PROD.

Fix missed use of global $testing

---

.gitignore
SETUP/CHANGELOG.md
SETUP/DEVELOPMENT.md
SETUP/INSTALL.md
SETUP/generate_manifest_cache.php
SETUP/install_dependencies.sh
eslint.config.js
package-lock.json
package.json
pinc/html_page_common.inc
webpack.config.js

This is the final PR into `js-infra` and after this merges in the branch is ready for merging back into `master`.
This PR adds the requisite bundling infra to ensure we can get proper cache control for ES6 modules. It uses [webpack](https://webpack.js.org/) to do this. Webpack builds a `manifest.json` file that the PHP code can read. There's a deployment script used for production deployments that converts the `manifest.json` into `manifest.php` for efficiently caching this in the opcache and prevents parsing the JSON file on every page load.
Please see the extensive updates to `SETUP/DEVELOPMENT.md` in this PR for an explanation in how this works and what this means for doing JS development.
I evaluated a few different JS bundlers, including:
* esbuild
* rollup
* parcel
The challenge I …

Bundle ES6 modules with webpack

---

stats/teams/team_topic.php

Missed global on update to SiteConfig, found in `php_errors` report. This has been hotfixed on PROD.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-missed-team-global/

Fix missed SiteConfig global

---

accounts/activate.php
accounts/addproofer.php
accounts/login_failure.php
accounts/require_login.php
activity_hub.php
credits.php
faq/privacy.php
index.php
locale/translators/index.php
pinc/theme.inc
stats/equilibria.php
stats/includes/team.inc
stats/members/mdetail.php
stats/misc_stats1.php
stats/misc_user_graphs.php
stats/pages_proofed_graphs.php
stats/projects_Xed_graphs.php
stats/teams/new_team.php
stats/teams/tdetail.php
stats/teams/tedit.php
stats/user_logon_graphs.php
tools/proofers/for_mentors.php
tools/site_admin/sitenews.php

The sidebar is not generally useful, but the default for the past 25 years has been to show it and opt individual pages out. Flip the default to not show the sidebar instead.
This removes the sidebar for the member and team pages, and all of the stats subpages, but keeps it for the main stats page as well as the new user registration and activation (in addition to where you would expect, like the main page, the Activity Hub, round pages, etc).
Also fixes a few small issues I found when testing this against the docker solution that didn't have goals defined, or team icons/avatars directories.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/default-sidebar-off/

Default to not showing the sidebar on pages

---

scripts/page_browse.js
scripts/view_splitter.js
tools/page_browser.js
tools/project_manager/show_word_context.js

The image in show word context could go off the screen or not scroll far enough if the window changes size or when switching between horizontal and vertical split. This was observed by @srjfoo. This adds a function to reset the scroll function in such cases.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/browse_resize

Fix page browser problem for show word context

---

SETUP/generate_manifest_cache.php
SETUP/install_dependencies.sh
pinc/html_page_common.inc

The main deployment code installs into a temporary directory (`c.new`) before it is moved into the main directory (`c`). During this time `$code_dir` points to the final destination, not the temporary directory, so we can't rely on it to find files as part of our deployment process.
The deployment scripts already know the temporary directory we're installing into, we just need to use that when we're generating our manifest cache.

Fix dependency install into temp directory

---

SETUP/ci/check_require_login.php
tools/post_proofers/smooth_reading.php

Require the user to be logged in to access the Smoothreading page. From a discussion with @lhamilton1 & @srjfoo.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/sr-login-required/

Require login for Smoothreading

---

pinc/POFile.inc

If `msgmerge` doesn't think the PO file needs updating it won't change it, but we rely on the timestamp of the file to know it was merged with the template, so always update the time.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/touch-messages-file/

Always update timestamp of POfile on merge
