- .travis.yml
For Travis-CI runs from DistributedProofreaders/dproofreaders
push build status notifications to the PGDP Slack team.
> Notify PGDP Slack for Travis-CI runs

- tools/project_manager/manage_image_sources.php
variables used for escaped strings instead of using sprintf
> fix for problem with % in code_name

- SETUP/db_schema.sql
- SETUP/installation.txt
- SETUP/upgrade/12/20180311_alter_user_project_info.php
- SETUP/upgrade/12/20180316_alter_pg_books.php
- crontab/import_pg_catalog.php
- pinc/DPDatabase.inc
- pinc/DPage.inc
- pinc/forum_interface.inc
- stats/jpgraph_files/pages_in_states.php
This fixes a variety of small issues required to work with Ubuntu 16.04. Surprisingly, very very few of these are for PHP 7.x -- the bulk of the work is to support newer versions of MySQL that are less forgiving with lax SQL.
> Ubuntu 16.04 fixes

- tools/site_admin/manage_special_days.php
Your eyes do not deceive you, this isn't the same thing as https://github.com/DistributedProofreaders/dproofreaders/pull/7 but it sure does look like it! That fix was for `manage_image_sources.php` and this one is for `manage_special_days.php`.
> Don't use sprintf() as $std_fields_sql can contain %

- tasks.php
- tools/authors/manage.php
- tools/project_manager/word_freq_table.inc
Also adjustment to table in authors/manage.php to make it clearer which multiple biographies belong to each author.
> 'each' (deprecated in PHP7.2) replaced in 3 files.

- pinc/project_quick_check.inc
This add a simple automatic test to project quick check to see if there is at least one word on both the good and bad word lists for a project. If there isn't, it returns a Warning as this might be intentional.
> Add a check for good/bad word lists to project quick check

- activity_hub.php
- default.php
- faq/pophelp/prefs/prefs_pophelp.inc
- pinc/BrowseUtility.inc
- pinc/ProjectTransition.inc
- pinc/filter_project_list.inc
- pinc/quizzes.inc
- pinc/showavailablebooks.inc
- project.php
- stats/includes/member.inc
- stats/release_queue.php
- tools/authors/add.php
- tools/authors/manage.php
- tools/authors/search.inc
- tools/pending_access_requests.php
- tools/post_proofers/download_scannos.php
- tools/project_manager/add_files.php
- tools/project_manager/show_image_sources.php
- tools/project_manager/show_specials.php
- tools/proofers/PPage.inc
- tools/proofers/review_work.php
- tools/proofers/round.php
- tools/set_project_event_subs.php
- tools/site_admin/edit_mail_address_for_non_activated_user.php
- tools/site_admin/index.php
- tools/site_admin/manage_site_access_privileges.php
This incorporates lots of excellent feedback from @srjfoo during her work shepherding the French translation through to production. This makes strings like "none" and "all" easier to translate and consolidates some strings.
> Translation fixes

- userprefs.php
This caused browser to report an illegal character
functionality is unchanged
> Unnecessary backslash removed

- tasks.php
After a user has 'Me Too'd a task, the button goes away. This can lead to confusion why it shows up for users on some pages but not others. It would be better to indicate that they have already "Me Too!'d the task.
While I was in here I did some massaging on the CSS to bring it better inline with HTML5, however it isn't fully compliant.
> Change 'Me Too!' link after it has been selected - Task 1679

- faq/prooffacehelp.php
These are updates to the proofreading interface help to reflect
the changes made in the DPOD wiki. Updates courtesy of lhamilton.
> Update proofreading interface help

- faq/es/proofreading_guidelines.php
- faq/it/proofreading_guidelines.php
- faq/nl/proofreading_guidelines.php
- faq/proofreading_guidelines.php
- faq/pt/proofreading_guidelines.php
- pinc/faq.inc
- tools/proofers/greek2ascii.php
[Here](https://www.pgdp.net/c/tasks.php?action=show&task_id=1548) is task #1548.
> Switch PG link to DP one in the Greek transliteration popup (task 1548)

- SETUP/tests/manual_web/manual_page_compare_test.php
Page name had been changed but not action destination.
Also spurious colon removed.
> Incorrect form action attribute removed

- feeds/backend.php
- pinc/showavailablebooks.inc
- stats/members/mbr_xml.php
- stats/teams/teams_xml.php
- tools/authors/authorxml.php
- tools/authors/bioxml.php
- tools/post_proofers/download_scannos.php
Based on this task: https://www.pgdp.net/c/tasks.php?action=show&task_id=1108
Also fixes that error with RSS and XML feeds which occurred when a book title contained letters with diacritical marks. (@cpeel found the solution to that)
> Add XML and RSS feeds for smooth reading

- styles/layout.css
- styles/layout.less
- tools/project_manager/remote_file_manager.php
This started with a request from @srjfoo to allow all users to upload files into the Commons folder.
While I was here I standardized some of the page styles, streamlined some common operations to remove interstitials, and addressed a race condition in the resumable upload reassembly.
> Remote file manager updates

- tasks.php
implements task #1694.
a new value 'notify_new' is added to the UserSetting 'taskctr_notice'
for this purpose.
(the existing code uses also the value 'all'. This seems to be
only partially implemented since there is no way of setting it).
> functionality for notification of new tasks

- feeds/backend.php
- pinc/showavailablebooks.inc
- pinc/site_news.inc
- Added @srjfoo's and @jmdyck's optimized query for SR
- Changed number of items in RSS feed to 20
- Disabled RSS refresh delay on TEST server to make testing easier
> Various RSS feed optimizations and configurations

- pinc/Project.inc
We should properly escape values in the dc.xml file so that it is a valid XML file.  Task 1730
> Properly escape values in dc.xml

- tasks.php
- tools/authors/add.php
- tools/mentors/view_page_text_image.php
- tools/project_manager/displayimage.php
- tools/proofers/mktable.php
- tools/site_admin/manage_special_days.php
- tools/site_admin/show_common_words_from_project_word_lists.php
- userprefs.php
In addition to the Task Center (which was the request from Task 1733) I scoured the code for places where we could be using type=numeric input fields. These are the ones that I found, fixed, and tested.
> Use type=number inputs for numeric form fields

- tools/proofers/round.php
> Update release queue wording on round pages

- pinc/js_newwin.inc
rather than reusing one opened earlier (if this option is enabled)
(It would be possible to remove the prep... function and
incorporate it into the get_onclick... function but means more
changes)
> Always open link to project page in new window

- tools/mentors/view_page_text_image.php
- tools/project_manager/displayimage.php
f43d4da63 enforced maximum image zoom levels to 100%, but users need to be able to zoom in more than 100%.
> Allow users to zoom in more than 100%

- tools/proofers/preview.inc
- tools/proofers/preview.js
Multiple anchors for the same footnote is not itself an issue but could indicate a misread anchor.
> Multi anchor

- tasks.php
> Trim whitespace from summary, details, and comments

- pinc/ProjectSearchForm.inc
- pinc/genres.inc
- tools/project_manager/edit_common.inc
Rather than putting genres into a global variable upon file load, lets move them into a function that returns the list.
> Move genre translations into a function

- pinc/base.inc
- pinc/theme.inc
Add server time at the bottom of every page. This gives users an indication of when the page was loaded if it's been sitting up on their computer for a while.
> Add server time page was built to footer

- tools/proofers/previewControl.js
escape is deactivated when leving preview and also when entering
the configure pane and reactivated going back to preview from
configure
> Escape key now quits preview

- pinc/DPage.inc
- pinc/RoundDescriptor.inc
- tools/project_manager/handle_bad_page.php
The `hbp2.php` script on PROD allows squirrels to update project page texts. Alas, this script has not been updated after the move to mysqli. This PR pulls in the core functionality by allowing squirrels the ability to update a page text for a project in any around.
> Allow squirrels to update any round's page text

- project.php
Include the time as well as the date on the SR deadline.
[Task 1718](https://www.pgdp.net/c/tasks.php?action=show&task_id=1718)
> Specify time as well as date for SR deadline

- crontab/notify_old_pp.php
- project.php
Rather than (ab)using modifieddate to determine when the PPer last
visited the project, use user_project_info which tracks this info
already.
> Use user_project_info to determine last PPer visit

- faq/pophelp/prefs/prefs_pophelp.inc
- pinc/prefs_options.inc
- tools/proofers/mark_wrap.js
- tools/proofers/proof_frame_enh.inc
- tools/proofers/text_frame_std.inc
new function to get wrap mode in pinc/prefs_options.inc
help message for wrap preferences revised
> JS function to mark line endings in line-wrap mode

- faq/prooffacehelp.php
Update the proofreading interface help for the new character picker. Wording by @srjfoo.
> Update proofing interface help for character picker

- pinc/Project.inc
- pinc/ProjectSearchResults.inc
- pinc/js_newwin.inc
- pinc/user_project_info.inc
- project.php
- styles/layout.css
- styles/layout.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- styles/themes/theme.less
- tools/project_manager/projectmgr.php
- tools/proofers/my_projects.php
- userprefs.php
When working on the new My Projects updates, various backend changes were made to support the new code. I pulled these out into their own commit to reduce the review overhead.
The two big changes in this MR:
* New tabbed interface for the Prefs and PM page.
* Move PP/PPV logic into Project class and out of the project.php page.
> Backend updates for My Projects work

- pinc/ProofreadingToolbox.inc
- styles/global.css
- styles/global.less
- styles/layout.css
- styles/layout.less
- tools/proofers/ctrl_frame.php
- tools/proofers/toolbox.js
Character picker can be shown or hidden. State persists using local storage.
> Hide picker

- .eslintrc.js
> lint config file added

- tools/project_manager/edit_common.inc
- tools/project_manager/editproject.php
This addresses task 1788
Using `&nbsp;` here and elsewhere rather than nothing to avoid validation errors.
Alternatively we could put some text like "Choose a genre"
> Blank option added at start of genres for new project

- pinc/prefs_options.inc
- project.php
This addresses two small PHP errors in the recent deployment.
> Fix two PHP errors in recent deployment

- tools/proofers/preview.js
and removing trailing white space before checks
> check for case where last line could be a section heading

- pinc/ProofreadingToolbox.inc
This should now work much the same as it did originally.
I originally changed it when working on an api version but it was probably not such a good idea there either.
> Use the $pi_tools_for_P and _F from stages.inc to define tools

- pinc/project_quick_check.inc
- tools/project_manager/project_quick_check.php
This adds a check to see if the clearance value matches a known good pattern. It also adds the Difficulty to to the manual field test.
Tasks 1723, 1796
> Add Clearance and Difficulty to PQC

- .eslintrc.js
- pinc/CharacterSelector.inc
- pinc/misc.inc
- tools/proofers/character_selector.js
- tools/proofers/ctrl_frame.php
- tools/proofers/proof.php
This implements a 'most recently used' character picker.
To get the clock icon to work html_safe changed to not double-encode html entities. This should be useful also in tasks.php. Could it cause any problems anywhere else?
> most recently used character picker added

- SETUP/upgrade/13/20200110_update_access_log.php
- tools/request_access.php
- tools/site_admin/show_access_log.php
This corrects the regression of the AUTO-GRANTED rename in f102b2e and also removes the filtering of AUTO-GRANTED entries from the access log viewer.
> Fix AUTO-GRANTED name regression

- quiz/generic/main.php
Otherwise we get an error if there is no projectid
> Put in a dummy projectID for ctrl_frame to use

- tools/proofers/for_mentors.php
[Task 1310](https://www.pgdp.net/c/tasks.php?action=show&task_id=1310)
This is accessible in [this sandbox](https://www.pgdp.org/~cpeel/c.branch/wordcheck-in-for-mentors/tools/proofers/for_mentors.php).
> Add WordCheck column to mentors page

- SETUP/db_schema.sql
- SETUP/upgrade/13/20200111_create_tasks_related_tasks.php
- tasks.php
The main focus for this work was to make task relationships bi-directional. If we say task B is related to task A, both tasks should show that relationship.
While I was here I addressed a few other pet peeves of mine, most notably that URLs inside comments and details weren't actually links.
You can demo this branch in the [taskcenter-related-tasks](https://www.pgdp.org/~cpeel/c.branch/taskcenter-related-tasks/tasks.php?action=show&task_id=2211) sandbox.
I'm also going to call [Task 33](https://www.pgdp.net/c/tasks.php?action=show&task_id=33) closed when this merges.
> Task Center updates

- pinc/theme.inc
- styles/statsbar.css
- styles/statsbar.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- styles/themes/theme.less
Tweak the statistics in the sidebar to be more inline with our current site style. You can see a demo of it in my [sidebar-stats-tweaks](https://www.pgdp.org/~cpeel/c.branch/sidebar-stats-tweaks/tools/proofers/round.php?round_id=P1) sandbox ('actual' values are random/faked to give more interesting demo).
[Task 1057](https://www.pgdp.net/c/tasks.php?action=show&task_id=1057)
> Add total user page count to sidebar

- README.md
Looking to contribute where necessary and noticed this while trying to familiarize myself with the codebase.
> Correct README link to intallation

- SETUP/README.md
- SETUP/db_schema.sql
- SETUP/site_admin_notes.txt
- styles/README.md
- styles/design_philosophy.php
- styles/style_demo.php
- styles/themes/README.md
This updates the theming documentation and adds the 3 built-in themes to the site upon initial creation.
> Update style and theme docs and initial config

- tools/proofers/PPage.inc
- tools/proofers/text_frame_std.inc
Create display_image url for image button to allow quick navigation
> 1449: Enhanced Image button

- tools/proofers/srchrep.php
> Add 'u' flag to regular expression.

- SETUP/CHANGELOG.md
- SETUP/INSTALL.md
- SETUP/UPGRADE.md
- SETUP/apache2.conf.example
- SETUP/check_db_schema.template
- pinc/ProofreadingToolbox.inc
- pinc/RoundDescriptor.inc
- pinc/stages.inc
This is a collection of documentation and release-related tooling updates. After https://github.com/DistributedProofreaders/dproofreaders/pull/197 goes in, I believe this is the last thing to merge before we do a release.
> Pre-release doc & tooling updates

- crontab/import_pg_catalog.php
(I've already hacked this change into the file at pgdp.net in order to test it.)
> Improve error-handling in import_pg_catalog.php

- tools/proofers/dp_proof.js
retain selection only for surroundSelection, not picker selection
> 1826 Picker character remains selected

- styles/layout.css
- styles/layout.less
So better contrast with black.
> Changed bad character colour to lighter hot pink

- pastnews.php
- pinc/site_news.inc
add global news_page_id
add to queries for individual page news
add to query for past news
> #1804: Add the ability to do global news items

- pinc/ProofreadingToolbox.inc
- tools/proofers/srchrep.php
> Allow \n and treat as newline character

- tools/proofers/preview.inc
- tools/proofers/preview.js
- tools/proofers/previewControl.js
- tools/proofers/preview_strings.php
- tools/proofers/proof_frame_enh.inc
- tools/proofers/text_frame_std.inc
This avoids error message in console about MIME type
and simplifies code
> Change way translated strings are transferred to javascript

- faq/prooffacehelp.php
- pinc/ProofreadingToolbox.inc
- tools/proofers/srchrep.php
move notes to a link to reduce repeating information
replace some tabs with spaces
help content:
search replace dialog:
> add documentation on search/replace

- styles/preview.css
- tools/proofers/preview.inc
remove defined width for confiure style lines and change to flex style
> change styling so french format preview lines do not wrap

- pinc/Project.inc
- project.php
- tools/project_manager/edit_common.inc
- tools/project_manager/editproject.php
add edit for char suites in edit project page
> add char suites to project info page

- SETUP/tests/UnicodeTest.php
- pinc/CharacterSelector.inc
- pinc/unicode.inc
- tools/charsuites.php
Add additional UTF-8 helper functions when dealing with codepoints
and strings. This also introduces the concept of combined characters
to the code and a format to specify them, although does not include
the full implementation.
This was a collaboration between cpeel and 70ray.
> UTF-8 helper functions and intro to combined chars

- styles/global.css
- styles/global.less
- tools/proofers/proof_frame_enh.inc
- tools/proofers/text_frame_std.inc
This is how it was before the changes for handle_bad_page.
> Make validator window full height even if little text.

- SETUP/tests/UnicodeTest.php
- pinc/codepoint_validator.inc
- pinc/unicode.inc
- quiz/generic/proof.php
- scripts/character_test.js
- scripts/text_validator.js
- tools/project_manager/handle_bad_page.php
- tools/proofers/process_diacritcal_markup.js
- tools/proofers/proof_frame_enh.inc
- tools/proofers/spellcheck.inc
- tools/proofers/text_frame_std.inc
Here is some code I was playing with on how to support combined characters as fully-fledged first-class citizens in the code based on @70ray's comments in [Task 2261](https://www.pgdp.org/c.unicode/tasks.php?action=show&task_id=2261). I'm interested in some thoughts on this implementation. The `charsuite-combined.inc` file is for this review purpose only and wouldn't be included in the final merge.
This code isn't merge ready, but you can play with it in the [unicode-combined-chars](https://www.pgdp.org/~cpeel/c.branch/unicode-combined-chars/tools/charsuites.php?projectid=projectID45c225f598e32) sandbox.
> Support Unicode combined chars

- tools/project_manager/show_project_wordcheck_usage.php
Instead of showing **all** WordChecks for a page, only show the number
of WordCheck events for the person who most recently saved a page.
This mirrors the new logic in project.php and page_table.inc.
[Task 1860](https://www.pgdp.net/c/tasks.php?action=show&task_id=1860)
Available in the [fix-wc-pm-interface](https://www.pgdp.org/~cpeel/c.branch/fix-wc-pm-interface) sandbox.
> Only show WordCheck status for user who saved page

- project.php
add timestamp next to SR report for download
> 1777: Show timestamp for uploaded SR reports

- faq/translate.php
- locale/debug_ui_language.php
- pinc/POFile.inc
- pinc/gettext_setup.inc
- tools/site_admin/index.php
This is a small collection of commits that came out of some gettext troubleshooting from another site that is trying to use our code. The last commit is the most important one, the others are small things found along the way.
> Ensure proper gettext translations

- SETUP/tests/misc_ZipMethodsTest.php
- pinc/misc.inc
- tools/upload_text.php
construct zipped html and images folder after upload
> For smooth reading upload singly-zipped files

- SETUP/CHANGELOG.md
- SETUP/INSTALL.md
- SETUP/UNICODE.md
- tools/site_admin/index.php
Here is at least a start at some code-level documentation about the new unicode changes.
What else should we include in here?
> Unicode docs

- pinc/access_change_emails.inc
- pinc/stages.inc
Add an access granted email for F1, similar to what we now have for PP. The email contents are courtesy of @srjfoo.
> F1 access email

- .eslintignore
- .gitignore
- .travis.yml
- package-lock.json
- package.json
- tools/dropdown.js
- tools/project_manager/projectmgr.js
- tools/proofers/dp_proof.js
- tools/proofers/dp_scroll.js
- tools/proofers/preview.js
- tools/proofers/previewControl.js
- tools/proofers/toolbox.js
add npm init for eslint
turn off rules causing failures
fix autofixable issues
> 1856: Add eslint to TravisCI

- .travis.yml
- SETUP/CODE_STYLE.md
- SETUP/README.md
Add some docs for devs to discover more about the code style and how to run the linters.
Also move the JS linting near the PHP linting in TravisCI file.
> Add docs on code style and linting

- tools/site_admin/copy_pages.php
Copy all data (files and events) when doing project copy/merges.
[Task 1862](https://www.pgdp.net/c/tasks.php?action=show&task_id=1862)
> Copy all WordCheck data on project copy

- tools/project_manager/autorelease.inc
Note that there are 2 commits: the first is a refactor to express the limit more sensibly, the second is the actual limit change.
> Increase PM limit for auto-releases

- pinc/ProofreadingToolbox.inc
- tools/proofers/toolbox.js
close opened toolbar popups when unloading the frame
> 1850: Search-and-replace dies between pages

- tools/upload_text.php
Also top level directory removed first as it should have been.
> embedded zip files removed after unzipping

- pinc/misc.inc
- tools/upload_text.php
applied to main zip and any zips inside it
> New method of removing overall directory in zip file

- tools/project_manager/word_freq_table.inc
empty tbody in firefox have issue with borders as outlined https://bugzilla.mozilla.org/show_bug.cgi?id=1023761.
> Firefox border issue

- SETUP/db_schema.sql
- SETUP/upgrade/14/20200425_alter_queue_defns.php
By Squirrel request, increase the length of the queue name field.
> Increase size of queue name field

- tools/proofers/character_selector.js
IE doesn't support findIndex(), so use another method.
> Ie mru fix

- pinc/wordcheck_engine.inc
- tools/project_manager/show_adhoc_word_details.php
- tools/project_manager/show_all_good_word_suggestions.php
- tools/project_manager/show_current_flagged_words.php
- tools/project_manager/show_good_word_suggestions.php
- tools/project_manager/show_project_possible_bad_words.php
- tools/project_manager/show_project_stealth_scannos.php
- tools/project_manager/word_freq_table.inc
add add words to bad word list
remember cutoff between POSTs
> 1590: Wordcheck: Be able to reject a suggestion

- tools/proofers/preview.js
This reverts commit a3c117b73e450a6f16e04efbea8bb48483a7eef4.
> Revert "Handle non-Latin punc & chars in format preview (#289)"

- pinc/misc.inc
It does not itself appear in a zip made in windows but does in
Linux and macOS
> remove common sub-directory always

- tools/project_manager/show_word_context.php
Add ability to change results count without manually modifying query param
> 1844: No truncation for GWL context list or option to see ALL if wanted

- tools/proofers/srchrep.php
update regular expression escaping to match javascript regex engine.
> 1895: Search and Replace does not correctly find and replace formatting tags

- tools/proofers/preview.js
if parameters are undefined use defaults.
> fix for IE no default parameters

- userprefs.php
> Increase width of number inputs in user preferences.

- tools/proofers/report_bad_page.php
add required to report bad image reason
> 1836: Browser should enforce the input for required form fields

- pinc/CharSuites.inc
- pinc/unicode.inc
Based on [this discussion](https://www.pgdp.net/phpBB3/viewtopic.php?p=1207023#p1207023) add some additional Unicode dashes to the auto-conversion list. Based on the follow-up discussion from bunny-crunch I am inclined not to add the quote characters in that discussion.
In addition, add the space character to the globally-valid list.
Not to self: after this merges, update https://www.pgdp.net/wiki/Site_conversion_to_Unicode#Unicode_to_ASCII_mapping
> Update global and restricted character lists

- tools/post_proofers/ppv_report.php
> PPV report: Change lines re cover image requirements

- pinc/templates/comment_files/diac.txt
- tools/proofers/process_diacritcal_markup.js
> 1894: Do not convert [,x] to character with cedilla.

- scripts/character_test.js
This should make character validation work correctly.
> u flag added to XRegexp functions

- pinc/SortUtility.inc
- pinc/User.inc
- pinc/UserProfile.inc
- pinc/authors.inc
Improve the SQL in some files in `pinc/`, including removing unused code from `pinc/SortUtility.inc`.
> Improve SQL in some pinc/ files

- tools/project_manager/manage_image_sources.php
Update the manage image sources page to use the new DPDatabase functions. Moreover, ensure that we enforce a maximum size limit for all of the fields both in the UI and when inserting into the table.
Someone attempted to insert an overly-long public comment field on PROD which generated an error in the logs a day or two ago.
This is available for testing in the [manage-image-overflow](https://www.pgdp.org/~cpeel/c.branch/manage-image-overflow) sandbox.
> Update manage image sources to use new DB funcs

- pinc/page_controls.inc
- pinc/prefs_options.inc
- scripts/page_browse.js
- styles/global.css
- styles/global.less
- styles/layout.css
- styles/layout.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- styles/themes/theme.less
- tools/mentors/page_text_image.js
- tools/mentors/view_page_text_image.php
- tools/project_manager/display_image.js
- tools/project_manager/displayimage.php
- tools/proofers/previewControl.js
Construct displayimsge and view_page_image using javascript.
> View page image

- tools/post_proofers/postcomments.php
- tools/post_proofers/ppv_report.php
Will put in sandbox after my srchrep PR is merged or I figure out how to host 2 branches at the same time.
> use new query utils for post_proofers directory

- tools/project_manager/edit_common.inc
switch to checkboxes
in sandbox: https://www.pgdp.org/~chrismiceli/c/
> 1913: Convert character suite multi-select to checkboxes

- SETUP/db_schema.sql
- SETUP/upgrade/14/20200523_alter_projects.php
- pinc/CharSuites.inc
- pinc/Project.inc
- pinc/unicode.inc
- tools/charsuites.php
- tools/project_manager/editproject.php
Allow each project to include a set of characters that can be included as adhoc characters for the project. These appear in a special 'Proj' menu in the character picker.
This is available in the [per-project-charsuite](https://www.pgdp.org/~cpeel/c.branch/per-project-charsuite/) sandbox.
> Allow a per-project custom character suite

- pinc/page_controls.inc
- scripts/page_browse.js
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- styles/themes/theme.less
- tools/mentors/page_text_image.js
- tools/project_manager/display_image.js
Changes colours and adds hotkeys Alt up or down arrow. It could be more intuitive the other way round!
> Display image adjust

- tools/charsuites.php
Render the character suite contents in the user's proofreading font.
This is available in the [charsuite-proofreading-font](https://www.pgdp.org/~cpeel/c.branch/charsuite-proofreading-font) sandbox.
> Use proofreading font for charsuite characters

- pinc/page_controls.inc
- pinc/prefs_options.inc
- scripts/page_browse.js
transfer just the font sizes without indices.
> Transfer font sizes only

- accounts/activate.php
- pastnews.php
- pinc/Project.inc
- pinc/ProjectSearchResults.inc
- pinc/ProjectSearchResultsConfig.inc
- pinc/base.inc
- pinc/metarefresh.inc
- pinc/misc.inc
- pinc/showavailablebooks.inc
- pinc/theme.inc
- project.php
- tools/proofers/proof.php
- tools/set_project_event_subs.php
- tools/setlangcookie.php
To prevent XSS from invalid input, correctly escape raised exception messages.
Thanks to M. Dipu for finding and reporting this problem.
OBB-1281669
Note: waiting to hear back from M. Dipu for how they want to be recognized for finding this flaw. This is hotfixed on PROD already.
> Fix various potential XSS vulnerabilities

- tools/project_manager/page_table.inc
remove edit link for bad pages
I didn't see comments on the issue, so if it is not desired, I can close this MR. FYI @srjfoo
> 1390: Remove Edit link from a page marked bad.

- faq/feeds_sdk/index.php
This is just to update the URLs in this document. [Task 1927](https://www.pgdp.net/c/tasks.php?action=show&task_id=1927)
You can check it out in the [update-feed-sdk](https://www.pgdp.org/~cpeel/c.branch/update-feed-sdk/faq/feeds_sdk/) sandbox.
> Update URLs in feed SDK

- tools/project_manager/add_files.php
- tools/project_manager/automodify.php
- tools/project_manager/autorelease.inc
- tools/project_manager/diff.php
- tools/project_manager/downloadproofed.php
- tools/project_manager/edit_common.inc
- tools/project_manager/edit_project_word_lists.php
- tools/project_manager/handle_bad_page.php
- tools/project_manager/page_compare.php
- tools/project_manager/page_operations.inc
This was all manual and is probably error prone so I've deployed it to my sandbox here:  https://www.pgdp.org/~chrismiceli/c.branch/tools-query-update
I did notice what looked like 2 issues in the existing uber queries that may happened to have worked out, note the missing ending ' character:
https://github.com/DistributedProofreaders/dproofreaders/blob/master/tools/project_manager/edit_uberproject.php#L347
https://github.com/DistributedProofreaders/dproofreaders/blob/master/tools/project_manager/edit_uberproject.php#L384
I hope I didn't update them erroneously.
> Update queries in some tools files

- styles/preview.css
so hover messages scroll with it.
This addresses task 1929 [https://www.pgdp.net/c/tasks.php?action=show&task_id=1929](url)
> Position the text_preview div

- tools/proofers/my_projects.php
- tools/proofers/review_work.php
This does some wide-ranging improvements (each in their own commit) to improve argument validation and SQL for the Review Work page. This is in service to [Task 1373](https://www.pgdp.net/c/tasks.php?action=show&task_id=1373) which requests this be added to the My Projects page -- which this does. Wording updates on the new sentence in My Projects as well as the intro sentence to Review Work would be appreciated!
Viewable in the [review-work-tweaks](https://www.pgdp.org/~cpeel/c.branch/review-work-tweaks) sandbox.
> Improve Review Work validation and SQL

- pinc/ProjectSearchForm.inc
- pinc/ProjectSearchResults.inc
- pinc/ProjectSearchResultsConfig.inc
- pinc/SettingsClass.inc
- pinc/site_news.inc
Use the new DPDatabase functions for project search code and the UserSettings class (which the project search code uses).
Available in the [more-db-validation](https://www.pgdp.org/~cpeel/c.branch/more-db-validation/) sandbox.
> Improve DB queries for project search

- pinc/templates/comment_files/BG1b.txt
- pinc/templates/comment_files/BGr2.txt
Changes to the BEGIN template BG1b.txt.
Sandbox available: [fix-bg1b-template](https://www.pgdp.org/~srjfoo/c.branch/fix-bg1b-template/). See [this post](https://www.pgdp.net/phpBB3/viewtopic.php?p=1221643#p1221643) and following for context. There are two BEGIN projects in P1 in the sandbox for verification.
> fix-bg1b-template -- mentor-requested updates

- pinc/list_projects.inc
- styles/layout.less
- styles/statsbar.css
- styles/statsbar.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
Standardize the completed title listings between the sidebar and the list_ebooks pages.
Kick the tires in the [book-listings](https://www.pgdp.org/~cpeel/c.branch/book-listings/default.php) sandbox.
> Standardize completed title listings

- api/dp-openapi.yaml
- api/v1_stats.inc
- default.php
(All publicly available information already.)
While here clean up default.php to use new PHP features.
> Add 1, 7, and 30 day active users to v1/stats/site

- styles/layout.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/project_manager/add_files.php
- tools/proofers/review_work.php
add_files.php and review_work.php still had inline styles for status colors. Moved those to classes and defined the background colors in layout.less.
Test in [update-layout-colors](https://www.pgdp.org/~srjfoo/c.branch/update-layout-colors/) sandbox.
> update-layout-colors: add_files and review_work

- pinc/TallyBoard.inc
Just do Tallyboard.inc here since it has a lot of changes. Its use is limited to the following files though
* `tools/proofers/for_mentors.php`
* `pinc/daily_page_limit.inc`
* `pinc/Activity.inc`
* `pinc/page_tally.inc`
* `stats/jpgraph_files/pages_daily.php`
* `crontab/take_tally_snapshots.php`
> q2: Clean up queries using new query & escape fns, list destructuring.

- styles/layout.less
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tasks.php
This updates the Task Center styling to match that of the rest of the site. This involves quite a lot of changes since it was a beast unto itself.
Testable in the [style-task-center](https://www.pgdp.org/~cpeel/c.branch/style-task-center/) sandbox.
> Update Task Center style to match site

- pinc/dpsession_via_php_sessions.inc
- pinc/list_projects.inc
- pinc/mentorbanner.inc
- pinc/page_tally.inc
- pinc/user_project_info.inc
Do several `.inc` files here. These are relatively small, but touch many pages
> q1: Clean up queries using new query & escape fns, list destructuring.

- SETUP/upgrade/06/update_projects_table.php
- pinc/ProjectSearchResults.inc
- stats/release_queue.php
- stats/stats_central.php
- tools/project_manager/manage_image_sources.php
Several files with small changes and a larger set of changes to `ProjectSearchResults.inc`
> q3: Clean up queries using new query & escape fns, list destructuring.

- pinc/Project.inc
Tested by browsing a bunch of project-related pages on pgdp.org
> Project.inc: Use modern DPDatabase::query, escaping, sprintf

- stats/teams/new_team.php
And make the extraction (and cleanup) of the args from @POST more
consistent, so that what's checked against and displayed and insterted
into the DB are all the same.
> stats/new_team: Use DPDatabase::query, more consistent arg escaping

- tools/project_manager/editproject.php
2a48723c4 regressed the SQL used to create new projects
> Fix SQL for editproject.php

- pinc/new_user_mails.inc
GM requested revisions to the Welcome email to new users. Can be tested at [revise-welcome-email](https://www.pgdp.org/~srjfoo/c.branch/revise-welcome-email).
> GM requested updates to new user welcome email

- stats/teams/tedit.php
While here, move all the parameter extraction to the top of the file.
> stats/teams/tedit.php: Use modern DPDatabase::query, escaping etc

- SETUP/tests/NonactivatedUserTest.php
- pinc/NonactivatedUser.inc
Unit tests pass (yay for unit tests)
> NonactivatedUser.inc: Use modern DPDatabase::query, escaping, sprintf

- tasks.php
Use `sprintf()` and DPDatabase functions for `tasks.php`.
Testable in the [fix-tasks-db-calls](https://www.pgdp.org/~cpeel/c.branch/fix-tasks-db-calls/tasks.php) sandbox.
> Use DPDatabase functions for task SQL calls

- api/index.php
This fixes a stupid logic bug where the count would not get reset to zero when the API window limit was reached.
Debugged, tested, and live on PROD with help from @bpfoley.
> Reset the API limit when the window is reached

- pinc/Project.inc
does_project_page_table_exist would throw an exception if the
project didn't exist.
Found by srjfoo.
> Project.inc: Fix bug introduced by daa207bd

- tools/site_admin/copy_pages.php
Interestingly, several cases here were incorrectly escaped: they
were already validated projectIDs, and are used as table names.
> site_admin/copy_pages.php: Use modern DPDatabase::query, escape, sprintf

- tools/site_admin/copy_pages.php
While not a perfect check, provide some guidance to SAs about charsuite mismatches when copying pages between projects. @srjfoo identified this functional gap of the prior code in her testing of https://github.com/DistributedProofreaders/dproofreaders/pull/486.
> Provide charsuite guidance for copy pages

- pinc/DPage.inc
This was tricky. I've treble checked the diffs and tested various parts of the proofing interface, and found some mistakes along the way. Extra eyeballs appreciated though.
> DPage.inc: Use modern DPDatabase::query, escaping, sprintf

- tools/project_manager/page_detail.php
Do more robust validation for page detail parameters and address an XSS vulnerability.
This change also allows any user to see the pages for a specific user by setting `select_by_user` to that username. This data is already visible to them in the table so why make it harder to see?
Testable in the [page-detail-params](https://www.pgdp.org/~cpeel/c.branch/page-detail-params/) sandbox.
> Better param validation for page detail

- SETUP/tests/jsTests/srchrepTests.js
ignore warning so test can mock real code
refactor tests to reuse logic.
> fix lint warning

- pinc/DPage.inc
- pinc/misc.inc
- tools/site_admin/manage_special_days.php
Move set_col_num, set_col_str to misc because it's generally useful.
> manage_special_days.php: Use DPDatabase APIs, sprintf, set_col_str

- stats/misc_stats1.php
This file really needs a more comprehensive cleanup,
but at least this is a step in the right direction.
Sandbox for testing at 
https://www.pgdp.org/~bfoley/c.branch/cleanup17/stats/misc_stats1.php?tally_name=P2
> stats/misc_stats1.php: Use DPDatabase::escape

- stats/stats_central.php
Sandbox at: https://www.pgdp.org/~bfoley/c.branch/cleanup21
> stats_central.php: Use DPDatabase, and factor out repeated code

- tools/proofers/for_mentors.php
This needs a more comprehensive cleanup -- embedding UI values in the
SQL queries is horrible --  but baby steps.
> for_mentors.php: Use DPDatabase::escape()

- pinc/wordcheck_engine.inc
Sandbox in https://www.pgdp.org/~bfoley/c.branch/cleanup18/
Tested by going through various permutations of the wordcheck interface.
> wordcheck_engine: Use DPDatabase APIs and use PHP7 array syntax

- project.php
And a couple of minor code cleanups.
> project.php: Use DPDatabase APIs, more robust escaping

- stats/pp_stats.php
More cleanup needed, but we should start somewhere.
> pp_stats.php: Sprinkle DPDatabase::escape()

- pinc/unicode.inc
Split into separate MR to increase confidence in its correctness.
> avoid \X due to issues splitting graphemes correctly

- .gitignore
- .travis.yml
- SETUP/tests/MARCRecordTest.php
- SETUP/tests/NonactivatedUserTest.php
- SETUP/tests/ProjectTest.php
- SETUP/tests/README.md
- SETUP/tests/SettingsTest.php
- SETUP/tests/UnicodeTest.php
- SETUP/tests/UserTest.php
- SETUP/tests/misc_FlattenDirectoryTest.php
- SETUP/tests/misc_ParamValidatorTest.php
- SETUP/tests/misc_ZipMethodsTest.php
- SETUP/tests/pinc_WordCheckEngineTest.php
> Support phpunit8 and phpunit9

- .travis.yml
- SETUP/Makefile
- SETUP/tests/README.md
- SETUP/tests/phpunit.xml
Creates a configuration file for phpunit that specifies the bootstrap settings we need. Small improvements to various README files and comments around testing as well.
> Create config file for phpunit and improve docs

- tools/proofers/character_selector.js
filter out characters not present in character picker
> 1889: MRU picker can contain characters not in enabled character suite

- SETUP/check_require_login.php
- pinc/3rdparty/parsedown/LICENSE.txt
- pinc/3rdparty/parsedown/Parsedown.php
- pinc/3rdparty/parsedown/README.md
- pinc/3rdparty/parsedown/details.json
- tasks.php
sandbox: https://www.pgdp.org/~chrismiceli/c.branch/task_markdown
> enable markdown in tasks

- pinc/ProjectSearchForm.inc
This implements task 1961. https://www.pgdp.net/c/tasks.php?task_id=1961.
This is the easy option leaving the api function uncahnged.
Running in sandbox https://www.pgdp.org/~rp31/c.branch/spec_days_1
> Birthday and otherday Special days

- SETUP/check_db_schema.template
- SETUP/db_schema.sql
- SETUP/upgrade/15/20210104_generate_archive_metadata.php
- tools/proofers/hiero/index.php
- tools/site_admin/manage_special_days.php
This is a set of various minor updates found over the past week or so as I was preparing for a release. Most (but not all) of these are in `SETUP/` scripts. Of note are two small wikihiero updates to address some edgecases.
> Small set of pre-release updates

- stats/release_queue.php
Correctly catch and report errors on bad project selectors in the release queues.
Compare the P1 queue in [this sandbox](https://www.pgdp.org/~cpeel/c.branch/better-queue-errors/stats/release_queue.php?round_id=P1) vs [TEST](https://www.pgdp.org/c/stats/release_queue.php?round_id=P1). Note the last queue has an error in the selector.
> Properly show errors on queue selector errors

- tools/proofers/proof.php
This fixes an error seen in the PROD `php_errors` logs a few times. This is due to a user manipulating the `Start Proofreading` link URL and removing the `expected_state` param. While I was here I centralized on using the handy `abort()` tool that outputs some useful links.
If $expected_state is missing the code would fall back to 'new_project' state, which is a valid state but one not within a round and thus cause errors when trying to provide a useful error message. Instead, default to NULL and validate it directly if missing.
Compare:
* Updated message with missing `expected_state` param:
* [new](https://www.pgdp.org/~cpeel/c/tools/proofers/proof.php?projectid=projectID463e6a9454485) vs [old](https://www.pgdp.org/c/tools/proofers/proof.php?projectid=projectID463e6a9454485)
* Updated …
> Better validate missing $expected_state

- SETUP/CHANGELOG.md
- SETUP/INSTALL.md
- SETUP/UNICODE.md
- SETUP/site_admin_notes.txt
- tools/site_admin/manage_special_days.php
Update the documentation for the new release, most notably the `CHANGELOG.md` and `INSTALL.md`. Please let me know if you think there are things we should include in the changelog that are not there or if I have who-worked-on-what wrong! Figuring out what goes into the changelog is always rather arbitrary, but I try to include things that other site SAs would be surprised to find out another way.
I will hold this MR open to capture any late doc additions until the release is ready in ~2.5 weeks.
> New release documentation update

- tools/project_manager/show_good_word_suggestions_detail.js
- tools/project_manager/show_good_word_suggestions_detail.php
replace frameset with splitcontrol
This is step 1. There is at least one more nested frame in this path, then I can replace the parent frameset. Available in sandbox: https://www.pgdp.org/~chrismiceli/c.branch/issue/562 and can be seen at https://www.pgdp.org/c/tools/project_manager/show_all_good_word_suggestions.php
> 562 Remove frameset from PM WordCheck tools

- SETUP/tests/jsTests/dp_proofTests.js
- SETUP/tests/qunit.html
- tools/proofers/dp_proof.js
> 1494: Modify the behaviour of the [** ] button

- accounts/login_failure.php
- faq/pophelp/prefs/prefs_pophelp.inc
- pinc/LPage.inc
- pinc/ProjectSearchResults.inc
- pinc/charsuite-symbols-collection.inc
- pinc/project_edit.inc
- project.php
- quiz/generic/wizard/checks.php
- quiz/tuts/tut_p_greek_3.php
- stats/release_queue.php
- tools/proofers/for_mentors.php
- tools/proofers/preview.inc
This is a collection of mostly small tweaks to the phrasing of a few
of the user-visible messages, to make them easier to localize, or
to standardize them with similar messages. Fixed a couple of typos.
Viewable in the [message-tweaks](https://www.pgdp.org/~srjfoo/c.branch/message-tweaks/) sandbox.
> Update messages for better translation

- pinc/page_controls.inc
- scripts/page_browse.js
- tools/page_browser.js
- tools/project_manager/show_all_good_word_suggestions.js
- tools/project_manager/show_all_good_word_suggestions.php
- tools/project_manager/show_good_word_suggestions_detail.php
- tools/project_manager/show_word_context.js
- tools/project_manager/show_word_context.php
show_word_context uses same pattern as show_good_word_suggestions_detail, using a common js file renamed as show_word_context.js since this name seems appropriate for both cases.
show_all_good_word_suggestions uses an iframe
Running in https://www.pgdp.org/~rp31/c.branch/all_suggestions
> Deframe show_all_good_word_suggestions and show_word_context

- pinc/ProofreadingToolbox.inc
- tools/proofers/srchrep.php
update text to indicate changes will be lost
> 1263: search/replace undo also undoes other formatting

- tools/project_manager/word_freq_table.inc
surround input with label to ease clicking
https://www.pgdp.org/~chrismiceli/c.branch/issue_1488
> 1488: Clickable words in Good Words Candidate List

- api/index.php
We use usernames as memcache keys when tracking API access for rate limiting. Memcache keys can't contain whitespaces or control characters -- but usernames _can_ contain whitespaces -- which causes API access to fail for users with spaces in their names. This results in a server error which breaks the Page Browser for these users.
We can't merely replace spaces with another character as that might potentially conflict with a different user. To fix this, simply hash the username. Also log the error server-side so we are aware of it.
Testable in the [fix-api-rate-key-names](https://www.pgdp.org/~cpeel/c.branch/fix-api-rate-key-names) sandbox.
> Ensure valid memcache keys for API rate limiting

- scripts/page_browse.js
This should make the behaviour like it was before.
in sandbox https://www.pgdp.org/~rp31/c.branch/change_page_scroll
> scroll text and image to top when page changes

- SETUP/check_require_login.php
- package-lock.json
- package.json
This is to address a comment from @cpeel that our js linter should fail on warnings. I also took the liberty to update dependencies to the latest versions.
> Fail on warnings

- scripts/page_browse.js
- tools/page_browser.js
Simplify interface and validate displayMode
> Browse improve

- tools/proofers/for_mentors.php
Change sort order of lists of projects at the top of the for_mentors script to display projects available and waiting based on when they left the mentored round, and include the date and time that each project left the mentored round so that mentors can see for themseves when each project left the mentored round.
Existing sort is based on `projects.modifieddate`, which may or may not give the correct information on which project slice left the mentored round soonest; because of the duplicate author block, if there are a lot of different titles, slices can be released out of order. Changed sort to look at `project_events.timestamp` for the round complete event for the mentored round.
Compare [fix-mentor-sort](https://www.pgdp.org/~srjfoo/c.branch/fix-mentor-sort/tools/proofers/for_mentors.p …
> Fix sort order of mentor projects

- scripts/control_bar.js
- scripts/page_browse.js
- scripts/splitControl.js
Add setSplitPercent() function to imageControl for this.
imageControl, textControl, controlBar, imageWidget & textWidget
use different storage keys for h or v layout and return setup
functions to use the key to find and apply settings.
Switching h/v fires a callback to do this.
control bar names improved to compassPoint etc.
> Allow different settings for horizontal/vertical split

- SETUP/db_schema.sql
Noticed this when trying to setup a local dp from scratch.
> Fix issue referencing table before created

- pinc/control_bar.inc
- pinc/page_controls.inc
- scripts/control_bar.js
- scripts/page_browse.js
- scripts/splitControl.js
- styles/page_interfaces.less
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/page_browser.js
- tools/page_browser.php
- tools/project_manager/show_all_good_word_suggestions.php
- tools/project_manager/show_good_word_suggestions_detail.php
- tools/project_manager/show_word_context.js
- tools/project_manager/show_word_context.php
It sounds like the Image Widget is ready to merge.
This merges the `image-widget` branch into `master` after a rebase. The rebase was necessary because there was merge conflicts on `tools/page_browser.js` -- so we should do a cursory test of Page Browser in this branch before merging it in.
Testable in the [image-widget-rebased](https://www.pgdp.org/~cpeel/c.branch/image-widget-rebased/) sandbox.
> Merge Image Widget into master

- scripts/svgCharts.js
- stats/jpgraph_files/round_backlog.php
- stats/jpgraph_files/round_backlog_days.php
- styles/layout.less
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/site_admin/sitenews.php
https://www.pgdp.org/~chrismiceli/c.branch/round_backlog/tools/proofers/round.php?round_id=P2
Note, this requires manually updating news items that reference the round_days.php img.
> Convert round_backlog to an iframed full html page

- pinc/ProjectSearchResults.inc
- pinc/project_quick_check.inc
- pinc/showavailablebooks.inc
- project.php
- tools/project_manager/edit_common.inc
- tools/project_manager/editproject.php
- tools/project_manager/show_image_sources.php
sandbox:
https://www.pgdp.org/~chrismiceli/c.branch/genre_safe/
There should be no visible changes unless you are aware of some persisted XSS :).
> html_safe project properties more cautiously

- project.php
https://www.pgdp.org/~chrismiceli/c.branch/html_safe/
> fix render issue on project

- activity_hub.php
This is a precursor to an MR I will open once this is merged.
There should be no visible differences, but I've a sandbox to test it in: [ah-sql-update](https://www.pgdp.org/~srjfoo/c.branch/ah-sql-update/activity_hub.php).
> Update sql on AH to current style best practice

- activity_hub.php
All activity stages except Smooth Reading show information in the site progress snapshot table on the Activity Hub. This adds the SR counts and implements the spirit of task #728.
Sandbox at [ah-sr](https://www.pgdp.org/~srjfoo/c.branch/ah-sr/activity_hub.php)
Testers: note that you must have proofed at least 2 pages in order to see the filters (I decreased it just especially for this sandbox).
> Add SR to the snapshot table on the AH

- pinc/graph_data.inc
- stats/equilibria.php
- stats/includes/member.inc
- stats/includes/team.inc
- stats/misc_user_stats.php
- stats/pages_in_states.php
- stats/pages_proofed_graphs.php
- stats/percent_users_who_proof.php
- stats/pp_stage_goal.php
- stats/projects_Xed_graphs.php
- stats/round_backlog.php
- stats/round_backlog_days.php
- stats/stats_central.php
- stats/user_logon_stats.php
- tools/project_manager/show_project_wordcheck_stats.php
https://www.pgdp.org/~chrismiceli/c.branch/cleanup/
> create utility for js construction

- SETUP/GRAPH.md
- SETUP/GRAPHS.md
- SETUP/README.md
- pinc/graph_data.inc
- scripts/svgGraphs.js
- stats/equilibria.php
- stats/includes/member.inc
- stats/includes/team.inc
- stats/misc_user_stats.php
- stats/pages_in_states.php
- stats/pages_proofed_graphs.php
- stats/percent_users_who_proof.php
- stats/pp_stage_goal.php
- stats/projects_Xed_graphs.php
- stats/round_backlog.php
- stats/round_backlog_days.php
- stats/stats_central.php
- stats/user_logon_stats.php
- styles/layout.less
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/project_manager/show_project_wordcheck_stats.php
remove chart references in favor of graph
https://www.pgdp.org/~chrismiceli/c.branch/documentation/stats/stats_central.php
> Document graphing library

- pinc/control_bar.inc
- scripts/control_bar.js
This should avoid the image degradtion of the canvas method.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/image_rotate_css
> Image rotate css

- package-lock.json
- package.json
per my comment in the other auto generated MR.
> run npm update on dependencies

- pinc/base.inc
- pinc/dpsession_via_php_sessions.inc
Random recommendations from a somewhat strict mozilla tool for website security
https://observatory.mozilla.org/analyze/www.pgdp.org
> mozilla observer changes

- scripts/svgGraphs.js
Fix yAxis for area charts as seen on user logon stats page
https://www.pgdp.org/~chrismiceli/c.branch/areaYAxisWidth/stats/user_logon_stats.php
also add 2 px between yAxis and label for bar line charts to give a little more room per request form @srjfoo
> stacked area y axis width adjustment

- scripts/svgGraphs.js
- stats/stats_central.php
- stats/user_logon_graphs.php
https://www.pgdp.org/~chrismiceli/c.branch/userLogonGraphs/stats/stats_central.php
also fixed integers showing with .0 in some bar graphs.
> User Logon Graph improvements

- .github/workflows/static-checks.yml
- package-lock.json
> Update node version

- SETUP/tests/jsTests/formatPreviewTests.js
- tools/proofers/preview.js
This enables multi-line proofers' notes and allows nested pairs of brackets inside proofers' notes. Tasks https://www.pgdp.net/c/tasks.php?action=show&task_id=2001 and https://www.pgdp.net/c/tasks.php?action=show&task_id=1977.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/multi_note
> Multi note

- tools/proofers/preview.js
but encode as part of showStyle function.
If any serious issues showStyle is not called so
encode tags instead.
This avoids the encoded ampersand causing all-cap text
to be interpreted as mixed case. Addresses https://www.pgdp.net/c/tasks.php?action=show&task_id=2014
Sandbox at: https://www.pgdp.org/~rp31/c.branch/small_cap_ampersand
> Do not encode tags before show style

- tools/project_manager/handle_bad_page.php
The refactor in 108f00f77 missed one function call.
Current code error: [handle_bad_page](https://www.pgdp.org/c/tools/project_manager/handle_bad_page.php?projectid=projectID4c49f39aa829c&image=016.png)
Sand box fix: [handle_bad_page](https://www.pgdp.org/~cpeel/c/tools/project_manager/handle_bad_page.php?projectid=projectID4c49f39aa829c&image=016.png)
> Fix handle_bad_page

- pinc/Project.inc
- pinc/RoundDescriptor.inc
- pinc/project_states.inc
- pinc/user_project_info.inc
- pinc/wordcheck_engine.inc
- project.php
Micro-optimizations for the project page. Most notably this reduces the total number of queries to the DB by more than half.
Testable in the [project-page-optimizations](https://www.pgdp.org/~cpeel/c.branch/project-page-optimizations/) sandbox.
> Project page optimizations

- crontab/import_pg_catalog.php
Sharon noticed this when testing https://github.com/DistributedProofreaders/dproofreaders/pull/762. During the PG catalog import, skip empty sub-types for octet-streams. While here, update the DB functions and remove some debugging.
This will make format entries in the MW extension and on the Gold Lists change from:
```
[; HTML; Text (us-ascii)]
```
to
```
[HTML; Text (us-ascii)]
```
This has ben run on TEST and you can see the format strings now do not start with the empty `;`: https://www.pgdp.org/~cpeel/c/list_etexts.php?x=g&sort=5 like they do on PROD https://www.pgdp.net/c/list_etexts.php?x=g&sort=5
Here's a run on TEST with a slightly-modified job to allow running this way:
```
$ curl https://www.pgdp.org/~cpeel/c/crontab/import_pg_catalog.php
000.0 Scanning files in …
```
> Skip empty PG book format subtypes

- stats/misc_user_graphs.php
https://www.pgdp.org/~chrismiceli/c.branch/misc_user_graphs/stats/misc_user_graphs.php
> Update misc user graphs title

- pinc/graph_data.inc
sandbox: https://www.pgdp.org/~chrismiceli/c.branch/user_logon_graph_safari/stats/user_logon_graphs.php
> Fix date format for safari

- pinc/Project.inc
- project.php
- tools/project_manager/editproject.php
When cloning a project, clone the project holds as well. This is [Task 1993](https://www.pgdp.net/c/tasks.php?task_id=1993). This was super easy now that we hold the project data in a Project object so metadata like this doesn't get in the way.
Testable in the [clone-project-holds](https://www.pgdp.org/~cpeel/c.branch/clone-project-holds/) sandbox.
> Copy project holds when cloning

- scripts/svgGraphs.js
https://www.pgdp.org/~chrismiceli/c.branch/yAxisLines/
Per request of @lhamilton1
> Add yAxisLines

- tools/project_manager/editproject.php
We still need to allow PFs to create projects that get assigned to them.
> Allow PFs to create their own projects

- pinc/access_change_emails.inc
- pinc/stages.inc
This completes the move of the access change emails from `master` to `pgdp-production`. Sandbox at [move-access-change-2](https://www.pgdp.org/~srjfoo/c.branch/move-access-change-2).
> Add access change emails to pgdp-production

- SETUP/generate_css_from_less.sh
- package-lock.json
- package.json
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
Just updating versions. Sandbox for font change
https://www.pgdp.org/~chrismiceli/c.branch/node-dependency-updates/
> Node dependency updates

- SETUP/tests/jsTests/formatPreviewTests.js
- tools/proofers/preview.js
to avoid problem with & in upper case small cap markup, add comments and tests.
This addresses issue https://www.pgdp.net/c/tasks.php?action=show&task_id=2040
> encode ampersand in two stages

- pinc/image_check.inc
- pinc/project_quick_check.inc
- tools/project_manager/add_files.php
Per request, adding the logic to project load too similar to large image checks.
https://www.pgdp.org/~chrismiceli/c.branch/small-images/
> Add small image check to project load

- tools/post_proofers/ppv_report.php
Instead of Some/Significant use Basic/Average/Complex Treat recording of illos the same as other features Require 3, not 4, complex features for project to be "Difficult" Round permitted number of errors to nearest integer, not downwards Reduce size-per-error values for Very Good rating by 20%
Also minor form changes:
Remove side bar
Remove spaces from br examples
Update the expected title format
> Adjust PPV rating algorithm

- package-lock.json
In response to the dependabot PR, this updates all the transitive deps.
> All transitive

- pinc/misc.inc
- tools/site_admin/manage_special_days.php
for allowed characters or starts with Birthday or Otherday.
Addresses task https://www.pgdp.net/c/tasks.php?task_id=2050
Sandbox at: https://www.pgdp.org/~rp31/c.branch/birth_other_day
> Check Special day ID

- SETUP/tests/phpunit_test_helpers.inc
- pinc/Activity.inc
- pinc/ProjectTransition.inc
Add global declarations for php unit
more cleanup functions
Set date_created for test user so we can do tests for projects only available for new users.
> Changes to facilitate testing

- pinc/lang_data.inc
- pinc/languages.inc
- pinc/theme.inc
This data structure has been the file since 2004 and never used. Stop carrying along this.
> Remove unused lang_forum() code

- pinc/unicode.inc
This enables digits to appear in the numerical character picker.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/fix_integers
> convert range parameters to int instead of char

- SETUP/tests/jsTests/addprooferTests.js
- accounts/addproofer.js
- pinc/graph_data.inc
- pinc/html_page_common.inc
- scripts/file_resume.js
- scripts/filter_project.js
- scripts/text_validator.js
- tools/page_browser.js
- tools/project_manager/add_files.php
- tools/project_manager/handle_bad_page.js
- tools/project_manager/handle_bad_page.php
- tools/project_manager/projectmgr.js
- tools/project_manager/show_all_good_word_suggestions.js
- tools/project_manager/show_word_context.js
- tools/project_manager/show_word_context.php
- tools/proofers/preview.js
- tools/proofers/process_diacritcal_markup.js
- tools/proofers/proof_frame_enh.inc
- tools/proofers/proof_image.js
- tools/proofers/proof_validate.js
- tools/proofers/spellcheck.inc
- tools/proofers/text_frame_std.inc
- tools/proofers/toolbox.js
- tools/proofers/wordcheck.js
- userprefs.php
@70ray and I were considering the possibility of removing the jQuery dependency. I started the work and it doesn't appear that hard, but wanted to get a review of the approach and ensure the time wouldn't be wasted. This PR probably accounts for about 50% of the work if I'm not bad at estimating (which I am).
You can test these changes in the sandbox:
https://www.pgdp.org/~chrismiceli/c.branch/jquery/
The experiences that would need to be tested are
1. page browser: https://www.pgdp.org/~chrismiceli/c.branch/jquery/tools/page_browser.php?project=projectID4c185eb94cc34&imagefile=046.png&mode=image
2. signup "how did you hear about us": https://www.pgdp.org/~chrismiceli/c.branch/jquery/accounts/addproofer.php
3. Handle bad page from image list if you are PM. The submit button for editing …
> Reduce jquery usage

- scripts/file_resume.js
sandbox:
https://www.pgdp.org/~chrismiceli/c.branch/drag-drop/
This is for task https://www.pgdp.net/c/tasks.php?action=show&task_id=2057
> Fix drag and drop

- tools/upload_text.php
fixes task [https://www.pgdp.net/c/tasks.php?task_id=2056](url)
Sandbox at: https://www.pgdp.org/~rp31/c.branch/music_upload
> include music directory in smooth read html zip

- project.php
This addresses https://www.pgdp.net/c/tasks.php?task_id=2059
Sandbox at: https://www.pgdp.org/~rp31/c.branch/post_music.
This project has a music zip (added by @srjfoo )
https://www.pgdp.org/~rp31/c.branch/post_music/project.php?id=projectID44dd012611ab0
> Add link in post files for music

- SETUP/tests/jsTests/formatPreviewTests.js
- tools/proofers/preview.inc
- tools/proofers/preview.js
Do not attempt to identify section headings since the markup does not distinguish between a paragraph and a section heading, but mark an all-bold paragraph as a possible issue.
Continue to mark all-bold headings and sub-headings as definite issues.
add test
Sandbox at: https://www.pgdp.org/~rp31/c.branch/bold_para
> mark an all-bold paragraph as a possible issue.

- SETUP/tests/jsTests/formatPreviewTests.js
- styles/preview.css
- tools/proofers/preview.inc
- tools/proofers/preview.js
- tools/proofers/previewControl.js
This should fix the issues noticed in the previous version.
I've added some unit tests for those issues. We could add some more tests but the unit tests are perhaps not the best way to go because it is not obvious what the source or result would look like on the page. Maybe we could make a project with pages to exercise various scenarios.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/new_rewrap (updated)
> New rewrap

- SETUP/tests/manual_web/split_test/switchable_split.js
- SETUP/tests/manual_web/split_test/vertical_horizontal_split.js
- SETUP/tests/manual_web/split_test/vertical_split.js
- scripts/page_browse.js
- scripts/splitControl.js
- tools/project_manager/show_all_good_word_suggestions.js
- tools/project_manager/show_word_context.js
This should not change any behaviour but should make the code more comprehensible.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/sim_split2
> Sim split2

- pinc/ProjectTransition.inc
Includes transitions to Unavailable for PP and Unavailable in a round
Addresses the essence of [task #1881](https://www.pgdp.net/c/tasks.php?action=show&task_id=1881)
Sandbox at: https://www.pgdp.org/~windymilla/c.branch/unavailable-events
> Email PM if project made unavailable

- pinc/ProjectTransition.inc
Just mopping up a rare case where the PM wouldn't
have been automatically informed
> Notify PM of PP Unavail to Checked out transition

- .github/workflows/static-checks.yml
- SETUP/tests/jsUnit.js
- package-lock.json
- package.json
This should only impact tests. I confirmed the less utility we use for the css generation produces the same results as well. No need for a sandbox unless we think it is necessary.
> Update to node 18 and latest dependencies

- scripts/page_browse.js
- styles/page_interfaces.less
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
Use just one image and change its source rather than showing and hiding alternate jquery object buttons.
Sandbox at https://www.pgdp.org/~rp31/c.branch/sim_split
> simplify the split direction control button

- tools/project_manager/show_current_flagged_words.php
- tools/project_manager/show_project_stealth_scannos.php
- tools/project_manager/show_project_wordcheck_stats.php
This was a miss from the refactor in 360fffdce. Thank you to @70ray for catching this!
Available in sandbox: https://www.pgdp.org/~cpeel/c.branch/fix-gbwffpt-calls/
> Fix calls to get_bad_word_freqs_for_project_text()

- userprefs.php
On the Preferences page, if using tabs other than proofreading, the font preferences do not appear and javascript exceptions were shown in the developer tools console if it is open.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/prefs_exceptions
> check if javascript variables not null

- tools/proofers/my_projects.php
21bba1bac (one of the commits in the My Suggestions branch) attempted to escape usernames in the SQL but broke them as state selectors often contain `%s`. Calculate and use the escaped values instead. This effectively reverts that commit and changes how the escaping is done.
Testable in https://www.pgdp.org/~cpeel/c.branch/fix-my-projects/
> Fix SQL in My Projects

- pinc/upload_file.inc
I tested it with a couple of files. Do we need to make a sandbox?
> change to using hash_file()

- styles/preview.css
- tools/proofers/preview.inc
and split the inline demo line so it is not so long.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/format_sample
> Show block quote and no wrap separately in demo

- default.php
- pinc/theme.inc
_Note this is changing `pgdp-production`-only code and will be merged into that branch._
Remove Twitter icon from the main page and the site metadata. Requested by @lhamilton1.
Viewable at https://www.pgdp.org/~cpeel/c.branch/remove-xitter/
> Remove Twitter from socials

- pinc/gradual.inc
- quiz/generic/data/qd_p_basicx_1.inc
- quiz/generic/data/qd_p_basicx_2.inc
- quiz/generic/data/qd_p_old_3.inc
- quiz/generic/wizard/output.php
- stats/includes/member.inc
- stats/teams/teams_xml.php
- tools/authors/add.php
- tools/authors/addbio.php
- tools/authors/bio.php
- tools/post_proofers/ppv_report.php
- tools/project_manager/page_compare.php
- tools/project_manager/projectmgr.inc
- tools/project_manager/show_image_sources.php
- tools/site_admin/copy_pages.php
- tools/site_admin/delete_pages.php
- tools/site_admin/show_common_words_from_project_word_lists.php
- tools/upload_text.php
To help reduce the translation burden, standardize a few strings to match others.
Testable in https://www.pgdp.org/~cpeel/c.branch/massage-strings/
> Standardize some close-but-not-quite strings

- stats/release_queue.php
> release_queue.php: Remove dead code

- tools/project_manager/projectmgr.js
- tools/project_manager/projectmgr.php
https://www.pgdp.org/~chrismiceli/c.branch/bug_2072/tools/project_manager/projectmgr.php
Note the format is maintained
> Remove moment dependency

- api/dp-openapi.yaml
- api/v1.inc
- api/v1_projects.inc
Useful (amongst other things) to see when a project was created and when it left a round.
Try with:
ROOT=https://www.pgdp.org/~bfoley/c.branch/api-transitions curl -X GET "$ROOT/api/v1/projects/projectID5e23a810ef693/transitions" \
-H "X-API-KEY: $API_KEY"
> api: Add v1/projects/:projectid/transitions

- credits.php
> credits.php: load_composer_credit_details never took an arg

- tools/project_manager/remote_file_manager.php
Even back in a3af47bce in 2015.
Found by PHPStan
> remote_file_manager.php: confirm_is_local never took a 3rd arg

- tools/proofers/proof_frame_enh.inc
> proof_frame_enh.inc: echo_img has no $which_interface arg

- tasks.php
array_unique doesn't take an input by ref and modify it in place; it returns a new unique-ified array as output.
> tasks.php: Use array_unique properly.

- pinc/page_table.inc
- pinc/release_queue.inc
- pinc/wordcheck_engine.inc
No functional change, since it's just comments.
Found by PHPStan
> Sprinkle some PHPDoc corrections

- pinc/forum_interface_phpbb3.inc
We only support version 3, and the always-true triggers PHPStan warnings.
Diff with 'git diff --ignore-all-space' or github's hide whitespace.
> forum_interface_phpbb3.inc: Remove PHPBB_VERSION checks

- crontab/onoff_special_event_queues.php
- pinc/ProjectTransition.inc
- pinc/SortUtility.inc
- pinc/graph_data.inc
- pinc/js_newpophelp.inc
- pinc/js_newwin.inc
- pinc/languages.inc
- pinc/page_table.inc
- pinc/release_queue.inc
- project.php
- tools/post_proofers/ppv_report.php
- tools/project_manager/add_files.php
- tools/project_manager/manage_image_sources.php
- tools/proofers/spellcheck_text.inc
- tools/site_admin/copy_pages.php
Cherrypick a bunch of uncontroversial PHPStan cleanup patches into a separate patchset.
> Uncontroversial PHPStan cleanups

- .github/actions/setup-mysql-db/action.yml
- .github/actions/setup-node/action.yml
- .github/actions/setup-php/action.yml
- .github/workflows/static-checks.yml
Refactor GitHub actions a bit before adding more.
> GitHub actions

- SETUP/lint_json_files.sh
- SETUP/lint_php_files.sh
Our github action runners have 2 CPUs so this will speed up the linting step a bit.
> SETUP: Make PHP/JSON linting run in parallel

- crontab/import_pg_catalog.php
- crontab/onoff_special_event_queues.php
- pinc/Project.inc
- pinc/Round.inc
- pinc/abort.inc
- pinc/bad_bytes.inc
- pinc/dpsql.inc
- pinc/misc.inc
- pinc/showavailablebooks.inc
- pinc/user_project_info.inc
- pinc/wordcheck_engine.inc
- quiz/generic/quiz_page.inc
- tasks.php
- tools/modify_access.php
- tools/post_proofers/ppv_report.php
- tools/project_manager/add_files.php
- tools/project_manager/edit_common.inc
- tools/project_manager/handle_bad_page.php
- tools/project_manager/remote_file_manager.php
- tools/project_manager/show_current_flagged_words.php
- tools/project_manager/show_good_word_suggestions.php
- tools/project_manager/show_image_sources.php
- tools/project_manager/show_project_possible_bad_words.php
- tools/project_manager/word_freq_table.inc
- tools/site_admin/copy_pages.php
Opening this as WIP for review, and there's a sandbox at https://www.pgdp.org/~bfoley/c.branch/phpstan-cleanups.
This eliminates a bunch of the warnings at PHPStan level 4, and there's currently 17 more I haven't got around to yet.
There are different reasons for many of the changes and I've tried to group related changes into separate patches in the patchset, so it might be worth reviewing them one at a time. You might disagree with some of my reasons, and we can let the uncontroversial ones through, and nuke/rework the others.
> Phpstan cleanups

- .github/workflows/static-checks.yml
It saves an unnecesary github job
> .github: Only run misc tests on one config.

- pinc/abort.inc
- pinc/page_table.inc
- project.php
- tools/project_manager/diff.php
Small fixes for bugs found after the 2024-02 deployment. Some of these are from the code-cleanup but a couple were long-standing bugs found during the fixing of the others.
> Post-deploy hotfixes from code cleanup

- pinc/MARCRecord.inc
...so I can begin to understand this.
No functional change.
> MARCRecord.inc: Add some docs, links to specs, an example

- pinc/ProjectSearchResults.inc
- pinc/gradual.inc
- project.php
Finally close out [Task 259](https://www.pgdp.net/c/tasks.php?action=show&task_id=259)
> Change 'proofing' to 'proofreading'

- tools/project_manager/external_catalog_search.php
- tools/project_manager/projectmgr.inc
> external_catalog_search.php: Set the hide non-text checkbox by default

- pinc/showavailablebooks.inc
- pinc/user_is.inc
- stats/pp_stage_goal.php
- tools/project_manager/clearance_check.php
- tools/project_manager/show_image_sources.php
- tools/proofers/review_work.php
There are some more cases involving rounds. This might conflict with what @cpeel is doing on task #2000 so not done yet.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/use_defined
> Replace project state strings with constants

- pinc/image_check.inc
More informative; will help you decide if you're just off by a little.
Sandbox at `https://www.pgdp.org/~bfoley/c.branch/show-resolution` and a test image to Add/Replace from a project page at `/Users/bfoley/smallimg`
> image_check.inc: Report resolution of too-small image

- pinc/project_states.inc
Sandbox at: https://www.pgdp.org/~rp31/c.branch/use_defined_3
> List states explicitly in get_project_status_descriptor

- tools/project_manager/page_detail.php
As requested in https://www.pgdp.net/c/tasks.php?task_id=2049
Sandbox and example page at https://www.pgdp.org/~bfoley/c.branch/t2049-pagedetail-by-user/tools/project_manager/page_detail.php?project=projectID5894b5a113ec9&show_image_size=0&select_by_user=srjfoo&select_by_round=P3
> page_detail.php: Expose UI to allow PMs to filter by user

- dp_branding/index.php
> Correct typo in dp_branding page

- quiz/generic/proof.php
- tools/proofers/proof_frame_enh.inc
- tools/proofers/proof_validate.js
- tools/proofers/text_data_processor.js
- tools/proofers/text_frame_std.inc
Sandbox here: https://www.pgdp.org/~chrismiceli/c.branch/quiz-quotes/quiz/generic/main.php?quiz_page_id=p_basic_1
> Handle smart quotes in quizes also

- SETUP/CHANGELOG.md
- SETUP/INSTALL.md
- SETUP/upgrade/20/20240205_alter_queue_defns.php
- pinc/forum_interface_phpbb3.inc
A work-in-progress PR for pre-release updates, mostly the changelog but also other things we find before the release in March.
Your feedback on the changelog would be appreciated. Did I miss something? Is something included that doesn't really meet our "important things of note, but not the whole git commit log" cutoff? Tagging all devs who have contributed code to this release.
Leaving this in draft until I've done my final pre-release checks to ensure there isn't something else needed.
> R202403 pre-release updates

- tools/authors/author.php
- tools/proofers/proof_frame.php
- tools/remove_project_hold.php
Checked in sandbox by setting holds from the project page and removing them using the hold column in the project search page:
- https://www.pgdp.org/~bfoley/c.branch/validate-inputs/project.php?id=projectID455f238ba4664#holds
- https://www.pgdp.org/~bfoley/c.branch/validate-inputs/tools/search.php?show=search&title=woman
- https://www.pgdp.org/~bfoley/c.branch/validate-inputs/tools/authors/author.php?author_id=12345
> Validate inputs

- pinc/LPage.inc
- tools/proofers/PPage.inc
Move the code for getting info. from PPage to Lpage leaving PPage to wrap the info. in html. The LPage function can then be used also for the proofreading API.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/lp_data
> Get info in LPage.inc

- SETUP/showdeps.py
Example use:
```
./SETUP/showdeps.py --mode=graph pinc/base.inc
```
and feed the output into a tool such as https://dreampuf.github.io/GraphvizOnline
> Add an include_once dependency graphing tool for dev purposes.

- pinc/User.inc
phpBB has a minimum username length of 3, but we're not checking for that. The GM has requested a longer minimum. I'm lobbying for 4 but will await what @lhamilton1 decides on as the final number.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/enforce-min-username-len/
> Enforce minimum username length for new users

- api/v1_projects.inc
A minor code cleanup.
Checked against https://www.pgdp.org/~bfoley/c.branch/simplify-enable/api/v1/projects/specialdays
> api/v1_projects.inc: Simplify enable checks

- pinc/DPage.inc
- pinc/LPage.inc
- tools/project_manager/show_good_word_suggestions_detail.php
Use it in LPage and show_good_word_suggestions_detail.php. Lpage is really for impementing proofreading logic so not appropriate to use in show_good_word_suggestions_detail.
This is in preparation for making a change to Lpage to make it easier to integrate into the API.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/gen_text
> Make a general function for getting page text in DPage.inc

- pinc/LPage.inc
> Allow RoundInfo->forum_user to be null

- default.php
Does what it says on the tin. At the request of the GM.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/add-pg-links/
> Make Project Gutenberg a link on the home page

- SETUP/smoketests/pageload_smoketest.py
- SETUP/smoketests/smoketest_setup.sh
- SETUP/smoketests/test_tables.sql
This now gives us basic coverage of almost all of the pages on PGDP.
From here, we can start filling different action types and data to exercise different code paths.
> Add smoketests for tools/site_admin

- scripts/splitControl.js
Sandbox at: https://www.pgdp.org/~rp31/c.branch/limit_split
It should not now be possible to drag the splitter bar right to the edge so one of the panes disappears. The limit is set at 10% of the width but this can be changed if it seems too large or small.
The splitter is used in the image and text viewer: tools/page_browser.php  and also in:
tools/project_manager/show_all_good_word_suggestions.php
tools/project_manager/show_good_word_suggestions_detail.php
tools/project_manager/show_word_context.php
and can also be tested in the demonstrations at https://www.pgdp.org/~rp31/c.branch/limit_split/SETUP/tests/manual_web/split_test/index.html
> put limits on split ratio so neither pane can disappear

- SETUP/GRAPHS.md
- pinc/graph_data.inc
- scripts/svgGraphs.js
- stats/equilibria.php
- stats/misc_stats1.php
- stats/misc_user_graphs.php
- stats/pages_in_states.php
- stats/pages_proofed_graphs.php
- stats/percent_users_who_proof.php
- stats/pp_stage_goal.php
- stats/projects_Xed_graphs.php
- stats/round_backlog.php
- stats/round_backlog_days.php
- stats/user_logon_graphs.php
- styles/layout.less
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/project_manager/show_project_wordcheck_stats.php
Sandbox here:
https://www.pgdp.org/~chrismiceli/c.branch/download-chart/stats/stats_central.php
> Add download button for charts

- scripts/svgGraphs.js
Addressed point 1 of https://github.com/DistributedProofreaders/dproofreaders/issues/1198
https://www.pgdp.org/~chrismiceli/c.branch/issue_1198/stats/pages_proofed_graphs.php?tally_name=P1
> Adjust line rendering

- tools/proofers/my_projects.php
The original selection criteria for the "Available" tab on the My Projects page was very broad: the project was in some available state. That's not really useful for most users who are thinking of "available" as available for them to work on right now.
Change the tab to reflect this smaller set of available-to-them projects and make it the first tab as it's arguably the most useful now. Reminder: the My Projects page saves the last tab the user is on, so moving this first isn't going to impact most users but will help newbies.
Note that the My Suggestions page handles these cases already.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/my-projects-available/
> Make "Available" tab mean "available to work in right now"

- .github/workflows/ci.yml
- SETUP/ci/Makefile
- SETUP/ci/check_includes.php
- SETUP/ci/check_require_login.php
- SETUP/ci/check_security.sh
- SETUP/ci/lint_charsuites.php
- SETUP/ci/lint_json_files.sh
- SETUP/ci/lint_php_files.sh
Move our CI tooling into a `SETUP/ci` directory to declutter `SETUP`.
> Group CI tooling together

- styles/README.md
following from SETUP restructuring.
> adjust make less instructions

- SETUP/UPGRADE.md
Be clearer about taking the site offline during upgrades.
> Clarify site upgrade recommendations

- quiz/generic/proof.php
- styles/page_interfaces.less
- styles/preview.css
- styles/themes/charcoal.css
- styles/themes/classic_grey.css
- styles/themes/project_gutenberg.css
- styles/themes/royal_blues.css
- tools/proofers/PPage.inc
Sandbox at: https://www.pgdp.org/~rp31/c.branch/pi_indent
> Make polytonic greek accents visible in proofreading interface etc.

- tools/proofers/proof_frame.php
When a user requests a new page, handle it all inline to the initial `proof_frame.php` load instead of doing a 302 redirect.
Currently when a user clicks "Start Proofreading" we load `proof_frame.php` for it to figure out which page to give the user and then it redirects back to itself. But there's no need to do the redirect -- we already have all of the data we need to just serve the page up. We could have removed one more level of indirection and just construct the PPage object directly instead of calling `get_requested_PPage()` but this keeps the PPage construction all in one place.
Except for removing the redirect, this should work exactly like it did before. This page is loaded within a frame in `proof.php` so the change in the URL is transparent to the user.
Sandbox: …
> Process new page request inline without redirect

- SETUP/CODE_STYLE.md
> Update docs on running php-cs-fixer

- scripts/text_validator.js
Sandbox at: https://www.pgdp.org/~rp31/c.branch/alt_bad_page
> test if buttons exist before adding event listeners

- pinc/page_tally.inc
- stats/pp_stage_goal.php
These two commits reduce tablescans on the site_tally_pages and the projects tables respectively.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/reduce-table-scans/
> Reduce table scans

- tools/site_admin/manage_special_days.php
The file is self-contained so it should be pretty safe.
Manually tested the change by adding a new special day, setting it to a project and made sure that it showed up.
_Update by cpeel_: Sandbox avail at https://www.pgdp.org/~cpeel/c.branch/julien_type_special_days/
> Add type annotations to manage_special_days.php

- tools/project_manager/add_files.php
Those are based on type inspection.
Manually tested adding a file with:
1. no error
2. some errors
---
Edit by srjfoo: Sandbox at [https://www.pgdp.org/~srjfoo/c.branch/julien_type_add_files/](https://www.pgdp.org/~srjfoo/c.branch/julien_type_add_files/)
> Add types to tools/project_manager/add_files.php

- tools/site_admin/sitenews.php
Manually tested the type by adding and moving
some sitenews to several sections.
_Edit: Sandbox at [julien_type_news_admin/](https://www.pgdp.org/~srjfoo/c.branch/julien_type_news_admin/)_
> Type sitenews.php

- tools/upload_text.php
Types were inferred by inspection.
Tested uploading a valid zip file for PP.
> Type tools/upload_text.php

- SETUP/tests/smoketests/pageload_smoketest.py
Add cronjobs and some more page test variations to the smoketests.
> Add cronjobs and additional pages to smoketests

- SETUP/DEVELOPMENT.md
Noticed when browsing to look at updated documentation.
> Fix styles README link in DEVELOPMENT doc

- pinc/Quiz.inc
- quiz/generic/quiz_page.inc
The types were easy to infer from the usage.
Manually tested passing some quizzes and confirmed that we render the quiz/start.php pages correctly. Also made sure the quiz checks for P2 are working.
_Update by srjfoo_: Sandbox available at https://www.pgdp.org/~srjfoo/c.branch/julien_type_quiz/
> Type pinc/Quiz.inc

- SETUP/tests/unittests/ProjectTest.php
- pinc/Project.inc
- pinc/forum_interface_json.inc
- pinc/forum_interface_phpbb3.inc
- tools/project_manager/editproject.php
These are both null or ints but we need to fix some places where they weren't assigned as such.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/project-field-types/
> Correct postednum & topic_id type definitions

- api/dp-openapi.yaml
- api/v1_projects.inc
- pinc/Project.inc
Add the forum URL to the project object returned from the API. [Task 2085](https://www.pgdp.net/c/tasks.php?action=show&task_id=2085)
Example:
```bash
curl -H "Accept: application/json" -H "X-API-KEY: $API_KEY"
-X GET "https://www.pgdp.org/~cpeel/c.branch/forum-url-to-api/api/index.php?url=v1/projects/projectID45b5cfaa0ff81"
```
```json
{
"projectid": "projectID45b5cfaa0ff81",
"title": "Test and Consequences 1",
"author": "Board, Lincoln",
"languages": [
"Welsh",
"Greek, Ancient (to 1453)"
],
"genre": "Collection",
"difficulty": "average",
"special_day": "",
"project_manager": "okrick",
"image_source": "_internal",
"image_preparer": "kraester",
"text_preparer": "kraester",
"pg_ebook_number": null,
"comments": "<trimmed out of output>",
"comment_format": "html",
"custom_characters": "", …
```
> Add forum_url to projects API

- SETUP/db_schema.sql
- SETUP/upgrade/21/20240714_update_user_project_info.php
- pinc/user_project_info.inc
- project.php
- tools/proofers/my_projects.php
Allow users to bookmark arbitrary projects and see them on the My Projects page. [Task 2084](https://www.pgdp.net/c/tasks.php?action=show&task_id=2084)
Sandbox: https://www.pgdp.org/~cpeel/c.branch/project-bookmarks/
> Allow users to bookmark projects

- tools/proofers/for_mentors.php
Minor wording update in the button label in the updated mentors interface.
> Adjust spacing in mentors button

- pinc/Project.inc
This is the file with the most missing types
so starting work on typing it.
This PR mostly add return types as those
are easy to infer from the code.
TEST=Manipulated a project, including adding/removing a charsuite.
_Update from cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_partly_type_Project/
> Partly type pinc/Project.inc

- tools/project_manager/remote_file_manager.php
TEST=Interacted with the remote file manager (uploaded/deleted files, check directories)
_Edit by srjfoo_: Sandbox at [~srjfoo/c.branch/julien_type_tools_remote_file_manager/](https://www.pgdp.org/~srjfoo/c.branch/julien_type_tools_remote_file_manager/)
> Type tools/project_manager/remote_file_manager.php

- SETUP/ci/check_security.php
- pinc/phpbb3.inc
The `check_security` script complained about comments in `phpbb3.inc`, so I changed the comments
and removed it from the `ok_system_calls` whitelist.
> Issue #1274 remove false positive security violation in phpbb3.inc

- tools/project_manager/projectmgr.js
it will not when search refine or result configure.
> check if timespan exists

- pinc/ProjectSearchForm.inc
For issue #1298
Sandbox at: https://www.pgdp.org/~rp31/c.branch/search_form_js
> Clear the search form by submission instead of onClick handler

- tools/authors/add.php
- tools/authors/authors.inc
- tools/authors/authorxml.php
- tools/authors/bioxml.php
- tools/authors/manage.php
- tools/authors/menu.inc
- tools/authors/search.inc
Those are inter-related so it made sense to
handle them in one PR.
TEST=Added/updated several authors with a mix
of unknown fields and AC/BC dates.
_Update by cpeel_: sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_tools_charsuite/
> Type the files in tools/authors/

- SETUP/ci/check_security.php
- SETUP/configuration.sh
- SETUP/tests/unittests/WordCheckEngineTest.php
- SETUP/tests/unittests/phpunit_bootstrap.php
- locale/translators/index.php
- pinc/POFile.inc
- pinc/Project.inc
- pinc/site_vars.php.template
- pinc/upload_file.inc
- tools/project_manager/show_project_stealth_scannos.php
- tools/proofers/processtext.php
This removes the remainder of the exec/shell/system calls in the code and closes #1274. Updated script areas:
* translation center
* project delete
* AV scans on file uploads
* stealth scanno WordCheck tool
Sandbox: https://www.pgdp.org/~cpeel/c.branch/remove-remaining-shell/
> Remove remaining shell calls

- tools/project_manager/show_word_context.js
- tools/project_manager/show_word_context.php
Submit form when the 'Number of word context results' selector changes revised.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/wordcontsel
> Move change event handler to javascript file

- pinc/DPage.inc
TEST=Manipulated a project (adding pages, doing some P1 reviews, transitioning).
_Update from cpeel:_ Sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_type_DPage/
> Type DPage.inc

- scripts/tasks.js
- tasks.php
Sandbox at: https://www.pgdp.org/~rp31/c.branch/taskjs
> Move javascript from tasks.php to a new file

- quiz/generic/returnfeed.php
- quiz/start.php
- stats/members/mbr_list.php
- stats/teams/new_team.php
- stats/teams/tedit.php
- stats/teams/tlist.php
The change updates quiz/* and stats/*.
TESTS=Opened and submitted a quiz, tried some stats pages.
Sandbox at https://www.pgdp.org/~cpeel/c.branch/julien_remove_array_get_2/
> [2/n] Remove array_get

- tools/project_manager/add_files.php
- tools/project_manager/automodify.php
- tools/project_manager/clearance_check.php
- tools/project_manager/diff.php
- tools/project_manager/edit_common.inc
- tools/project_manager/edit_project_word_lists.php
- tools/project_manager/editproject.php
- tools/project_manager/external_catalog_search.php
- tools/project_manager/handle_bad_page.php
- tools/project_manager/manage_image_sources.php
- tools/project_manager/marc_inspector.php
- tools/project_manager/page_detail.php
- tools/project_manager/remote_file_manager.php
- tools/project_manager/show_adhoc_word_details.php
- tools/project_manager/show_all_good_word_suggestions.php
- tools/project_manager/show_good_word_suggestions_detail.php
The change only updates the files in
tools/project_manager.
TESTS=Created a new project, uploaded some pages for it, edited the description and word lists.
Sandbox at: https://www.pgdp.org/~cpeel/c.branch/julien_remove_array_get_6/
> [6/n] Remove array_get

- SETUP/tests/unittests/ApiTest.php
- SETUP/tests/unittests/DPDatabaseTest.php
- SETUP/tests/unittests/FlattenDirectoryTest.php
- SETUP/tests/unittests/MARCRecordTest.php
- SETUP/tests/unittests/MiscUtilsTest.php
- SETUP/tests/unittests/NonactivatedUserTest.php
- SETUP/tests/unittests/PageCompareTest.php
- SETUP/tests/unittests/ParamValidatorTest.php
- SETUP/tests/unittests/ProjectTest.php
- SETUP/tests/unittests/ProjectUtils.inc
- SETUP/tests/unittests/RoundTest.php
- SETUP/tests/unittests/SettingsTest.php
- SETUP/tests/unittests/TableDocumentationTest.php
- SETUP/tests/unittests/UnicodeTest.php
- SETUP/tests/unittests/WordCheckEngineTest.php
- SETUP/tests/unittests/ZipMethodsTest.php
- SETUP/tests/unittests/phpunit_test_helpers.inc
The PR is mostly typing the test functions
that should be returning `void`.
> Type SETUP/tests/unittests/

- SETUP/tests/unittests/ApiTest.php
- api/dp-openapi.yaml
- api/v1_projects.inc
- pinc/Project.inc
The array in get_project_fields_with_attr() is cheated even more than before.
Also add test helper and tests, use helper in existing test.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/round_type
> Add round_type to project data for API

- scripts/page_browse.js
Previously the field was not specified and all fields were returned.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/browse_title
> Request only project title field in page browser.

- SETUP/tests/jsTests/ajaxTests.js
- scripts/api.js
This is one of the possible ways of sending an array.
> Encode array in query parameter

- pinc/wordcheck_engine.inc
- tools/site_admin/copy_pages.php
- tools/site_admin/delete_pages.php
- tools/site_admin/manage_site_word_lists.php
- tools/site_admin/project_jump.php
- tools/site_admin/rename_pages.php
- tools/site_admin/shared_postednums.php
- tools/site_admin/show_access_log.php
TESTS=tested all the scripts under SA in the UI.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_tools_admin
> Type tools/site_admin/*

- api/README.md
Minor API development doc updates. Originally I thought I had more things to update here but this seemed useful. If there are other questions or things reviewers think should be addressed in our API docs I'm happy to do that in this PR.
> Minor API dev doc updates

- SETUP/tests/unittests/ApiTest.php
- api/dp-openapi.yaml
- api/v1.inc
- api/v1_docs.inc
- api/v1_validators.inc
- pinc/faq.inc
This works only with the documents referred to in $external_faq_overrides in pinc/faq.inc but this is sufficient for the present purpose.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/api_docs
> Add api endpoints for documents

- pinc/RandomRule.inc
I ended up not typing the row itself but the
generic getter (`__get`) through some @property-read.
TESTS=checked some random rules and added a new set of rules through the SA page.
Sandbox: https://www.pgdp.org/~jchaffraix/c.branch/julien_type_projectsearch
> Type RandomRule

- pinc/iso_lang_list.inc
- pinc/phpbb3.inc
- pinc/theme.inc
- pinc/upload_file.inc
> Fix / remove broken URLs in comments

- tools/proofers/report_bad_page.php
This was nominally to resolve https://github.com/DistributedProofreaders/dproofreaders/issues/1141 but really the instructions were quite bad so I just rewrote them. I'm very open to changes, but let's settle on something that is better than what we have now vs letting perfect be the enemy of good enough.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/revise-report-bad-page/
> Update instructions for reporting a bad page

- .github/workflows/ci.yml
- SETUP/ci/lint_json_files.sh
- SETUP/ci/lint_php_files.sh
Rev the version of Ubuntu our CI runs on to 24.04 since that's the version we'll be upgrading to here shortly.
If the CI passes for this PR, it's good.
> Run PHP 8.3 tests on Ubuntu 24.04

- SETUP/tests/unittests/ApiTest.php
- api/dp-openapi.yaml
- api/index.php
- api/v1.inc
- api/v1_projects.inc
- pinc/DPage.inc
- pinc/LPage.inc
- pinc/Project.inc
- tools/project_manager/handle_bad_page.php
- tools/proofers/report_bad_page.php
Sandbox at: https://www.pgdp.org/~rp31/c.branch/report_bad
> Add API endpoint to report a bad page.

- tools/proofers/report_bad_page.php
These showed up in the html validator.
> Fix html problems in report bad page

- api/v1_projects.inc
- pinc/CharSuites.inc
Use the function in v1_projects.inc. This will make it possible to use the toolbox of the new proofreading interface in the quiz (without any api calls).
Sandbox at: https://www.pgdp.org/~rp31/c.branch/move_verbose
> make function get_verbose_pickersets() in trait CharSuiteSet

- SETUP/tests/jsTests/splitControlTests.js
- SETUP/tests/manual_web/split_test/split_test.css
- SETUP/tests/manual_web/split_test/switchable_split.js
- SETUP/tests/manual_web/split_test/vertical_horizontal_split.js
- SETUP/tests/manual_web/split_test/vertical_split.js
- scripts/page_browse.js
- scripts/splitControl.js
- scripts/text_view.js
- tools/project_manager/show_all_good_word_suggestions.js
- tools/project_manager/show_word_context.js
In preparation for re-styling the splitter bar
> Remove jQuery from split control

- scripts/control_bar.js
Make image visibility hidden until it is positioned.
Sandbox at: https://www.pgdp.org/~rp31/c.branch/no_flash
> Avoid initial image flash.

- SETUP/tests/README.md
- SETUP/tests/jsTests/jsUnit.js
- package-lock.json
- package.json
Log failures
update packages for npm audit
> Log js failure

- tools/project_manager/add_files.php
- tools/project_manager/manage_image_sources.php
- tools/proofers/for_mentors.php
This PR fixes three small issues that @srjfoo has identified in various testing over the past couple of weeks.
Sandbox: https://www.pgdp.org/~cpeel/c.branch/small-misc-fixes/
> Set of small fixes

- crontab/ImportPGCatalog.inc
This reverts commit 31c63526523efc55489e7661d80f15341b31c070 in `pgdp-production` which adds the infrastructure to support the `in_progress_check.php` script in noncvs.
> Remove in progress check code

- pinc/stages.inc
GM request -- to hopefully avoid running out of pages to format in F1.
> F1 daily page limit reduction

- tools/proofers/previewControl.js
For format preview to support the same unicode markup that was recently added to the m2svg utility.
Sandbox: [https://www.pgdp.org/~mrducky/c.branch/mathjax](https://www.pgdp.org/~mrducky/c.branch/mathjax)
I tested using format preview, with the following text taken from [Principia mathematica (Vol. 1 of 3) {LaTeX}](https://www.pgdp.net/c/project.php?id=projectID5fb6b1641fc59). I had to replace a few special characters because I haven't learned yet how to add characters to a project.
```
From 328.png
Thus we are led to three general definitions for descriptive double
functions, namely (if \(x\unicode{x2640} y\) be any such function)
\[
\begin{aligned}
x\unicode{x2640} \text{ is the relation of }x\unicode{x2640} y\text{ to }&y\text{ for any }y,\\
\unicode{x2640} y\quad "\quad "\quad "\quad …
```
> Configure MathJax to support unicode markup.

- .github/workflows/ci.yml
Fixes the aspell package installs for our CI. If the CI passes for this PR that's success.
> Fix aspell installs for CI
